#INCLUDE "protheus.ch"

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M10E06()

PRIVATE AESTRU := {}
PRIVATE NX := 0

FWMSGRUN(,{||U_M10E06A()},"PICKING - LIST","GERANDO DADOS...")

FOR NX := 1 TO  LEN(AESTRU)
    FWMSGRUN(,{||U_M10E05()},"PICKING - LIST","GERANDO ETIQUETAS...")
NEXT

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M10E06A()

LOCAL OPRINTER := NIL

LOCAL NROW := - (70)
LOCAL CDATA := DTOC(DATE())+" "+TIME()
PRIVATE _CNUMOP := SC2->C2_NUM
PRIVATE _NQTDOP := SC2->C2_QUANT
PRIVATE _CCODPROD := SC2->C2_PRODUTO
PRIVATE NPAGE := 1
PRIVATE OFONT9 := TFONT():NEW("ARIAL",,9)
PRIVATE OFONT12 := TFONT():NEW("ARIAL",,12)
PRIVATE OFONT12B := TFONT():NEW("ARIAL",,12, .T. , .T. )
PRIVATE OFONT14B := TFONT():NEW("ARIAL",,14, .T. , .T. )
PRIVATE OFONT18T := TFONT():NEW("ARIAL",,18, .T. , .T. )
PRIVATE NESTRU := 0

IF MR02POSICIONA()

    M10RIITENS(OPRINTER,OFONT9,OFONT12,OFONT12B,@NROW,@NPAGE,CDATA,_CNUMOP,_NQTDOP,_CCODPROD)
ENDIF

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M10RIITENS(OPRINTER,OFONT9,OFONT12,OFONT12B,NROW,NPAGE,CDATA,_CNUMOP,_NQTDOP,_CCODPROD)

PRIVATE CQUERY := ""
PRIVATE _NREGSG1 := 0
PRIVATE NCOLBAR := 2.3
PRIVATE NROWSTEP := 25
PRIVATE NROWBAR := 60
PRIVATE NX := 0
PRIVATE NESTRU := 0
PRIVATE CANSUL := " "
PRIVATE NPAGINA := 0

CQUERY := "WITH ESTRUT( CODIGO, COD_PAI, COD_COMP, QTD, PERDA, DT_INI, DT_FIM, ANSUL, NIVEL ) AS "
CQUERY += "( "

CQUERY += "SELECT G1_COD PAI, G1_COD, G1_COMP, G1_QUANT, G1_PERDA, G1_INI, G1_FIM, G1_XANSUL, 1 AS NIVEL "
CQUERY += "FROM "+RETSQLNAME("SG1")+" SG1 (NOLOCK) "
CQUERY += "WHERE SG1.D_E_L_E_T_ = '' "
CQUERY += "AND G1_FILIAL      = '"+FWXFILIAL("SG1")+"' "

CQUERY += "UNION ALL "

CQUERY += "SELECT CODIGO, G1_COD, G1_COMP, QTD * G1_QUANT, G1_PERDA, G1_INI, G1_FIM, G1_XANSUL, NIVEL + 1 "
CQUERY += "FROM "+RETSQLNAME("SG1")+" SG1 (NOLOCK) "
CQUERY += "INNER JOIN ESTRUT EST "
CQUERY += "ON G1_COD = COD_COMP "
CQUERY += "WHERE SG1.D_E_L_E_T_ = '' "
CQUERY += "AND SG1.G1_FILIAL = '"+FWXFILIAL("SG1")+"' "

CQUERY += ") "

CQUERY += "SELECT * "
CQUERY += "FROM ESTRUT E1 "
CQUERY += "WHERE E1.CODIGO = '"+_CCODPROD+"' "
CQUERY += "AND E1.DT_FIM >= '20471231' "

DBUSEAREA( .T. ,"TOPCONN",TCGENQRY(,,CQUERY),CALIAS := GETNEXTALIAS(), .F. , .T. )
(CALIAS)->(DBEVAL({||_NREGSG1++}))
(CALIAS)->(DBGOTOP())

WHILE !((CALIAS)->(EOF()))
 
    DBSELECTAREA("SB1")
    DBSETORDER(1)
    DBSEEK(XFILIAL("SB1")+CALIAS->COD_COMP)
    
    IF SB1->B1_XPICLIS<>"1"
        (CALIAS)->(DBSKIP())
        LOOP 
    ENDIF
    
    AADD(AESTRU,{FWXFILIAL("SD3"),"501",CALIAS->COD_COMP,SB1->B1_DESC,SB1->B1_TIPO,SB1->B1_UM,CALIAS->QTD,_CNUMOP,SB1->B1_LOCPAD,CALIAS->ANSUL, .F. })
    
    (CALIAS)->(DBSKIP())
    ENDDO

(CALIAS)->(DBCLOSEAREA())

AESTRU := ASORT(AESTRU,,,{|X,Y|X[10]+X[3]<Y[10]+Y[3]})

NROW += NROWSTEP

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR02POSICIONA()

LOCAL LRET :=  .T. 

DBSELECTAREA("SB1")
DBSETORDER(1)
IF !(SB1->(DBSEEK(XFILIAL("SB1")+SC2->C2_PRODUTO)))
    MSGINFO(I18N("NÃO FORAM ENCONTRADOS DADOS DO PRODUTO #1 ." + CRLF+"VERIFIQUE.",{SC2->C2_PRODUTO}),"ATENÇÃO")
    LRET :=  .F. 
ENDIF

RETURN LRET
