#INCLUDE "protheus.ch"
STATIC LPCPREVATU := FINDFUNCTION("PCPREVATU") .AND. SUPERGETMV("MV_REVFIL", .F. , .F. )

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M10R18()

LOCAL OREPORT

OREPORT := U_RPORTDEF()
OREPORT:PRINTDIALOG()

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION RPORTDEF()
LOCAL OREPORT
LOCAL OSECTION1
LOCAL OSECTION2

OREPORT := TREPORT():NEW("M10R18",OEMTOANSI(IIF((CPAISLOC) $ ("ANG|PTG"),"RELAÇÃO SIMPLIFICADA DAS ESTRUTURAS","RELACAO SIMPLIFICADA DAS ESTRUTURAS")),"M10R18",{|OREPORT|U_RPORTPRINT(OREPORT)},OEMTOANSI(IIF((CPAISLOC) $ ("ANG|PTG"),"ESTE PROGRAMA EMITE A RELAÇÃO DE ESTRUTURA DE UM DETERMINADO ARTIGO","ESTE PROGRAMA EMITE A RELAÇÄO DE ESTRUTURA DE UM DETERMINADO PRODUTO"))+" "+OEMTOANSI(IIF((CPAISLOC) $ ("ANG|PTG"),"SELECCIONADO PELO UTILIZADOR. ESTA RELAÇÃO NÄO DEMONSTRA CUSTOS. CASO O","SELECIONADO PELO USUÁRIO. ESTA RELAÇÄO NÄO DEMONSTRA CUSTOS. CASO O"))+" "+OEMTOANSI(IIF((CPAISLOC) $ ("ANG|PTG"),"PRODUTO USE OPCIONAIS, SERÁ LISTADA A ESTRUTURA COM OS OPCIONAIS PADRÃO.","PRODUTO USE OPCIONAIS, SERÁ LISTADA A ESTRUTURA COM OS OPCIONAIS PADRÄO.")))
OREPORT:SETLANDSCAPE()

PERGUNTE(OREPORT:UPARAM, .F. )

OSECTION1 := TRSECTION():NEW(OREPORT,IIF((CPAISLOC) $ ("ANG|PTG"),"DETALHES DO ARTIGO PAI","DETALHES DO PRODUTO PAI"),{"SG1","SB1"})
OSECTION1:SETLINESTYLE()

NB1_COD := TAMSX3("B1_COD")[1]+1
NB1_DESC := TAMSX3("B1_DESC")[1]+1
NB1_TIPO := TAMSX3("B1_TIPO")[1]+1
NB1_GRUPO := TAMSX3("B1_GRUPO")[1]+1
NB1_UM := TAMSX3("B1_UM")[1]+1
NB1_QB := TAMSX3("B1_QB")[1]+1
NB1_OPC := TAMSX3("B1_OPC")[1]+1

TRCELL():NEW(OSECTION1,"G1_COD","SG1",,,NB1_COD,,)
TRCELL():NEW(OSECTION1,"B1_DESC","SB1",,,NB1_DESC,,)
TRCELL():NEW(OSECTION1,"B1_TIPO","SB1",,,NB1_TIPO,,)
TRCELL():NEW(OSECTION1,"B1_GRUPO","SB1",,,NB1_GRUPO,,)
TRCELL():NEW(OSECTION1,"B1_UM","SB1",,,NB1_UM,,)
TRCELL():NEW(OSECTION1,"B1_QB","SB1",,,NB1_QB,,{||IIF(RETFLDPROD(SB1->B1_COD,"B1_QB")==0,1,RETFLDPROD(SB1->B1_COD,"B1_QB"))})
TRCELL():NEW(OSECTION1,"B1_OPC","SB1",,,NB1_OPC,,{||RETFLDPROD(SB1->B1_COD,"B1_OPC")})

OSECTION1:SETNOFILTER("SB1")

OSECTION2 := TRSECTION():NEW(OSECTION1,"ESTRUTURAS",{"SG1","SB1"})

TRCELL():NEW(OSECTION2,"NIVEL","   ",IIF((CPAISLOC) $ ("ANG|PTG"),"NÍVEL","NIVEL"),,10,,)
TRCELL():NEW(OSECTION2,"G1_COMP","SG1",IIF((CPAISLOC) $ ("ANG|PTG"),"CÓDIGO","CODIGO"),,NB1_COD,,)
TRCELL():NEW(OSECTION2,"G1_TRT","SG1",IIF((CPAISLOC) $ ("ANG|PTG"),"TRT","TRT"),,,,)
TRCELL():NEW(OSECTION2,"B1_TIPO","SB1",IIF((CPAISLOC) $ ("ANG|PTG"),"TP.","TP"),,,,)
TRCELL():NEW(OSECTION2,"B1_GRUPO","SB1",IIF((CPAISLOC) $ ("ANG|PTG"),"GRUP","GRUP"),,,,)
IF NB1_DESC>30
    TRCELL():NEW(OSECTION2,"B1_DESC","SB1",IIF((CPAISLOC) $ ("ANG|PTG"),"DESCRIÇÃO","DESCRIÇÃO"),,30,,)
ELSE 
    TRCELL():NEW(OSECTION2,"B1_DESC","SB1",IIF((CPAISLOC) $ ("ANG|PTG"),"DESCRIÇÃO","DESCRIÇÃO"),,NB1_DESC,,)
ENDIF

TRCELL():NEW(OSECTION2,"G1_OBSERV","SG1",IIF((CPAISLOC) $ ("ANG|PTG"),"OBSERVAÇÃO","OBSERVAÇÃO"),,45,,)
TRCELL():NEW(OSECTION2,"QUANTITEM","   ",IIF((CPAISLOC) $ ("ANG|PTG"),"QTDE.NECESSÁRIA","QTDE.NECESSARIA"),PESQPICT("SG1","G1_QUANT",14),14,,)
TRCELL():NEW(OSECTION2,"B1_UM","SB1",IIF((CPAISLOC) $ ("ANG|PTG"),"UM","UM"),,,,)
TRCELL():NEW(OSECTION2,"G1_PERDA","SG1",IIF((CPAISLOC) $ ("ANG|PTG"),"PERDA %","PERDA %"),,,,)
TRCELL():NEW(OSECTION2,"G1_QUANT","SG1",IIF((CPAISLOC) $ ("ANG|PTG"),"QUANTIDADE","QUANTIDADE"),,,,)
TRCELL():NEW(OSECTION2,"B1_QB","SB1",IIF((CPAISLOC) $ ("ANG|PTG"),"QTD. BASE","QTD. BASE"),,,,{||IIF(RETFLDPROD(SB1->B1_COD,"B1_QB")==0,1,RETFLDPROD(SB1->B1_COD,"B1_QB"))})
TRCELL():NEW(OSECTION2,"G1_FIXVAR","SG1",IIF((CPAISLOC) $ ("ANG|PTG"),"TIPO DE QUANTIDADE","TIPO QUANTIDADE"),,,,)
TRCELL():NEW(OSECTION2,"G1_INI","SG1",IIF((CPAISLOC) $ ("ANG|PTG"),"INI. DA VALIDADE","INI.VALID"),,,,)
TRCELL():NEW(OSECTION2,"G1_FIM","SG1",IIF((CPAISLOC) $ ("ANG|PTG"),"FIM DA VALIDADE","FIM VALID"),,,,)
TRCELL():NEW(OSECTION2,"G1_GROPC","SG1",IIF((CPAISLOC) $ ("ANG|PTG"),"GRP. OPC.","GRP. OPC."),,,,)
TRCELL():NEW(OSECTION2,"G1_OPC","SG1",IIF((CPAISLOC) $ ("ANG|PTG"),"ELEMENTO OPC.","ITEM OPC."),,,,)

OSECTION2:SETHEADERPAGE()
OSECTION2:SETNOFILTER("SB1")

RETURN OREPORT

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION RPORTPRINT(OREPORT)

LOCAL OSECTION1 := OREPORT:SECTION(1)
LOCAL OSECTION2 := OREPORT:SECTION(1):SECTION(1)
LOCAL CPRODUTO := ""
LOCAL NNIVEL := 0
LOCAL LCONTINUA :=  .T. 
LOCAL LDATREF := !(EMPTY(MV_PAR10))
PRIVATE LNEGESTR := GETMV("MV_NEGESTR")
PRIVATE CNEGATIVO :=  ALLTRIM(STR(MV_PAR11))
PRIVATE CSEQZG1
PRIVATE CPRODPAI

DBSELECTAREA("ZG1")

MV_PAR10 := DATE()

IF MV_PAR13==1
    CQUERY := "DELETE FROM "+RETSQLNAME("ZG1")
    CQUERY += " WHERE ZG1_FILIAL = '"+XFILIAL("ZG1")+"' "
    CQUERY += " AND ZG1_DTINCL = '"+DTOS(DATE())+"' "
    TCSQLEXEC(CQUERY)
ENDIF

CQUERY := " SELECT SG1.R_E_C_N_O_ REGSG1, SG1.G1_COD, SG1.G1_COMP, SG1.G1_TRT"
CQUERY += " FROM "+RETSQLNAME("SG1")+" SG1 ,"+RETSQLNAME("SB1")+" SB1 "
CQUERY += " WHERE SG1.G1_FILIAL = '"+XFILIAL("SG1")+"' "
CQUERY += " AND SG1.G1_COD BETWEEN '"+MV_PAR01+"' AND '"+MV_PAR02+"'"
CQUERY += " AND SG1.D_E_L_E_T_ = '' "
CQUERY += " AND SB1.B1_FILIAL = '"+XFILIAL("SB1")+"' "
CQUERY += " AND SB1.B1_COD = SG1.G1_COD "
CQUERY += " AND SB1.B1_TIPO  BETWEEN '"+MV_PAR03+"' AND '"+MV_PAR04+"'"
CQUERY += " AND SB1.B1_GRUPO BETWEEN '"+MV_PAR05+"' AND '"+MV_PAR06+"'"

IF !(EMPTY(MV_PAR12))
    CQUERY += " AND SB1.B1_TIPO IN "+FORMATIN(MV_PAR12,"/")
ENDIF

IF MV_PAR11==2
    CQUERY += " AND SB1.B1_MSBLQL <> '1' "
ENDIF

IF MV_PAR14<>4

    IF MV_PAR14==1
        CDATAINI := DTOS(DDATABASE-90)
    ELSEIF MV_PAR14==2
        CDATAINI := DTOS(DDATABASE-180)
    ELSEIF MV_PAR14==3
        CDATAINI := DTOS(DDATABASE-365)
    ENDIF

    CQUERY += " AND (SELECT COUNT(*) FROM "+RETSQLNAME("SC6")+" SC6 "
    CQUERY += " WHERE SC6.C6_FILIAL <> 'XX' "
    CQUERY += " AND SC6.C6_PRODUTO = G1_COD "
    CQUERY += " AND SC6.C6_QTDVEN > SC6.C6_QTDENT "
    CQUERY += " AND C6_BLQ <> 'R' "
    CQUERY += " AND SC6.D_E_L_E_T_ = '' ) > 0 "

    CQUERY += " OR (SELECT COUNT(*) FROM "+RETSQLNAME("SC6")+" SC6, "+RETSQLNAME("SC5")+" SC5 "
    CQUERY += " WHERE SC6.C6_FILIAL <> 'XX' "
    CQUERY += " AND SC6.C6_PRODUTO = G1_COD "
    CQUERY += " AND SC6.D_E_L_E_T_ = '' "
    CQUERY += " AND SC5.C5_FILIAL = SC6.C6_FILIAL  "
    CQUERY += " AND SC5.C5_NUM = SC6.C6_NUM "
    CQUERY += " AND SC5.C5_EMISSAO >= '"+CDATAINI+"'"
    CQUERY += " AND SC5.D_E_L_E_T_ = '' ) > 0 "

    CQUERY += " OR (SELECT COUNT(*) FROM "+RETSQLNAME("SC2")+" SC2  "
    CQUERY += " WHERE SC2.C2_FILIAL = '"+XFILIAL("SC2")+"' "
    CQUERY += " AND SC2.C2_PRODUTO = G1_COD "
    CQUERY += " AND (SC2.C2_EMISSAO >= '"+CDATAINI+"' OR SC2.C2_DATRF = ' ' )"
    CQUERY += " AND SC2.D_E_L_E_T_ = '' ) > 0 "
ENDIF

CQUERY += " AND SB1.D_E_L_E_T_ = '' "
CQUERY += " ORDER BY SG1.G1_COD, SG1.G1_COMP, SG1.G1_TRT ASC "

CQUERY := CHANGEQUERY(CQUERY)
DBUSEAREA( .T. ,"TOPCONN",TCGENQRY(,,CQUERY),"SG1TRB", .F. , .T. )

DBSELECTAREA("SG1TRB")

OREPORT:SETMETER((SG1TRB)->(LASTREC()))
OSECTION1:INIT( .F. )

WHILE !(OREPORT:CANCEL) .AND. !(SG1TRB)->(EOF())
 
    OREPORT:INCMETER()

    DBSELECTAREA("SG1")
    DBGOTO(SG1TRB->REGSG1)

    IF LDATREF .AND. ((G1_INI>MV_PAR10) .OR. (G1_FIM<MV_PAR10))
        DBSELECTAREA("SG1TRB")
        (SG1TRB)->(DBSKIP())
        LOOP 
    ENDIF

    CPRODUTO := SG1->G1_COD
    CPRODPAI := SG1->G1_COD
    NNIVEL := 2
    LCONTINUA :=  .T. 
    CSEQZG1 := "001"

    DBSELECTAREA("SB1")
    MSSEEK(XFILIAL("SB1")+CPRODUTO)
    
    IF (EOF()) .OR. ((SB1->B1_TIPO<MV_PAR03) .OR. ((SB1->B1_TIPO>MV_PAR04) .OR. ((SB1->B1_GRUPO<MV_PAR05) .OR. (SB1->B1_GRUPO>MV_PAR06))))
        DBSELECTAREA("SG1")
        WHILE !(OREPORT:CANCEL()) .AND. !(EOF()) .AND. XFILIAL("SG1")+CPRODUTO==SG1TRB->G1_FILIAL+SG1TRB->G1_COD
        
            DBSKIP()
            OREPORT:INCMETER()
            ENDDO

        LCONTINUA :=  .F. 
    ENDIF

    IF LCONTINUA

     OSECTION1:INIT( .F. )
        OREPORT:SKIPLINE()

        IF !(EMPTY(RETFLDPROD(SB1->B1_COD,"B1_OPC")))
            OSECTION1:CELL("B1_OPC"):SHOW()
        ELSE 
            OSECTION1:CELL("B1_OPC"):HIDE()
        ENDIF

        OSECTION1:PRINTLINE()
        OREPORT:SKIPLINE()
        OSECTION1:FINISH()

        OSECTION2:INIT()

        U_MTR225EXPLG(OREPORT,OSECTION2,CPRODUTO,IIF(RETFLDPROD(SB1->B1_COD,"B1_QB")==0,1,RETFLDPROD(SB1->B1_COD,"B1_QB")),NNIVEL,RETFLDPROD(SB1->B1_COD,"B1_OPC"),IIF(RETFLDPROD(SB1->B1_COD,"B1_QB")==0,1,RETFLDPROD(SB1->B1_COD,"B1_QB")),IIF(EMPTY(MV_PAR08),IIF(LPCPREVATU,PCPREVATU(SB1->B1_COD),SB1->B1_REVATU),MV_PAR08))

        OSECTION2:FINISH()

        IF MV_PAR07==1
            OSECTION1:SETPAGEBREAK( .T. )
        ELSE 
            OREPORT:THINLINE()
        ENDIF
    ENDIF

    DBSELECTAREA("SG1TRB")
    WHILE SG1TRB->G1_COD==CPRODUTO
    
        DBSKIP()
        ENDDO
        ENDDO

DBSELECTAREA("SG1TRB")
DBCLOSEAREA()

DBSELECTAREA("SG1")
DBCLEARFILTER()
DBSETORDER(1)

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION MTR225EXPLG(OREPORT,OSECTION2,CPRODUTO,NQUANTPAI,NNIVEL,COPCIONAIS,NQTDBASE,CREVISAO)

LOCAL NREG := 0
LOCAL NQUANTITEM := 0
LOCAL NPRINTNIVEL := 0
LOCAL CATENIV := IIF(MV_PAR09="   ","999",MV_PAR09)
LOCAL CREVEST := ""
LOCAL LDATREF := !(EMPTY(MV_PAR10))
LOCAL LVLOPC :=  .T. 

DBSELECTAREA("SG1")
WHILE !(OREPORT:CANCEL()) .AND. !(EOF()) .AND. SG1->G1_FILIAL+SG1->G1_COD==XFILIAL("SG1")+CPRODUTO
 
    OSECTION2:INCMETER()
    NREG := RECNO()
    
    IF (EMPTY(COPCIONAIS)) .OR. (COPCIONAIS==NIL)
        LVLOPC :=  .F. 
    ENDIF
    
    NQUANTITEM := EXPLESTR(NQUANTPAI,IIF(LDATREF,MV_PAR10,NIL),COPCIONAIS,CREVISAO,,,,,,,,,LVLOPC)
    DBSELECTAREA("SG1")
    
    IF NNIVEL<= VAL(CATENIV)
        
        IF ((LNEGESTR) .OR. (!(LNEGESTR) .AND. QTDCOMP(NQUANTITEM, .T. )>QTDCOMP(0))) .AND. QTDCOMP(NQUANTITEM, .T. )<>QTDCOMP(0, .T. )
            
            DBSELECTAREA("SB1")
            DBSETORDER(1)
            MSSEEK(XFILIAL("SB1")+SG1->G1_COMP)
            
            NPRINTNIVEL := IIF(NNIVEL>17,17,NNIVEL-2)
            OSECTION2:CELL("NIVEL"):SETVALUE(SPACE(NPRINTNIVEL)+ STRZERO(NNIVEL,3))
            OSECTION2:CELL("QUANTITEM"):SETVALUE(NQUANTITEM)
            OSECTION2:PRINTLINE()
            
            DBSELECTAREA("SG1")
            MSSEEK(XFILIAL("SG1")+SG1->G1_COMP)
            CREVEST := IIF(LPCPREVATU,PCPREVATU(SB1->B1_COD),SB1->B1_REVATU)
            
            IF FOUND()
                U_MTR225EXPLG(OREPORT,OSECTION2,SG1->G1_COD,NQUANTITEM,NNIVEL+1,SB1->B1_OPC,IIF(RETFLDPROD(SB1->B1_COD,"B1_QB")==0,1,RETFLDPROD(SB1->B1_COD,"B1_QB")),IIF(!(EMPTY(CREVEST)),CREVEST,MV_PAR08))
            ENDIF
            DBGOTO(NREG)
            
            IF MV_PAR13==1
                RECLOCK("ZG1", .T. )
                ZG1->ZG1_FILIAL := XFILIAL("ZG1")
                ZG1->ZG1_COD := CPRODPAI
                ZG1->ZG1_SEQ := CSEQZG1
                ZG1->ZG1_COMP := SG1->G1_COMP
                ZG1->ZG1_NIVEL :=  STRZERO(NNIVEL,3)
                ZG1->ZG1_QUANT := NQUANTITEM
                ZG1->ZG1_QTBASE := IIF(RETFLDPROD(SB1->B1_COD,"B1_QB")==0,1,RETFLDPROD(SB1->B1_COD,"B1_QB"))
                ZG1->ZG1_PERDA := SG1->G1_PERDA
                ZG1->ZG1_FIXVAR := SG1->G1_FIXVAR
                ZG1->ZG1_DTINCL := DATE()
                MSUNLOCK()
            ENDIF
            DBSELECTAREA("SG1")
            
            CSEQZG1 := SOMA1(CSEQZG1)
        ENDIF
    ENDIF
    
    DBSKIP()
    ENDDO

RETURN 
