#INCLUDE "protheus.ch"

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION MACOMXFUN()

RETURN NIL

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION CLEARTEXT()
LOCAL CVARIABLE
LOCAL CFIELD
LOCAL BBLOCK
LOCAL ACHARACTERS
LOCAL LNOMVC
LOCAL LRETURN
LOCAL CSTRING := ""

LNOMVC := FWMODELACTIVE()==NIL
CVARIABLE := READVAR()
CFIELD := SUBSTRING(CVARIABLE,AT(">",CVARIABLE)+1, LEN(CVARIABLE))
IF LNOMVC
    CSTRING := &(CVARIABLE)
ELSE 

    CSTRING := FWFLDGET(CFIELD)
ENDIF

IF CSTRING==NIL
    RETURN  .T. 
ELSE 
    CSTRING :=  ALLTRIM(CSTRING)
ENDIF

BBLOCK := {|CHAR|CSTRING := STRTRAN(CSTRING,CHAR,"")}
ACHARACTERS := SEPARA('"<>&}{*%$#@!*|'+"';+;¨;¬",";")
LRETURN :=  .T. 

AEVAL(ACHARACTERS,BBLOCK)

IF LNOMVC
    &(CVARIABLE) := FWNOACCENT(CSTRING)
ELSE 

    FWFLDPUT(CFIELD,FWNOACCENT(CSTRING))
ENDIF

RETURN LRETURN

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION BUSCAVEND()

LOCAL CNOMEVEN := POSICIONE("SA3",1,XFILIAL("SA3")+POSICIONE("SF2",1,XFILIAL("SF2")+SB6->B6_DOC,"F2_VEND1"),"A3_NOME")

RETURN CNOMEVEN

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION BLOQPROD()

LOCAL _LRET :=  .T. 
LOCAL CCODOPER := BUSCACOLS("C6_OPER")

DO CASE 
 CASE CCODOPER=="03" .AND. !((RETCODUSR()) $ ("000000|000131|000241|000690|000728|000736"))
    MSGSTOP("AS OPERAÇÕES 03 E 04 ESTÃO INDISPONÍVEIS PARA USO. ENTRE EM CONTATO COM O DEPARTAMENTO FISCAL.","ATENÇÃO")
    _LRET :=  .F. 
CASE CCODOPER=="04" .AND. !((RETCODUSR()) $ ("000000|000131|000241|000690|000728|000736"))
    MSGSTOP("AS OPERAÇÕES 03 E 04 ESTÃO INDISPONÍVEIS PARA USO. ENTRE EM CONTATO COM O DEPARTAMENTO FISCAL.","ATENÇÃO")
    _LRET :=  .F. 
CASE CCODOPER=="07" .AND. !((RETCODUSR()) $ ("000000|000131|000241|000385|000095|000332|000587|000467|000728|000736"))
    MSGSTOP("AS OPERAÇÕES 07 E 08 ESTÃO INDISPONÍVEIS PARA USO. ENTRE EM CONTATO COM O DEPARTAMENTO FISCAL.","ATENÇÃO")
    _LRET :=  .F. 
CASE CCODOPER=="08" .AND. !((RETCODUSR()) $ ("000000|000131|000241|000385|000095|000332|000587|000467|000728|000736"))
    MSGSTOP("AS OPERAÇÕES 07 E 08 ESTÃO INDISPONÍVEIS PARA USO. ENTRE EM CONTATO COM O DEPARTAMENTO FISCAL.","ATENÇÃO")
    _LRET :=  .F. 
CASE CCODOPER=="36" .AND. !((RETCODUSR()) $ ("000000"))
    MSGSTOP("A OPERAÇÃO 36 FOI DESCONTINUADA E ESTÁ FORA DE USO. ENTRE EM CONTATO COM O DEPARTAMENTO FISCAL.","ATENÇÃO")
    _LRET :=  .F. 
ENDCASE
RETURN _LRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION BUSTPVEN(CTPVEN,CCAMPO)

LOCAL AAREA := GETAREA()
LOCAL AAREASX3 := SX3->(GETAREA())
LOCAL CDESCTPVEN := "          "

DBSELECTAREA("SX3")
DBSETORDER(2)
IF SX3->(MSSEEK(CCAMPO))
    CCOMBO := SX3->(X3CBOX())
    ACOMBO := STRTOKARR(CCOMBO,";")
    
    NPOS := ASCAN(ACOMBO,{|X|LEFT(X[1],2)==CTPVEN})
    
    IF NPOSARR<>0
        CDESCTPVEN := ACOMBO[NPOSARR]
    ENDIF
ENDIF

RESTAREA(AAREASX3)
RESTAREA(AAREA)

RETURN CDESCTPVEN

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION SEND2(CMAILDESTINO,CASSUNTO,CTEXTO,CANEXOS,LMENSAGEM,CMENSQDOERRO,CTPENVIO)

LOCAL LRETURN
LOCAL CTPENVIO := IIF(VALTYPE(CTPENVIO)<>"U",CTPENVIO,"D")
PRIVATE CMAILDESTINO := IIF(VALTYPE(CMAILDESTINO)<>"U",CMAILDESTINO,"")
PRIVATE LMENSAGEM := IIF(VALTYPE(LMENSAGEM)<>"U",LMENSAGEM, .T. )

IF CTPENVIO=="D"
    
    IF LMENSAGEM
        LRETURN := PROCESSA({||U_SENDMAIL2(CMAILDESTINO,CASSUNTO,CTEXTO,CANEXOS,LMENSAGEM,CMENSQDOERRO)})
    ELSE 
        LRETURN := U_SENDMAIL2(CMAILDESTINO,CASSUNTO,CTEXTO,CANEXOS,LMENSAGEM,CMENSQDOERRO)
    ENDIF
ENDIF

RETURN LRETURN

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION SENDMAIL2(CMAILDESTINO,CASSUNTO,CTEXTO,CANEXOS,LMENSAGEM,CMENSQDOERRO)

LOCAL CTITADIC :=  ALLTRIM(GETMV("ES_WFTITAD",,""))

PRIVATE CMAILCONTA := GETMV("MV_RELACNT")
PRIVATE CMAILSENHA := GETMV("MV_RELPSW")
PRIVATE CMAILSERVER := GETMV("MV_RELSERV")

CASSUNTO := IIF(TYPE(CASSUNTO)<>"U",CASSUNTO,"")
CTEXTO := IIF(VALTYPE(CTEXTO)<>"U",CTEXTO,"")
CANEXOS := IIF(VALTYPE(CANEXOS)<>"U",CANEXOS,"")
LCONEXAO :=  .F. 
LENVIO :=  .F. 
LDESCONEXAO :=  .F. 
CERRO_CONEXAO := ""
CERRO_ENVIO := ""
CERRO_DESCONEXAO := ""
CMENSQDOERRO := IIF(VALTYPE(CMENSQDOERRO)<>"U",CMENSQDOERRO,"")

IF LMENSAGEM
    PROCREGUA(3)
ENDIF

IF EMPTY(CMAILDESTINO)
    
    IF LMENSAGEM
        MSGSTOP("CONTA(S) DE EMAIL DESTINO NAO INFORMADA "+CMENSQDOERRO,)
    ENDIF
    RETURN  .F. 
ENDIF

IF EMPTY(CASSUNTO)
    
    IF LMENSAGEM
        MSGSTOP("ASSUNTO DO E-MAIL NAO INFORMADO"+CMENSQDOERRO,)
    ENDIF
    RETURN  .F. 
ENDIF

IF EMPTY(CTEXTO)
    
    IF LMENSAGEM
        MSGSTOP("TEXTO DO E-MAIL NAO INFORMADO"+CMENSQDOERRO,)
    ENDIF
    RETURN  .F. 
ENDIF

IF LMENSAGEM
    INCPROC("CONECTANDO AO SERVIDOR DE EMAIL !!!")
ENDIF

FOR NPROC := 1 TO 10
    
    IF ( .F. ) 
    LCONEXAO := CALLPROC("MAILSMTPON",CMAILSERVER,CMAILCONTA,CMAILSENHA,,,)
    ELSE
    LCONEXAO := MAILSMTPON(CMAILSERVER,CMAILCONTA,CMAILSENHA,,,)
    ENDIF
    
    IF !(LCONEXAO) .AND. NPROC==10
        
        IF ( .F. ) 
        CERRO_CONEXAO := CALLPROC("MAILGETERR")
        ELSE
        CERRO_CONEXAO := MAILGETERR()
        ENDIF
        MSGSTOP("NAO FOI POSSIVEL ESTABELECER A CONEXAO COM O SERVIDOR - "+CERRO_CONEXAO+" - "+CMENSQDOERRO,)
        RETURN  .F. 
    ENDIF
NEXT

IF GETMV("MV_RELAUTH")
    MAILAUTH(CMAILCONTA,CMAILSENHA)
ENDIF

IF LMENSAGEM
    INCPROC("ENVIANDO EMAIL !!!")
ENDIF

IF !(EMPTY(CANEXOS))
    
    IF ( .F. ) 
    LENVIO := CALLPROC("MAILSEND",CMAILCONTA,{CMAILDESTINO},{},{},CTITADIC+CASSUNTO,CTEXTO,{CANEXOS}, .T. ,,)
    ELSE
    LENVIO := MAILSEND(CMAILCONTA,{CMAILDESTINO},{},{},CTITADIC+CASSUNTO,CTEXTO,{CANEXOS}, .T. ,,)
    ENDIF
ELSE 
    
    IF ( .F. ) 
    LENVIO := CALLPROC("MAILSEND",CMAILCONTA,{CMAILDESTINO},{},{},CTITADIC+CASSUNTO,CTEXTO,{}, .T. ,,)
    ELSE
    LENVIO := MAILSEND(CMAILCONTA,{CMAILDESTINO},{},{},CTITADIC+CASSUNTO,CTEXTO,{}, .T. ,,)
    ENDIF
ENDIF

IF !(LENVIO)
    
    IF ( .F. ) 
    CERRO_ENVIO := CALLPROC("MAILGETERR")
    ELSE
    CERRO_ENVIO := MAILGETERR()
    ENDIF
    
    IF LMENSAGEM
        MSGSTOP("NAO FOI POSSIVEL ENVIAR A MENSAGEM - "+CERRO_ENVIO+" - "+CMENSQDOERRO,)
    ENDIF
    RETURN  .F. 
ENDIF

IF LMENSAGEM
    INCPROC("DESCONECTANDO DO SERVIDOR DE EMAIL !!!")
ENDIF

IF ( .F. ) 
 LDESCONEXAO := CALLPROC("MAILSMTPOFF")
 ELSE
 LDESCONEXAO := MAILSMTPOFF()
 ENDIF

IF !(LDESCONEXAO)
    
    IF ( .F. ) 
    CERRO_DESCONEXAO := CALLPROC("MAILGETERR")
    ELSE
    CERRO_DESCONEXAO := MAILGETERR()
    ENDIF
    
    IF LMENSAGEM
        MSGSTOP("NAO FOI POSSIVEL DESCONECTAR DO SERVIDOR - "+CERRO_DESCONEXAO,)
    ENDIF
    RETURN  .F. 
ENDIF

RETURN  .T. 
