#INCLUDE "protheus.ch"

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M02M02()

PRIVATE NHDL := 0
PRIVATE ASTRUCT := {}
PRIVATE ALOG := {}

CTYPE := "ARQUIVOS NAO PROCESSADOS | *.CSV | ARQUIVOS JA PROCESSADOS | *.PRC "

CARQ := CGETFILE(CTYPE,OEMTOANSI("SELECIONE O ARQUIVO DE INTERFACE"),1,"", .F. ,48+0)

IF !(FILE(CARQ))
    AVISO("ATENÇÃO !","ARQUIVO SELECIONADO NAO LOCALIZADO !",{"OK"})
    RETURN 
ENDIF

PROCESSA({||U_M02M022(CARQ)},"PROCESSANDO LEITURA...")

PROCESSA({||U_M02M023()},"PROCESSANDO GRAVAÇÃO...")

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M02M022(CARQ)

LOCAL LCONTINUA :=  .T. 
LOCAL NPROC
LOCAL CCODPROD := ""
LOCAL CCODEND := ""
LOCAL NQTDINV := 0
LOCAL CCONTAGEM := ""
LOCAL CLOCAL := ""
LOCAL CDOCUMENTO := ""
LOCAL CDATAINV := CTOD("  /  /  ")

NHDL := FT_FUSE(CARQ)

IF NHDL<>NIL .AND. NHDL<=0
    
    AVISO("ATENÇÃO !","NÃO FOI POSSÍVEL A ABERTURA DO ARQUIVO "+ ALLTRIM(CARQ)+" !",{"OK"})
    
    FT_FUSE()
    
    RETURN 
ENDIF

PROCREGUA(FT_FLASTREC())

FT_FGOTOP()
LPRIMLINHA :=  .T. 

WHILE !(FT_FEOF())
 
    INCPROC("ANALISANDO ARQUIVO...")
    
    CBUFFER :=  ALLTRIM(FT_FREADLN())
    CBUFFER :=  UPPER(CBUFFER)
    
    CBUFFER := STRTRAN(CBUFFER,'"',"")
    
    ACAMPOS := {}
    FOR NPROC := 1 TO 6
        
        NPOS := AT(";",CBUFFER)
        
        IF LPRIMLINHA .AND. NPROC==1 .AND. !((LEFT( ALLTRIM(LEFT(CBUFFER,NPOS-1)),1)) $ ("ABCDEFGHI"))
            IIF(FINDFUNCTION("APMSGSTOP"),MSGSTOP(OEMTOANSI("DIVERGÊNCIA DE LAYOUT NA PRIMEIRA COLUNA ! FAVOR VERIFICAR ! "),),MSGSTOP(OEMTOANSI("DIVERGÊNCIA DE LAYOUT NA PRIMEIRA COLUNA ! FAVOR VERIFICAR ! "),))
            LCONTINUA :=  .F. 
            EXIT 
        ENDIF
        
        IF NPOS==0 .AND. NPROC<>8
            IIF(FINDFUNCTION("APMSGSTOP"),MSGSTOP(NPROC,),MSGSTOP(NPROC,))
            IIF(FINDFUNCTION("APMSGSTOP"),MSGSTOP(OEMTOANSI("ERRO NA IMPORTAÇÂO DO ARQUIVO ! DIVERGÊNCIA DE QUANTIDADE DE COLUNAS !"),),MSGSTOP(OEMTOANSI("ERRO NA IMPORTAÇÂO DO ARQUIVO ! DIVERGÊNCIA DE QUANTIDADE DE COLUNAS !"),))
            LCONTINUA :=  .F. 
            EXIT 
        ELSEIF NPOS==0
            NPOS := 100
        ENDIF
        
        AADD(ACAMPOS,LEFT(CBUFFER,NPOS-1))
        CBUFFER :=  SUBSTR(CBUFFER,NPOS+1)
    NEXT
    
    IF !(LCONTINUA)
        EXIT 
    ENDIF
    
    CCODCONTR :=  ALLTRIM(ACAMPOS[1])
    CFORNECE :=  ALLTRIM(ACAMPOS[2])
    CLOJA :=  ALLTRIM(ACAMPOS[3])
    CPRODUTO :=  ALLTRIM(ACAMPOS[4])
    NQTDENTR :=  VAL(STRTRAN(ACAMPOS[5],",","."))
    DDTENTR := CTOD( ALLTRIM(ACAMPOS[6]))
    
    DBSELECTAREA("SB1")
    DBSETORDER(1)
    
    IF EMPTY(CCODPROD) .AND. !(LPRIMLINHA)
        IIF(FINDFUNCTION("APMSGSTOP"),MSGSTOP(OEMTOANSI("CÓDIGO DE PRODUTO EM BRANCO ! CÓDIGO : ")+CCODPROD,),MSGSTOP(OEMTOANSI("CÓDIGO DE PRODUTO EM BRANCO ! CÓDIGO : ")+CCODPROD,))
        AADD(ALOG,"CÓDIGO DE PRODUTO EM BRANCO. CÓDIGO : "+CCODPROD)
        FT_FSKIP()
        LOOP 
    
    ELSEIF !(LPRIMLINHA) .AND. !(DBSEEK(XFILIAL("SB1")+CCODPROD))
        IIF(FINDFUNCTION("APMSGSTOP"),MSGSTOP(OEMTOANSI("CÓDIGO DE PRODUTO NÃO ENCONTRADO, SOLICITAR INCLUSÃO AO DEPTO DE CADASTRO.. CÓDIGO : ")+CCODPROD,),MSGSTOP(OEMTOANSI("CÓDIGO DE PRODUTO NÃO ENCONTRADO, SOLICITAR INCLUSÃO AO DEPTO DE CADASTRO.. CÓDIGO : ")+CCODPROD,))
        AADD(ALOG,"CODIGO DA PRODUTO NÃO ENCONTRADO .. CÓDIGO : "+CCODPROD)
        FT_FSKIP()
        LOOP 
    ENDIF
    
    IF !(LPRIMLINHA)
        
        AADD(ASTRUCT,{CCODCONTR,CFORNECE,CLOJA,CPRODUTO,NQTDENTR,DDTENTR})
    ENDIF
    LPRIMLINHA :=  .F. 
    
    FT_FSKIP()
    ENDDO

FT_FUSE()

IF !(LCONTINUA)
    RETURN 
ENDIF

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M02M023()

LOCAL CPRODUTO
LOCAL NPROC

DBSELECTAREA("SC7")
DBSETORDER(1)

PROCREGUA( LEN(ASTRUCT))

FOR NPROC := 1 TO  LEN(ASTRUCT)
    
    INCPROC("GRAVANDO INVENTARIO...")
    
    CPRODUTO := LEFT(ASTRUCT[NPROC][1]+"               ",15)
    
    RECLOCK("SC7", .T. )
    SC7->C7_FILIAL := XFILIAL("SC7")
    SC7->C7_NUM := ASTRUCT[NPROC][1]
    
    SC7->C7_XENDERE := ASTRUCT[NPROC][2]
    SC7->C7_QUANT := ASTRUCT[NPROC][3]
    SC7->C7_CONTAGE := ASTRUCT[NPROC][4]
    SC7->C7_LOCAL := ASTRUCT[NPROC][5]
    SC7->C7_DOC := ASTRUCT[NPROC][6]
    SC7->C7_DATA := ASTRUCT[NPROC][7]
    SC7->C7_TIPO := POSICIONE("SB1",1,XFILIAL("SB1")+CPRODUTO,"B1_TIPO")
    SC7->C7_ORIGEM := "M02M02"
    SC7->C7_XCODUSR :=  SUBSTR(CUSUARIO,7,15)
    
    MSUNLOCK()
NEXT

IF  LEN(ALOG)>0
    IIF(FINDFUNCTION("APMSGSTOP"),MSGSTOP(OEMTOANSI("ATENÇÃO ! RELATÓRIO DE INCONSISTÊNCIAS NA IMPORTAÇÃO !"),),MSGSTOP(OEMTOANSI("ATENÇÃO ! RELATÓRIO DE INCONSISTÊNCIAS NA IMPORTAÇÃO !"),))
    U_M02M02IMP()
ENDIF

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M02M02IMP()

LOCAL NPROC

CBTXT := ""
CBCONT := ""
NORDEM := 0
TAMANHO := "P"
LIMITE := 80
TITULO := "                         IMPORTACAO AUT. ENTREGA                          "
CDESC1 := "       ESTE PROGRAMA IRA EMITIR O LOG DE IMPORTACAO DE AUT. ENTREGA       "
CDESC2 := ""
CDESC3 := ""
CNATUREZA := ""
ARETURN := {"ESPECIAL",1,"ADMINISTRACAO",1,2,1,"",1}
NOMEPROG := "M02M02"
CPERG := "M02M02"
NLASTKEY := 0
LCONTINUA :=  .T. 
NLIN := 0
WNREL := "M02M02"
AORD := {}
NTAM := 66

CSTRING := ""
WNREL := SETPRINT(CSTRING,WNREL,,TITULO,CDESC1,CDESC2,CDESC3, .F. ,AORD, .F. ,TAMANHO,, .F. )

IF NLASTKEY==27
    RETURN 
ENDIF

SETDEFAULT(ARETURN,CSTRING)

IF NLASTKEY==27
    RETURN 
ENDIF

FOR NPROC := 1 TO  LEN(ALOG)
    
    IF NLIN>50
        PRINTOUT(0,0,AVALIMP(LIMITE),)
        NLIN := 3
    ENDIF
    
    PRINTOUT(NLIN,0,ALOG[NPROC],)
    NLIN++
NEXT

SET(20,"SCREEN")

IF ARETURN[5]==1
    SET(24,"")
    DBCOMMITALL()
    OURSPOOL(WNREL)
ENDIF

MS_FLUSH()

RETURN 
