#INCLUDE "protheus.ch"

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M02R06(LENVEMAIL)

LOCAL AAREA := GETAREA()

FWMSGRUN(,{||U_M02R06A(LENVEMAIL)},"CONTRATO DE PARCEIRIA","GERANDO RELATÓRIO...")

RESTAREA(AAREA)

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M02R06A(LENVEMAIL)

LOCAL OPRINTER := NIL
LOCAL OFONT14B := NIL
LOCAL OFONT12 := NIL
LOCAL OFONT12B := NIL
LOCAL OFONT18T := NIL
LOCAL OFONT9 := NIL
LOCAL NROW := - (80)
LOCAL CDATA := DTOC(DATE())+" "+TIME()

LOCAL NTOTPED := 0
LOCAL NVALFRET := 0
LOCAL NVALDESP := 0
LOCAL NVALDESC := 0
LOCAL NVALST := 0
LOCAL CLOCAL := GETSRVPROFSTRING("STARTPATH","")

PRIVATE _CALIASSA1 := GETNEXTALIAS()
PRIVATE _OBRUSH := TBRUSH():NEW(,240+(240) * (256)+(240) * (65536))
PRIVATE _CNUMORC := SC7->C7_NUM
PRIVATE _LOK :=  .T. 
PRIVATE NPAGE := 1
PRIVATE NROWSTEP := 45

M02RFONT(@OFONT9,@OFONT12,@OFONT12B,@OFONT14B,@OFONT18T)

IF !(LENVEMAIL)
    CFILEIMP := "CP"+SC3->C3_NUM+"_"+ SUBSTR(DTOS(DATE()),7,2)+"_"+STRTRAN(TIME(),":","")
    OPRINTER := FWMSPRINTER():NEW(CFILEIMP,6, .T. ,, .T. )
ELSE 
    CFILEIMP := "CP"+SC3->C3_NUM+"_"+DTOS(DATE())
    CLOCAL := "\SPOOL\"

    FERASE(CLOCAL+CFILEIMP+".PDF")

    OPRINTER := FWMSPRINTER():NEW(CFILEIMP,6, .T. ,CLOCAL, .T. ,,,,,,, .F. )

    OPRINTER:CPATHPDF := CLOCAL
    OPRINTER:NDEVICE := 6
ENDIF

OPRINTER:SETRESOLUTION(78)
OPRINTER:SETLANDSCAPE()
OPRINTER:SETMARGIN(0,0,0,0)

OPRINTER:STARTPAGE()

MR02CAB1(OPRINTER,OFONT14B,OFONT12,@NROW)

IF MR02POSICIONA()

    MR02CAB2(OPRINTER,OFONT12,OFONT18T,@NROW,OFONT14B)

    MR02CAB4(OPRINTER,OFONT12,OFONT14B,OFONT18T,@NROW)

    M02RIITENS(OPRINTER,OFONT9,OFONT12,OFONT12B,@NROW,@NPAGE,CDATA,@NTOTPED,@NVALFRET,@NVALDESP,@NVALDESC,@NVALST)

    MR02ROD(OPRINTER,OFONT12,OFONT12B,OFONT14B,NROW,NPAGE,CDATA,@NTOTPED,@NVALFRET,@NVALDESP,@NVALDESC,@NVALST)

    OPRINTER:ENDPAGE()
    OPRINTER:PRINT()
    FREEOBJ(OPRINTER)
ENDIF

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M02RICABIT(OPRINTER,OFONT12B,NROW)

LOCAL NROWSTEP := 45
NROW += NROWSTEP

OPRINTER:BOX(NROW,100,NROW+(NROWSTEP) * (2.5),3200)

OPRINTER:BOX(NROW,180,NROW+(NROWSTEP) * (2.5),403)

OPRINTER:BOX(NROW,650,NROW+(NROWSTEP) * (2.5),1250)

OPRINTER:BOX(NROW,1400,NROW+(NROWSTEP) * (2.5),1500)

OPRINTER:BOX(NROW,1700,NROW+(NROWSTEP) * (2.5),1950)
OPRINTER:BOX(NROW,1700,NROW+(NROWSTEP) * (1.25),1950)
OPRINTER:BOX(NROW+(NROWSTEP) * (1.3),1700,NROW+(NROWSTEP) * (2.5),1770)

OPRINTER:BOX(NROW,1950,NROW+(NROWSTEP) * (1.25),2200)
OPRINTER:BOX(NROW+(NROWSTEP) * (1.3),1950,NROW+(NROWSTEP) * (2.5),2020)

OPRINTER:BOX(NROW,2200,NROW+(NROWSTEP) * (2.5),2450)
OPRINTER:BOX(NROW,2200,NROW+(NROWSTEP) * (1.25),2450)
OPRINTER:BOX(NROW+(NROWSTEP) * (1.3),2200,NROW+(NROWSTEP) * (2.5),2270)

OPRINTER:BOX(NROW,2700,NROW+(NROWSTEP) * (2.5),2950)

NROW += NROWSTEP
OPRINTER:SAY(NROW,110,"ITEM",OFONT12B)
OPRINTER:SAY(NROW,200,"DT.ENTREGA",OFONT12B)
OPRINTER:SAY(NROW,480,"CÓDIGO",OFONT12B)
OPRINTER:SAY(NROW,850,"DESCRIÇÃO",OFONT12B)
OPRINTER:SAY(NROW,1280,"MEDIDA",OFONT12B)
OPRINTER:SAY(NROW,1420,"QTD",OFONT12B)
OPRINTER:SAY(NROW,1550,"VALOR",OFONT12B)
OPRINTER:SAY(NROW+NROWSTEP,1540,"UNITÁRIO",OFONT12B)

OPRINTER:SAY(NROW,1800,"IPI",OFONT12B)
OPRINTER:SAY(NROW+NROWSTEP,1720,"%",OFONT12B)
OPRINTER:SAY(NROW+NROWSTEP,1810,"VALOR",OFONT12B)

OPRINTER:SAY(NROW,2040,"ICMS",OFONT12B)
OPRINTER:SAY(NROW+NROWSTEP,1970,"%",OFONT12B)
OPRINTER:SAY(NROW+NROWSTEP,2060,"VALOR",OFONT12B)

OPRINTER:SAY(NROW,2260,"PIS/COFINS",OFONT12B)
OPRINTER:SAY(NROW+NROWSTEP,2220,"%",OFONT12B)
OPRINTER:SAY(NROW+NROWSTEP,2300,"VALOR",OFONT12B)

OPRINTER:SAY(NROW,2490,"VALOR ICMS",OFONT12B)
OPRINTER:SAY(NROW+NROWSTEP,2540,"ST",OFONT12B)

OPRINTER:SAY(NROW,2750,"VALOR TOTAL",OFONT12B)
OPRINTER:SAY(NROW+NROWSTEP,2750,"+ FRET/DESP",OFONT12B)

OPRINTER:SAY(NROW,2980,"VALOR TOTAL",OFONT12B)
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M02RIITENS(OPRINTER,OFONT9,OFONT12,OFONT12B,NROW,NPAGE,CDATA,NTOTPED,NVALFRET,NVALDESP,NVALDESC,NVALST)
LOCAL NROWSTEP := 45
LOCAL _CALIAS := GETNEXTALIAS()
LOCAL NITEM := 0
LOCAL _NTOTAL := 0

M02RICABIT(OPRINTER,OFONT12B,@NROW)

MR02PLANIL(SC3->C3_NUM,@_CALIAS,@_NTOTAL)

NROW += NROWSTEP+10

(_CALIAS)->(DBGOTOP())

WHILE !(_CALIAS)->(EOF())
 
    NITEM++
    MR02IMPITEM(_CALIAS,OPRINTER,@NROW,OFONT9,OFONT12B,NITEM,@NTOTPED,@NVALFRET,@NVALDESP,@NVALDESC,@NVALST)

    MR02ENDPAG(OPRINTER,OFONT12,OFONT12B,@NROW,NROWSTEP,@NPAGE,CDATA,NITEM,_NTOTAL)

    (_CALIAS)->(DBSKIP())
    ENDDO

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR02IMPITEM(_CALIAS,OPRINTER,NROW,OFONT9,OFONT12B,NITEM,NTOTPED,NVALFRET,NVALDESP,NVALDESC,NVALST)
LOCAL NDESC := 1
LOCAL NROWSTEP := 45
LOCAL ADESC := {}
LOCAL CDESCB5 := ""
LOCAL CPICVAL := "@E 99,999,999.99"
LOCAL CPICALIQ := "@E 999.99"

LOCAL NTAXACOF := SUPERGETMV("MV_TXCOFIN", .F. ,0)
LOCAL NTAXAPIS := SUPERGETMV("MV_TXPIS", .F. ,0)
PRIVATE CPICQTD := "@E 999999.99"

CDESCB5 := POSICIONE("SB5",1,XFILIAL("SB5")+_CALIAS->_PRODUTO,"B5_CEME")

ADESC := M02RDESCR( ALLTRIM(_CALIAS->_PRODUTO),IIF(!(EMPTY(CDESCB5)), ALLTRIM(CDESCB5),"PRODUTO SEM COMPLEMENTO"), ALLTRIM(_CALIAS->_DESCRI),0,0,0,_CALIAS->_ITEM)

OPRINTER:BOX(NROW,100,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),3200)
OPRINTER:BOX(NROW,180,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),403)
OPRINTER:BOX(NROW,650,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),1250)
OPRINTER:BOX(NROW,1400,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),1500)
OPRINTER:BOX(NROW,1700,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),1950)
OPRINTER:BOX(NROW,1700,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),1770)
OPRINTER:BOX(NROW,1950,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),2200)
OPRINTER:BOX(NROW,1950,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),2020)
OPRINTER:BOX(NROW,2200,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),2450)
OPRINTER:BOX(NROW,2200,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),2270)
OPRINTER:BOX(NROW,2700,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),2950)

NROW += NROWSTEP
OPRINTER:SAY(NROW-8,120, SUBSTR( ALLTRIM(_CALIAS->_ITEM),1,15),OFONT9)
OPRINTER:SAY(NROW-8,225, SUBSTR(_CALIAS->_DATPRF,7,2)+"/"+ SUBSTR(_CALIAS->_DATPRF,5,2)+"/"+ SUBSTR(_CALIAS->_DATPRF,1,4),OFONT9)
OPRINTER:SAY(NROW-8,415,_CALIAS->_PRODUTO,OFONT9)
OPRINTER:SAY(NROW-8,1267,POSICIONE("SB1",1,XFILIAL("SB1")+_CALIAS->_PRODUTO,"B1_UM"),OFONT9)
OPRINTER:SAY(NROW-8,1414,TRANSFORM(NOROUND(_CALIAS->_QTDCOM,2),"@E 999999.99"),OFONT9)
OPRINTER:SAY(NROW-8,1540,TRANSFORM(NOROUND(_CALIAS->_PRUNIT,2),CPICVAL),OFONT9)
OPRINTER:SAY(NROW-8,1709,TRANSFORM(NOROUND(_CALIAS->_IPI,2),CPICALIQ),OFONT9)
OPRINTER:SAY(NROW-8,1810,TRANSFORM(NOROUND(_CALIAS->_VALIPI,2),CPICVAL),OFONT9)
OPRINTER:SAY(NROW-8,1954,TRANSFORM(NOROUND(_CALIAS->_PICM,2),CPICALIQ),OFONT9)
OPRINTER:SAY(NROW-8,2050,TRANSFORM(NOROUND(_CALIAS->_VALICM,2),CPICVAL),OFONT9)
OPRINTER:SAY(NROW-8,2210,TRANSFORM(NOROUND(NTAXACOF+NTAXAPIS,2),CPICALIQ),OFONT9)
OPRINTER:SAY(NROW-8,2290,TRANSFORM(NOROUND(_CALIAS->_VALIMP5+_CALIAS->_VALIMP6,2),CPICVAL),OFONT9)
OPRINTER:SAY(NROW-8,2550,TRANSFORM(NOROUND(_CALIAS->_ICMSRET,2),CPICVAL),OFONT9)
OPRINTER:SAY(NROW-8,2780,TRANSFORM(NOROUND(_CALIAS->_TOTAL+_CALIAS->_FRETE+_CALIAS->_DESPESA+(_CALIAS->_VALIPI) / (_CALIAS->_QTDCOM),2),CPICVAL),OFONT9)
OPRINTER:SAY(NROW-8,3010,TRANSFORM(NOROUND(_CALIAS->_TOTAL+_CALIAS->_FRETE+_CALIAS->_DESPESA+_CALIAS->_VALIPI,2),CPICVAL),OFONT12B)

NTOTPED += _CALIAS->_TOTAL+_CALIAS->_VALIPI+_CALIAS->_FRETE+_CALIAS->_DESPESA
NVALFRET += _CALIAS->_VALFRE
NVALDESP += _CALIAS->_DESPESA
NVALDESC += _CALIAS->_DESCONT
NVALST += _CALIAS->_ICMSRET

FOR NDESC := 1 TO  LEN(ADESC)
    OPRINTER:SAY(NROW-8,660,ADESC[NDESC],OFONT9)
    NROW += NROWSTEP
NEXT

NROW -= NROWSTEP
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M02RDESCR(CPROD,CDESCSB1,CDESCSC6,NCOMP,NLAR,NALT,CITEM)
LOCAL ARET := {}
LOCAL CAUX := ""
LOCAL CLETRAS := ""
LOCAL CRET := ""
LOCAL I := 0
LOCAL NTAM := 45
LOCAL NINI := 1
LOCAL NQUEBRA := 1
LOCAL CPIC := "@E 999999"

IF CPROD=="N/A"
    CDESC := CDESCSC6
ELSE 
    CDESC := CDESCSB1
    
    IF NCOMP>0 .AND. NLAR>0 .AND. NALT>0
        CDESC += " - MEDINDO: "+ ALLTRIM(TRANSFORM(NCOMP,CPIC))+" X "+ ALLTRIM(TRANSFORM(NLAR,CPIC))+" X "+ ALLTRIM(TRANSFORM(NALT,CPIC))
    ENDIF
ENDIF

REPLACE(CDESC,CHR(13)," ")

FOR I := 1 TO  LEN(CDESC)-1
    CLETRAS :=  SUBSTR(CDESC,I,2)
    
    IF CLETRAS<>"  "
        CRET += LEFT(CLETRAS,1)
    ENDIF
NEXT

IF I>0 .AND. CLETRAS<>"  "
    CRET += RIGHT(CLETRAS,1)
ENDIF

CDESC := CRET

WHILE  LEN(CDESC)>0
 
    CAUX := SUBSTRING(CDESC,1,NTAM)
    
    IF NTAM<= LEN(CDESC)
        NQUEBRA := RAT(" ",CAUX)
        
        AADD(ARET,SUBSTRING(CDESC,1,NQUEBRA))
    ELSE 
        AADD(ARET,CDESC)
        EXIT 
    ENDIF
    
    NINI := NQUEBRA++
    CDESC := SUBSTRING(CDESC,NINI, LEN(CDESC))
    ENDDO

RETURN ACLONE(ARET)

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR02POSICIONA()
LOCAL LRET :=  .T. 

SA2->(DBSETORDER(1))
SA2->(DBGOTOP())

IF !(SA2->(DBSEEK(XFILIAL("SA2")+(SC3)->(C3_FORNECE+C3_LOJA))))
    IIF(FINDFUNCTION("APMSGINFO"),MSGINFO(I18N("NÃO FORAM ENCONTRADOS DADOS DO FORNECEDOR #1 LOJA #2." + CRLF+"VERIFIQUE.",{SC3->C3_FORNECE,SC3->C3_LOJA}),"ATENÇÃO"),MSGINFO(I18N("NÃO FORAM ENCONTRADOS DADOS DO FORNECEDOR #1 LOJA #2." + CRLF+"VERIFIQUE.",{SC3->C3_FORNECE,SC3->C3_LOJA}),"ATENÇÃO"))
    LRET :=  .F. 
ENDIF

RETURN LRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M02RFONT(OFONT9,OFONT12,OFONT12B,OFONT14B,OFONT18T)
OFONT9 := TFONT():NEW("ARIAL",,9)
OFONT12 := TFONT():NEW("ARIAL",,12)
OFONT12B := TFONT():NEW("ARIAL",,12, .T. , .T. )
OFONT14B := TFONT():NEW("ARIAL",,14, .T. , .T. )
OFONT18T := TFONT():NEW("ARIAL",,18, .T. , .T. )
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR02CAB1(OPRINTER,OFONT14B,OFONT12,NROW)
LOCAL CNOME := " AÇOS MACOM INDÚSTRIA E COMERCIO LTDA"
LOCAL CENDC := "AV JULIA GAIOLLI, 474, BONSUCESSO, GUARULHOS-SP, CEP 07251-500"
LOCAL CCGC := " CNPJ: 43.553.668/0001-79 I.E.: 336.179.661.113"
LOCAL CTEL := "TELEFONE: 55 11 2085-7000"
LOCAL CMAIL := "WWW.ACOSMACOM.COM.BR"
LOCAL NROWSTEP := 45

OPRINTER:SAYBITMAP(NROW,100,GETSRVPROFSTRING("STARTPATH","")+"LOGO_M05R02.BMP",751,178)

OPRINTER:SAY(NROW,2450,CNOME,OFONT14B)
OPRINTER:SAY(NROW += NROWSTEP,2404,CENDC,OFONT12)
OPRINTER:SAY(NROW += NROWSTEP,2600,CCGC,OFONT12)
OPRINTER:SAY(NROW += NROWSTEP,2880,CTEL,OFONT12)
OPRINTER:SAY(NROW += NROWSTEP,2900,CMAIL,OFONT12)

NROW += NROWSTEP
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR02CAB2(OPRINTER,OFONT12,OFONT18T,NROW,OFONT14B)
LOCAL LRET :=  .T. 
LOCAL CMASCCPF := "@R 999.999.999-99"
LOCAL CMASCCNPJ := "@R 99.999.999/9999-99"
LOCAL NROWSTEP := 45

IF LRET
    NROW += NROWSTEP
    
    OPRINTER:SAY(NROW += NROWSTEP,100, UPPER( ALLTRIM(SA2->A2_NOME)),OFONT18T)
    OPRINTER:SAY(NROW,1800,"CNPJ/CPF: ",OFONT12)
    OPRINTER:SAY(NROW,2000,TRANSFORM( ALLTRIM(SA2->A2_CGC),IIF(SA2->A2_TIPO=="F",CMASCCPF,CMASCCNPJ)),OFONT12)
    OPRINTER:SAY(NROW += NROWSTEP,100, UPPER( ALLTRIM(SA2->A2_END)),OFONT12)
    OPRINTER:SAY(NROW,1800,"IE.: ",OFONT12)
    OPRINTER:SAY(NROW,2000,TRANSFORM( ALLTRIM(SA2->A2_INSCR),"@R 999.999.999.999"),OFONT12)
    OPRINTER:SAY(NROW,2700,"GUARULHOS, "+MR02DATE(),OFONT12)
    OPRINTER:SAY(NROW += NROWSTEP,100, UPPER( ALLTRIM(SA2->A2_BAIRRO))+" - "+ UPPER( ALLTRIM(SA2->A2_MUN))+" - "+ UPPER( ALLTRIM(SA2->A2_EST))+" - CEP: "+TRANSFORM( ALLTRIM(SA2->A2_CEP),"@R 99999-999"),OFONT12)
    
    NROW += NROWSTEP
    OPRINTER:LINE(NROW,100,NROW,3200)
    OPRINTER:SAY(NROW+70,1300,"CONTRATO DE PARCERIA",OFONT18T)
ENDIF

RETURN LRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR02CAB4(OPRINTER,OFONT12,OFONT14B,OFONT18T,NROW)
LOCAL NROWSTEP := 45
PRIVATE OBRUSH := TBRUSH():NEW(,240+(240) * (256)+(240) * (65536))

NROW += (NROWSTEP) * (2)

OPRINTER:LINE(NROW,100,NROW,3200)

OPRINTER:SAY(NROW += NROWSTEP,100,"CONTRATO DE FORNECIMENTO: ",OFONT12)
OPRINTER:SAY(NROW,640,SC3->C3_NUM,OFONT14B)

OPRINTER:SAY(NROW,2700,"FORNECEDOR/LOJA:",OFONT12)
OPRINTER:SAY(NROW,3050,SC3->C3_FORNECE+"/"+SC3->C3_LOJA,OFONT12)

OPRINTER:SAY(NROW += NROWSTEP,100,"COND PAG: ",OFONT12)
OPRINTER:SAY(NROW,440,MR02GETCPG(),OFONT12)

OPRINTER:SAY(NROW,2700,"SOLIC. COMPRA: ",OFONT12)

OPRINTER:SAY(NROW += NROWSTEP,100,"OBSERVAÇÕES",OFONT12)

OPRINTER:SAY(NROW += NROWSTEP,100,"COMPRADOR RESPONSÁVEL",OFONT12)
OPRINTER:SAY(NROW,550, ALLTRIM(USRFULLNAME(SC3->C3_USER)),OFONT12)

OPRINTER:SAY(NROW,2700,"CONTATO: ",OFONT12)
OPRINTER:SAY(NROW,3050,SC3->C3_CONTATO,OFONT12)

NROW += (NROWSTEP) * (0.5)
OPRINTER:LINE(NROW,100,NROW,3200)
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR02ROD(OPRINTER,OFONT12,OFONT12B,OFONT14B,NROW,NPAGE,CDATA,NTOTPED,NVALFRET,NVALDESP,NVALDESC,NVALST)

LOCAL NROWSTEP := 45
PRIVATE CPICVAL := "@E 99,999,999.99"
PRIVATE CPICALIQ := "@E 999.99"
PRIVATE CPICQTD := "@E 999999.99"
PRIVATE CPOLITIC := "A MACOM ADOTA A POLÍTICA DE PROIBIÇÃO DE OFERTA E/OU RECEBIMENTO DE PRESENTES/BRINDES EM TRANSAÇÕES COMERCIAIS, PREZANDO POR SUA LEGITIMIDADE, TRANSPARÊNCIA E IMPARCIALIDADE."
PRIVATE AAREA := {}

NROW += (NROWSTEP) * (5)

OPRINTER:SAY(NROW+1260,100,CPOLITIC,OFONT14B)

IF NROW>1600
    NROW := 2100+NROWSTEP

    OPRINTER:SAY(NROW += NROWSTEP,100,I18N("CONTRATO DE FORNECIMENTO #1 IMPRESSO EM #2.",{SC3->C3_NUM,CDATA}),OFONT12)
    OPRINTER:SAY(NROW,3000,I18N("PÁG. #1",{OPRINTER:NPAGECOUNT}),OFONT12)

    OPRINTER:ENDPAGE()
    OPRINTER:STARTPAGE()
    NROW := 0

    NPAGE++
ENDIF

OPRINTER:SAY(NROW,2450,"DESCONTO:",OFONT12)
OPRINTER:SAY(NROW,2900,TRANSFORM(NOROUND(NVALDESC,2),"@E 999999.99"),OFONT12)

OPRINTER:SAY(NROW += NROWSTEP,2450,"VALOR FRETE: ",OFONT12)
OPRINTER:SAY(NROW,2900,TRANSFORM(NOROUND(NVALFRET,2),"@E 999999.99"),OFONT12)

OPRINTER:SAY(NROW += NROWSTEP,2450,"DESPESA",OFONT12)
OPRINTER:SAY(NROW,2900,TRANSFORM(NOROUND(NVALDESP,2),"@E 999999.99"),OFONT12)

NROW += NROWSTEP

OPRINTER:LINE(NROW-(NROWSTEP) * (0.5),2350,NROW-(NROWSTEP) * (0.5),3200)
OPRINTER:SAY(NROW += NROWSTEP,2450,"TOTAL GERAL",OFONT14B)
OPRINTER:SAY(NROW,2900,TRANSFORM(NOROUND(NTOTPED+NVALFRET+NVALST-NVALDESC,2),"@E 9,999,999.99"),OFONT14B)

NROW += NROWSTEP
NROW += NROWSTEP

OPRINTER:SAY(NROW += NROWSTEP,2450,"AÇOS MACOM INDÚSTRIA E COMERCIO LTDA",OFONT12B)

NROW += NROWSTEP

NROW := 2100+NROWSTEP

OPRINTER:SAY(NROW += NROWSTEP,100,I18N("CONTRATO DE FORNECIMENTO #1 IMPRESSO EM #2.",{SC3->C3_NUM,CDATA}),OFONT12)
OPRINTER:SAY(NROW,3000,I18N("PÁG. #1",{OPRINTER:NPAGECOUNT}),OFONT12)

OPRINTER:SAY(NROW += NROWSTEP,100,"NOTA: SÓ ACEITAREMOS A MERCADORIA SE NA SUA NOTA FISCAL CONSTAR O NUMERO DE NOSSO CONTRATO",OFONT12)
OPRINTER:SAY(NROW += NROWSTEP,100,"AS FATURAS/BOLETOS PARA PAGAMENTOS AOS FORNECEDORES SERÃO EFETUADOS SOMENTE AS SEXTAS-FEIRAS, RESPEITANDO O PRAZO MÍNIMO ACORDADO EM CONTRATO DE FORNECIMENTO.",OFONT12)

OPRINTER:ENDPAGE()
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR02GETCPG()
LOCAL CRET := ""

SE4->(DBSETORDER(1))
SE4->(DBGOTOP())

IF SE4->(DBSEEK(XFILIAL("SE4")+SC3->C3_COND))
    CRET :=  ALLTRIM(SE4->E4_CODIGO)+": "+ ALLTRIM(SE4->E4_DESCRI)
ENDIF
RETURN CRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR02DATE()
LOCAL CDAY :=  STRZERO(DAY(SC3->C3_EMISSAO),2)
LOCAL NMON := MONTH(SC3->C3_EMISSAO)
LOCAL CMON := ""
LOCAL CYEAR := CVALTOCHAR(YEAR(SC3->C3_EMISSAO))

DO CASE 
 CASE NMON==1
CMON := "JANEIRO"
CASE NMON==2
CMON := "FEVEREIRO"
CASE NMON==3
CMON := "MARÇO"
CASE NMON==4
CMON := "ABRIL"
CASE NMON==5
CMON := "MAIO"
CASE NMON==6
CMON := "JUNHO"
CASE NMON==7
CMON := "JULHO"
CASE NMON==8
CMON := "AGOSTO"
CASE NMON==9
CMON := "SETEMBRO"
CASE NMON==10
CMON := "OUTUBRO"
CASE NMON==11
CMON := "NOVEMBRO"
CASE NMON==12
CMON := "DEZEMBRO"
ENDCASE

CRET := CDAY+" DE "+CMON+" DE "+CYEAR
RETURN CRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR02ENDPAG(OPRINTER,OFONT12,OFONT12B,NROW,NROWSTEP,NPAGE,CDATA,NITEM,_NTOTAL)
IF NROW>2000
    
    NROW := 2100+NROWSTEP
    
    OPRINTER:SAY(NROW += NROWSTEP,100,I18N("CONTRATO DE FORNECIMENTO #1 IMPRESSO EM #2.",{SC3->C3_NUM,CDATA}),OFONT12)
    OPRINTER:SAY(NROW,3000,I18N("PÁG. #1",{OPRINTER:NPAGECOUNT}),OFONT12)
    OPRINTER:SAY(NROW += NROWSTEP,2450,"AÇOS MACOM INDÚSTRIA E COMERCIO LTDA",OFONT12B)
    OPRINTER:ENDPAGE()
OPRINTER:STARTPAGE()
    NROW := 0
    
    NPAGE++
ENDIF
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR02PLANIL(CNUM,CALIASPED,_NTOTAL)

PRIVATE NBASEICM := 0
PRIVATE NVALICM := 0
PRIVATE NVALIPI := 0
PRIVATE NBASERET := 0
PRIVATE NVALRET := 0
PRIVATE NVLRTOT := 0
PRIVATE NBASEISS := 0
PRIVATE VVALISS := 0
PRIVATE NTOTVALDESC := 0
PRIVATE NC5DESC1 := 0
PRIVATE NC5DESC2 := 0
PRIVATE NC5DESC3 := 0
PRIVATE NC5DESC4 := 0
PRIVATE NC5FRETE := 0
PRIVATE NC5SEGURO := 0
PRIVATE NC5DESPESA := 0

PRIVATE CCONDICAO := ""
PRIVATE APARCELAS := {}
PRIVATE APEDCLI := {}
PRIVATE AC5RODAPE := {}
PRIVATE AFISGET := NIL
PRIVATE AFISGETSC5 := NIL
PRIVATE CKEY := ""
PRIVATE CALIASSC3 := "SC3"
PRIVATE CQRYAD := ""
PRIVATE CPEDIDO := ""
PRIVATE CCLIENT := ""
PRIVATE CNFORI := NIL
PRIVATE CSERIORI := NIL
PRIVATE NDESCONTO := 0
PRIVATE NPESLIQ := 0
PRIVATE NRECNOSD1 := NIL
PRIVATE NG := 0
PRIVATE NFRETE := 0
PRIVATE NSEGURO := 0
PRIVATE NFRETAUT := 0
PRIVATE NDESPESA := 0
PRIVATE NDESCCAB := 0
PRIVATE NPDESCAB := 0
PRIVATE NY := 0
PRIVATE NVALMERC := 0
PRIVATE NPRCLISTA := 0
PRIVATE NACRESFIN := 0
PRIVATE NCONT := 0
PRIVATE AITEMPED := {}
PRIVATE ACABPED := {}
PRIVATE NVLRTOTAL := 0
PRIVATE NVALSOL := 0

CALIASPED:=CALIASSC3:=GETNEXTALIAS()

_cQry := " SELECT SC3.R_E_C_N_O_ AS REC_CAB, "
_cQry += "        SC3.R_E_C_N_O_ AS REC_ITEM, "
_cQry += "        SC3.C3_FILIAL AS _FILIAL, "
_cQry += "        SC3.C3_NUM AS _NUM, "
_cQry += "        SC3.C3_FORNECE AS _FORNECE, "
_cQry += "        SC3.C3_LOJA AS _LOJA, "
_cQry += "        SC3.C3_EMISSAO AS _EMISSAO, "
_cQry += "        SC3.C3_DATPRF AS _DATPRF, "
_cQry += "        SC3.C3_COND AS _CONDPAG, "
_cQry += "        SC3.C3_QUANT AS _QTDCOM, "
_cQry += "        SC3.C3_PRECO AS _PRUNIT, "
_cQry += "        SC3.C3_TOTAL AS _TOTAL, "
_cQry += "        SC3.C3_FRETE AS _FRETE, "
_cQry += "        SC3.C3_VALFRE AS _VALFRE, "
_cQry += "        SC3.C3_TPFRETE AS _TFRETE, "
_cQry += "        SC3.C3_MOEDA AS _MOEDA, "
_cQry += "        SC3.C3_PRODUTO AS _PRODUTO, "
_cQry += "        SC3.C3_ITEM AS _ITEM, "
_cQry += "        SC3.C3_DATPRF AS _ENTREG, "
_cQry += "        0 AS _DESPESA, "
_cQry += "        0 AS _SEGURO, "
_cQry += "        '   ' AS _TES, "
_cQry += "        ' ' AS _CODTAB, "
_cQry += "        0 AS _VALDESC, "
_cQry += "        ' ' AS _DESCRI, "
_cQry += "        ' ' AS _UM, "
_cQry += "        0 AS _DESCONT, "
_cQry += "        ' ' AS _LOCAL, "
_cQry += "        0 AS _IPI, "
_cQry += "        0 AS _VALIPI, "
_cQry += "        0 AS _PICM, "
_cQry += "        0 AS _VALICM, "
_cQry += "        0 AS _VALIMP5, "
_cQry += "        0 AS _VALIMP6, "
_cQry += "        0 AS _ICMSRET, "
_cQry += "        SC3.C3_OBS AS _OBS, "
_cQry += "        SC3.C3_USER AS _CODUSR "
_cQry += " FROM "+RETSQLNAME("SC3")+" SC3 "
_cQry += " WHERE SC3.C3_FILIAL = '"+XFILIAL("SC3")+"' "
_cQry += "   AND SC3.C3_NUM = "+___SQLGETVALUE(CNUM)+" "
_cQry += "   AND SC3.D_E_L_E_T_= ' ' "
_cQry += " ORDER BY SC3.C3_ITEM "
__EXECSQL(CALIASPED,_cQry,{}, .F. )

(CALIASPED)->(DBGOTOP())
RETURN 
