#INCLUDE "protheus.ch"
STATIC _CPEDIDO1 := "", _CPEDIDO2 := "", _CRAPRE := ""

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M05A12(NTIPO)
PRIVATE _AAREA := GETAREA()
PRIVATE _AONLYFLD1 := {}
PRIVATE _AONLYFLD2 := {}
PRIVATE _AFIELDS1 := {}
PRIVATE _AFIELDS2 := {}

PRIVATE _CALIAS1 := ""
PRIVATE _CALIAS2 := ""
PRIVATE _CARQ1 := ""
PRIVATE _CARQ2 := ""
PRIVATE _CMSG1 := ""
PRIVATE _CMSG2 := ""
PRIVATE _CPICTURE := "@E 9,999,999,999,999.99"
PRIVATE _CTITLE := "COMPENSAÇÃO DE CLIENTE - "

PRIVATE _NVALOR1 := 0
PRIVATE _NVALOR2 := 0
PRIVATE _NSALDO1 := 0
PRIVATE _NSALDO2 := 0
PRIVATE _NSALDOC1 := 0
PRIVATE _NSALDOC2 := 0
PRIVATE _NATRASO1 := 0
PRIVATE _NATRASO2 := 0

PRIVATE _OMARK1 := NIL
PRIVATE _OMARK2 := NIL
PRIVATE _OLAYER := NIL
PRIVATE _ODLG := NIL
PRIVATE _OPAINEL1 := NIL
PRIVATE _OPAINEL2 := NIL
PRIVATE _ASIZE := FWGETDIALOGSIZE(OMAINWND)
PRIVATE _LREOPEN :=  .F. 
PRIVATE OTFONT := TFONT():NEW("COURIER NEW",,- (10), .F. )
PRIVATE ODLGCLI := NIL
PRIVATE LOK :=  .F. 
PRIVATE CCLIENTE := SPACE(TAMSX3("A1_COD")[1])
PRIVATE CLOJA := SPACE(TAMSX3("A1_LOJA")[1])

PRIVATE _ASTRU := {}
PRIVATE _CPICTUREC := "@!"
PRIVATE _CPICTUREN := "@E 9,999,999,999,999.99"
PRIVATE AROTINA := {}

CCLIENTE := IIF(VALTYPE(CCLIENTE)=="U",SPACE(TAMSX3("A1_COD")[1]),CCLIENTE)
CLOJA := IIF(VALTYPE(CLOJA)=="U",SPACE(TAMSX3("A1_LOJA")[1]),CLOJA)
NTIPO := IIF(VALTYPE(NTIPO)=="U",1,NTIPO)

_CRAPRE :=  ALLTRIM(GETMV("MV_X06A001", .F. ,"PVA"))

IF NTIPO>1
    
    IF (EMPTY(CCLIENTE)) .OR. (EMPTY(CLOJA))
        ODLGCLI := MSDIALOG():NEW(0,0,180,400,"COMPENSAÇÃO DE CLIENTE",,, .F. ,128,,,,, .T. ,,, .F. )

        TSAY():NEW(20,20,{||"CLIENTE:"},ODLGCLI,,, .F. , .F. , .F. , .T. ,,,,, .F. , .F. , .F. , .F. , .F. , .F. )
        TGET():NEW(17,50,{ | U |IIF(PCOUNT()==0,CCLIENTE,CCLIENTE := U)},ODLGCLI,100,10,,,,,, .F. ,, .T. ,, .F. ,, .F. , .F. ,, .F. , .F. ,"SA1","CCLIENTE",,,,)

        TSAY():NEW(40,20,{||"LOJA:"},ODLGCLI,,, .F. , .F. , .F. , .T. ,,,,, .F. , .F. , .F. , .F. , .F. , .F. )
        TGET():NEW(37,50,{ | U |IIF(PCOUNT()==0,CLOJA,CLOJA := U)},ODLGCLI,100,10,,,,,, .F. ,, .T. ,, .F. ,, .F. , .F. ,, .F. , .F. ,,"CLOJA",,,,)

        TBUTTON():NEW(70,55,"CONFIRMAR",ODLGCLI,{||LOK :=  .T. , ODLGCLI:END()},40,12,,, .F. , .T. , .F. ,, .F. ,,, .F. )
        TBUTTON():NEW(70,105,"CANCELAR",ODLGCLI,{||ODLGCLI:END()},40,12,,, .F. , .T. , .F. ,, .F. ,,, .F. )

        ODLGCLI:ACTIVATE(ODLGCLI:BLCLICKED,ODLGCLI:BMOVED,ODLGCLI:BPAINTED, .T. ,,,,ODLGCLI:BRCLICKED,)
    ELSE 
        LOK :=  .T. 
    ENDIF
ELSE 
    LOK :=  .T. 
    CCLIENTE := SC5->C5_CLIENTE
    CLOJA := SC5->C5_LOJACLI
ENDIF

IF LOK

    _ASTRU := M05ASTRU()
    _CALIAS1 := M05ATRAB(_ASTRU,@_CARQ1)
    _CALIAS2 := M05ATRAB(_ASTRU,@_CARQ2)

    _AFIELDS1 := M05AGETFLD( .T. )
    _AFIELDS2 := M05AGETFLD( .F. )

    _AONLYFLD1 := M05AGETOFL(_ASTRU, .T. )
    _AONLYFLD2 := M05AGETOFL(_ASTRU, .F. )

    M05ATAB1IN(_CALIAS1,@_NVALOR1,@_NSALDO1,@_NSALDOC1,@_NATRASO1,CCLIENTE,CLOJA)
    M05ATAB2IN(_CALIAS2,@_NVALOR2,@_NSALDO2,@_NSALDOC2,@_NATRASO2,CCLIENTE,CLOJA)

    _ODLG := MSDIALOG():NEW(_ASIZE[1],_ASIZE[2],_ASIZE[3],_ASIZE[4],_CTITLE+CCLIENTE+" - "+CLOJA,,, .F. ,,,,,OMAINWND, .T. ,,, .F. )
    _OLAYER := FWLAYER():NEW()
    _OLAYER:INIT(_ODLG, .T. )

    _OLAYER:ADDLINE("PANEL1",50, .F. )
    _OLAYER:ADDLINE("PANEL2",50, .T. )

    _OPAINEL1 := _OLAYER:GETLINEPANEL("PANEL1")
    _OMARK1 := FWMARKBROWSE():NEW()

    _CMSG1 := " | VLR: "+TRANSFORM(_NVALOR1,_CPICTURE)+"                  | SLD A REC.: "+TRANSFORM(_NSALDO1,_CPICTURE)+"                  | SLD A COMP.: "+TRANSFORM(_NSALDOC1,_CPICTURE)+"                  | SLD COMP.: "+TRANSFORM(_NVALOR1-_NSALDO1-_NSALDOC1,_CPICTURE)+"                  | VLR ATRASO: "+TRANSFORM(_NATRASO1,_CPICTURE)
    _CMSG2 := " | VLR: "+TRANSFORM(_NVALOR2,_CPICTURE)+"                  | SLD A REC.: "+TRANSFORM(_NSALDO2,_CPICTURE)+"                  | VLR REC.: "+TRANSFORM(_NVALOR2-_NSALDO2,_CPICTURE)+"                  | VLR ATRASO: "+TRANSFORM(_NATRASO2,_CPICTURE)

    _OMARK1:SETTEMPORARY( .T. )
    _OMARK1:SETFONTBROWSE(OTFONT)
    _OMARK1:SETALIAS(_CALIAS1)
    _OMARK1:SETDESCRIPTION(_CMSG1)
    _OMARK1:SETFIELDS(_AFIELDS1)
    _OMARK1:SETONLYFIELDS(_AONLYFLD1)
    _OMARK1:SETFIELDMARK("E1_OK")
    _OMARK1:ADDLEGEND("E1_SALDO > 0 .AND. E1_VENCREA < DATE()  ","BR_CINZA","TÍTULO VENCIDO")
    _OMARK1:ADDLEGEND("E1_XSALDO >  0 ","BR_VERDE","TÍTULO COM SALDO A COMPENSAR")
    _OMARK1:ADDLEGEND("E1_XSALDO <= 0 ","BR_VERMELHO","TÍTULO SEM SALDO A COMPENSAR")

    _OMARK1:SETMENUDEF("")
    _OMARK1:ACTIVATE(_OPAINEL1)

    _OPAINEL2 := _OLAYER:GETLINEPANEL("PANEL2")
    _OMARK2 := FWMARKBROWSE():NEW()

    _OMARK2:SETTEMPORARY( .T. )
    _OMARK2:SETALIAS(_CALIAS2)
    _OMARK2:SETDESCRIPTION(_CMSG2)
    _OMARK2:SETFIELDS(_AFIELDS2)
    _OMARK2:SETONLYFIELDS(_AONLYFLD2)
    _OMARK2:SETFIELDMARK("E1_OK")
    _OMARK2:ADDLEGEND("E1_SALDO > 0 .AND. E1_VENCREA < DATE()  ","BR_CINZA","TÍTULO VENCIDO")
    _OMARK2:ADDLEGEND("E1_SALDO > 0 .AND. E1_SALDO == E1_VALOR ","BR_VERDE","EM ABERTO")
    _OMARK2:ADDLEGEND("E1_SALDO > 0 .AND. E1_SALDO <> E1_VALOR ","BR_AZUL","PARCIALMENTE BAIXADO")
    _OMARK2:ADDLEGEND("E1_SALDO <= 0 ","BR_VERMELHO","BAIXADO")

    _OMARK2:SETMENUDEF("")

    _OMARK2:ADDBUTTON("&EXCLUIR",{||IIF(M05AEXCL(_CALIAS2,_OMARK2),(_LREOPEN :=  .T. , _ODLG:END()),)},,4)
    _OMARK2:ADDBUTTON("&SAIR",{||_LREOPEN :=  .F. ,_ODLG:END()},,4)

    _OMARK2:ACTIVATE(_OPAINEL2)

    _ODLG:ACTIVATE(_ODLG:BLCLICKED,_ODLG:BMOVED,_ODLG:BPAINTED, .T. ,,,,_ODLG:BRCLICKED,)

    RESTAREA(_AAREA)

    _CPEDIDO1 := ""
    _CPEDIDO2 := ""
    _CRAPRE := ""

    M05ADELTRA(_CALIAS1,_CARQ1)
    M05ADELTRA(_CALIAS2,_CARQ2)
ENDIF
RETURN IIF(LOK,IIF(_LREOPEN,U_M05A12(NTIPO), .T. ), .T. )

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05ADELTRA(_CALIAS,_CARQ)
IF SELECT(_CALIAS)>0
    (_CALIAS)->(DBCLOSEAREA())
ENDIF

FERASE(_CARQ+GETDBEXTENSION())
FERASE(_CARQ+ORDBAGEXT())
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05ACOMP(_CALIAS1,_CALIAS2,_OMARK1,_OMARK2)
LOCAL _LRET :=  .T. 
LOCAL _NRECNO1 := 0
LOCAL _NRECNO2 := 0
LOCAL _NVALREC := 0
LOCAL _CMSG := ""
LOCAL _CPICTURE := "@E 9,999,999,999,999.99"

PROCREGUA(3)
INCPROC("VALIDANDO TÍTULOS...")

_LRET := M05AVALID(_CALIAS1,_CALIAS2,_OMARK1,_OMARK2,@_NRECNO1,@_NRECNO2,@_CMSG)

IF _LRET
    BEGIN TRANSACTION

    INCPROC("COMPENSANDO TÍTULO...")
    _LRET := M05ABAIXA(_CALIAS1,_CALIAS2,_NRECNO1,_NRECNO2,@_NVALREC)

    INCPROC("ATUALIZANDO SALDO...")
    
    IF _LRET
        _LRET := M05ASETRA(_NRECNO1,- (_NVALREC))

        IF _LRET
            _LRET := M05ASETNF(_NRECNO2,_CALIAS1)
        ENDIF
    ENDIF

    IF !_LRET
        
        DISARMTRANSACTION()
    ENDIF

    END TRANSACTION
    MSUNLOCKALL()
ENDIF

IF _LRET
    AVISO("ATENÇÃO","VALOR DA COMPENSAÇÃO: "+TRANSFORM(_NVALREC,_CPICTURE) + CRLF+_CMSG,{"OK"},3)
ENDIF
RETURN _LRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05ABAIXA(_CALIAS1,_CALIAS2,_NRECNO1,_NRECNO2,_NVALREC)
LOCAL _NOPC := 3
LOCAL _AARRAY := {}
LOCAL _LRET :=  .T. 

_NVALREC := 0

M05AGOTO(_CALIAS1,_NRECNO1)
M05AGOTO(_CALIAS2,_NRECNO2)

_NVALREC := _CALIAS2->E1_SALDO

SE1->(DBGOTO(_NRECNO2))

_NVALREC -= SOMAABAT(SE1->E1_PREFIXO,SE1->E1_NUM,SE1->E1_PARCELA,"R",1,,SE1->E1_CLIENTE,SE1->E1_LOJA)

AADD(_AARRAY,{"E1_PREFIXO",_CALIAS2->E1_PREFIXO,NIL})
AADD(_AARRAY,{"E1_NUM",_CALIAS2->E1_NUM,NIL})
AADD(_AARRAY,{"E1_PARCELA",_CALIAS2->E1_PARCELA,NIL})
AADD(_AARRAY,{"E1_TIPO",_CALIAS2->E1_TIPO,NIL})
AADD(_AARRAY,{"E1_CLIENTE",_CALIAS2->E1_CLIENTE,NIL})
AADD(_AARRAY,{"E1_LOJA",_CALIAS2->E1_LOJA,NIL})
AADD(_AARRAY,{"AUTMOTBX","CMP",NIL})
AADD(_AARRAY,{"AUTDTBAIXA",DDATABASE,NIL})
AADD(_AARRAY,{"AUTDTCREDITO",DDATABASE,NIL})
AADD(_AARRAY,{"AUTHIST","BAIXA POR COMPENSACAO",NIL})
AADD(_AARRAY,{"AUTJUROS",0,NIL})
AADD(_AARRAY,{"AUTVALREC",_NVALREC,NIL})

LMSERROAUTO :=  .F. 

MSEXECAUTO({|X,Y|FINA070(X,Y)},_AARRAY,_NOPC)

IF LMSERROAUTO
    _LRET :=  .F. 
    If !IsBlind()
        MOSTRAERRO()
    Endif
ENDIF
RETURN _LRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05ASETNF(_NRECNO,_CALIAS)
LOCAL _LRET :=  .F. 

SE1->(DBGOTO(_NRECNO))

IF _LRET := !SE5->(EOF())
    RECLOCK("SE5", .F. )
    SE5->E5_DOCUMEN := _CALIAS->E1_PREFIXO+_CALIAS->E1_NUM+_CALIAS->E1_PARCELA+_CALIAS->E1_TIPO
    SE5->(MSUNLOCK())
ENDIF

IF !(_LRET)
    IIF(FINDFUNCTION("MSGINFO"),MSGINFO("ERRO AO ATUALIZAR HISTÓRICO COMPENSADO." + CRLF + CRLF+"OPERAÇÃO CANCELADA.","ATENÇÃO"),MSGINFO("ERRO AO ATUALIZAR HISTÓRICO COMPENSADO." + CRLF + CRLF+"OPERAÇÃO CANCELADA.","ATENÇÃO"))
ENDIF
RETURN _LRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05ASETRA(_NRECNO,_NVAL)
LOCAL _LRET :=  .F. 

SE1->(DBGOTOP())
SE1->(DBGOTO(_NRECNO))

IF !SE1->(EOF())

    _LRET :=  .T. 
ENDIF

IF !(_LRET)
    IIF(FINDFUNCTION("MSGINFO"),MSGINFO("ERRO AO ATUALIZAR SALDO A COMPENSAR." + CRLF + CRLF+"OPERAÇÃO CANCELADA.","ATENÇÃO"),MSGINFO("ERRO AO ATUALIZAR SALDO A COMPENSAR." + CRLF + CRLF+"OPERAÇÃO CANCELADA.","ATENÇÃO"))
ENDIF
RETURN _LRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05AGOTO(_CALIAS,_NRECNO)

(_CALIAS)->(DBGOTOP())

WHILE !(_CALIAS)->(EOF())
 
    IF _NRECNO==_CALIAS->E1_RECNO
        EXIT 
    ENDIF

    (_CALIAS)->(DBSKIP())
    ENDDO

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05AVALID(_CALIAS1,_CALIAS2,_OMARK1,_OMARK2,_NRECNO1,_NRECNO2,_CMSG)
LOCAL _LRET :=  .T. 
LOCAL _CPEDIDO1 := ""
LOCAL _CPEDIDO2 := ""

_CMSG := ""

IF _LRET
    _LRET := M05AMARK1(_CALIAS1,_OMARK1,@_NRECNO1,@_CPEDIDO1,@_CMSG)
ENDIF

IF _LRET
    _LRET := M05AMARK1(_CALIAS2,_OMARK2,@_NRECNO2,@_CPEDIDO2,@_CMSG)
ENDIF

IF _LRET .AND. !(_LRET := _CPEDIDO1==_CPEDIDO2)
    MSGSTOP("PEDIDOS DEVEM SER IGUAIS." + CRLF+"VERIFIQUE.",)
ENDIF

IF _LRET .AND. !(_LRET := _CALIAS2->E1_PORCJUR==0 .AND. _CALIAS2->E1_VALJUR==0)
    MSGSTOP("TAZA PERMAN. E PORC JUROS DEVEM SER IGUAIS A ZERO." + CRLF+"VERIFIQUE.",)
ENDIF

IF _LRET .AND. !(_LRET :=  ALLTRIM(_CALIAS1->E1_PREFIXO)==_CRAPRE)
    MSGSTOP(I18N("SOMENTE TÍTULOS COM PREFIXO #1 PODEM SER COMPENSADOS." + CRLF+"VERIFIQUE.",{_CRAPRE}),)
ENDIF

RETURN _LRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05AMARK1(_CALIAS,_OMARK,_NRECNO,_CPEDIDO,_CMSG)
LOCAL _LRET :=  .T. 
LOCAL _LMARK :=  .F. 
LOCAL _LSALDO :=  .T. 
LOCAL _CMARK := _OMARK:MARK()
LOCAL _NREC := (_CALIAS)->(RECNO())
LOCAL _AAREA := GETAREA()

(_CALIAS)->(DBGOTOP())

WHILE !(_CALIAS)->(EOF())
 
    IF _OMARK:ISINVERT()
        
        IF _CMARK<>_CALIAS->E1_OK
            
            IF _LMARK
                _LRET :=  .F. 
                EXIT 
            ELSE 
                _LMARK :=  .T. 
                _NRECNO := _CALIAS->E1_RECNO
                _CPEDIDO := _CALIAS->E1_PEDIDO

                _CMSG += CHR(13)+CHR(10)+"PREFIXO: "+_CALIAS->E1_PREFIXO + CRLF+"TIPO: "+_CALIAS->E1_TIPO + CRLF+"NUMERO:  "+_CALIAS->E1_NUM+" "+_CALIAS->E1_PARCELA + CRLF

                IF _CALIAS->E1_PREFIXO==_CRAPRE .AND. !(_LSALDO:=_LRET:=_CALIAS->E1_SALDO>0)
                    MSGSTOP("RECEBIMENTO NÃO POSSUI SALDO A COMPENSAR." + CRLF+"VERIFIQUE.",)
                    EXIT 
                ENDIF
            ENDIF
        ENDIF
    ELSE 
        
        IF _CMARK==_CALIAS->E1_OK
            
            IF _LMARK
                _LRET :=  .F. 
                EXIT 
            ELSE 
                _LMARK :=  .T. 
                _NRECNO := _CALIAS->E1_RECNO
                _CPEDIDO := _CALIAS->E1_PEDIDO

                _CMSG += CHR(13)+CHR(10)+"PREFIXO: "+_CALIAS->E1_PREFIXO + CRLF+"TIPO: "+_CALIAS->E1_TIPO + CRLF+"NUMERO:  "+_CALIAS->E1_NUM+" "+_CALIAS->E1_PARCELA + CRLF

                IF _CALIAS->E1_PREFIXO==_CRAPRE .AND. !(_LSALDO:=_LRET:=_CALIAS->E1_SALDO>0)
                    MSGSTOP("RECEBIMENTO NÃO POSSUI SALDO A COMPENSAR." + CRLF+"VERIFIQUE.",)
                    EXIT 
                ENDIF
            ENDIF
        ENDIF
    ENDIF

    (_CALIAS)->(DBSKIP())
    ENDDO

IF !(_LRET) .AND. _LMARK .AND. _LSALDO
    MSGSTOP("APENAS UM REGISTRO DEVE SER MARCADO." + CRLF+"VERIFIQUE.",)
ENDIF

IF !(_LMARK)
    _LRET :=  .F. 
    MSGSTOP("É OBRIGATÓRIO MARCAR UM REGISTRO.",)
ENDIF

_OMARK:GOTO(_NREC, .F. )

RESTAREA(_AAREA)
RETURN _LRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05ATAB1IN(_CALIAS1,_NVALOR1,_NSALDO1,_NSALDOC1,_NATRASO1,CCLIENTE,CLOJA)
LOCAL _ARET := {}
LOCAL _AAUX := {}
LOCAL _CALIASSE1 := GETNEXTALIAS()
PRIVATE _DBAIXA := CTOD("  /  /  ")

_cQry := " SELECT E1_FILIAL, "
_cQry += "        E1_PREFIXO, "
_cQry += "        E1_NUM, "
_cQry += "        E1_PARCELA, "
_cQry += "        E1_TIPO, "
_cQry += "        E1_VALOR, "
_cQry += "        E1_SALDO, "
_cQry += "        E1_XSALDO, "
_cQry += "        E1_PEDIDO, "
_cQry += "        E1_EMISSAO, "
_cQry += "        E1_VENCTO, "
_cQry += "        E1_VENCREA, "
_cQry += "        E1_BAIXA, "
_cQry += "        E1_CLIENTE, "
_cQry += "        E1_LOJA, "
_cQry += "        E1_NOMCLI, "
_cQry += "        E1_SITUACA, "
_cQry += "        E1_STATUS, "
_cQry += "        R_E_C_N_O_ AS E1_RECNO, "
_cQry += "        E1_XDTFAT, "
_cQry += "        E1_VALJUR, "
_cQry += "        E1_PORCJUR, "
_cQry += "        E1_DESCONT, "
_cQry += "        E1_EMIS1, "
_cQry += "        E1_JUROS "
_cQry += " FROM "+RETSQLNAME("SE1")+" SE1 "
_cQry += " WHERE E1_CLIENTE = "+___SQLGETVALUE(CCLIENTE)+" "
_cQry += "   AND E1_LOJA = "+___SQLGETVALUE(CLOJA)+" "
_cQry += "   AND (E1_PREFIXO = "+___SQLGETVALUE(_CRAPRE)+" "
_cQry += "        OR E1_TIPO = 'RA ' "
_cQry += "        OR E1_TIPO = 'NCC' "
_cQry += "        OR E1_TIPO = 'CRA') "
_cQry += "   AND SE1.D_E_L_E_T_= ' ' "
_cQry += " ORDER BY E1_FILIAL, "
_cQry += "          E1_PEDIDO, "
_cQry += "          E1_PREFIXO, "
_cQry += "          E1_NUM, "
_cQry += "          E1_PARCELA, "
_cQry += "          E1_TIPO"
__EXECSQL(_CALIASSE1,_cQry,{}, .F. )

WHILE !(_CALIASSE1)->(EOF())
 
    _AAUX := {}
    _NVALOR1 += _CALIASSE1->E1_VALOR

    IF _CALIASSE1->E1_SALDO>0 .AND. _CALIASSE1->E1_VENCREA<DATE()
        _NATRASO1 += _CALIASSE1->E1_SALDO
    ENDIF

    RECLOCK(_CALIAS1, .T. )
    _CALIAS1->E1_RECNO := _CALIASSE1->E1_RECNO
    _CALIAS1->E1_FILIAL := _CALIASSE1->E1_FILIAL
    _CALIAS1->E1_PEDIDO := _CALIASSE1->E1_PEDIDO
    _CALIAS1->E1_CLIENTE := _CALIASSE1->E1_CLIENTE
    _CALIAS1->E1_LOJA := _CALIASSE1->E1_LOJA
    _CALIAS1->E1_NOMCLI := _CALIASSE1->E1_NOMCLI

    _CALIAS1->E1_PREFIXO := _CALIASSE1->E1_PREFIXO
    _CALIAS1->E1_NUM := _CALIASSE1->E1_NUM
    _CALIAS1->E1_PARCELA := _CALIASSE1->E1_PARCELA
    _CALIAS1->E1_TIPO := _CALIASSE1->E1_TIPO

    _CALIAS1->E1_VALOR := _CALIASSE1->E1_VALOR

    IF  ALLTRIM(_CALIASSE1->E1_PREFIXO)<>_CRAPRE .AND. ( ALLTRIM(_CALIASSE1->E1_TIPO)) $ ("|RA|NCC|CRA")
        _CALIAS1->E1_SALDO := 0
        _CALIAS1->E1_XSALDO := _CALIASSE1->E1_SALDO
        _NSALDOC1 += _CALIASSE1->E1_SALDO
    ELSE 
        _CALIAS1->E1_SALDO := _CALIASSE1->E1_SALDO
        _CALIAS1->E1_XSALDO := 0
        _NSALDOC1 += _CALIASSE1->E1_XSALDO
        _NSALDO1 += _CALIASSE1->E1_SALDO
    ENDIF

    _CALIAS1->E1_VALJUR := _CALIASSE1->E1_VALJUR
    _CALIAS1->E1_PORCJUR := _CALIASSE1->E1_PORCJUR
    _CALIAS1->E1_DESCONT := _CALIASSE1->E1_DESCONT

    _CALIAS1->E1_EMISSAO := _CALIASSE1->E1_EMISSAO
    _CALIAS1->E1_VENCTO := _CALIASSE1->E1_VENCTO
    _CALIAS1->E1_VENCREA := _CALIASSE1->E1_VENCREA
    _CALIAS1->E1_BAIXA := _CALIASSE1->E1_BAIXA
    _CALIAS1->E1_SITUACA := _CALIASSE1->E1_SITUACA
    _CALIAS1->E1_STATUS := _CALIASSE1->E1_STATUS
    _CALIAS1->E1_XDTFAT := _CALIASSE1->E1_XDTFAT
    _CALIAS1->E1_EMIS1 := _CALIASSE1->E1_EMIS1
    _CALIAS1->E1_JUROS := _CALIASSE1->E1_JUROS
    (_CALIAS1)->(MSUNLOCK())

    (_CALIASSE1)->(DBSKIP())
    ENDDO

(_CALIASSE1)->(DBCLOSEAREA())
RETURN ACLONE(_ARET)

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05ATAB2IN(_CALIAS2,_NVALOR2,_NSALDO2,_NSALDOC2,_NATRASO2,CCLIENTE,CLOJA)
LOCAL _ARET := {}
LOCAL _AAUX := {}
LOCAL _CALIASSE1 := GETNEXTALIAS()

_cQry := " SELECT E1_FILIAL, "
_cQry += "        E1_PREFIXO, "
_cQry += "        E1_NUM, "
_cQry += "        E1_PARCELA, "
_cQry += "        E1_TIPO, "
_cQry += "        E1_VALOR, "
_cQry += "        E1_SALDO, "
_cQry += "        E1_XSALDO, "
_cQry += "        E1_PEDIDO, "
_cQry += "        E1_EMISSAO, "
_cQry += "        E1_VENCTO, "
_cQry += "        E1_VENCREA, "
_cQry += "        E1_BAIXA, "
_cQry += "        E1_CLIENTE, "
_cQry += "        E1_LOJA, "
_cQry += "        E1_NOMCLI, "
_cQry += "        E1_SITUACA, "
_cQry += "        E1_STATUS, "
_cQry += "        R_E_C_N_O_ AS E1_RECNO, "
_cQry += "        E1_XDTFAT, "
_cQry += "        E1_VALJUR, "
_cQry += "        E1_PORCJUR, "
_cQry += "        E1_DESCONT, "
_cQry += "        E1_EMIS1, "
_cQry += "        E1_JUROS "
_cQry += " FROM "+RETSQLNAME("SE1")+" SE1 "
_cQry += " WHERE E1_CLIENTE = "+___SQLGETVALUE(CCLIENTE)+" "
_cQry += "   AND E1_LOJA = "+___SQLGETVALUE(CLOJA)+" "
_cQry += "   AND E1_TIPO = 'NF' "
_cQry += "   AND SE1.D_E_L_E_T_= ' ' "
_cQry += " ORDER BY E1_FILIAL, "
_cQry += "          E1_PEDIDO, "
_cQry += "          E1_PREFIXO, "
_cQry += "          E1_NUM, "
_cQry += "          E1_PARCELA, "
_cQry += "          E1_TIPO"
__EXECSQL(_CALIASSE1,_cQry,{}, .F. )

WHILE !(_CALIASSE1)->(EOF())
 
    _AAUX := {}
    _NVALOR2 += _CALIASSE1->E1_VALOR
    _NSALDO2 += _CALIASSE1->E1_SALDO
    _NSALDOC2 += _CALIASSE1->E1_XSALDO

    IF _CALIASSE1->E1_SALDO>0 .AND. _CALIASSE1->E1_VENCREA<DATE()
        _NATRASO2 += _CALIASSE1->E1_SALDO
    ENDIF

    RECLOCK(_CALIAS2, .T. )
    _CALIAS2->E1_RECNO := _CALIASSE1->E1_RECNO
    _CALIAS2->E1_FILIAL := _CALIASSE1->E1_FILIAL
    _CALIAS2->E1_PEDIDO := _CALIASSE1->E1_PEDIDO
    _CALIAS2->E1_CLIENTE := _CALIASSE1->E1_CLIENTE
    _CALIAS2->E1_LOJA := _CALIASSE1->E1_LOJA
    _CALIAS2->E1_NOMCLI := _CALIASSE1->E1_NOMCLI

    _CALIAS2->E1_PREFIXO := _CALIASSE1->E1_PREFIXO
    _CALIAS2->E1_NUM := _CALIASSE1->E1_NUM
    _CALIAS2->E1_PARCELA := _CALIASSE1->E1_PARCELA
    _CALIAS2->E1_TIPO := _CALIASSE1->E1_TIPO

    _CALIAS2->E1_VALOR := _CALIASSE1->E1_VALOR
    _CALIAS2->E1_SALDO := _CALIASSE1->E1_SALDO
    _CALIAS2->E1_XSALDO := _CALIASSE1->E1_SALDO

    _CALIAS2->E1_VALJUR := _CALIASSE1->E1_VALJUR
    _CALIAS2->E1_PORCJUR := _CALIASSE1->E1_PORCJUR
    _CALIAS2->E1_DESCONT := _CALIASSE1->E1_DESCONT

    _CALIAS2->E1_EMISSAO := _CALIASSE1->E1_EMISSAO
    _CALIAS2->E1_VENCTO := _CALIASSE1->E1_VENCTO
    _CALIAS2->E1_VENCREA := _CALIASSE1->E1_VENCREA
    _CALIAS2->E1_BAIXA := _CALIASSE1->E1_BAIXA
    _CALIAS2->E1_SITUACA := _CALIASSE1->E1_SITUACA
    _CALIAS2->E1_STATUS := _CALIASSE1->E1_STATUS
    _CALIAS2->E1_XDTFAT := _CALIASSE1->E1_XDTFAT
    _CALIAS2->E1_EMIS1 := _CALIASSE1->E1_EMIS1
    _CALIAS2->E1_JUROS := _CALIASSE1->E1_JUROS
    (_CALIAS2)->(MSUNLOCK())

    (_CALIASSE1)->(DBSKIP())
    ENDDO

(_CALIASSE1)->(DBCLOSEAREA())
RETURN ACLONE(_ARET)

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05AGETOFL(_ASTRU,_LSALDO)
LOCAL _ARET := {}
LOCAL _NX := 0

FOR _NX := 1 TO  LEN(_ASTRU)
    
    IF _ASTRU[_NX][1]=="E1_XSALDO"
        
        IF _LSALDO
            AADD(_ARET,_ASTRU[_NX][1])
        ENDIF
    ELSE 
        AADD(_ARET,_ASTRU[_NX][1])
    ENDIF
NEXT
RETURN ACLONE(_ARET)

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05ASTRU()

AADD(_ASTRU,{"E1_OK","C",2,0,""})
AADD(_ASTRU,{"E1_RECNO","N",19,0,""})
AADD(_ASTRU,{"E1_FILIAL","C",TAMSX3("E1_FILIAL")[1],TAMSX3("E1_FILIAL")[2],""})
AADD(_ASTRU,{"E1_PEDIDO","C",TAMSX3("E1_PEDIDO")[1],TAMSX3("E1_PEDIDO")[2],_CPICTUREC})

AADD(_ASTRU,{"E1_PREFIXO","C",TAMSX3("E1_PREFIXO")[1],TAMSX3("E1_PREFIXO")[2],_CPICTUREC})
AADD(_ASTRU,{"E1_NUM","C",TAMSX3("E1_NUM")[1],TAMSX3("E1_NUM")[2],_CPICTUREC})
AADD(_ASTRU,{"E1_PARCELA","C",TAMSX3("E1_PARCELA")[1],TAMSX3("E1_PARCELA")[2],_CPICTUREC})
AADD(_ASTRU,{"E1_TIPO","C",TAMSX3("E1_TIPO")[1],TAMSX3("E1_TIPO")[2],_CPICTUREC})

AADD(_ASTRU,{"E1_VALOR","N",TAMSX3("E1_VALOR")[1],TAMSX3("E1_VALOR")[2],_CPICTUREN})
AADD(_ASTRU,{"E1_SALDO","N",TAMSX3("E1_SALDO")[1],TAMSX3("E1_SALDO")[2],_CPICTUREN})
AADD(_ASTRU,{"E1_XSALDO","N",TAMSX3("E1_XSALDO")[1],TAMSX3("E1_XSALDO")[2],_CPICTUREN})

AADD(_ASTRU,{"E1_VALJUR","N",TAMSX3("E1_VALJUR")[1],TAMSX3("E1_VALJUR")[2],_CPICTUREN})
AADD(_ASTRU,{"E1_PORCJUR","N",TAMSX3("E1_PORCJUR")[1],TAMSX3("E1_PORCJUR")[2],_CPICTUREN})
AADD(_ASTRU,{"E1_JUROS","N",TAMSX3("E1_JUROS")[1],TAMSX3("E1_JUROS")[2],_CPICTUREN})
AADD(_ASTRU,{"E1_DESCONT","N",TAMSX3("E1_DESCONT")[1],TAMSX3("E1_DESCONT")[2],_CPICTUREN})

AADD(_ASTRU,{"E1_CLIENTE","C",TAMSX3("E1_CLIENTE")[1],TAMSX3("E1_CLIENTE")[2],_CPICTUREC})
AADD(_ASTRU,{"E1_LOJA","C",TAMSX3("E1_LOJA")[1],TAMSX3("E1_LOJA")[2],_CPICTUREC})
AADD(_ASTRU,{"E1_NOMCLI","C",TAMSX3("E1_NOMCLI")[1],TAMSX3("E1_NOMCLI")[2],_CPICTUREC})

AADD(_ASTRU,{"E1_EMISSAO","D",TAMSX3("E1_EMISSAO")[1],TAMSX3("E1_EMISSAO")[2],""})
AADD(_ASTRU,{"E1_XDTFAT","D",TAMSX3("E1_XDTFAT")[1],TAMSX3("E1_XDTFAT")[2],""})
AADD(_ASTRU,{"E1_EMIS1","D",TAMSX3("E1_EMIS1")[1],TAMSX3("E1_EMIS1")[2],""})
AADD(_ASTRU,{"E1_VENCTO","D",TAMSX3("E1_VENCTO")[1],TAMSX3("E1_VENCTO")[2],""})
AADD(_ASTRU,{"E1_VENCREA","D",TAMSX3("E1_VENCREA")[1],TAMSX3("E1_VENCREA")[2],""})
AADD(_ASTRU,{"E1_BAIXA","D",TAMSX3("E1_BAIXA")[1],TAMSX3("E1_BAIXA")[2],""})
AADD(_ASTRU,{"E1_SITUACA","C",TAMSX3("E1_SITUACA")[1],TAMSX3("E1_SITUACA")[2],"!"})
AADD(_ASTRU,{"E1_STATUS","C",TAMSX3("E1_STATUS")[1],TAMSX3("E1_STATUS")[2],"!"})
RETURN ACLONE(_ASTRU)

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05ATRAB(_ASTRU,_CARQ)
LOCAL _CALIAS := GETNEXTALIAS()

//_CARQ := CRIATRAB(_ASTRU, .F. )+GETDBEXTENSION()
//
//DBCREATE(_CARQ,_ASTRU)
//DBUSEAREA( .T. ,__LOCALDRIVER,_CARQ,_CALIAS, .F. )



//Cria a temporária
oTempTable := FWTemporaryTable():New(_CALIAS)
 

 
//Define as colunas usadas
oTempTable:SetFields( _ASTRU )
 

 
//Efetua a criação da tabela
oTempTable:Create()



RETURN _CALIAS

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05AGETFLD(_LSALDO)
LOCAL _ARET := {}
LOCAL _CPICTUREC := "@!"
LOCAL _CPICTUREN := "@E 9,999,999,999,999.99"

AADD(_ARET,{"FILIAL","E1_FILIAL","C",TAMSX3("E1_FILIAL")[1],TAMSX3("E1_FILIAL")[2],""})
AADD(_ARET,{"PEDIDO","E1_PEDIDO","C",TAMSX3("E1_PEDIDO")[1],TAMSX3("E1_PEDIDO")[2],_CPICTUREC})

AADD(_ARET,{"PREFIXO","E1_PREFIXO","C",TAMSX3("E1_PREFIXO")[1],TAMSX3("E1_PREFIXO")[2],_CPICTUREC})
AADD(_ARET,{"NÚMERO","E1_NUM","C",TAMSX3("E1_NUM")[1],TAMSX3("E1_NUM")[2],_CPICTUREC})
AADD(_ARET,{"PARCELA","E1_PARCELA","C",TAMSX3("E1_PARCELA")[1],TAMSX3("E1_PARCELA")[2],_CPICTUREC})
AADD(_ARET,{"TIPO","E1_TIPO","C",TAMSX3("E1_TIPO")[1],TAMSX3("E1_TIPO")[2],_CPICTUREC})
AADD(_ARET,{"VALOR","E1_VALOR","N",TAMSX3("E1_VALOR")[1],TAMSX3("E1_VALOR")[2],_CPICTUREN})

AADD(_ARET,{"SALDO (RECEBER)","E1_SALDO","N",TAMSX3("E1_SALDO")[1],TAMSX3("E1_SALDO")[2],_CPICTUREN})

IF _LSALDO
    AADD(_ARET,{"SALDO (COMPENSAR)","E1_XSALDO","N",TAMSX3("E1_XSALDO")[1],TAMSX3("E1_XSALDO")[2],_CPICTUREN})
ENDIF

AADD(_ARET,{"TX PERMAN.","E1_VALJUR","N",TAMSX3("E1_VALJUR")[1],TAMSX3("E1_VALJUR")[2],""})
AADD(_ARET,{"PORC JUROS","E1_PORCJUR","N",TAMSX3("E1_PORCJUR")[1],TAMSX3("E1_PORCJUR")[2],""})
AADD(_ARET,{"DESCONTO","E1_DESCONT","N",TAMSX3("E1_DESCONT")[1],TAMSX3("E1_DESCONT")[2],""})
AADD(_ARET,{"JUROS","E1_JUROS","N",TAMSX3("E1_JUROS")[1],TAMSX3("E1_JUROS")[2],""})

AADD(_ARET,{"CLIENTE","E1_CLIENTE","C",TAMSX3("E1_CLIENTE")[1],TAMSX3("E1_CLIENTE")[2],_CPICTUREC})
AADD(_ARET,{"LOJA","E1_LOJA","C",TAMSX3("E1_LOJA")[1],TAMSX3("E1_LOJA")[2],_CPICTUREC})
AADD(_ARET,{"NOME","E1_NOMCLI","C",TAMSX3("E1_NOMCLI")[1],TAMSX3("E1_NOMCLI")[2],_CPICTUREC})

AADD(_ARET,{"EMISSÃO","E1_EMISSAO","D",TAMSX3("E1_EMISSAO")[1],TAMSX3("E1_EMISSAO")[2],""})
AADD(_ARET,{"DT FAT.","E1_XDTFAT","D",TAMSX3("E1_XDTFAT")[1],TAMSX3("E1_XDTFAT")[2],""})
AADD(_ARET,{"DT CONTAB.","E1_EMIS1","D",TAMSX3("E1_EMIS1")[1],TAMSX3("E1_EMIS1")[2],""})
AADD(_ARET,{"VENCIMENTO","E1_VENCTO","D",TAMSX3("E1_VENCTO")[1],TAMSX3("E1_VENCTO")[2],""})
AADD(_ARET,{"VENC. REAL","E1_VENCREA","D",TAMSX3("E1_VENCREA")[1],TAMSX3("E1_VENCREA")[2],""})
AADD(_ARET,{"BAIXA","E1_BAIXA","D",TAMSX3("E1_BAIXA")[1],TAMSX3("E1_BAIXA")[2],""})
AADD(_ARET,{"SITUAÇÃO","E1_SITUACA","C",TAMSX3("E1_SITUACA")[1],TAMSX3("E1_SITUACA")[2],"!"})
AADD(_ARET,{"STATUS","E1_STATUS","C",TAMSX3("E1_STATUS")[1],TAMSX3("E1_STATUS")[2],"!"})
AADD(_ARET,{"RECNO","E1_RECNO","N",14,0,""})
RETURN ACLONE(_ARET)

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MENUDEF()
LOCAL AROTINA := {}

AADD(AROTINA,{"PESQUISAR","PESQBRW",0,1,0, .T. })
RETURN ACLONE(AROTINA)

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05AEXCL(_CALIAS2,_OMARK)
LOCAL _LRET :=  .T. 
LOCAL _CPEDIDO := ""
LOCAL _CMSG := ""
LOCAL _CPICTURE := "@E 9,999,999,999,999.99"
LOCAL _NRECNORA := 0
LOCAL _NRECNO2 := 0
LOCAL _NRECNOB := 0
LOCAL _NVALREC := 0

IF _LRET
    _LRET := M05AMARK1(_CALIAS2,_OMARK,@_NRECNO2,@_CPEDIDO,@_CMSG)
ENDIF

IF _LRET
    _LRET := M05AGETBAI(_CALIAS2,_NRECNO2,@_NRECNOB,@_NRECNORA)
ENDIF

IF _LRET
    BEGIN TRANSACTION
    
    FWMSGRUN(,{||_LRET := M05AEXCLUI(_NRECNO2,_NRECNOB,@_NVALREC)},,"EXCLUINDO COMPENSAÇÃO...")
    
    IF _LRET
        FWMSGRUN(,{||_LRET := M05ASETRA(_NRECNORA,+ (_NVALREC))},,"ATUALIZANDO SALDO...")
    ENDIF
    
    IF !_LRET
        DISARMTRANSACTION()
    ENDIF

    END TRANSACTION
    MSUNLOCKALL()
ENDIF

IF _LRET
    AVISO("ATENÇÃO","VALOR DA EXCLUSÃO: "+TRANSFORM(_NVALREC,_CPICTURE) + CRLF+_CMSG,{"OK"},3)
ENDIF
RETURN _LRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05AGETBAI(_CALIAS2,_NRECNO2,_NRECNOB,_NRECNORA)
LOCAL _LRET :=  .T. 
LOCAL _CLISTBOX := ""
LOCAL _ABAIXAS := {}
LOCAL _ABAIXASEL := {}
LOCAL _ODLGEX := NIL
LOCAL _NOPBAIXA,_NX := 0
LOCAL _ASIZE := FWGETDIALOGSIZE(OMAINWND)
PRIVATE _CPICTURE := "@E 9,999,999,999,999.99"

_ABAIXAS := M05ASELSE5(_NRECNO2)

_LRET :=  LEN(_ABAIXAS)>0

IF !(_LRET)
    MSGSTOP("NÃO FORAM ENCONTRADAS BAIXAS PARA ESTE TÍTULO." + CRLF+"VERIFIQUE.",)
ELSE 

    IF  LEN(_ABAIXAS)>0
        FOR _NX := 1 TO  LEN(_ABAIXAS)
            AADD(_ABAIXASEL,_ABAIXAS[_NX][1])
        NEXT

        _CLISTBOX := _ABAIXASEL[1]

        _ODLGEX := MSDIALOG():NEW(_ASIZE[1],_ASIZE[2],28,100,"ESCOLHA A BAIXA",,, .F. ,,,,,, .F. ,,, .F. )

        TLISTBOX():NEW(2.5,2,{ | U |IIF(PCOUNT()==0,_CLISTBOX,_CLISTBOX := U)},_ABAIXASEL,360,153,,,,,, .F. , .F. ,,_ODLGEX:OFONT,, .F. ,,,, .F. , .F. ,)
        SBUTTON():NEW(10,17,1,{||_NOPBAIXA := 1, _ODLGEX:END()},_ODLGEX, .T. ,,)
        SBUTTON():NEW(10,55,2,{||_ODLGEX:END()},_ODLGEX, .T. ,,)

        _ODLGEX:ACTIVATE(_ODLGEX:BLCLICKED,_ODLGEX:BMOVED,_ODLGEX:BPAINTED, .T. ,,,,_ODLGEX:BRCLICKED,)
    ENDIF

    IF _LRET := _NOPBAIXA==1
        FOR _NX := 1 TO  LEN(_ABAIXAS)
            
            IF _ABAIXAS[_NX][1]==_CLISTBOX
                _NRECNOB := _ABAIXAS[_NX][2]
                _NRECNORA := _ABAIXAS[_NX][3]
                EXIT 
            ENDIF
        NEXT

        _LRET := F070VENBX(_ABAIXAS,_NX)
    ELSE 
        MSGSTOP("NENHUMA BAIXA FOI SELECIONADA.",)
    ENDIF
ENDIF
RETURN _LRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05ASELSE5(_NRECNO2)
LOCAL _ARET := {}
LOCAL _CALIAS := GETNEXTALIAS()
LOCAL _CPICTURE := "@E 9,999,999,999,999.99"
LOCAL _CPREFIXO := ""
LOCAL _CNUMERO := ""
LOCAL _CPARCELA := ""
LOCAL _CTIPO := ""

SE1->(DBGOTO(_NRECNO2))

_CPREFIXO := SE1->E1_PREFIXO
_CNUMERO := SE1->E1_NUM
_CPARCELA := SE1->E1_PARCELA
_CTIPO := SE1->E1_TIPO

_cQry := " SELECT E5_PREFIXO, "
_cQry += "        E5_NUMERO, "
_cQry += "        E5_PARCELA, "
_cQry += "        E5_TIPO, "
_cQry += "        E5_CLIFOR, "
_cQry += "        E5_LOJA, "
_cQry += "        E5_DATA, "
_cQry += "        E5_VALOR, "
_cQry += "        E5_DOCUMEN, "
_cQry += "        E5_SEQ, "
_cQry += "        SE5.R_E_C_N_O_ AS E5_RECNO, "
_cQry += "        SE1.R_E_C_N_O_ AS E1_RECNO "
_cQry += " FROM "+RETSQLNAME("SE5")+" SE5 "
_cQry += " INNER JOIN SE1010 SE1 ON E1_FILIAL = '"+XFILIAL("SE1")+"' "
_cQry += " AND SE1.D_E_L_E_T_= ' ' "
_cQry += " AND E1_PREFIXO + E1_NUM + E1_PARCELA + E1_TIPO = E5_DOCUMEN "
_cQry += " WHERE E5_FILIAL = '"+XFILIAL("SE5")+"' "
_cQry += "   AND SE5.D_E_L_E_T_= ' ' "
_cQry += "   AND E5_PREFIXO = "+___SQLGETVALUE(_CPREFIXO)+" "
_cQry += "   AND E5_NUMERO = "+___SQLGETVALUE(_CNUMERO)+" "
_cQry += "   AND E5_PARCELA = "+___SQLGETVALUE(_CPARCELA)+" "
_cQry += "   AND E5_TIPO = "+___SQLGETVALUE(_CTIPO)+" "
_cQry += "   AND E5_DOCUMEN <> ''"
__EXECSQL(_CALIAS,_cQry,{}, .F. )

WHILE !(_CALIAS)->(EOF())
 
    AADD(_ARET,{DTOC(_CALIAS->E5_DATA)+" "+_CALIAS->E5_PREFIXO+" "+_CALIAS->E5_NUMERO+" "+_CALIAS->E5_PARCELA+" "+_CALIAS->E5_TIPO+" "+TRANSFORM(_CALIAS->E5_VALOR,_CPICTURE)+" "+_CALIAS->E5_SEQ+" "+_CALIAS->E5_DOCUMEN,_CALIAS->E5_RECNO,_CALIAS->E1_RECNO})
    (_CALIAS)->(DBSKIP())
    ENDDO

(_CALIAS)->(DBCLOSEAREA())
RETURN ACLONE(_ARET)

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05AEXCLUI(_NRECNO2,_NRECNOB,_NVALREC)
LOCAL _NOPC := 6
LOCAL _AARRAY := {}
LOCAL _LRET :=  .T. 
LOCAL _NOPBAIXA := 1

PERGUNTE("FIN070", .F. )

SE1->(DBSETORDER(1))
SE1->(DBGOTO(_NRECNO2))

SE5->(DBSETORDER(1))
SE5->(DBGOTO(_NRECNOB))

_NVALREC := SE5->E5_VALOR
_NOPBAIXA :=  VAL(SE5->E5_SEQ)

AADD(_AARRAY,{"E1_PREFIXO",SE1->E1_PREFIXO,NIL})
AADD(_AARRAY,{"E1_NUM",SE1->E1_NUM,NIL})
AADD(_AARRAY,{"E1_PARCELA",SE1->E1_PARCELA,NIL})
AADD(_AARRAY,{"E1_TIPO",SE1->E1_TIPO,NIL})
AADD(_AARRAY,{"E1_CLIENTE",SE1->E1_CLIENTE,NIL})
AADD(_AARRAY,{"E1_LOJA",SE1->E1_LOJA,NIL})
AADD(_AARRAY,{"AUTMOTBX",SE5->E5_MOTBX,NIL})

LMSERROAUTO :=  .F. 

MSEXECAUTO({|X,Y,W,Z|FINA070(X,Y,W,Z)},_AARRAY,_NOPC, .F. ,_NOPBAIXA)

IF LMSERROAUTO
    _LRET :=  .F. 
    	If (!IsBlind()) // COM INTERFACE GRÁFICA
	MostraErro() // TELA
Else // EM ESTADO DE JOB
	cError := MostraErro("/dirdoc", "error.log") // ARMAZENA A MENSAGEM DE ERRO

	ConOut(PadC("Automatic routine ended with error", 80))
	ConOut("Error: "+ cError)
EndIf

ENDIF
RETURN _LRET
