#INCLUDE "protheus.ch"

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M05A01(_CFUNC,LATUOPER)
LOCAL _NPRECOVEND := 0
LOCAL _CTIPO := ""
LOCAL _CTIPOCLI := ""

LOCAL _NXPRCTAB := 0
LOCAL _CPRODUTO := ""
LOCAL _CTES := ""

LOCAL _NALIQIMP := 0
LOCAL _NPIS := 0
LOCAL _NCOFINS := 0
LOCAL _NICMS := 0
LOCAL _NICMORI := 0
LOCAL _NICMDES := 0
LOCAL _NIPI := 0

LOCAL _NALIQICM := 0
LOCAL _NALIQFCP := 0
LOCAL _NXVLRIMP := 0

LOCAL _CCLIENT := ""
LOCAL _CLOJA := ""
LOCAL _NQTD := 0
LOCAL _NBASICM := 0

LOCAL _NSOL := 0

LATUOPER := IIF(VALTYPE(LATUOPER)=="U", .T. ,LATUOPER)

SETPRCTAB(_CFUNC)

IF LATUOPER
    SETOPER(_CFUNC)
ENDIF

IF LATUOPER
    SETTES(_CFUNC)
ENDIF

MAFISEND()

GETVALUEIT(_CFUNC,@_CPRODUTO,@_CTES,@_NXPRCTAB,@_NQTD,@_NBASICM)
GETVALUECA(_CFUNC,@_CTIPO,@_CTIPOCLI,@_CCLIENT,@_CLOJA)

MAFISINI(_CCLIENT,_CLOJA,_CTIPO,"N",_CTIPOCLI,NIL,NIL,NIL,NIL,"MATA410")

MAFISADD(_CPRODUTO,_CTES,1,_NXPRCTAB-0,0,"","",NIL,0,0,0,0,_NXPRCTAB,0)

_NALIQICM := MAFISRET(1,"IT_ALIQICM")
_NPIS := GETPIS("ALIQ")
_NCOFINS := GETCOFINS("ALIQ")
_NICMS := GETICM("ALIQ",_CTES,_NALIQICM)
_NICMORI := GETICMORI("ALIQ",_NALIQICM)
_NICMDES := GETICMDES("ALIQ",_NALIQICM)
_NALIQFCP := GETFCP("ALIQ")
_NIPI := GETIPI("ALIQ",_NICMS,_NICMORI,_NICMDES,_NALIQFCP,_CTES,_CPRODUTO,_CTIPOCLI)
_NSOL := GETSOL("ALIQ")

MAFISEND()

_NALIQIMP := _NPIS+_NCOFINS+_NICMS+_NICMORI+_NICMDES+_NIPI+_NALIQFCP
_NPRECOVEND := A410ARRED((_NXPRCTAB) / (((_NALIQIMP) / (100)-1) * (- (1))),"C6_PRCVEN")

SETPRCVEN(_CFUNC,_NPRECOVEND)
SETALIIMP(_CFUNC,_NPIS,_NCOFINS,_NICMS,_NICMORI,_NICMDES,_NALIQFCP,_NIPI,_NALIQIMP,_NSOL)

MAFISINI(_CCLIENT,_CLOJA,_CTIPO,"N",_CTIPOCLI,NIL,NIL,NIL,NIL,"MATA410")

MAFISADD(_CPRODUTO,_CTES,1,_NPRECOVEND-0,0,"","",NIL,0,0,0,0,(_NPRECOVEND) * (1),0)

_NPIS := GETPIS("VLR")
_NCOFINS := GETCOFINS("VLR")
_NICMS := GETICM("VLR")
_NICMORI := GETICMORI("VLR",_NALIQICM)
_NICMDES := GETICMDES("VLR",_NALIQICM)
_NALIQFCP := GETFCP("VLR")
_NIPI := GETIPI("VLR",_NICMS,_NICMORI,_NICMDES,_NALIQFCP,"","",_CTIPOCLI)
_NXVLRIMP := MAFISRET(,"NF_TOTAL")
_NSOL := GETSOL("VLR")

SETPRCIMP(_CFUNC,_NPIS,_NCOFINS,_NICMS,_NICMORI,_NICMDES,_NALIQFCP,_NIPI,_NXVLRIMP,_NBASICM,_NSOL)
SETVLUNIT(_CFUNC,_NPRECOVEND,_NQTD)

MAFISEND()

U_M05A03(_CFUNC)

RETURN _NPRECOVEND

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION SETVLUNIT(_CFUNC,_NPRECOVEND,_NQTD)
LOCAL _NTOTALSOL := 0
LOCAL _NTOTALPS2 := 0
LOCAL _NTOTALCF2 := 0
LOCAL _NTOTALDIF := 0
LOCAL _NTOTALIPI := 0
LOCAL _NTOTALICM := 0
LOCAL _NTOTICORI := 0
LOCAL _NTOTICDES := 0
LOCAL _NTOTALIMP := 0

DO CASE 
 CASE _CFUNC=="PV"
_NTOTALSOL := A410ARRED((GDFIELDGET("C6_XVLUSOL",N)) * (_NQTD),"C6_XVLTSOL")
_NTOTALPS2 := A410ARRED((GDFIELDGET("C6_XVLUPS2",N)) * (_NQTD),"C6_XVLTPS2")
_NTOTALCF2 := A410ARRED((GDFIELDGET("C6_XVLUCF2",N)) * (_NQTD),"C6_XVLTCF2")
_NTOTALDIF := A410ARRED((GDFIELDGET("C6_XVLUFCP",N)) * (_NQTD),"C6_XVLTFCP")
_NTOTALIPI := A410ARRED((GDFIELDGET("C6_XVLUIPI",N)) * (_NQTD),"C6_XVLTIPI")
_NTOTALICM := A410ARRED((GDFIELDGET("C6_XVLUICM",N)) * (_NQTD),"C6_XVLTICM")
_NTOTICORI := A410ARRED((GDFIELDGET("C6_XVLUICO",N)) * (_NQTD),"C6_XVLTICO")
_NTOTICDES := A410ARRED((GDFIELDGET("C6_XVLUICD",N)) * (_NQTD),"C6_XVLTICD")
_NTOTALIMP := A410ARRED((GDFIELDGET("C6_XVLUIMP",N)) * (_NQTD),"C6_XVLTIMP")

CASE _CFUNC=="OV"

_NTOTALSOL := A410ARRED(((TMP1)->(FIELDGET(FIELDPOS("CK_XVLUSOL")))) * (_NQTD),"CK_XVLTSOL")
_NTOTALPS2 := A410ARRED(((TMP1)->(FIELDGET(FIELDPOS("CK_XVLUPS2")))) * (_NQTD),"CK_XVLTPS2")
_NTOTALCF2 := A410ARRED(((TMP1)->(FIELDGET(FIELDPOS("CK_XVLUCF2")))) * (_NQTD),"CK_XVLTCF2")
_NTOTALDIF := A410ARRED(((TMP1)->(FIELDGET(FIELDPOS("CK_XVLUFCP")))) * (_NQTD),"CK_XVLTFCP")
_NTOTALIPI := A410ARRED(((TMP1)->(FIELDGET(FIELDPOS("CK_XVLUIPI")))) * (_NQTD),"CK_XVLTIPI")
_NTOTALICM := A410ARRED(((TMP1)->(FIELDGET(FIELDPOS("CK_XVLUICM")))) * (_NQTD),"CK_XVLTICM")
_NTOTICORI := A410ARRED(((TMP1)->(FIELDGET(FIELDPOS("CK_XVLUICO")))) * (_NQTD),"CK_XVLTICO")
_NTOTICDES := A410ARRED(((TMP1)->(FIELDGET(FIELDPOS("CK_XVLUICD")))) * (_NQTD),"CK_XVLTICD")
_NTOTALIMP := A410ARRED(((TMP1)->(FIELDGET(FIELDPOS("CK_XVLUIMP")))) * (_NQTD),"CK_XVLTIMP")
ENDCASE

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION SETPRCIMP(_CFUNC,_NPIS,_NCOFINS,_NICMS,_NICMORI,_NICMDES,_NALIQFCP,_NIPI,_NXVLRIMP,_NBASICM,_NSOL)

DO CASE 
 CASE _CFUNC=="PV"

GDFIELDPUT("C6_XVLUSOL",_NSOL,N)
GDFIELDPUT("C6_XVLUIPI",_NIPI,N)
GDFIELDPUT("C6_XVLUICM",_NICMS,N)
GDFIELDPUT("C6_XVLUICO",_NICMORI,N)
GDFIELDPUT("C6_XVLUICD",_NICMDES,N)
GDFIELDPUT("C6_XVLUPS2",_NPIS,N)
GDFIELDPUT("C6_XVLUCF2",_NCOFINS,N)
GDFIELDPUT("C6_XVLUFCP",_NALIQFCP,N)
GDFIELDPUT("C6_XVLUBRU",_NXVLRIMP,N)
GDFIELDPUT("C6_XVLUIMP",_NPIS+_NCOFINS+_NICMS+_NICMORI+_NICMDES+_NALIQFCP+_NIPI,N)

GDFIELDPUT("C6_XBASICM",_NBASICM,N)

CASE _CFUNC=="OV"
(TMP1)->(FIELDPUT(FIELDPOS("CK_XVLUSOL"),_NSOL))
(TMP1)->(FIELDPUT(FIELDPOS("CK_XVLUIPI"),_NIPI))
(TMP1)->(FIELDPUT(FIELDPOS("CK_XVLUICM"),_NICMS))
(TMP1)->(FIELDPUT(FIELDPOS("CK_XVLUICO"),_NICMORI))
(TMP1)->(FIELDPUT(FIELDPOS("CK_XVLUICD"),_NICMDES))
(TMP1)->(FIELDPUT(FIELDPOS("CK_XVLUPS2"),_NPIS))
(TMP1)->(FIELDPUT(FIELDPOS("CK_XVLUCF2"),_NCOFINS))
(TMP1)->(FIELDPUT(FIELDPOS("CK_XVLUFCP"),_NALIQFCP))
(TMP1)->(FIELDPUT(FIELDPOS("CK_XVLUBRU"),_NXVLRIMP))
(TMP1)->(FIELDPUT(FIELDPOS("CK_XVLUIMP"),_NPIS+_NCOFINS+_NICMS+_NICMORI+_NICMDES+_NALIQFCP+_NIPI))
ENDCASE
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION SETALIIMP(_CFUNC,_NPIS,_NCOFINS,_NICMS,_NICMORI,_NICMDES,_NALIQFCP,_NIPI,_NALIQIMP,_NSOL)

DO CASE 
 CASE _CFUNC=="PV"
GDFIELDPUT("C6_XALQIPI",_NIPI,N)
GDFIELDPUT("C6_XALQICM",_NICMS,N)
GDFIELDPUT("C6_XALQICO",_NICMORI,N)
GDFIELDPUT("C6_XALQICD",_NICMDES,N)
GDFIELDPUT("C6_XALQPS2",_NPIS,N)
GDFIELDPUT("C6_XALQCF2",_NCOFINS,N)
GDFIELDPUT("C6_XALQFCP",_NALIQFCP,N)
GDFIELDPUT("C6_XALQIMP",_NALIQIMP,N)
GDFIELDPUT("C6_XALQSOL",_NSOL,N)

CASE _CFUNC=="OV"
(TMP1)->(FIELDPUT(FIELDPOS("CK_XALQIPI"),_NIPI))
(TMP1)->(FIELDPUT(FIELDPOS("CK_XALQICM"),_NICMS))
(TMP1)->(FIELDPUT(FIELDPOS("CK_XALQICO"),_NICMORI))
(TMP1)->(FIELDPUT(FIELDPOS("CK_XALQICD"),_NICMDES))
(TMP1)->(FIELDPUT(FIELDPOS("CK_XALQPS2"),_NPIS))
(TMP1)->(FIELDPUT(FIELDPOS("CK_XALQCF2"),_NCOFINS))
(TMP1)->(FIELDPUT(FIELDPOS("CK_XALQFCP"),_NALIQFCP))
(TMP1)->(FIELDPUT(FIELDPOS("CK_XALQIMP"),_NALIQIMP))
(TMP1)->(FIELDPUT(FIELDPOS("CK_XALQSOL"),_NSOL))
ENDCASE
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION SETPRCVEN(_CFUNC,_NRET,LATUVALOR)

LATUVALOR := IIF(VALTYPE(LATUVALOR)=="U", .F. ,LATUVALOR)

DO CASE 
 CASE _CFUNC=="PV"

GDFIELDPUT("C6_PRCVEN",_NRET,N)
GDFIELDPUT("C6_PRUNIT",_NRET,N)
GDFIELDPUT("C6_XVLULIQ",_NRET,N)

IF LATUVALOR
    GDFIELDPUT("C6_VALOR",(_NRET) * (GDFIELDGET("C6_QTDVEN",N)),N)
ENDIF

CASE _CFUNC=="OV"
(TMP1)->(FIELDPUT(FIELDPOS("CK_PRCVEN"),_NRET))
(TMP1)->(FIELDPUT(FIELDPOS("CK_PRUNIT"),_NRET))
(TMP1)->(FIELDPUT(FIELDPOS("CK_XVLULIQ"),_NRET))

IF LATUVALOR
    (TMP1)->(FIELDPUT(FIELDPOS("CK_VALOR"),(_NRET) * ((TMP1)->(FIELDGET(FIELDPOS("CK_QTDVEN"))))))
ENDIF
ENDCASE
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION GETVALUEIT(_CFUNC,_CPRODUTO,_CTES,_NXPRCTAB,_NQTD,_NBASICM)

DO CASE 
 CASE _CFUNC=="PV"
_CPRODUTO := GDFIELDGET("C6_PRODUTO",N)
_CTES := GDFIELDGET("C6_TES",N)
_NXPRCTAB := GDFIELDGET("C6_XVLUTAB",N)
_NQTD := GDFIELDGET("C6_QTDVEN",N)

_NBASICM := POSICIONE("SF4",1,XFILIAL("SF4")+_CTES,"F4_BASEICM")

CASE _CFUNC=="OV"
_CPRODUTO := (TMP1)->(FIELDGET(FIELDPOS("CK_PRODUTO")))
_CTES := (TMP1)->(FIELDGET(FIELDPOS("CK_TES")))
_NXPRCTAB := (TMP1)->(FIELDGET(FIELDPOS("CK_XVLUTAB")))
_NQTD := (TMP1)->(FIELDGET(FIELDPOS("CK_QTDVEN")))

_NBASICM := POSICIONE("SF4",1,XFILIAL("SF4")+_CTES,"F4_BASEICM")
ENDCASE
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION GETVALUECA(_CFUNC,_CTIPO,_CTIPOCLI,_CCLIENT,_CLOJA)

DO CASE 
 CASE _CFUNC=="PV"
_CCLIENT := M->C5_CLIENTE
_CLOJA := M->C5_LOJACLI

IF M->C5_TIPO<>"B"
    _CTIPO := "C"
    _CTIPOCLI := POSICIONE("SA1",1,XFILIAL("SA1")+_CCLIENT+_CLOJA,"A1_TIPO")
ELSE 
    _CTIPO := "F"
    _CTIPOCLI := POSICIONE("SA2",1,XFILIAL("SA2")+_CCLIENT+_CLOJA,"A2_TIPO")
ENDIF

CASE _CFUNC=="OV"
_CCLIENT := M->CJ_CLIENT
_CLOJA := M->CJ_LOJA
_CTIPO := "C"
_CTIPOCLI := POSICIONE("SA1",1,XFILIAL("SA1")+_CCLIENT+_CLOJA,"A1_TIPO")
ENDCASE
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION GETPIS(_CREF)
LOCAL _NRET := 0

IF _CREF=="ALIQ"
    _NRET := MAFISRET(1,"IT_ALIQPS2")
ELSE 
    _NRET := MAFISRET(1,"IT_VALPS2")
ENDIF
RETURN _NRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION GETCOFINS(_CREF)
LOCAL _NRET := 0

IF _CREF=="ALIQ"
    _NRET := MAFISRET(1,"IT_ALIQCF2")
ELSE 
    _NRET := MAFISRET(1,"IT_VALCF2")
ENDIF
RETURN _NRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION GETSOL(_CREF)
LOCAL _NRET := 0

IF _CREF=="ALIQ"
    _NRET := MAFISRET(1,"IT_ALIQSOL")
ELSE 
    _NRET := MAFISRET(1,"IT_VALSOL")
ENDIF
RETURN _NRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION GETICM(_CREF,_CTES,_NALIQICM)
LOCAL _NRET := 0
LOCAL _NPERICM := 0

IF _CREF=="ALIQ"
    _NPERICM := (POSICIONE("SF4",1,XFILIAL("SF4")+_CTES,"F4_BASEICM")) / (100)

    IF _NPERICM>0
        _NRET := (_NALIQICM) * (_NPERICM)
    ELSE 
        _NRET := _NALIQICM
    ENDIF
ELSE 
    _NRET := MAFISRET(1,"IT_VALICM")
ENDIF
RETURN _NRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION GETICMDES(_CREF,_NALIQICM)
LOCAL _NRET := 0

IF _CREF=="ALIQ"
    _NRET := ((MAFISRET(1,"IT_DIFAL")) * (100)) / (MAFISRET(1,"IT_BASEICM"))
ELSE 
    _NRET := MAFISRET(1,"IT_DIFAL")
ENDIF
RETURN _NRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION GETICMORI(_CREF,_NALIQICM)
LOCAL _NRET := 0

IF _CREF=="ALIQ"
    _NRET := ((MAFISRET(1,"IT_VALCMP")) * (100)) / (MAFISRET(1,"IT_BASEICM"))
ELSE 
    _NRET := MAFISRET(1,"IT_VALCMP")
ENDIF
RETURN _NRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION GETFCP(_CREF)
LOCAL _NRET := 0

IF _CREF=="ALIQ"
    _NRET := ((MAFISRET(1,"IT_VFCPDIF")) * (100)) / (MAFISRET(1,"IT_BASEICM"))
ELSE 
    _NRET := MAFISRET(1,"IT_VFCPDIF")
ENDIF
RETURN _NRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION GETIPI(_CREF,_NICMS,_NICMORI,_NICMDES,_NALIQFCP,_CTES,_CPRODUTO,_CTIPOCLI)
LOCAL _CINCIDE := ""
LOCAL _CORIGEM := ""
LOCAL _NRET := 0

IF _CREF=="ALIQ"
    _CINCIDE := POSICIONE("SF4",1,XFILIAL("SF4")+_CTES,"F4_INCIDE")
    _CORIGEM := POSICIONE("SB1",1,XFILIAL("SB1")+_CPRODUTO,"B1_ORIGEM")

    IF MAFISRET(1,"IT_VALIPI")>0
        
        IF _CTIPOCLI=="F" .AND. _CINCIDE=="F" .AND. _CORIGEM=="0"
            _NRET := (_NICMS+_NICMORI+_NICMDES+_NALIQFCP) * ((MAFISRET(1,"IT_ALIQIPI")) / (100))
        ELSEIF _CTIPOCLI=="F" .AND. _CINCIDE=="F" .AND. _CORIGEM<>"0"
            _NRET := (_NICMS+_NICMORI+_NICMDES+_NALIQFCP) * ((MAFISRET(1,"IT_ALIQIPI")) / (100))
        ENDIF
    ENDIF
ELSE 
    _NRET := MAFISRET(1,"IT_VALIPI")
ENDIF
RETURN _NRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION SETPRCTAB(_CFUNC)

LOCAL _NPRCTAB := 0
LOCAL _CPRODUTO := ""
LOCAL _DDATAVIG := CTOD("  /  /  ")
LOCAL _CCODUSR := SUPERGETMV("AM_USRTABP", .F. ,"000131|000151")

DO CASE 
 CASE _CFUNC=="PV"

_DDATAVIG := POSICIONE("DA1",1,XFILIAL("DA1")+M->C5_TABELA+GDFIELDGET("C6_PRODUTO",N),"DA1_DATVIG")

IF (_DDATAVIG>=DDATABASE) .OR. ((RETCODUSR()) $ (_CCODUSR))
    _NPRCTAB := POSICIONE("DA1",1,XFILIAL("DA1")+M->C5_TABELA+GDFIELDGET("C6_PRODUTO",N),"DA1_PRCVEN")
ELSE 
    IIF(FINDFUNCTION("MSGALERT"),MSGALERT("PRODUTO FORA DA VIGÊNCIA ! ENTRE EM CONTATO COM O DEPARTAMENTO COMERCIAL. VALOR UNITÁRIO NÃO ATUALIZADO !","ATENÇÃO!"),MSGALERT("PRODUTO FORA DA VIGÊNCIA ! ENTRE EM CONTATO COM O DEPARTAMENTO COMERCIAL. VALOR UNITÁRIO NÃO ATUALIZADO !","ATENÇÃO!"))
ENDIF

GDFIELDPUT("C6_XVLUTAB",_NPRCTAB,N)

CASE _CFUNC=="OV"
_CPRODUTO := (TMP1)->(FIELDGET(FIELDPOS("CK_PRODUTO")))
_NPRCTAB := POSICIONE("DA1",1,XFILIAL("DA1")+M->CJ_TABELA+_CPRODUTO,"DA1_PRCVEN")

(TMP1)->(FIELDPUT(FIELDPOS("CK_XVLUTAB"),_NPRCTAB))
ENDCASE
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION SETOPER(_CFUNC)
LOCAL _CPRODUTO := ""
LOCAL _CTIPO := ""
LOCAL _COPER := ""
LOCAL _CTIPOCLI := ""

DO CASE 
 CASE _CFUNC=="PV"
_CPRODUTO := GDFIELDGET("C6_PRODUTO",N)
_CTIPO := POSICIONE("SB1",1,XFILIAL("SB1")+_CPRODUTO,"B1_TIPO")
_COPER := U_M05A02(M->C5_TIPOCLI,_CTIPO)

GDFIELDPUT("C6_OPER",_COPER,N)
GDFIELDPUT("C6_XOPER",_COPER,N)

CASE _CFUNC=="OV"
_CPRODUTO := (TMP1)->(FIELDGET(FIELDPOS("CK_PRODUTO")))
_CTIPO := POSICIONE("SB1",1,XFILIAL("SB1")+_CPRODUTO,"B1_TIPO")
_CTIPOCLI := POSICIONE("SA1",1,XFILIAL("SA1")+M->CJ_CLIENT+M->CJ_LOJA,"A1_TIPO")
_COPER := U_M05A02(_CTIPOCLI,_CTIPO)

(TMP1)->(FIELDPUT(FIELDPOS("CK_OPER"),_COPER))
(TMP1)->(FIELDPUT(FIELDPOS("CK_XOPER"),_COPER))
ENDCASE

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION SETTES(_CFUNC)
LOCAL _CPRODUTO := ""
LOCAL _COPER := ""
LOCAL _CTES := ""

DO CASE 
 CASE _CFUNC=="PV"
_CPRODUTO := GDFIELDGET("C6_PRODUTO",N)
_COPER := GDFIELDGET("C6_OPER",N)
_CTES := MATESINT(2,_COPER,M->C5_CLIENT,M->C5_LOJAENT,IIF((M->C5_TIPO) $ ("DB"),"F","C"),_CPRODUTO,"C6_TES")

GDFIELDPUT("C6_TES",_CTES,N)

CASE _CFUNC=="OV"
_CPRODUTO := (TMP1)->(FIELDGET(FIELDPOS("CK_PRODUTO")))
_COPER := (TMP1)->(FIELDGET(FIELDPOS("CK_OPER")))
_CTES := MATESINT(2,_COPER,M->CJ_CLIENT,M->CJ_LOJA,"C",_CPRODUTO,"CK_TES")

(TMP1)->(FIELDPUT(FIELDPOS("CK_TES"),_CTES))
ENDCASE
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M05A01_A(_CFUNC)
LOCAL _NPRECOVEND := 0

CALCPRCA(_CFUNC,@_NPRECOVEND)
SETTES(_CFUNC)
SETPRCVEN(_CFUNC,_NPRECOVEND, .T. )
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION CALCPRCA(_CFUNC,_NPRECOVEND)

DO CASE 
 CASE _CFUNC=="PV"
_NPRECOVEND := (GDFIELDGET("C6_XVLTBRU",N)) / (GDFIELDGET("C6_QTDVEN",N))

CASE _CFUNC=="OV"
_NPRECOVEND := ((TMP1)->(FIELDGET(FIELDPOS("CK_XVLTBRU")))) / ((TMP1)->(FIELDGET(FIELDPOS("CK_QTDVEN"))))
ENDCASE

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M05A01_B(_CFUNC)
LOCAL _NPRECOVEND := 0

CALCPRCB(_CFUNC,@_NPRECOVEND)
SETTES(_CFUNC)
SETPRCVEN(_CFUNC,_NPRECOVEND, .T. )
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION CALCPRCB(_CFUNC,_NPRECOVEND)

DO CASE 
 CASE _CFUNC=="PV"
IF !((GDFIELDGET("C6_OPER",N)) $ ("27|44"))
    _NPRECOVEND := GDFIELDGET("C6_PRCVEN",N)+GDFIELDGET("C6_XVLUSOL",N)
ELSE 
    _NPRECOVEND := GDFIELDGET("C6_PRCVEN",N)
ENDIF

CASE _CFUNC=="OV"
_NPRECOVEND := (TMP1)->(FIELDGET(FIELDPOS("CK_PRCVEN")))+(TMP1)->(FIELDGET(FIELDPOS("CK_XVLUSOL")))
ENDCASE

RETURN 
