#INCLUDE "protheus.ch"

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M05A28(CFUNC,LITEM,NVALOR)
LOCAL LRET :=  .T. 
LOCAL AAREA := GETAREA()
LOCAL NITENS := 0
LOCAL NDESCCAB := 1

LOCAL CMSG := ""
LOCAL CGRPAPR := GETMV("AM_05A28_A",,"")
LOCAL LAPROV := U_M00A01(CGRPAPR)
LOCAL CCODUSR := RETCODUSR()
PRIVATE CNOMUSR := USRFULLNAME(CCODUSR)
PRIVATE NDESCITE := 1

NVALOR := IIF(NVALOR==NIL,0,NVALOR)

NDESCCAB := MA05GETDEC(CFUNC)

LRET := MA05GETTOT(CFUNC,NDESCCAB,@CMSG,LITEM,@NITENS,NVALOR)

IF !(LRET := EMPTY(CMSG))

    IF LAPROV
        LRET := MSGYESNO(I18N("DESCONTO CONCEDIDO É MAIOR QUE O PERMITIDO PARA OS #1 ITENS ABAIXO." + CRLF+"#2" + CRLF + CRLF+"DESEJA APROVAR TODOS OS DESCONTOS?",{NITENS,CMSG}),)
        
        IF LRET
            M->C5_XAPROV := USRFULLNAME(RETCODUSR())
        ELSE 
            M->C5_DESC1 := 0
            M->C5_DESC2 := 0
        ENDIF
    ELSE 
        AVISO("ATENÇÃO",I18N("DESCONTO CONCEDIDO É MAIOR QUE O PERMITIDO PARA OS #1 ITENS ABAIXO:" + CRLF+"#2",{NITENS,CMSG}),{"OK"},3)
    ENDIF
ENDIF

RESTAREA(AAREA)
RETURN LRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MA05GETDEC(CFUNC)
LOCAL ADESC := {}
LOCAL _NX := 0
LOCAL NPERDESC := 1

DO CASE 
 CASE CFUNC=="PV"
AADD(ADESC,1-(M->C5_DESC1) / (100))
AADD(ADESC,1-(M->C5_DESC2) / (100))
AADD(ADESC,1-(M->C5_DESC3) / (100))
AADD(ADESC,1-(M->C5_DESC4) / (100))

CASE CFUNC=="OV"

AADD(ADESC,1-(M->CJ_DESC1) / (100))
AADD(ADESC,1-(M->CJ_DESC2) / (100))
AADD(ADESC,1-(M->CJ_DESC3) / (100))
AADD(ADESC,1-(M->CJ_DESC4) / (100))
ENDCASE

FOR _NX := 1 TO  LEN(ADESC)
    NPERDESC := (NPERDESC) * (ADESC[_NX])
NEXT

RETURN NPERDESC

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MA05GETTOT(CFUNC,NPERDESC,CMSG,LITEM,NITENS,NVALOR)

LOCAL AAREA := GETAREA()
LOCAL NBKP
LOCAL NITEM := 0
LOCAL ADESC := {}
LOCAL LRET :=  .T. 

DO CASE 
 CASE CFUNC=="PV"
IF LITEM
    AAUX := MA05DESCPV(NPERDESC,NVALOR)
    AADD(ADESC,AAUX)
ELSE 

    NBKP := N
    N := 1
    
    IF  LEN(ACOLS)>0 .AND. !(EMPTY(GDFIELDGET("C6_PRODUTO",N)))
        FOR N := 1 TO  LEN(ACOLS)
            AAUX := {}
            AAUX := MA05DESCPV(NPERDESC)
            AADD(ADESC,AAUX)
        NEXT
        N := NBKP
        OGETDAD:OBROWSE:REFRESH()
    ENDIF
ENDIF

CASE CFUNC=="OV"
IF LITEM
    AAUX := MA05DESCOV(NPERDESC,NVALOR)
    AADD(ADESC,AAUX)
ELSE 

    (TMP1)->(DBGOTOP())

    IF !(TMP1)->(EOF()) .AND. !(EMPTY((TMP1)->(FIELDGET(FIELDPOS("CK_PRODUTO")))))
        WHILE !(TMP1)->(EOF())
        
            AAUX := {}
            AAUX := MA05DESCOV(NPERDESC,NVALOR)
            AADD(ADESC,AAUX)

            (TMP1)->(DBSKIP())
            ENDDO

        (TMP1)->(DBGOTOP())

        OGETDAD:OBROWSE:REFRESH()
    ENDIF
ENDIF
ENDCASE

FOR NITEM := 1 TO  LEN(ADESC)
    
    IF ADESC[NITEM][4]>0 .AND. ADESC[NITEM][4]<ADESC[NITEM][3]
        CMSG += CHR(13)+CHR(10)+I18N("SEQ.: #1 |PROD.: #2 |DESC. APLICADO: #3 % |MÁXIMO: #4 %",{ADESC[NITEM][5],ADESC[NITEM][1],ADESC[NITEM][3],ADESC[NITEM][4]})
        LRET :=  .F. 
        NITENS++
    ENDIF
NEXT

RESTAREA(AAREA)
RETURN LRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MA05DESCPV(NPERDESC,NVALOR)

LOCAL CPROD := ""
LOCAL CFAMILIA := ""
LOCAL CITEM := ""
LOCAL NDESCFAM := 0
LOCAL NDESCTOT := 1

LOCAL NDESCI := 0
LOCAL ARET := {}
LOCAL CCODUSER := RETCODUSR()
PRIVATE NITEM := 1

NVALOR := IIF(NVALOR==NIL,0,NVALOR)

IF TYPE("M->C6_DESCONT")=="N"
    NDESCI := 1-(M->C6_DESCONT) / (100)
ELSE 
    NDESCI := 1-(GDFIELDGET("C6_DESCONT",N)) / (100)
ENDIF

IF TYPE("M->C6_DESCONT")=="U"
    NDESCI := ((NVALOR) / (GDFIELDGET("C6_XVLTBRU",N))) * (100)
    NDESCI := 100-NDESCI

    IF (READVAR()=="M->C5_DESC1") .OR. (READVAR()=="M->C5_DESC2")
        NDESCTOT := 100-(NPERDESC) * (NDESCI)
    ELSE 
        NDESCTOT := (NPERDESC) * (NDESCI)
    ENDIF
ELSE 
    NDESCTOT := (NPERDESC) * (NDESCI)
    NDESCTOT := 100-(NDESCTOT) * (100)
ENDIF

IF READVAR()=="M->C5_DESC1" .AND. M->C5_DESC1==0
    NDESCTOT := 0
ENDIF

CPROD := GDFIELDGET("C6_PRODUTO",N)
CFAMILIA := POSICIONE("SB1",1,XFILIAL("SB1")+CPROD,"B1_XFAMILI")
NDESCFAM := POSICIONE("ZA1",1,XFILIAL("ZA1")+CFAMILIA,"ZA1_DESCON")
CITEM := GDFIELDGET("C6_ITEM",N)

IF (CCODUSER) $ ("000036|000078|000113|000190")
    NDESCFAM := 30
ENDIF

IF CCODUSER=="000034"
    NDESCFAM := 40
ENDIF

AADD(ARET,CPROD)
AADD(ARET,CFAMILIA)
AADD(ARET,NDESCTOT)
AADD(ARET,NDESCFAM)
AADD(ARET,CITEM)
RETURN ACLONE(ARET)

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MA05DESCOV(NPERDESC,NVALOR)
LOCAL CPROD := ""
LOCAL CFAMILIA := ""
LOCAL CITEM := ""
LOCAL NDESCFAM := 0
LOCAL NDESCTOT := 1
LOCAL NDESCI := 0
LOCAL ARET := {}
LOCAL CUSUARIO := RETCODUSR()
PRIVATE NITEM := 1
NVALOR := IIF(NVALOR==NIL,0,NVALOR)

IF (READVAR()) $ ("M->CJ_DESC1")
    NPERDESC := 1-NPERDESC
    NDESCTOT := M->CJ_DESC1
ELSE 
    NPERDESC := 1-NPERDESC
    NDESCTOT := M->CJ_DESC1+M->CJ_DESC2
    
    IF TYPE("M->CK_DESCONT")=="N"
        NDESCI := (M->CK_DESCONT) / (100)
    ELSE 
        NDESCI := 1-((TMP1)->(FIELDGET(FIELDPOS("CK_DESCONT")))) / (100)
    ENDIF
    
    IF TYPE("M->CK_DESCONT")=="U"
        NDESCI := ((NVALOR) / ((TMP1)->(FIELDGET(FIELDPOS("CK_XVLTBRU"))))) * (100)
        NDESCI := 100-NDESCI
        NDESCTOT := (NPERDESC) * (NDESCI)
    ELSE 
        NDESCTOT := NPERDESC+NDESCI
        NDESCTOT := (NDESCTOT) * (100)
    ENDIF
    
    IF READVAR()=="M->CJ_DESC1" .AND. M->CJ_DESC1==0
        NDESCTOT := 100-(NDESCTOT) * (100)
    ENDIF
ENDIF

CPROD := (TMP1)->(FIELDGET(FIELDPOS("CK_PRODUTO")))
CFAMILIA := POSICIONE("SB1",1,XFILIAL("SB1")+CPROD,"B1_XFAMILI")
NDESCFAM := POSICIONE("ZA1",1,XFILIAL("ZA1")+CFAMILIA,"ZA1_DESCON")
CITEM := (TMP1)->(FIELDGET(FIELDPOS("CK_ITEM")))

IF (CUSUARIO) $ ("000036|000078|000113")
    NDESCFAM := 30
ENDIF

IF CUSUARIO=="000034"
    NDESCFAM := 40
ENDIF

AADD(ARET,CPROD)
AADD(ARET,CFAMILIA)
AADD(ARET,NDESCTOT)
AADD(ARET,NDESCFAM)
AADD(ARET,CITEM)

RETURN ACLONE(ARET)
