#INCLUDE "protheus.ch"

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M05D01U()
LOCAL ASAY
LOCAL CTITULO
LOCAL ABOTOES
LOCAL LSIMULACAO
LOCAL CARQUIVOORIGEM
LOCAL CLOGARQUIVO
LOCAL CNOMEARQUIVO

ASAY := {}
CTITULO := FUNNAME()+" - IMPORTA TABELA DE PREÇO"
ABOTOES := {}
LSIMULACAO := MSGYESNO("DESEJA EXECUTAR EM MODO SIMULAÇÃO?",)
CARQUIVOORIGEM := ""
CLOGARQUIVO := ""
CNOMEARQUIVO := ""

IF LSIMULACAO
    AADD(ASAY,OEMTOANSI("*** SIMULAÇÃO *** "))
ENDIF

AADD(ASAY,OEMTOANSI("ROTINA DE ATUALIZAÇÃO DE TABELA DE PREÇOS/PRODUTOS INFORMADOS NO ARQUIVO CSV"))
AADD(ASAY,OEMTOANSI(" "))
AADD(ASAY,OEMTOANSI("IMPORTANTE! "))
AADD(ASAY,OEMTOANSI(" - OS NÚMEROS DEVEM UTILIZAR PONTO [.] COMO SEPARADOR DE CASA DECIMAL"))
AADD(ASAY,OEMTOANSI(" - OS CAMPOS DEVER SER SEPARADOS POR PONTO E VÍRGULA [;]"))
AADD(ASAY,OEMTOANSI(" - A TABELA/PRODUTO INFORMADOS DEVEM ESTAR CADASTRADOS NO PROTHEUS"))

AADD(ABOTOES,{1, .T. ,{||PROCESSA({||M05D01OK(LSIMULACAO,@CARQUIVOORIGEM,@CLOGARQUIVO,@CNOMEARQUIVO)}),FECHABATCH()}})
AADD(ABOTOES,{2, .T. ,{||FECHABATCH()}})

FORMBATCH(CTITULO,ASAY,ABOTOES)

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05D01OK(LSIMULACAO,CARQUIVOORIGEM,CLOGARQUIVO,CNOMEARQUIVO)
LOCAL OTELA
LOCAL OARQUIVOORIGEM
LOCAL OLOGARQUIVO
LOCAL CTITULO

CTITULO := "IMPORTAÇÃO DE ITENS DA TABELA DE PREÇO"

IF LSIMULACAO
    CTITULO += OEMTOANSI(" *** SIMULAÇÃO *** ")
ENDIF

CARQUIVOORIGEM := "                                                                                                                                                                                                        "
CLOGARQUIVO := "                                                                                                                                                                                                        "

OTELA := MSDIALOG():NEW(0,0,300,900,CTITULO,,, .F. ,128,,,,, .T. ,,, .F. )

TSAY():NEW(20,20,{||"ARQUIVO ORIGEM *.CSV:"},OTELA,,, .F. , .F. , .F. , .T. ,,,,, .F. , .F. , .F. , .F. , .F. , .F. )
OARQUIVOORIGEM := TGET():NEW(17,80,{ | U |IIF(PCOUNT()==0,CARQUIVOORIGEM,CARQUIVOORIGEM := U)},OTELA,300,10,,,,,, .F. ,, .T. ,, .F. ,{|| .F. }, .F. , .F. ,, .F. , .F. ,,"CARQUIVOORIGEM",,,)

TBUTTON():NEW(17,400,"SELEC. ARQUIVO",OTELA,{||SELECIONAARQUIVO(1,@CARQUIVOORIGEM,NIL)},40,15,,, .F. , .T. , .F. ,, .F. ,,, .F. )

TSAY():NEW(40,20,{||"ARQUIVO LOG:"},OTELA,,, .F. , .F. , .F. , .T. ,,,,, .F. , .F. , .F. , .F. , .F. , .F. )
OLOGARQUIVO := TGET():NEW(37,80,{ | U |IIF(PCOUNT()==0,CLOGARQUIVO,CLOGARQUIVO := U)},OTELA,300,10,,,,,, .F. ,, .T. ,, .F. ,{|| .F. }, .F. , .F. ,, .F. , .F. ,,"CLOGARQUIVO",,,)

TBUTTON():NEW(37,400,"SELEC. ARQUIVO",OTELA,{||SELECIONAARQUIVO(2,NIL,@CLOGARQUIVO,@CNOMEARQUIVO)},40,15,,, .F. , .T. , .F. ,, .F. ,,, .F. )

TBUTTON():NEW(120,170,"CONFIRMAR",OTELA,{||CONFIRMAR(LSIMULACAO,@CARQUIVOORIGEM,@CLOGARQUIVO,@OTELA,@CNOMEARQUIVO)},40,12,,, .F. , .T. , .F. ,, .F. ,,, .F. )
TBUTTON():NEW(120,220,"CANCELAR",OTELA,{||OTELA:END()},40,12,,, .F. , .T. , .F. ,, .F. ,,, .F. )

OTELA:ACTIVATE(OTELA:BLCLICKED,OTELA:BMOVED,OTELA:BPAINTED, .T. ,,,,OTELA:BRCLICKED,)

CARQUIVOORIGEM := ""
CLOGARQUIVO := ""

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION CONFIRMAR(LSIMULACAO,CARQUIVOORIGEM,CLOGARQUIVO,OTELA,CNOMEARQUIVO)
IF VALIDAARQUIVOS(CARQUIVOORIGEM,CLOGARQUIVO)
    PROCESSADADOS(LSIMULACAO,@CARQUIVOORIGEM,@CLOGARQUIVO,@CNOMEARQUIVO)
    OTELA:END()
ENDIF

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION PROCESSADADOS(LSIMULACAO,CARQUIVOORIGEM,CLOGARQUIVO,CNOMEARQUIVO)
LOCAL AREGISTROS
LOCAL NTOTAL
LOCAL CMAILMENSAGEM
LOCAL NREGISTROS
LOCAL LENVIOU
LOCAL LRETRY
LOCAL CLOG
LOCAL CERROR
LOCAL CMENSAGEMPROCESSAMENTO
LOCAL NINCLUIDOSREGISTROS
LOCAL NREGISTROSALTERADOS
LOCAL CHTMLLOG

AREGISTROS := {}
NTOTAL := 0
CMAILMENSAGEM := ""
NREGISTROS := 0
LENVIOU :=  .F. 
LRETRY :=  .T. 
CLOG := "INICIO "+DTOC(DATE())+" "+TIME() + CRLF + CRLF
CERROR := ""
CMENSAGEMPROCESSAMENTO := ""
NINCLUIDOSREGISTROS := 0
NREGISTROSALTERADOS := 0
CHTMLLOG := ""
 
    IF !(CARREGADADOS(CARQUIVOORIGEM,@AREGISTROS,@NTOTAL))
        CMENSAGEM := "FALHA AO CARREGAR OS DADOS DO ARQUIVO CSV EM MEMÓRIA."
        BREAK 
    ENDIF

    CMAILMENSAGEM := CABECALHOEMAIL()

    FWMSGRUN(,{||ATUALIZATABELAS(AREGISTROS,@CLOG,@NREGISTROSALTERADOS,@NINCLUIDOSREGISTROS,@CMAILMENSAGEM,LSIMULACAO)},,I18N("IMPORTANDO ITEM #1 DE #2 ...",{++NREGISTROS,NTOTAL}))

    CMENSAGEMPROCESSAMENTO := GERALOG(CLOGARQUIVO,CMENSAGEMPROCESSAMENTO,@CLOG,NREGISTROSALTERADOS,NINCLUIDOSREGISTROS)

    IF !(LSIMULACAO)
        WHILE !(LENVIOU) .AND. LRETRY
        
            FWMSGRUN(,{||LENVIOU := ENVIAEMAIL(CMAILMENSAGEM,@CERROR,@CHTMLLOG)},,"GERANDO LOG...")

            IF !(LENVIOU) .AND. LRETRY

                LRETRY := MSGYESNO("OCORREU UM ERRO AO ENVIAR O E-MAIL:" + CRLF + CRLF+" ["+ ALLTRIM(CERROR)+"] " + CRLF + CRLF+"ESTA OPERAÇÃO NÃO IMPEDIRÁ A INCLUSÃO DOS DADOS, PORÉM É IMPORTANTE PARA A EXISTÊNCIA DO LOG DE IMPORTAÇÃO." + CRLF+"CASO OPTE POR NÃO PROSSEGUIR, SERÁ GERADO O LOG DE PROCESSAMENTO LOCALMENTE." + CRLF + CRLF+"TENTAR NOVAMENTE? ","PROCESSADADOS")
            ENDIF
            ENDDO

        IF !(LENVIOU) .AND. !(LRETRY)
            GRAVALOGLOCAL(CHTMLLOG,CNOMEARQUIVO)
        ENDIF
    ENDIF

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION GERALOG(CLOGARQUIVO,CMENSAGEMPROCESSAMENTO,CLOG,NREGISTROSALTERADOS,NINCLUIDOSREGISTROS)
LOCAL NHANDLE := 0

NHANDLE := FCREATE(CLOGARQUIVO)

CLOG := CHR(13)+CHR(10) + CRLF+I18N("REGISTROS INCLUÍDOS: #1",{NINCLUIDOSREGISTROS}) + CRLF+I18N("REGISTROS ATUALIZADOS: #1",{NREGISTROSALTERADOS}) + CRLF + CRLF+CLOG
CLOG += CHR(13)+CHR(10) + CRLF+"FIM "+DTOC(DATE())+" "+TIME() + CRLF + CRLF

IF NHANDLE=- (1)
    CMENSAGEMPROCESSAMENTO += " ERRO AO CRIAR ARQUIVO - FERROR "+STR(FERROR())
ELSE 
    CMENSAGEMPROCESSAMENTO += " VERIFIQUE ARQUIVO DE LOG GERADO: " + CRLF+"#2 " + CRLF
    FWRITE(NHANDLE,CLOG)
    FCLOSE(NHANDLE)
ENDIF
RETURN CMENSAGEMPROCESSAMENTO

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION ATUALIZATABELAS(AREGISTROS,CLOG,NREGISTROSALTERADOS,NINCLUIDOSREGISTROS,CMAILMENSAGEM,LSIMULACAO)
LOCAL NREGISTRO
LOCAL CPRODUTO
LOCAL CITEM
LOCAL CLOGMENSAGEM
LOCAL NPRECOVENDA
LOCAL DDATAVIGENCIA
LOCAL NANTIGOPRECOVENDA
LOCAL CTABELADEPRECO

FOR NREGISTRO := 2 TO  LEN(AREGISTROS)
    CTABELADEPRECO := PADR( ALLTRIM(AREGISTROS[NREGISTRO][1]),TAMSX3("DA0_CODTAB")[1])
    CPRODUTO := PADR( ALLTRIM(AREGISTROS[NREGISTRO][2]),TAMSX3("DA1_CODPRO")[1])
    CITEM := SPACE(TAMSX3("DA1_ITEM")[1])
    CLOGMENSAGEM := ""
    NPRECOVENDA :=  VAL(AREGISTROS[NREGISTRO][3])
    DDATAVIGENCIA := CTOD(AREGISTROS[NREGISTRO][4])
    NANTIGOPRECOVENDA := 0
    
        IF !(EXISTETABELADEPRECO(CTABELADEPRECO,@CLOGMENSAGEM))
            BREAK 
        ENDIF
        
        IF !(EXISTEPRODUTO(CPRODUTO,@CLOGMENSAGEM))
            BREAK 
        ENDIF
        
        INCLUIREGISTROTABELADEPRECO(CTABELADEPRECO,CPRODUTO,NPRECOVENDA,@NANTIGOPRECOVENDA,@CITEM,@CLOGMENSAGEM,@NREGISTROSALTERADOS,@NINCLUIDOSREGISTROS,DDATAVIGENCIA,LSIMULACAO)
    
    GRAVALOG(CTABELADEPRECO,CPRODUTO,NPRECOVENDA,NANTIGOPRECOVENDA,CITEM,CLOGMENSAGEM,@CLOG,@CMAILMENSAGEM,DDATAVIGENCIA)
NEXT

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION EXISTETABELADEPRECO(CTABELADEPRECO,CLOGMENSAGEM)
LOCAL LRETURN

DA0->(DBSETORDER(1))
DA0->(DBGOTOP())

LRETURN :=  .F. 
 
    IF !(DA0->(DBSEEK(XFILIAL("DA0")+CTABELADEPRECO)))
        CLOGMENSAGEM := I18N("TABELA #1 NÃO ENCONTRADA",{CTABELADEPRECO})
        BREAK 
    ENDIF

    LRETURN :=  .T. 

RETURN LRETURN

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION EXISTEPRODUTO(CPRODUTO,CLOGMENSAGEM)
LOCAL LRETURN

SB1->(DBSETORDER(1))
SB1->(DBGOTOP())

LRETURN :=  .F. 
 
    IF !(SB1->(DBSEEK(XFILIAL("SB1")+CPRODUTO)))
        CLOGMENSAGEM := I18N("PRODUTO #1 INVALIDO",{CPRODUTO})
        BREAK 
    ENDIF

    LRETURN :=  .T. 

RETURN LRETURN

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION INCLUIREGISTROTABELADEPRECO(CTABELADEPRECO,CPRODUTO,NPRECOVENDA,NANTIGOPRECOVENDA,CITEM,CLOGMENSAGEM,NREGISTROSALTERADOS,NINCLUIDOSREGISTROS,DDATAVIGENCIA,LSIMULACAO)
LOCAL NREGISTRODA1

IF EXISTEREGISTROTABELADEPRECO(CTABELADEPRECO,CPRODUTO,@CITEM,@NREGISTRODA1)
    DA1->(DBGOTOP())
    DA1->(DBGOTO(NREGISTRODA1))

    NANTIGOPRECOVENDA := DA1->DA1_PRCVEN

    IF !(LSIMULACAO) .AND. (((RETCODUSR()) $ (GETMV("MV_XIMPTAB"))) .OR. (FWISADMIN()))
        RECLOCK("DA1", .F. )
        DA1->DA1_PRCVEN := NPRECOVENDA
        DA1->DA1_DATVIG := DDATAVIGENCIA
        DA1->(MSUNLOCK())

        CLOGMENSAGEM := " ALTERACAO EFETUADA"
    ELSE 

        CLOGMENSAGEM := " ALTERACAO NAO PERMITIDA"
    ENDIF

    ++NREGISTROSALTERADOS
ELSE 

    CITEM := PROXIMOITEMDA1(CTABELADEPRECO)
    NANTIGOPRECOVENDA := 0

    IF !(LSIMULACAO)
        RECLOCK("DA1", .T. )
        DA1->DA1_FILIAL := XFILIAL("DA1")
        DA1->DA1_ITEM := CITEM
        DA1->DA1_CODTAB := CTABELADEPRECO
        DA1->DA1_CODPRO := CPRODUTO
        DA1->DA1_GRUPO := POSICIONE("SB1",1,XFILIAL("SB1")+CPRODUTO,"B1_GRUPO")
        DA1->DA1_PRCVEN := NPRECOVENDA
        DA1->DA1_ATIVO := "1"
        DA1->DA1_TPOPER := "4"
        DA1->DA1_QTDLOT := 999999.99
        DA1->DA1_MOEDA := 1
        DA1->DA1_DATVIG := DDATAVIGENCIA
        DA1->(MSUNLOCK())
    ENDIF

    CLOGMENSAGEM := " INCLUÍDO"
    ++NINCLUIDOSREGISTROS
ENDIF

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION PROXIMOITEMDA1(CTABELADEPRECO)
LOCAL CRETURN
LOCAL CALIASDA1

CRETURN := ""
CALIASDA1 := GETNEXTALIAS()

_cQry := " SELECT MAX(DA1_ITEM) AS DA1_ITEM "
_cQry += " FROM "+RETSQLNAME("DA1")+" DA1 "
_cQry += " WHERE DA1.D_E_L_E_T_= ' ' "
_cQry += "   AND DA1_FILIAL = '"+XFILIAL("DA1")+"' "
_cQry += "   AND DA1_CODTAB = "+___SQLGETVALUE(CTABELADEPRECO)
__EXECSQL(CALIASDA1,_cQry,{}, .F. )

DBSELECTAREA(CALIASDA1)
IF !(CALIASDA1)->(EOF())
    CRETURN := SOMA1(CALIASDA1->DA1_ITEM)
ENDIF

(CALIASDA1)->(DBCLOSEAREA())

RETURN CRETURN

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION EXISTEREGISTROTABELADEPRECO(CTABELADEPRECO,CPRODUTO,CITEM,NREGISTRODA1)
LOCAL CALIASDA1
LOCAL LEXISTE

CALIASDA1 := GETNEXTALIAS()
LEXISTE :=  .F. 

_cQry := " SELECT DA1.R_E_C_N_O_ AS DA1_RECNO, "
_cQry += "        DA1_ITEM, "
_cQry += "        DA1_CODTAB, "
_cQry += "        DA1_CODPRO, "
_cQry += "        DA1_DATVIG "
_cQry += " FROM "+RETSQLNAME("DA1")+" DA1 "
_cQry += " WHERE DA1.D_E_L_E_T_= ' ' "
_cQry += "   AND DA1_FILIAL = '"+XFILIAL("DA1")+"' "
_cQry += "   AND DA1_CODTAB = "+___SQLGETVALUE(CTABELADEPRECO)+" "
_cQry += "   AND DA1_CODPRO = "+___SQLGETVALUE(CPRODUTO)+" "
_cQry += "   AND DA1_ATIVO = '1' "
_cQry += " ORDER BY DA1_DATVIG DESC "
__EXECSQL(CALIASDA1,_cQry,{}, .F. )

DBSELECTAREA(CALIASDA1)
IF !(CALIASDA1)->(EOF())
    NREGISTRODA1 := CALIASDA1->DA1_RECNO
    CITEM := CALIASDA1->DA1_ITEM
    LEXISTE :=  .T. 
ENDIF

(CALIASDA1)->(DBCLOSEAREA())

RETURN LEXISTE

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION GRAVALOG(CTABELADEPRECO,CPRODUTO,NPRECOVENDA,NANTIGOPRECOVENDA,CITEM,CLOGMENSAGEM,CLOG,CMAILMENSAGEM,DDATAVIGENCIA)
LOCAL CANTIGOPRECOVENDA
LOCAL CNOVOPRECODEVENDA

CANTIGOPRECOVENDA := TRANSFORM(NANTIGOPRECOVENDA,"@E 9,999,999.999999")
CNOVOPRECODEVENDA := TRANSFORM(NPRECOVENDA,"@E 9,999,999.999999")

CLOG += CHR(13)+CHR(10)
CLOG += " | TABELA: "+CTABELADEPRECO
CLOG += " | ITEM: "+CITEM
CLOG += " | PRODUTO: "+CPRODUTO
CLOG += " | PRC VENDA: "+CANTIGOPRECOVENDA
CLOG += " | PRC VENDA NOVO: "+CNOVOPRECODEVENDA
CLOG += " | DATA DE VIGÊNCIA: "+DTOC(DDATAVIGENCIA)
CLOG += " | STATUS: "+CLOGMENSAGEM+" |"

NOVOITEMEMAIL(CTABELADEPRECO,CITEM,CPRODUTO,CANTIGOPRECOVENDA,CNOVOPRECODEVENDA,CLOGMENSAGEM,@CMAILMENSAGEM,DDATAVIGENCIA)

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION CARREGADADOS(CARQUIVOORIGEM,AREGISTROS,NTOTAL)
LOCAL ALINHA
LOCAL CCONTEUDO
LOCAL LRETURN

LRETURN :=  .F. 
 
 BEGIN SEQUENCE

    IF FT_FUSE(CARQUIVOORIGEM)<0
        CMENSAGEM := "FALHA AO ABRIR O ARQUIVO CSV EM MEMÓRIA."
        BREAK 
    ENDIF

    FT_FGOTOP()

    WHILE !(FT_FEOF())
    
        CCONTEUDO := FT_FREADLN()
        ALINHA := {}
        ALINHA := SEPARA(CCONTEUDO,";", .F. )

        IF  LEN(ALINHA)>0
            AADD(AREGISTROS,ALINHA)
        ENDIF

        FT_FSKIP()
    ENDDO

    NTOTAL :=  LEN(AREGISTROS)-1

    FT_FUSE()

    LRETURN :=  .T. 

   RECOVER

    MSGSTOP(CMENSAGEM,)
 END SEQUENCE

RETURN LRETURN

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION VALIDAARQUIVOS(CARQUIVOORIGEM,CLOGARQUIVO)
LOCAL LRETURN
 
 BEGIN SEQUENCE

    IF EMPTY(CARQUIVOORIGEM)
        BREAK 
    ENDIF

    IF EMPTY(CLOGARQUIVO)
        BREAK 
    ENDIF

    LRETURN :=  .T. 

    RECOVER

    MSGINFO("ARQUIVO ORIGEM E ARQUIVO DE LOG SÃO OBRIGATÓRIOS." + CRLF+"VERIFIQUE.",)
 END SEQUENCE

RETURN LRETURN

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION SELECIONAARQUIVO(NTIPO,CARQUIVOORIGEM,CLOGARQUIVO,CNOMEARQUIVO)

IF NTIPO==1
    CARQUIVOORIGEM := IIF(FINDFUNCTION("FWHASACCMODE") .AND. FINDFUNCTION("AVGETFILE") .AND. FWHASACCMODE(1),AVGETFILE("CSV | *.CSV","SELECIONE ARQUIVO DE PRODUTOS",,"", .T. ,0+48+8,,,,,,,),CGETFILE("CSV | *.CSV","SELECIONE ARQUIVO DE PRODUTOS",,"", .T. ,0+48+8,,))

ELSEIF NTIPO==2
    CLOGARQUIVO := IIF(FINDFUNCTION("FWHASACCMODE") .AND. FINDFUNCTION("AVGETFILE") .AND. FWHASACCMODE(1),AVGETFILE("*.TXT","INFORME DIRETORIO PARA ARQUIVO DE LOG",0,"", .F. ,NOR(48,8,128), .F. , .T. ,,,,,),CGETFILE("*.TXT","INFORME DIRETORIO PARA ARQUIVO DE LOG",0,"", .F. ,NOR(48,8,128),, .T. ))
    CNOMEARQUIVO := "LOG_IMPORTACAO_PRECO_"+DTOS(DATE())+"_"+STRTRAN(TIME(),":","")
    CLOGARQUIVO += CNOMEARQUIVO+".TXT"
ENDIF

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION CABECALHOEMAIL()
LOCAL CCABECALHO

CCABECALHO := ""

CCABECALHO += "<TR>"

CCABECALHO += '<TD WIDTH=80 ALIGN="MIDDLE" STYLE="BORDER-TOP:SOLID #BBBBBB 1.0PT;'
CCABECALHO += 'BORDER-LEFT:SOLID #D5D5D5 1.0PT;'
CCABECALHO += 'BORDER-BOTTOM:NONE;'
CCABECALHO += 'BORDER-RIGHT:SOLID #F2F2F2 1.0PT;'
CCABECALHO += 'BACKGROUND:#DEDEDE;'
CCABECALHO += 'PADDING:6.0PT 6.0PT 6.0PT 6.0PT">'
CCABECALHO += "TABELA"
CCABECALHO += "</TD>"

CCABECALHO += '<TD WIDTH=80 ALIGN="MIDDLE" STYLE="BORDER-TOP:SOLID #BBBBBB 1.0PT;'
CCABECALHO += 'BORDER-LEFT:SOLID #D5D5D5 1.0PT;'
CCABECALHO += 'BORDER-BOTTOM:NONE;'
CCABECALHO += 'BORDER-RIGHT:SOLID #F2F2F2 1.0PT;'
CCABECALHO += 'BACKGROUND:#DEDEDE;'
CCABECALHO += 'PADDING:6.0PT 6.0PT 6.0PT 6.0PT">'
CCABECALHO += "ITEM"
CCABECALHO += "</TD>"

CCABECALHO += '<TD WIDTH=150 ALIGN="MIDDLE" STYLE="BORDER-TOP:SOLID #BBBBBB 1.0PT;'
CCABECALHO += 'BORDER-LEFT:SOLID #D5D5D5 1.0PT;'
CCABECALHO += 'BORDER-BOTTOM:NONE;'
CCABECALHO += 'BORDER-RIGHT:SOLID #F2F2F2 1.0PT;'
CCABECALHO += 'BACKGROUND:#DEDEDE;'
CCABECALHO += 'PADDING:6.0PT 6.0PT 6.0PT 6.0PT">'
CCABECALHO += "PRODUTO"
CCABECALHO += "</TD>"

CCABECALHO += '<TD WIDTH=100 ALIGN="MIDDLE" STYLE="BORDER-TOP:SOLID #BBBBBB 1.0PT
CCABECALHO += 'BORDER-LEFT:SOLID #D5D5D5 1.0PT;'
CCABECALHO += 'BORDER-BOTTOM:NONE;'
CCABECALHO += 'BORDER-RIGHT:SOLID #F2F2F2 1.0PT;'
CCABECALHO += 'BACKGROUND:#DEDEDE;'
CCABECALHO += 'PADDING:6.0PT 6.0PT 6.0PT 6.0PT">'
CCABECALHO += "TIPO"
CCABECALHO += "</TD>"

CCABECALHO += '<TD WIDTH=300 ALIGN="MIDDLE" STYLE="BORDER-TOP:SOLID #BBBBBB 1.0PT
CCABECALHO += 'BORDER-LEFT:SOLID #D5D5D5 1.0PT;'
CCABECALHO += 'BORDER-BOTTOM:NONE;'
CCABECALHO += 'BORDER-RIGHT:SOLID #F2F2F2 1.0PT;'
CCABECALHO += 'BACKGROUND:#DEDEDE;'
CCABECALHO += 'PADDING:6.0PT 6.0PT 6.0PT 6.0PT">'
CCABECALHO += "DESCRICAO"
CCABECALHO += "</TD>"

CCABECALHO += '<TD WIDTH=125 ALIGN="MIDDLE" STYLE="BORDER-TOP:SOLID #BBBBBB 1.0PT;'
CCABECALHO += 'BORDER-LEFT:SOLID #D5D5D5 1.0PT;'
CCABECALHO += 'BORDER-BOTTOM:NONE;'
CCABECALHO += 'BORDER-RIGHT:SOLID #F2F2F2 1.0PT;'
CCABECALHO += 'BACKGROUND:#DEDEDE;'
CCABECALHO += 'PADDING:6.0PT 6.0PT 6.0PT 6.0PT">'
CCABECALHO += "PREÇO ANTIGO"
CCABECALHO += "</TD>"

CCABECALHO += '<TD WIDTH=125 ALIGN="MIDDLE" ALIGN="MIDDLE" STYLE="BORDER-TOP:SOLID #BBBBBB 1.0PT;'
CCABECALHO += 'BORDER-LEFT:SOLID #D5D5D5 1.0PT;'
CCABECALHO += 'BORDER-BOTTOM:NONE;'
CCABECALHO += 'BORDER-RIGHT:SOLID #F2F2F2 1.0PT;'
CCABECALHO += 'BACKGROUND:#DEDEDE;'
CCABECALHO += 'PADDING:6.0PT 6.0PT 6.0PT 6.0PT">'
CCABECALHO += "PREÇO NOVO"
CCABECALHO += "</TD>"

CCABECALHO += '<TD WIDTH=125 ALIGN="MIDDLE" ALIGN="MIDDLE" STYLE="BORDER-TOP:SOLID #BBBBBB 1.0PT;'
CCABECALHO += 'BORDER-LEFT:SOLID #D5D5D5 1.0PT;'
CCABECALHO += 'BORDER-BOTTOM:NONE;'
CCABECALHO += 'BORDER-RIGHT:SOLID #F2F2F2 1.0PT;'
CCABECALHO += 'BACKGROUND:#DEDEDE;'
CCABECALHO += 'PADDING:6.0PT 6.0PT 6.0PT 6.0PT">'
CCABECALHO += "DATA DE VIGÊNCIA"
CCABECALHO += "</TD>"

CCABECALHO += '<TD WIDTH=250 ALIGN="MIDDLE" STYLE="BORDER-TOP:SOLID #BBBBBB 1.0PT;'
CCABECALHO += 'BORDER-LEFT:SOLID #D5D5D5 1.0PT;'
CCABECALHO += 'BORDER-BOTTOM:NONE;'
CCABECALHO += 'BORDER-RIGHT:SOLID #F2F2F2 1.0PT;'
CCABECALHO += 'BACKGROUND:#DEDEDE;'
CCABECALHO += 'PADDING:6.0PT 6.0PT 6.0PT 6.0PT">'
CCABECALHO += "STATUS"
CCABECALHO += "</TD>"

CCABECALHO += "</TR>"

RETURN CCABECALHO

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION NOVOITEMEMAIL(CTABELADEPRECO,CITEM,CPRODUTO,CANTIGOPRECOVENDA,CNOVOPRECODEVENDA,CLOGMENSAGEM,CMAILMENSAGEM,DDATAVIGENCIA)
LOCAL CTIPOPRODUTO
LOCAL CDESCRICAOPRODUTO

CTIPOPRODUTO := POSICIONE("SB1",1,XFILIAL("SB1")+PADR(CPRODUTO,TAMSX3("B1_COD")[1]),"B1_TIPO")
CDESCRICAOPRODUTO := POSICIONE("SB1",1,XFILIAL("SB1")+PADR(CPRODUTO,TAMSX3("B1_COD")[1]),"B1_DESC")

CMAILMENSAGEM += "<TR>"

CMAILMENSAGEM += '<TD  WIDTH=80 ALIGN="MIDDLE" STYLE="BORDER-TOP:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-LEFT:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-BOTTOM:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-RIGHT:SOLID #DEDEDE 1.0PT">'
CMAILMENSAGEM += CTABELADEPRECO
CMAILMENSAGEM += "</TD>"

CMAILMENSAGEM += '<TD  WIDTH=80 ALIGN="MIDDLE" STYLE="BORDER-TOP:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-LEFT:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-BOTTOM:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-RIGHT:SOLID #DEDEDE 1.0PT">'
CMAILMENSAGEM += CITEM
CMAILMENSAGEM += "</TD>"

CMAILMENSAGEM += '<TD  WIDTH=150 STYLE="BORDER-TOP:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-LEFT:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-BOTTOM:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-RIGHT:SOLID #DEDEDE 1.0PT">'
CMAILMENSAGEM += CPRODUTO
CMAILMENSAGEM += "</TD>"

CMAILMENSAGEM += '<TD  WIDTH=100 ALIGN="MIDDLE" STYLE="BORDER-TOP:SOLID #DEDEDE 1.0PT
CMAILMENSAGEM += 'BORDER-LEFT:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-BOTTOM:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-RIGHT:SOLID #DEDEDE 1.0PT">'
CMAILMENSAGEM += CTIPOPRODUTO
CMAILMENSAGEM += "</TD>"

CMAILMENSAGEM += '<TD  WIDTH=300 STYLE="BORDER-TOP:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-LEFT:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-BOTTOM:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-RIGHT:SOLID #DEDEDE 1.0PT">'
CMAILMENSAGEM += CDESCRICAOPRODUTO
CMAILMENSAGEM += "</TD>"

CMAILMENSAGEM += '<TD  WIDTH=125 ALIGN="RIGHT" STYLE="BORDER-TOP:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-LEFT:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-BOTTOM:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-RIGHT:SOLID #DEDEDE 1.0PT">'
CMAILMENSAGEM += CANTIGOPRECOVENDA
CMAILMENSAGEM += "</TD>"

CMAILMENSAGEM += '<TD  WIDTH=125 ALIGN="RIGHT" STYLE="BORDER-TOP:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-LEFT:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-BOTTOM:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-RIGHT:SOLID #DEDEDE 1.0PT">'
CMAILMENSAGEM += CNOVOPRECODEVENDA
CMAILMENSAGEM += "</TD>"

CMAILMENSAGEM += '<TD  WIDTH=125 ALIGN="RIGHT" STYLE="BORDER-TOP:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-LEFT:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-BOTTOM:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-RIGHT:SOLID #DEDEDE 1.0PT">'
CMAILMENSAGEM += DTOC(DDATAVIGENCIA)
CMAILMENSAGEM += "</TD>"

CMAILMENSAGEM += '<TD  WIDTH=250 STYLE="BORDER-TOP:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-LEFT:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-BOTTOM:SOLID #DEDEDE 1.0PT;'
CMAILMENSAGEM += 'BORDER-RIGHT:SOLID #DEDEDE 1.0PT">'
CMAILMENSAGEM += CLOGMENSAGEM
CMAILMENSAGEM += "</TD>"

CMAILMENSAGEM += "</TR>" + CRLF

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION ENVIAEMAIL(CMAILMENSAGEM,CERROR,CHTMLLOG)
LOCAL LDISCONNECT
LOCAL CDATAPROCESSAMENTO
LOCAL CHORAPROCESSAMENTO
LOCAL CSERVER
LOCAL CACCOUNT
LOCAL CPASSWORD
LOCAL LAUTH
LOCAL OPROCESS
LOCAL OHTML
LOCAL CBODY
LOCAL CPARA
LOCAL CUSUARIO
LOCAL CPROCESSO
LOCAL CASSUNTO
LOCAL LCONNECTED
LOCAL LRETURN

LDISCONNECT :=  .T. 
CDATAPROCESSAMENTO := DTOC(DATE())
CHORAPROCESSAMENTO := TIME()
CSERVER :=  ALLTRIM(GETMV("MV_RELSERV",,""))
CACCOUNT :=  ALLTRIM(GETMV("MV_RELACNT",,""))
CPASSWORD :=  ALLTRIM(GETMV("MV_RELPSW",,""))
LAUTH := GETMV("MV_RELAUTH",,"")
CBODY := ""
CPARA :=  ALLTRIM(GETMV("AM_05D0101",,""))
CUSUARIO :=  UPPER(USRRETNAME(RETCODUSR()))
CPROCESSO := "M05D01"
CASSUNTO := "ATUALIZAÇÃO DE TABELA DE PREÇO"
LCONNECTED :=  .F. 

LRETURN :=  .F. 
 
    IF EMPTY(CPARA)
        BREAK 
    ENDIF
    
    OPROCESS := TWFPROCESS():NEW("",CPROCESSO)
    OPROCESS:NEWTASK("INICIO","/WORKFLOW/MACOM/WF_MACOM_GENERICO.HTML")
    
    OHTML := OPROCESS:OHTML
    OHTML:VALBYNAME("PROCESSO",CPROCESSO+" - "+CASSUNTO)
    OHTML:VALBYNAME("USUARIO",CUSUARIO)
    OHTML:VALBYNAME("DATA",CDATAPROCESSAMENTO)
    OHTML:VALBYNAME("HORA",CHORAPROCESSAMENTO)
    OHTML:VALBYNAME("MSG",CMAILMENSAGEM)
    
    CBODY := OHTML:HTMLCODE()
    
    CHTMLLOG := CBODY
    
    IF ( .F. ) 
    LCONNECTED := CALLPROC("MAILSMTPON",CSERVER,CACCOUNT,CPASSWORD,,,)
    ELSE
    LCONNECTED := MAILSMTPON(CSERVER,CACCOUNT,CPASSWORD,,,)
    ENDIF
    
    IF LAUTH
        
        IF !(MAILAUTH(CACCOUNT,CPASSWORD))
            CERROR := "ERRO AO CONECTAR NA CONTA DE E-MAIL."
            
            IF ( .F. ) 
            CALLPROC("MAILSMTPOFF")
            ELSE
            MAILSMTPOFF()
            ENDIF
            
            BREAK 
        ENDIF
    ENDIF
    
    IF !(MAILSEND(CACCOUNT,{CPARA},{},{},"WORKFLOW MACOM - "+CASSUNTO,CBODY,{""}, .T. ))
        
        IF ( .F. ) 
        CERROR := CALLPROC("MAILGETERR")
        ELSE
        CERROR := MAILGETERR()
        ENDIF
        BREAK 
    ENDIF
    
    IF ( .F. ) 
    LDISCONNECT := CALLPROC("MAILSMTPOFF")
    ELSE
    LDISCONNECT := MAILSMTPOFF()
    ENDIF
    
    OPROCESS:FREE()
    OPROCESS := NIL
    
    LRETURN :=  .T. 

RETURN LRETURN

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION GRAVALOGLOCAL(CHTMLLOG,CNOMEARQUIVO)
LOCAL CCAMINHOLOG
LOCAL CARQUIVOHTML

CCAMINHOLOG := GETTEMPPATH()
CARQUIVOHTML := CNOMEARQUIVO+".HTML"

IF SUBSTRING(CCAMINHOLOG, LEN(CCAMINHOLOG),1)<>"\"
    CCAMINHOLOG += "\"
ENDIF

MEMOWRITE(CCAMINHOLOG+CARQUIVOHTML,CHTMLLOG)
SHELLEXECUTE("OPEN",CARQUIVOHTML,"",CCAMINHOLOG,1)

RETURN 
