#INCLUDE "protheus.ch"

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M05R02()

PRIVATE LIMPRVLR :=  .T. 

FWMSGRUN(,{||U_M05R02A()},,"GERANDO RELATÓRIO...")

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M05R02S()

PRIVATE LIMPRVLR :=  .F. 

FWMSGRUN(,{||U_M05R02A()},,"GERANDO RELATÓRIO...")

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M05R02A()
LOCAL OPRINTER := NIL
LOCAL OFONT14B := NIL
LOCAL OFONT12 := NIL
LOCAL OFONT12B := NIL
LOCAL OFONT18T := NIL
LOCAL OFONT9 := NIL
LOCAL NROW := - (80)
LOCAL CDATA := DTOC(DATE())+" "+TIME()
LOCAL NPAGE := 1

M05RFONT(@OFONT9,@OFONT12,@OFONT12B,@OFONT14B,@OFONT18T)

OPRINTER := FWMSPRINTER():NEW("PP"+SCJ->CJ_NUM+"_"+ SUBSTR(DTOS(DATE()),7,2)+"_"+STRTRAN(TIME(),":",""),6, .T. ,, .T. )

OPRINTER:SETRESOLUTION(78)
OPRINTER:SETLANDSCAPE()
OPRINTER:SETMARGIN(0,0,0,0)

OPRINTER:STARTPAGE()

MR05CAB1(OPRINTER,OFONT14B,OFONT12,@NROW)

IF MR05POSICIONA()

    MR05CAB2(OPRINTER,OFONT12,OFONT18T,@NROW)

    MR05CAB3(OPRINTER,OFONT12,@NROW)

    MR05CAB4(OPRINTER,OFONT12,OFONT14B,OFONT18T,@NROW)

    MAFISEND()

    M05RIITENS(OPRINTER,OFONT9,OFONT12,OFONT12B,@NROW,@NPAGE,CDATA)

    MR05ROD(OPRINTER,OFONT12,OFONT12B,OFONT14B,NROW,NPAGE,CDATA)

    MAFISEND()
    OPRINTER:ENDPAGE()
    OPRINTER:PRINT()
    FREEOBJ(OPRINTER)
ENDIF

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05RICABIT(OPRINTER,OFONT12B,NROW)
LOCAL NROWSTEP := 45

NROW += NROWSTEP

OPRINTER:BOX(NROW,100,NROW+(NROWSTEP) * (2.5),3200)

OPRINTER:BOX(NROW,200,NROW+(NROWSTEP) * (2.5),403)

OPRINTER:BOX(NROW,650,NROW+(NROWSTEP) * (2.5),1250)

OPRINTER:BOX(NROW,1400,NROW+(NROWSTEP) * (2.5),1500)

IF LIMPRVLR
    OPRINTER:BOX(NROW,1700,NROW+(NROWSTEP) * (2.5),1950)
    OPRINTER:BOX(NROW,1700,NROW+(NROWSTEP) * (1.25),1950)
    OPRINTER:BOX(NROW+(NROWSTEP) * (1.25),1700,NROW+(NROWSTEP) * (2.5),1770)

    OPRINTER:BOX(NROW,1950,NROW+(NROWSTEP) * (1.25),2200)
    OPRINTER:BOX(NROW+(NROWSTEP) * (1.25),1950,NROW+(NROWSTEP) * (2.5),2020)

    OPRINTER:BOX(NROW,2200,NROW+(NROWSTEP) * (2.5),2450)
    OPRINTER:BOX(NROW,2200,NROW+(NROWSTEP) * (1.25),2450)
    OPRINTER:BOX(NROW+(NROWSTEP) * (1.25),2200,NROW+(NROWSTEP) * (2.5),2270)

    OPRINTER:BOX(NROW,2700,NROW+(NROWSTEP) * (2.5),2950)
ELSE 

    OPRINTER:BOX(NROW,650,NROW+(NROWSTEP) * (2.5),2900)

    OPRINTER:BOX(NROW,3050,NROW+(NROWSTEP) * (2.5),3200)
ENDIF

NROW += NROWSTEP

OPRINTER:SAY(NROW,120,"ITEM",OFONT12B)
OPRINTER:SAY(NROW,250,"PLANTA",OFONT12B)
OPRINTER:SAY(NROW,480,"CÓDIGO",OFONT12B)
OPRINTER:SAY(NROW,850,"DESCRIÇÃO",OFONT12B)
OPRINTER:SAY(NROW,1280,"NCM",OFONT12B)
OPRINTER:SAY(NROW,1420,"QTD",OFONT12B)

IF LIMPRVLR
    OPRINTER:SAY(NROW,1550,"VALOR",OFONT12B)
    OPRINTER:SAY(NROW+NROWSTEP,1540,"UNITÁRIO",OFONT12B)

    OPRINTER:SAY(NROW,1800,"IPI",OFONT12B)
    OPRINTER:SAY(NROW+NROWSTEP,1720,"%",OFONT12B)
    OPRINTER:SAY(NROW+NROWSTEP,1810,"VALOR",OFONT12B)

    OPRINTER:SAY(NROW,2040,"ICMS",OFONT12B)
    OPRINTER:SAY(NROW+NROWSTEP,1970,"%",OFONT12B)
    OPRINTER:SAY(NROW+NROWSTEP,2060,"VALOR",OFONT12B)

 OPRINTER:SAY(NROW,2260,"PIS/COFINS",OFONT12B)
    OPRINTER:SAY(NROW+NROWSTEP,2220,"%",OFONT12B)
    OPRINTER:SAY(NROW+NROWSTEP,2300,"VALOR",OFONT12B)

    OPRINTER:SAY(NROW,2490,"VALOR ICMS",OFONT12B)
    OPRINTER:SAY(NROW+NROWSTEP,2540,"ST",OFONT12B)

    OPRINTER:SAY(NROW,2750,"VALOR UNIT",OFONT12B)
    OPRINTER:SAY(NROW+NROWSTEP,2750,"C/IMPOSTOS",OFONT12B)

    OPRINTER:SAY(NROW,2980,"VALOR TOTAL",OFONT12B)
ELSE 

    OPRINTER:SAY(NROW,2950,"NCM",OFONT12B)
    OPRINTER:SAY(NROW,3100,"QTD",OFONT12B)
ENDIF

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05RIITENS(OPRINTER,OFONT9,OFONT12,OFONT12B,NROW,NPAGE,CDATA)
LOCAL NROWSTEP := 45
LOCAL _CALIAS := GETNEXTALIAS()
LOCAL NITEM := 0
LOCAL _NTOTAL := 0

M05RICABIT(OPRINTER,OFONT12B,@NROW)

MR05PLANIL(SCJ->CJ_NUM,@_CALIAS,@_NTOTAL)

NROW += NROWSTEP+10

(_CALIAS)->(DBGOTOP())

WHILE !(_CALIAS)->(EOF())
 
    NITEM++
    MR05IMPITEM(_CALIAS,OPRINTER,@NROW,OFONT9,OFONT12B,NITEM)

    MR05ENDPAG(OPRINTER,OFONT12,OFONT12B,@NROW,NROWSTEP,@NPAGE,CDATA,NITEM,_NTOTAL)

    (_CALIAS)->(DBSKIP())
    ENDDO

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR05IMPITEM(_CALIAS,OPRINTER,NROW,OFONT9,OFONT12B,NITEM)
LOCAL NROWSTEP := 45
LOCAL CPICVAL := "@E 99,999,999.99"
LOCAL CPICALIQ := "@E 999.99"

LOCAL ADESC := M05RDESCR( ALLTRIM(_CALIAS->_PRODUTO),IIF(EMPTY(_CALIAS->B5_CEME),"PRODUTO SEM COMPLEMENTO", ALLTRIM(_CALIAS->B5_CEME)), ALLTRIM(_CALIAS->_DESCRI),_CALIAS->B5_COMPRLC,_CALIAS->B5_LARGLC,_CALIAS->B5_ALTURLC,_CALIAS->_ITEM)
LOCAL NDESC := 1

OPRINTER:BOX(NROW,100,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),3200)
OPRINTER:BOX(NROW,190,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),403)

IF LIMPRVLR

    OPRINTER:BOX(NROW,650,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),1250)
    OPRINTER:BOX(NROW,1400,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),1500)
ELSE 

    OPRINTER:BOX(NROW,650,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),2900)
    OPRINTER:BOX(NROW,3050,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),3200)
ENDIF

IF LIMPRVLR

    OPRINTER:BOX(NROW,1700,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),1950)
    OPRINTER:BOX(NROW,1700,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),1770)
    OPRINTER:BOX(NROW,1950,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),2200)
    OPRINTER:BOX(NROW,1950,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),2020)
    OPRINTER:BOX(NROW,2200,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),2450)
    OPRINTER:BOX(NROW,2200,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),2270)
    OPRINTER:BOX(NROW,2700,NROW+((NROWSTEP) * (1.25)) * ( LEN(ADESC)),2950)
ENDIF

NROW += NROWSTEP

OPRINTER:SAY(NROW-8,125,_CALIAS->_ITEM,OFONT9)
OPRINTER:SAY(NROW-8,200, SUBSTR( ALLTRIM(_CALIAS->_XITEMP),1,15),OFONT9)
OPRINTER:SAY(NROW-8,415,_CALIAS->_PRODUTO,OFONT9)

IF LIMPRVLR
    OPRINTER:SAY(NROW-8,1267,TRANSFORM(_CALIAS->B1_POSIPI,"@R 9999.99.99"),OFONT9)
    OPRINTER:SAY(NROW-8,1414,TRANSFORM(NOROUND(MAFISRET(NITEM,"IT_QUANT"),2),"@E 999999.99"),OFONT9)
    OPRINTER:SAY(NROW-8,1540,TRANSFORM(NOROUND(MAFISRET(NITEM,"IT_PRCUNI"),2),CPICVAL),OFONT9)
 OPRINTER:SAY(NROW-8,1709,TRANSFORM(NOROUND(MAFISRET(NITEM,"IT_ALIQIPI"),2),CPICALIQ),OFONT9)
    OPRINTER:SAY(NROW-8,1810,TRANSFORM(NOROUND(MAFISRET(NITEM,"IT_VALIPI"),2),CPICVAL),OFONT9)

    OPRINTER:SAY(NROW-8,1918,TRANSFORM(NOROUND(_CALIAS->_XALQICM,2),CPICVAL),OFONT9)
    OPRINTER:SAY(NROW-8,2050,TRANSFORM(NOROUND(MAFISRET(NITEM,"IT_VALICM"),2),CPICVAL),OFONT9)
    OPRINTER:SAY(NROW-8,2210,TRANSFORM(NOROUND(MAFISRET(NITEM,"IT_ALIQPS2")+MAFISRET(NITEM,"IT_ALIQCF2"),2),CPICALIQ),OFONT9)
    OPRINTER:SAY(NROW-8,2290,TRANSFORM(NOROUND(MAFISRET(NITEM,"IT_VALPS2")+MAFISRET(NITEM,"IT_VALCF2"),2),CPICVAL),OFONT9)
    OPRINTER:SAY(NROW-8,2550,TRANSFORM(NOROUND(MAFISRET(NITEM,"IT_VALSOL"),2),CPICVAL),OFONT9)
    OPRINTER:SAY(NROW-8,2780,TRANSFORM(NOROUND((MAFISRET(NITEM,"IT_TOTAL")-MAFISRET(NITEM,"IT_FRETE")+MAFISRET(NITEM,"IT_DESPESA")) / (_CALIAS->_QTDVEN),2),CPICVAL),OFONT9)
    OPRINTER:SAY(NROW-8,3010,TRANSFORM(NOROUND(MAFISRET(NITEM,"IT_TOTAL")-MAFISRET(NITEM,"IT_FRETE")+MAFISRET(NITEM,"IT_DESPESA"),2),CPICVAL),OFONT12B)
ELSE 

    OPRINTER:SAY(NROW-8,2925,TRANSFORM(_CALIAS->B1_POSIPI,"@R 9999.99.99"),OFONT9)
    OPRINTER:SAY(NROW-8,3050,TRANSFORM(NOROUND(MAFISRET(NITEM,"IT_QUANT"),2),"@E 999999.99"),OFONT9)
ENDIF

FOR NDESC := 1 TO  LEN(ADESC)
    OPRINTER:SAY(NROW-8,660,ADESC[NDESC],OFONT9)
    NROW += NROWSTEP
NEXT

NROW -= NROWSTEP

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05RDESCR(CPROD,CDESCSB1,CDESCSCK,NCOMP,NLAR,NALT,CITEM)
LOCAL ARET := {}
LOCAL CAUX := ""
LOCAL CLETRAS := ""
LOCAL CRET := ""
LOCAL I := 0
LOCAL NTAM := 45
LOCAL NINI := 1
LOCAL NQUEBRA := 1
LOCAL CPIC := "@E 999999"

IF !(LIMPRVLR)

    NTAM := (NTAM) * (3.5)
ENDIF

CDESCSB1 := IIF(VALTYPE(CDESCSB1)=="U","PRODUTO SEM COMPLEMENTO",CDESCSB1)

IF CPROD=="N/A"
    CDESC := CDESCSCK
ELSE 
    CDESC := CDESCSB1

    IF NCOMP>0 .AND. NLAR>0 .AND. NALT>0
        CDESC += " - MEDINDO: "+ ALLTRIM(TRANSFORM(NCOMP,CPIC))+" X "+ ALLTRIM(TRANSFORM(NLAR,CPIC))+" X "+ ALLTRIM(TRANSFORM(NALT,CPIC))
    ENDIF
ENDIF

IF SCJ->CJ_XFINAME=="1"
    CFINAME := POSICIONE("SB1",1,XFILIAL("SB1")+CPROD,"B1_XFINAME")
    CSERMACOM := POSICIONE("ZA0",1,XFILIAL("ZA0")+SCJ->CJ_NUM+CITEM,"ZA0_SERIE")
    CDESC := "COD.FINAME:"+CFINAME+" | "+"NR.SERIE:"+CSERMACOM+" | "+CDESC
ENDIF

REPLACE(CDESC,CHR(13)," ")

FOR I := 1 TO  LEN(CDESC)-1
    CLETRAS :=  SUBSTR(CDESC,I,2)

    IF CLETRAS<>"  "
        CRET += LEFT(CLETRAS,1)
    ENDIF
NEXT

IF I>0 .AND. CLETRAS<>"  "
    CRET += RIGHT(CLETRAS,1)
ENDIF

CDESC := CRET

WHILE  LEN(CDESC)>0
 
    CAUX := SUBSTRING(CDESC,1,NTAM)

    IF NTAM<= LEN(CDESC)
        NQUEBRA := RAT(" ",CAUX)

        AADD(ARET,SUBSTRING(CDESC,1,NQUEBRA))
    ELSE 
        AADD(ARET,CDESC)
        EXIT 
    ENDIF

    NINI := NQUEBRA++
    CDESC := SUBSTRING(CDESC,NINI, LEN(CDESC))
    ENDDO

RETURN ACLONE(ARET)

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR05POSICIONA()
LOCAL LRET :=  .T. 

SA1->(DBSETORDER(1))
SA1->(DBGOTOP())

IF !(SA1->(DBSEEK(XFILIAL("SA1")+(SCJ)->(CJ_CLIENTE+CJ_LOJA))))
    MSGINFO(I18N("NÃO FORAM ENCONTRADOS DADOS DO CLIENTE #1 LOJA #2." + CRLF+"VERIFIQUE.",{SCJ->CJ_CLIENTE,SCJ->CJ_LOJA}),"ATENÇÃO")
    LRET :=  .F. 
ENDIF

IF LRET
    SA3->(DBSETORDER(1))
    SA3->(DBGOTOP())

    IF !(SA3->(DBSEEK(XFILIAL("SA3")+SCJ->CJ_XVEND1)))
        MSGINFO(I18N("NÃO FORAM ENCONTRADOS DADOS DO VENDEDOR #1" + CRLF+"VERIFIQUE.",{SCJ->CJ_XVEND1}),"ATENÇÃO")
        LRET :=  .F. 
    ENDIF
ENDIF

RETURN LRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05RFONT(OFONT9,OFONT12,OFONT12B,OFONT14B,OFONT18T)
OFONT9 := TFONT():NEW("ARIAL",,9)
OFONT12 := TFONT():NEW("ARIAL",,12)
OFONT12B := TFONT():NEW("ARIAL",,12, .T. , .T. )
OFONT14B := TFONT():NEW("ARIAL",,14, .T. , .T. )
OFONT18T := TFONT():NEW("ARIAL",,18, .T. , .T. )
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR05CAB1(OPRINTER,OFONT14B,OFONT12,NROW)
LOCAL CNOME := "HOSHIZAKI MACOM LTDA"
LOCAL CENDC := "AV JULIA GAIOLLI, 474, BONSUCESSO, GUARULHOS-SP, CEP 07251-500"
LOCAL CCGC := "CNPJ: 43.553.668/0001-79 I.E.: 336.179.661.113"
LOCAL CTEL := "TELEFONE: 55 11 2085-7000"
LOCAL CMAIL := "WWW.HOSHIZAKIMACOM.COM.BR"
LOCAL NROWSTEP := 45

IF CFILANT<>"01"

    CENDC := CAPITAL( ALLTRIM(SM0->M0_ENDENT)+", "+ ALLTRIM(SM0->M0_BAIRENT)+", "+ ALLTRIM(SM0->M0_CIDENT))+"-"+ ALLTRIM(SM0->M0_ESTENT)+", CEP "+LEFT(SM0->M0_CEPENT,5)+"-"+ SUBSTR(SM0->M0_CEPENT,6,3)
    CCGC := "CNPJ: "+SM0->M0_CGC+" I.E.: "+ ALLTRIM(SM0->M0_INSC)
    CTEL := "TELEFONE: "+SM0->M0_TEL
ENDIF

OPRINTER:SAYBITMAP(NROW,100,GETSRVPROFSTRING("STARTPATH","")+"LOGO_M05R02.BMP",751,178)

OPRINTER:SAY(NROW,2100,CNOME,OFONT14B)
OPRINTER:SAY(NROW += NROWSTEP,2100,CENDC,OFONT12)
OPRINTER:SAY(NROW += NROWSTEP,2100,CCGC,OFONT12)
OPRINTER:SAY(NROW += NROWSTEP,2100,CTEL,OFONT12)
OPRINTER:SAY(NROW += NROWSTEP,2100,CMAIL,OFONT12)

NROW += NROWSTEP
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR05CAB2(OPRINTER,OFONT12,OFONT18T,NROW)
LOCAL LRET :=  .T. 
LOCAL CMASCCPF := "@R 999.999.999-99"
LOCAL CMASCCNPJ := "@R 99.999.999/9999-99"
LOCAL NROWSTEP := 45

IF LRET
    NROW += NROWSTEP

    OPRINTER:SAY(NROW += NROWSTEP,100, UPPER( ALLTRIM(SA1->A1_NOME)),OFONT18T)
    OPRINTER:SAY(NROW,1700,"CNPJ/CPF: ",OFONT12)
    OPRINTER:SAY(NROW,1900,TRANSFORM( ALLTRIM(SA1->A1_CGC),IIF(SA1->A1_PESSOA=="F",CMASCCPF,CMASCCNPJ)),OFONT12)

    OPRINTER:SAY(NROW += NROWSTEP,100, UPPER( ALLTRIM(SA1->A1_END))+IIF(!(EMPTY(SA1->A1_COMPLEM))," - "+SA1->A1_COMPLEM,""),OFONT12)
    OPRINTER:SAY(NROW,1700,"IE.: ",OFONT12)
    OPRINTER:SAY(NROW,1900,TRANSFORM( ALLTRIM(SA1->A1_INSCR),"@R 999.999.999.999"),OFONT12)
    OPRINTER:SAY(NROW,2700,"GUARULHOS, "+MR05DATE(),OFONT12)

    OPRINTER:SAY(NROW += NROWSTEP,100, UPPER( ALLTRIM(SA1->A1_BAIRRO))+" - "+ UPPER( ALLTRIM(SA1->A1_MUN))+" - "+ UPPER( ALLTRIM(SA1->A1_EST))+" - CEP: "+TRANSFORM( ALLTRIM(SA1->A1_CEP),"@R 99999-999"),OFONT12)
    OPRINTER:SAY(NROW,1700,"SUFRAMA.: ",OFONT12)
    OPRINTER:SAY(NROW,1900,SA1->A1_SUFRAMA,OFONT12)
    OPRINTER:SAY(NROW,2700,"REP.: "+ ALLTRIM(SA3->A3_NREDUZ),OFONT12)

    NROW += NROWSTEP

    OPRINTER:LINE(NROW,100,NROW,3200)
ENDIF
RETURN LRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR05CAB3(OPRINTER,OFONT12,NROW)
LOCAL NROWSTEP := 45
LOCAL CALIASCONT := GETNEXTALIAS()
LOCAL CENTIDADE := "SA1"
LOCAL CCODENT := PADR(SCJ->(CJ_CLIENTE+CJ_LOJA),TAMSX3("AC8_CODENT")[1])
LOCAL CPIC1 := "@R 9999-99999"
LOCAL CPIC2 := "@R (999)"

_cQry := " SELECT U5_CODCONT, "
_cQry += "        U5_CONTAT, "
_cQry += "        U5_EMAIL, "
_cQry += "        U5_FCOM1, "
_cQry += "        U5_DDD, "
_cQry += "        U5_CELULAR, "
_cQry += "        UM_DESC "
_cQry += " FROM "+RETSQLNAME("AC8")+" AC8 "
_cQry += " LEFT JOIN "+RETSQLNAME("SU5")+" SU5 ON SU5.D_E_L_E_T_= ' ' "
_cQry += " AND U5_FILIAL = '"+XFILIAL("SU5")+"' "
_cQry += " AND U5_CODCONT = AC8_CODCON "
_cQry += " INNER JOIN "+RETSQLNAME("SUM")+" SUM ON SUM.D_E_L_E_T_= ' ' "
_cQry += " AND UM_FILIAL = '"+XFILIAL("SUM")+"' "
_cQry += " AND UM_CARGO = U5_FUNCAO "
_cQry += " WHERE AC8_ENTIDA = "+___SQLGETVALUE(CENTIDADE)+" "
_cQry += "   AND AC8.D_E_L_E_T_= ' ' "
_cQry += "   AND AC8_FILIAL = '"+XFILIAL("AC8")+"' "
_cQry += "   AND AC8_CODENT = "+___SQLGETVALUE(CCODENT)
__EXECSQL(CALIASCONT,_cQry,{}, .F. )

IF EMPTY(SCJ->CJ_XCONT) .AND. EMPTY(SCJ->CJ_XCONT2) .AND. EMPTY(SCJ->CJ_XCONT3) .AND. EMPTY(SCJ->CJ_XCONT4) .AND. EMPTY(SCJ->CJ_XCONT5)
    
    IF !(CALIASCONT)->(EOF())
        WHILE !(CALIASCONT)->(EOF())
        
            OPRINTER:SAY(NROW += NROWSTEP,100,"CONTATO: ",OFONT12)
            OPRINTER:SAY(NROW,260, ALLTRIM(CALIASCONT->U5_CONTAT),OFONT12)

            OPRINTER:SAY(NROW,820, UPPER( ALLTRIM(CALIASCONT->UM_DESC)),OFONT12)

            OPRINTER:SAY(NROW,1360, UPPER( ALLTRIM(CALIASCONT->U5_EMAIL)),OFONT12)

            OPRINTER:SAY(NROW,2120,"CELULAR: ",OFONT12)
            OPRINTER:SAY(NROW,2300,TRANSFORM(CALIASCONT->U5_DDD,CPIC2)+" "+TRANSFORM(CALIASCONT->U5_CELULAR,CPIC1),OFONT12)

            OPRINTER:SAY(NROW,2700,"COMERCIAL: ",OFONT12)
       OPRINTER:SAY(NROW,2900,TRANSFORM(CALIASCONT->U5_DDD,CPIC2)+" "+TRANSFORM(CALIASCONT->U5_FCOM1,CPIC1),OFONT12)

            (CALIASCONT)->(DBSKIP())
            ENDDO
    ENDIF
ELSE 

    WHILE !(CALIASCONT)->(EOF())
    
        IF (CALIASCONT->U5_CODCONT==SCJ->CJ_XCONT) .OR. ((CALIASCONT->U5_CODCONT==SCJ->CJ_XCONT2) .OR. ((CALIASCONT->U5_CODCONT==SCJ->CJ_XCONT3) .OR. ((CALIASCONT->U5_CODCONT==SCJ->CJ_XCONT4) .OR. (CALIASCONT->U5_CODCONT==SCJ->CJ_XCONT5))))
            OPRINTER:SAY(NROW += NROWSTEP,100,"CONTATO: ",OFONT12)
            OPRINTER:SAY(NROW,260, ALLTRIM(CALIASCONT->U5_CONTAT),OFONT12)

            OPRINTER:SAY(NROW,820, UPPER( ALLTRIM(CALIASCONT->UM_DESC)),OFONT12)

            OPRINTER:SAY(NROW,1360, UPPER( ALLTRIM(CALIASCONT->U5_EMAIL)),OFONT12)

            OPRINTER:SAY(NROW,2120,"CELULAR: ",OFONT12)
            OPRINTER:SAY(NROW,2300,TRANSFORM(CALIASCONT->U5_DDD,CPIC2)+" "+TRANSFORM(CALIASCONT->U5_CELULAR,CPIC1),OFONT12)

            OPRINTER:SAY(NROW,2700,"COMERCIAL: ",OFONT12)
            OPRINTER:SAY(NROW,2900,TRANSFORM(CALIASCONT->U5_DDD,CPIC2)+" "+TRANSFORM(CALIASCONT->U5_FCOM1,CPIC1),OFONT12)
        ENDIF
        (CALIASCONT)->(DBSKIP())
        ENDDO
ENDIF

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR05CAB4(OPRINTER,OFONT12,OFONT14B,OFONT18T,NROW)
LOCAL NROWSTEP := 45

NROW += (NROWSTEP) * (2)

OPRINTER:LINE(NROW,100,NROW,3200)

OPRINTER:SAY(NROW += NROWSTEP,100,"PROPOSTA: ",OFONT12)
OPRINTER:SAY(NROW,300,SCJ->CJ_NUM,OFONT14B)

OPRINTER:SAY(NROW,1000,"CLIENTE/LOJA:",OFONT12)
OPRINTER:SAY(NROW,1250,SCJ->CJ_CLIENTE+"/"+SCJ->CJ_LOJA,OFONT12)

OPRINTER:SAY(NROW,1900,"REDE:",OFONT12)
OPRINTER:SAY(NROW,2150,POSICIONE("SA1",1,XFILIAL("SA1")+SCJ->CJ_CLIENTE+SCJ->CJ_LOJA,"A1_XREDE"),OFONT12)

OPRINTER:SAY(NROW,2700,"LOJA:",OFONT12)
OPRINTER:SAY(NROW,2900,POSICIONE("SA1",1,XFILIAL("SA1")+SCJ->CJ_CLIENTE+SCJ->CJ_LOJA,"A1_XIDLOJA"),OFONT12)

OPRINTER:SAY(NROW += NROWSTEP,100,"COND PAG (MEDIANTE ANÁLISE DE CRÉDITO): ",OFONT12)

OPRINTER:SAY(NROW,800,MR05GETCPG(),OFONT12)

OPRINTER:SAY(NROW += NROWSTEP,100,"REFERÊNCIA:",OFONT12)
OPRINTER:SAY(NROW,300, ALLTRIM(SCJ->CJ_XOBRAS),OFONT12)

NROW += (NROWSTEP) * (0.5)
OPRINTER:LINE(NROW,100,NROW,3200)
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR05ROD(OPRINTER,OFONT12,OFONT12B,OFONT14B,NROW,NPAGE,CDATA)
LOCAL NROWSTEP := 45
LOCAL CPICVAL := "@E 99,999,999.99"

LOCAL DVALIDA := SCJ->CJ_VALIDA
LOCAL CDESPESA := TRANSFORM(NOROUND(MAFISRET(,"NF_DESPESA"),2),CPICVAL)
LOCAL CFRETE := TRANSFORM(NOROUND(IIF(SCJ->CJ_XTFRETE=="C",MAFISRET(,"NF_FRETE"),0),2),CPICVAL)
LOCAL CTOTAL := TRANSFORM(NOROUND(MAFISRET(,"NF_TOTAL"),2),"@E 9,999,999,999.99")
LOCAL CSUBTOT := TRANSFORM(NOROUND(MAFISRET(,"NF_TOTAL")-MAFISRET(,"NF_FRETE")+MAFISRET(,"NF_DESPESA"),2),"@E 9,999,999,999.99")
LOCAL CMOEDA :=  ALLTRIM(GETMV("MV_MOEDA"+CVALTOCHAR(SCJ->CJ_MOEDA),,""))

NROW += (NROWSTEP) * (5)

IF NROW>1600
    NROW := 2100+NROWSTEP

    OPRINTER:SAY(NROW += NROWSTEP,100,I18N("PROPOSTA #1 IMPRESSA EM #2.",{SCJ->CJ_NUM,CDATA}),OFONT12)
    OPRINTER:SAY(NROW,3000,I18N("PÁG. #1",{OPRINTER:NPAGECOUNT}),OFONT12)

    OPRINTER:ENDPAGE()
    OPRINTER:STARTPAGE()
    NROW := 0

    NPAGE++
ENDIF

OPRINTER:SAY(NROW += NROWSTEP,100,"TIPO FRETE: ",OFONT12)
OPRINTER:SAY(NROW,300,M05RTPFRET(),OFONT12)

IF LIMPRVLR

    OPRINTER:LINE(NROW-(NROWSTEP) * (1.25),2350,NROW-(NROWSTEP) * (1.25),3200)
    OPRINTER:SAY(NROW,2450,"SUB-TOTAL ("+CMOEDA+")",OFONT12)
    OPRINTER:SAY(NROW,2900,CSUBTOT,OFONT12)

    OPRINTER:SAY(NROW += NROWSTEP,100,"INSTALAÇÃO: ",OFONT12)
    OPRINTER:SAY(NROW,300,M05RTPISNT(),OFONT12)
    OPRINTER:SAY(NROW,2450,"VALOR FRETE: ",OFONT12)
    OPRINTER:SAY(NROW,2900,CFRETE,OFONT12)

    OPRINTER:SAY(NROW += NROWSTEP,100,"VALIDADE: ",OFONT12)
    OPRINTER:SAY(NROW,300,DTOC(DVALIDA),OFONT12)

    OPRINTER:SAY(NROW,2450,"VALOR INSTALAÇÃO",OFONT12)
    OPRINTER:SAY(NROW,2900,CDESPESA,OFONT12)

    OPRINTER:SAY(NROW += NROWSTEP,100,"PRAZO DE EMBARQUE: ",OFONT12)
    OPRINTER:SAY(NROW,500,SCJ->CJ_XPRZEMB,OFONT12)

    OPRINTER:LINE(NROW-(NROWSTEP) * (0.5),2350,NROW-(NROWSTEP) * (0.5),3200)
    OPRINTER:SAY(NROW += NROWSTEP,2450,"TOTAL GERAL",OFONT14B)
    OPRINTER:SAY(NROW,2900,CTOTAL,OFONT14B)
ENDIF

NROW += NROWSTEP
NROW += NROWSTEP

OPRINTER:SAY(NROW += NROWSTEP,150,"DE ACORDO E CIENTE DAS CONDIÇÕES GERAIS DE FORNECIMENTO: ",OFONT12)

OPRINTER:SAY(NROW,2450,"HOSHIZAKI MACOM LTDA",OFONT12B)

OPRINTER:SAY(NROW += NROWSTEP,300, UPPER( ALLTRIM(SA1->A1_NOME)),OFONT12B)
OPRINTER:SAY(NROW,2450,"GERÊNCIA: "+ ALLTRIM(SA3->A3_SUPER),OFONT12)

NROW += NROWSTEP

OPRINTER:SAY(NROW += NROWSTEP,2450,"REPRESENTANTE COMERCIAL ",OFONT12)
OPRINTER:SAY(NROW += NROWSTEP,2450, ALLTRIM(SA3->A3_NOME),OFONT12)

OPRINTER:SAY(NROW += NROWSTEP,150,"POR:_______________________________________________________________________________________________________________ ",OFONT12)
OPRINTER:SAY(NROW,2450, ALLTRIM(SA3->A3_NREDUZ),OFONT12)

OPRINTER:SAY(NROW += NROWSTEP,200,"NOME E CARGO",OFONT12)
OPRINTER:SAY(NROW,1100,"ASSINATURA",OFONT12)
OPRINTER:SAY(NROW,1800,"DATA",OFONT12)
OPRINTER:SAY(NROW,2450,SA3->A3_DDDTEL+" "+TRANSFORM( ALLTRIM(SA3->A3_TEL),"@R 9999-99999"),OFONT12)

NROW := 2100+NROWSTEP

OPRINTER:SAY(NROW += NROWSTEP,100,I18N("PROPOSTA #1 IMPRESSA EM #2.",{SCJ->CJ_NUM,CDATA}),OFONT12)
OPRINTER:SAY(NROW,3000,I18N("PÁG. #1",{OPRINTER:NPAGECOUNT}),OFONT12)

OPRINTER:ENDPAGE()
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05RTPFRET()
LOCAL CRET := ""

DO CASE 
 CASE SCJ->CJ_XTFRETE=="C"
CRET := "CIF"
CASE SCJ->CJ_XTFRETE=="F"
CRET := "FOB"
CASE SCJ->CJ_XTFRETE=="T"
CRET := "POR CONTA DE TERCEIROS"
CASE SCJ->CJ_XTFRETE=="E"
CRET := "EX-WORKS"
CASE SCJ->CJ_XTFRETE=="S"
CRET := "SEM FRETE"
ENDCASE

RETURN CRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M05RTPISNT()
LOCAL CRET := ""

DO CASE 
 CASE SCJ->CJ_XTPINST=="1"
CRET := "SEM INSTALAÇÃO"
CASE SCJ->CJ_XTPINST=="2"
CRET := "CREDENCIADA (VIDE CONDIÇÕES GERAIS DE FORNECIMENTO)"
CASE SCJ->CJ_XTPINST=="3"
CRET := "MACOM"
CASE SCJ->CJ_XTPINST=="4"
CRET := "RATEIO NO PRODUTO"
ENDCASE

RETURN CRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR05GETCPG()
LOCAL CRET := ""

SE4->(DBSETORDER(1))
SE4->(DBGOTOP())

IF SE4->(DBSEEK(XFILIAL("SE4")+SCJ->CJ_CONDPAG))
    CRET :=  ALLTRIM(SE4->E4_CODIGO)+": "+ ALLTRIM(SE4->E4_DESCRI)+" - "+ ALLTRIM(SCJ->CJ_XDESPAG)
ENDIF
RETURN CRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR05GETSA1()
LOCAL CRET := ""

SA1->(DBSETORDER(1))
SA1->(DBGOTOP())

IF SA1->(DBSEEK(XFILIAL("SA1")+SCJ->CJ_CLIENTE+SCJ->CJ_LOJA))
    
    IF !(EMPTY(SA1->A1_COMPLEM))
        CRET :=  ALLTRIM(SA1->A1_END)+" - "+ ALLTRIM(SA1->A1_COMPLEM)+" - "+ ALLTRIM(SA1->A1_BAIRRO)+" - "+ ALLTRIM(SA1->A1_CEP)+" - "+ ALLTRIM(SA1->A1_MUN)+" - "+ ALLTRIM(SA1->A1_EST)
    ELSE 
        CRET :=  ALLTRIM(SA1->A1_END)+" - "+ ALLTRIM(SA1->A1_BAIRRO)+" - "+ ALLTRIM(SA1->A1_CEP)+" - "+ ALLTRIM(SA1->A1_MUN)+" - "+ ALLTRIM(SA1->A1_EST)
    ENDIF
ENDIF
RETURN CRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR05DATE()
LOCAL CDAY :=  STRZERO(DAY(SCJ->CJ_EMISSAO),2)
LOCAL NMON := MONTH(SCJ->CJ_EMISSAO)
LOCAL CMON := ""
LOCAL CYEAR := CVALTOCHAR(YEAR(SCJ->CJ_EMISSAO))

DO CASE 
 CASE NMON==1
CMON := "JANEIRO"
CASE NMON==2
CMON := "FEVEREIRO"
CASE NMON==3
CMON := "MARÇO"
CASE NMON==4
CMON := "ABRIL"
CASE NMON==5
CMON := "MAIO"
CASE NMON==6
CMON := "JUNHO"
CASE NMON==7
CMON := "JULHO"
CASE NMON==8
CMON := "AGOSTO"
CASE NMON==9
CMON := "SETEMBRO"
CASE NMON==10
CMON := "OUTUBRO"
CASE NMON==11
CMON := "NOVEMBRO"
CASE NMON==12
CMON := "DEZEMBRO"
ENDCASE

CRET := CDAY+" DE "+CMON+" DE "+CYEAR
RETURN CRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR05ENDPAG(OPRINTER,OFONT12,OFONT12B,NROW,NROWSTEP,NPAGE,CDATA,NITEM,_NTOTAL)
IF NROW>2000

    NROW := 2100+NROWSTEP

    OPRINTER:SAY(NROW += NROWSTEP,100,I18N("PROPOSTA #1 IMPRESSA EM #2.",{SCJ->CJ_NUM,CDATA}),OFONT12)
    OPRINTER:SAY(NROW,3000,I18N("PÁG. #1",{OPRINTER:NPAGECOUNT}),OFONT12)

    OPRINTER:ENDPAGE()
    OPRINTER:STARTPAGE()
    NROW := 0

    NPAGE++

    IF NITEM++<_NTOTAL
        M05RICABIT(OPRINTER,OFONT12B,@NROW)
        NROW += NROWSTEP+10
    ENDIF
ENDIF
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION FISGETINIT(AFISGET,AFISGETSC5)
LOCAL CVALID := ""
LOCAL CREFERENCIA := ""
LOCAL NPOSINI := 0
LOCAL NLEN := 0
Local aDados := {}
Local nX

IF AFISGET==NIL
    AFISGET := {}
    //Busca todos os campos da tabela de produtos
    aDados := FwSX3Util():GetAllFields("SCK")

    for nX := 1 to len(aDados)
        CVALID :=  UPPER(GetSX3Cache(aDados[nX], "X3_VALID")+GetSX3Cache(aDados[nX], "X3_VLDUSER"))
        
        IF ('MAFISGET("') $ (CVALID)
            NPOSINI := AT('MAFISGET("',CVALID)+10
            NLEN := AT('")', SUBSTR(CVALID,NPOSINI, LEN(CVALID)-NPOSINI))-1
            CREFERENCIA :=  SUBSTR(CVALID,NPOSINI,NLEN)
            AADD(AFISGET,{CREFERENCIA,aDados[nX],MAFISORDEM(CREFERENCIA)})
        ENDIF
        
        IF ('MAFISREF("') $ (CVALID)
            NPOSINI := AT('MAFISREF("',CVALID)+10
            CREFERENCIA :=  SUBSTR(CVALID,NPOSINI,AT('","MT410",',CVALID)-NPOSINI)
            AADD(AFISGET,{CREFERENCIA,aDados[nX],MAFISORDEM(CREFERENCIA)})
        ENDIF
    next
    /*DBSELECTAREA("SX3")
    DBSETORDER(1)
    MSSEEK("SCK")
    WHILE !(EOF()) .AND. X3_ARQUIVO=="SCK"
    
        CVALID :=  UPPER(X3_VALID+X3_VLDUSER)
        
        IF ('MAFISGET("') $ (CVALID)
            NPOSINI := AT('MAFISGET("',CVALID)+10
            NLEN := AT('")', SUBSTR(CVALID,NPOSINI, LEN(CVALID)-NPOSINI))-1
            CREFERENCIA :=  SUBSTR(CVALID,NPOSINI,NLEN)
            AADD(AFISGET,{CREFERENCIA,X3_CAMPO,MAFISORDEM(CREFERENCIA)})
        ENDIF
        
        IF ('MAFISREF("') $ (CVALID)
            NPOSINI := AT('MAFISREF("',CVALID)+10
            CREFERENCIA :=  SUBSTR(CVALID,NPOSINI,AT('","MT410",',CVALID)-NPOSINI)
            AADD(AFISGET,{CREFERENCIA,X3_CAMPO,MAFISORDEM(CREFERENCIA)})
        ENDIF
        DBSKIP()
    ENDDO*/
    
    ASORT(AFISGET,,,{|X,Y|X[3]<Y[3]})
ENDIF

IF AFISGETSC5==NIL
  AFISGETSC5 := {}
    aDados := FwSX3Util():GetAllFields("SCJ")
    for nX := 1 to len(aDados)
        CVALID :=  UPPER(GetSX3Cache(aDados[nX], "X3_VALID")+GetSX3Cache(aDados[nX], "X3_VLDUSER"))
        
        IF ('MAFISGET("') $ (CVALID)
            NPOSINI := AT('MAFISGET("',CVALID)+10
            NLEN := AT('")', SUBSTR(CVALID,NPOSINI, LEN(CVALID)-NPOSINI))-1
            CREFERENCIA :=  SUBSTR(CVALID,NPOSINI,NLEN)
            AADD(AFISGETSC5,{CREFERENCIA,aDados[nX],MAFISORDEM(CREFERENCIA)})
        ENDIF
        
        IF ('MAFISREF("') $ (CVALID)
            NPOSINI := AT('MAFISREF("',CVALID)+10
            CREFERENCIA :=  SUBSTR(CVALID,NPOSINI,AT('","MT410",',CVALID)-NPOSINI)
            AADD(AFISGETSC5,{CREFERENCIA,aDados[nX],MAFISORDEM(CREFERENCIA)})
        ENDIF
    next
    /*DBSELECTAREA("SX3")
    DBSETORDER(1)
    MSSEEK("SCJ")
    WHILE !(EOF()) .AND. X3_ARQUIVO=="SCJ"
    
        CVALID :=  UPPER(X3_VALID+X3_VLDUSER)
        
        IF ('MAFISGET("') $ (CVALID)
            NPOSINI := AT('MAFISGET("',CVALID)+10
            NLEN := AT('")', SUBSTR(CVALID,NPOSINI, LEN(CVALID)-NPOSINI))-1
            CREFERENCIA :=  SUBSTR(CVALID,NPOSINI,NLEN)
            AADD(AFISGETSC5,{CREFERENCIA,X3_CAMPO,MAFISORDEM(CREFERENCIA)})
        ENDIF
        
        IF ('MAFISREF("') $ (CVALID)
            NPOSINI := AT('MAFISREF("',CVALID)+10
            CREFERENCIA :=  SUBSTR(CVALID,NPOSINI,AT('","MT410",',CVALID)-NPOSINI)
            AADD(AFISGETSC5,{CREFERENCIA,X3_CAMPO,MAFISORDEM(CREFERENCIA)})
        ENDIF
        DBSKIP()
    ENDDO*/
    
    ASORT(AFISGETSC5,,,{|X,Y|X[3]<Y[3]})
ENDIF
MAFISEND()
RETURN  .T. 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MR05PLANIL(CNUM,CALIASPED,_NTOTAL)
LOCAL NTOTVALDESC := 0
LOCAL NC5DESC1 := 0
LOCAL NC5DESC2 := 0
LOCAL NC5DESC3 := 0
LOCAL NC5DESC4 := 0
LOCAL NC5FRETE := 0
LOCAL NC5SEGURO := 0
LOCAL NC5DESPESA := 0

LOCAL APEDCLI := {}
LOCAL AC5RODAPE := {}
LOCAL ARELIMP := MAFISRELIMP("MT100",{"SF2","SD2"})
LOCAL AFISGET := NIL
LOCAL AFISGETSC5 := NIL
LOCAL CALIASSC6 := "SC6"
LOCAL CQRYAD := ""
LOCAL CPEDIDO := ""
LOCAL CCLIENT := ""
LOCAL CNFORI := NIL
LOCAL CSERIORI := NIL
LOCAL NDESCONTO := 0
LOCAL NPESLIQ := 0
LOCAL NRECNOSD1 := NIL
LOCAL NFRETE := 0
LOCAL NSEGURO := 0
LOCAL NFRETAUT := 0
LOCAL NDESPESA := 0
LOCAL NDESCCAB := 0
LOCAL NPDESCAB := 0
LOCAL NY := 0
LOCAL NVALMERC := 0
LOCAL NPRCLISTA := 0
LOCAL NACRESFIN := 0
LOCAL AITEMPED := {}
LOCAL ACABPED := {}

LOCAL CALIASCAB := "SCJ"

FISGETINIT(@AFISGET,@AFISGETSC5)

CQRYAD := "%"
FOR NY := 1 TO  LEN(AFISGET)
    CQRYAD += ","+AFISGET[NY][2]
NEXT
FOR NY := 1 TO  LEN(AFISGETSC5)
    CQRYAD += ","+AFISGETSC5[NY][2]
NEXT
CQRYAD += "%"

CALIASPED:=CALIASSC6:=GETNEXTALIAS()

_cQry := " SELECT SCJ.R_E_C_N_O_ AS REC_CAB, "
_cQry += "        SCK.R_E_C_N_O_ AS REC_ITEM, "
_cQry += "        SCJ.CJ_FILIAL AS _FILIAL, "
_cQry += "        SCJ.CJ_NUM AS _NUM, "
_cQry += "        SCJ.CJ_CLIENTE AS _CLIENTE, "
_cQry += "        SCJ.CJ_LOJA AS _LOJA, "
_cQry += "        'N' AS _TIPO, "
_cQry += "        SA1.A1_TIPO AS _TIPOCLI, "
_cQry += "        SA1.A1_INCISS AS _INCISS, "
_cQry += "        SCJ.CJ_DESC1 AS _DESC1, "
_cQry += "        SCJ.CJ_DESC2 AS _DESC2, "
_cQry += "        SCJ.CJ_DESC3 AS _DESC3, "
_cQry += "        SCJ.CJ_DESC4 AS _DESC4, "
_cQry += "        SCJ.CJ_EMISSAO AS _EMISSAO, "
_cQry += "        SCJ.CJ_CONDPAG AS _CONDPAG, "
_cQry += "        SCJ.CJ_FRETE AS _FRETE, "
_cQry += "        SCJ.CJ_DESPESA AS _DESPESA, "
_cQry += "        SCJ.CJ_FRETAUT AS _FRETAUT, "
_cQry += "        SCJ.CJ_XTFRETE AS _TFRETE, "
_cQry += "        SCJ.CJ_SEGURO AS _SEGURO, "
_cQry += "        SCJ.CJ_TABELA AS _TABELA, "
_cQry += "        SCJ.CJ_MOEDA AS _MOEDA, "
_cQry += "        SE4.E4_ACRSFIN AS _ACRSFIN, "
_cQry += "        SCJ.CJ_XVEND1 AS _VEND1, "
_cQry += "        SCJ.CJ_PDESCAB AS _PDESCAB, "
_cQry += "        'N' AS _INSS, "
_cQry += "        SCK.CK_PRODUTO AS _PRODUTO, "
_cQry += "        SCK.CK_TES AS _TES, "
_cQry += "        ' ' AS _CF, "
_cQry += "        SCK.CK_QTDVEN AS _QTDVEN, "
_cQry += "        SCK.CK_PRUNIT AS _PRUNIT, "
_cQry += "        SCK.CK_VALDESC AS _VALDESC, "
_cQry += "        SCK.CK_VALOR AS _VALOR, "
_cQry += "        SCK.CK_ITEM AS _ITEM, "
_cQry += "        SCK.CK_XITEMP AS _XITEMP, "
_cQry += "        SCK.CK_DESCRI AS _DESCRI, "
_cQry += "        SCK.CK_UM AS _UM, "
_cQry += "        SCK.CK_PRCVEN AS _PRCVEN, "
_cQry += "        SCK.CK_ENTREG AS _ENTREG, "
_cQry += "        SCK.CK_DESCONT AS _DESCONT, "
_cQry += "        SCK.CK_LOCAL AS _LOCAL, "
_cQry += "        SCK.CK_XALQICM AS _XALQICM, "
_cQry += "        '' AS _TRANSP, "
_cQry += "        '' AS _VEND2, "
_cQry += "        '' AS _VEND3, "
_cQry += "        '' AS _VEND4, "
_cQry += "        '' AS _VEND5, "
_cQry += "        '' AS _COMIS1, "
_cQry += "        '' AS _COMIS2, "
_cQry += "        '' AS _COMIS3, "
_cQry += "        '' AS _COMIS4, "
_cQry += "        '' AS _COMIS5, "
_cQry += "        SCJ.CJ_XTFRETE AS _TPFRETE, "
_cQry += "        '0' AS _PBRUTO, "
_cQry += "        '0' AS _PESOL, "
_cQry += "        '0' AS _VOLUME1, "
_cQry += "        '0' AS _QTDEMP, "
_cQry += "        '0' AS _QTDLIB, "
_cQry += "        '0' AS _QTDENT, "
_cQry += "        '' AS _ESPECI1, "
_cQry += "        '' AS _REAJUST, "
_cQry += "        '' AS _BANCO, "
_cQry += "        '' AS _MENNOTA, "
_cQry += "        '' AS _NOTA, "
_cQry += "        '' AS _SERIE, "
_cQry += "        B1_POSIPI, "
_cQry += "        B5_CEME, "
_cQry += "        E4_DESCRI, "
_cQry += "        E4_ACRSFIN, "
_cQry += "        B5_COMPRLC, "
_cQry += "        B5_LARGLC, "
_cQry += "        B5_ALTURLC "+___SQLGETVALUE(CQRYAD)+" "
_cQry += " FROM "+RETSQLNAME("SCJ")+" SCJ "
_cQry += " INNER JOIN "+RETSQLNAME("SCK")+" SCK ON SCK.CK_FILIAL = '"+XFILIAL("SCK")+"' "
_cQry += " AND SCK.CK_NUM = SCJ.CJ_NUM "
_cQry += " AND SCK.D_E_L_E_T_= ' ' "
_cQry += " INNER JOIN "+RETSQLNAME("SA1")+" SA1 ON SA1.A1_FILIAL = '"+XFILIAL("SA1")+"' "
_cQry += " AND SA1.A1_COD = CJ_CLIENTE "
_cQry += " AND CJ_LOJA = A1_LOJA "
_cQry += " AND SA1.D_E_L_E_T_= ' ' "
_cQry += " INNER JOIN "+RETSQLNAME("SE4")+" SE4 ON SE4.E4_FILIAL = '"+XFILIAL("SE4")+"' "
_cQry += " AND E4_CODIGO = CJ_CONDPAG "
_cQry += " AND SE4.D_E_L_E_T_= ' ' "
_cQry += " INNER JOIN "+RETSQLNAME("SB1")+" SB1 ON SB1.B1_FILIAL = '"+XFILIAL("SB1")+"' "
_cQry += " AND B1_COD = CK_PRODUTO "
_cQry += " AND SB1.D_E_L_E_T_= ' ' "
_cQry += " LEFT JOIN "+RETSQLNAME("SB5")+" SB5 ON SB5.B5_FILIAL = '"+XFILIAL("SB5")+"' "
_cQry += " AND B1_COD = B5_COD "
_cQry += " AND SB5.D_E_L_E_T_= ' ' "
_cQry += " WHERE SCJ.CJ_FILIAL = '"+XFILIAL("SCJ")+"' "
_cQry += "   AND SCJ.D_E_L_E_T_= ' ' "
_cQry += "   AND SCJ.CJ_NUM = "+___SQLGETVALUE(CNUM)+" "
_cQry += " ORDER BY SCK.CK_XITEMP "
__EXECSQL(CALIASPED,_cQry,{}, .F. )

(CALIASPED)->(DBEVAL({||_NTOTAL++}))
(CALIASPED)->(DBGOTOP())

DBSELECTAREA(CALIASCAB)

CCLIENT := CALIASPED->_CLIENTE
ACABPED := {}

MAFISINI(CCLIENT,CALIASPED->_LOJA,IIF((CALIASPED->_TIPO) $ ("DB"),"F","C"),CALIASPED->_TIPO,CALIASPED->_TIPOCLI,ARELIMP,,,"SB1","MATA461")

NFRETE := CALIASPED->_FRETE
NSEGURO := CALIASPED->_SEGURO
NFRETAUT := CALIASPED->_FRETAUT
NDESPESA := CALIASPED->_DESPESA
NDESCCAB := 0
NPDESCAB := 0
NC5DESC1 := 0
NC5DESC2 := 0
NC5DESC3 := 0
NC5DESC4 := 0
NC5FRETE := NFRETE
NC5SEGURO := NSEGURO
NC5DESPESA := NDESPESA
AITEMPED := {}

ACABPED := {CALIASPED->_TIPO,CALIASPED->_CLIENTE,CALIASPED->_LOJA,CALIASPED->_TRANSP,CALIASPED->_CONDPAG,CALIASPED->_EMISSAO,CALIASPED->_NUM,CALIASPED->_VEND1,CALIASPED->_VEND2,CALIASPED->_VEND3,CALIASPED->_VEND4,CALIASPED->_VEND5,CALIASPED->_COMIS1,CALIASPED->_COMIS2,CALIASPED->_COMIS3,CALIASPED->_COMIS4,CALIASPED->_COMIS5,CALIASPED->_FRETE,CALIASPED->_TPFRETE,CALIASPED->_SEGURO,CALIASPED->_TABELA, VAL(CALIASPED->_VOLUME1),CALIASPED->_ESPECI1,CALIASPED->_MOEDA,CALIASPED->_REAJUST,CALIASPED->_BANCO,CALIASPED->_ACRSFIN}
NPESLIQ := 0
APEDCLI := {}

CPEDIDO := CALIASPED->_NUM
AC5RODAPE := {}

AADD(AC5RODAPE,{ VAL(CALIASPED->_PBRUTO), VAL(CALIASPED->_PESOL),0,0,0,0,CALIASPED->_MENNOTA})

DBSELECTAREA(CALIASPED)

FOR NY := 1 TO  LEN(AFISGETSC5)
    
    IF !(EMPTY(&(AFISGETSC5[NY][2])))
        
        IF AFISGETSC5[NY][1]=="NF_SUFRAMA"
            MAFISALT(AFISGETSC5[NY][1],IIF(&(AFISGETSC5[NY][2])=="1", .T. , .F. ), LEN(AITEMPED), .T. )
        ELSE 
            MAFISALT(AFISGETSC5[NY][1],&(AFISGETSC5[NY][2]), LEN(AITEMPED), .T. )
        ENDIF
    ENDIF
NEXT

WHILE !(CALIASPED)->(EOF())
 
    CNFORI := NIL
    CSERIORI := NIL
    NRECNOSD1 := NIL
    NDESCONTO := 0
    DBSELECTAREA("SCK")
    
    NVALMERC := CALIASPED->_VALOR
    NPRCLISTA := CALIASPED->_PRUNIT
    
    IF NPRCLISTA==0
        NPRCLISTA := NOROUND((NVALMERC) / (CALIASPED->_QTDVEN),TAMSX3("CK_PRCVEN")[2])
    ENDIF
    
    NACRESFIN := A410ARRED(((CALIASPED->_PRCVEN) * (CALIASPED->_ACRSFIN)) / (100),"D2_PRCVEN")
    NVALMERC += A410ARRED((CALIASPED->_QTDVEN) * (NACRESFIN),"D2_TOTAL")
    NDESCONTO := A410ARRED((NPRCLISTA) * (CALIASPED->_QTDVEN),"D2_DESCON")-NVALMERC
    NDESCONTO := IIF(NDESCONTO==0,CALIASPED->_VALDESC,NDESCONTO)
    NDESCONTO := MAX(0,NDESCONTO)
    NTOTVALDESC += NDESCONTO
    NPRCLISTA += NACRESFIN
    NVALMERC += NDESCONTO
    
    MAFISADD(CALIASPED->_PRODUTO,CALIASPED->_TES,CALIASPED->_QTDVEN,NPRCLISTA,NDESCONTO,CNFORI,CSERIORI,NRECNOSD1,0,0,0,0,NVALMERC,0,0,0)
    
    AADD(AITEMPED,{CALIASPED->_ITEM,CALIASPED->_PRODUTO,CALIASPED->_DESCRI,CALIASPED->_TES,CALIASPED->_CF,CALIASPED->_UM,CALIASPED->_QTDVEN,CALIASPED->_PRCVEN,CALIASPED->_NOTA,CALIASPED->_SERIE,CALIASPED->_CLIENTE,CALIASPED->_LOJA,CALIASPED->_VALOR,CALIASPED->_ENTREG,CALIASPED->_DESCONT,CALIASPED->_LOCAL, VAL(CALIASPED->_QTDEMP), VAL(CALIASPED->_QTDLIB), VAL(CALIASPED->_QTDENT),})
    
    DBSELECTAREA("SCK")
    FOR NY := 1 TO  LEN(AFISGET)
        
        IF !(EMPTY(&(AFISGET[NY][2])))
            MAFISALT(AFISGET[NY][1],&(AFISGET[NY][2]), LEN(AITEMPED))
      ENDIF
    NEXT
    
    SF4->(DBSETORDER(1))
    SF4->(MSSEEK(XFILIAL("SF4")+CALIASPED->_TES))
    
    IF CALIASPED->_INCISS=="N" .AND. CALIASPED->_TIPO=="N"
        
        IF SF4->F4_ISS=="S"
            NPRCLISTA := A410ARRED((NPRCLISTA) / (1-(MAALIQISS( LEN(AITEMPED))) / (100)),"D2_PRCVEN")
            NVALMERC := A410ARRED((NVALMERC) / (1-(MAALIQISS( LEN(AITEMPED))) / (100)),"D2_PRCVEN")
            MAFISALT("IT_PRCUNI",NPRCLISTA, LEN(AITEMPED))
            MAFISALT("IT_VALMERC",NVALMERC, LEN(AITEMPED))
        ENDIF
    ENDIF
    
    SB1->(DBSETORDER(1))
    SB1->(MSSEEK(XFILIAL("SB1")+CALIASPED->_PRODUTO))
    
    MAFISALT("IT_PESO",(CALIASPED->_QTDVEN) * (SB1->B1_PESO), LEN(AITEMPED))
    MAFISALT("IT_PRCUNI",NPRCLISTA, LEN(AITEMPED))
    MAFISALT("IT_VALMERC",NVALMERC, LEN(AITEMPED))
    
    (CALIASPED)->(DBSKIP())
    ENDDO

MAFISALT("NF_FRETE",NFRETE)
MAFISALT("NF_SEGURO",NSEGURO)
MAFISALT("NF_AUTONOMO",NFRETAUT)
MAFISALT("NF_DESPESA",NDESPESA)

IF NDESCCAB>0
    MAFISALT("NF_DESCONTO",MIN(MAFISRET(,"NF_VALMERC")-0.01,NDESCCAB+MAFISRET(,"NF_DESCONTO")))
ENDIF

IF NPDESCAB>0
    MAFISALT("NF_DESCONTO",A410ARRED(((MAFISRET(,"NF_VALMERC")) * (NPDESCAB)) / (100),"C6_VALOR")+MAFISRET(,"NF_DESCONTO"))
ENDIF

(CALIASPED)->(DBGOTOP())
RETURN 
