#INCLUDE "protheus.ch"

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M05R11()

LOCAL OREPORT

CUSUARIO := RETCODUSR()

IF U_M05G05()
    
    IF FINDFUNCTION("TREPINUSE") .AND. TREPINUSE()

        OREPORT := REPORTDEF()
        OREPORT:PRINTDIALOG()
    ENDIF
ELSE 
    MSGSTOP("USUÁRIO NÃO AUTORIZADO A EMITIR O RELATÓRIO. ENTRE EM CONTATO COM O DEPARTAMENTO DE T.I.","NÃO AUTORIZADO!")
ENDIF

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION REPORTDEF()

LOCAL OREPORT
LOCAL OVENPROD
LOCAL CALIASQRY := GETNEXTALIAS()

OREPORT := TREPORT():NEW("M05R11","FOLLOW UP","M05R11",{|OREPORT|REPORTPRINT(OREPORT,CALIASQRY,OVENPROD)},"ESTE RELATORIO EMITE A RELACAO DE ACOMPANHAMENTO "+" "+" DOS REGISTROS DE FOLLOW UP DOS ORÇAMENTOS.")
OREPORT:SETTOTALINLINE( .F. )

PERGUNTE(OREPORT:UPARAM, .F. )

OVENPROD := TRSECTION():NEW(OREPORT,"REGISTRO FOLLOW UP",{"ZA9","SCJ"},,,)
OVENPROD:SETTOTALINLINE( .F. )

TRCELL():NEW(OVENPROD,"FILIAL",,"FILIAL",PESQPICT("ZA9","ZA9_FILIAL"),TAMSX3("ZA9_FILIAL")[1],,{||CXFILIAL})
TRCELL():NEW(OVENPROD,"NUMORC",,"N.ORÇAMENTO",PESQPICT("ZA9","ZA9_XNUMOR"),TAMSX3("ZA9_XNUMOR")[1],,{||CNUMOR})
TRCELL():NEW(OVENPROD,"TOTAL",,"VLR. TOTAL",PESQPICT("SCK","CK_VALOR"),TAMSX3("CK_VALOR")[1],,{||NVALTOT})
TRCELL():NEW(OVENPROD,"STATUS",,"STATUS",PESQPICT("ZA9","ZA9_XFUST"),TAMSX3("A1_NREDUZ")[1]-15,,{||CSTATUS})
TRCELL():NEW(OVENPROD,"CODCLI",,"CODIGO",PESQPICT("SA1","A1_COD"),TAMSX3("A1_COD")[1],,{||CCODCLI})
TRCELL():NEW(OVENPROD,"CODLOJ",,"LOJA",PESQPICT("SA1","A1_LOJA"),TAMSX3("A1_LOJA")[1],,{||CCODLOJ})
TRCELL():NEW(OVENPROD,"NOME",,"NOME CLIENTE",PESQPICT("SA1","A1_NOME"),TAMSX3("A1_NOME")[1],,{||CNOME})
TRCELL():NEW(OVENPROD,"REGIAO",,"REGIAO",PESQPICT("SA1","A1_DSCREG"),TAMSX3("A1_DSCREG")[1],,{||CREGIAO})
TRCELL():NEW(OVENPROD,"ESTADO",,"ESTADO",PESQPICT("SA1","A1_EST"),TAMSX3("A1_EST")[1],,{||CUF})
TRCELL():NEW(OVENPROD,"VENDEDOR",,"VENDEDOR",PESQPICT("SA3","A3_NOME"),TAMSX3("A3_NOME")[1],,{||CVEND})
TRCELL():NEW(OVENPROD,"TIPOVEN",,"TIPO VENDA",PESQPICT("SCJ","CJ_XTPVEN"),TAMSX3("CJ_XTPVEN")[1],,{||CXTPVEN})
TRCELL():NEW(OVENPROD,"FECHAMENTO",,"PREV.FECHAMENTO",PESQPICT("ZA9","ZA9_XFUFEC"),TAMSX3("ZA9_XFUFEC")[1],,{||DDTFEC})
TRCELL():NEW(OVENPROD,"PRXCONT",,"PROX.CONTATO",PESQPICT("ZA9","ZA9_XFUPRX"),TAMSX3("ZA9_XFUPRX")[1],,{||DDTPRX})
TRCELL():NEW(OVENPROD,"ULTCOM",,"ULT.CONTATO",PESQPICT("ZA9","ZA9_XFUULT"),TAMSX3("ZA9_XFUULT")[1],,{||DDTULT})
TRCELL():NEW(OVENPROD,"MOTIVO",,"MOTIVO",PESQPICT("ZA9","ZA9_XFUMOT"),TAMSX3("ZA9_XFUMOT")[1],,{||CMOTIVO})
TRCELL():NEW(OVENPROD,"CONCOR",,"CONCORRENTE",PESQPICT("ZA9","ZA9_XFUCON"),TAMSX3("ZA9_XFUCON")[1],,{||CCONCOR})
TRCELL():NEW(OVENPROD,"USUARIO",,"USUARIO",PESQPICT("ZA9","ZA9_XFUUSR"),TAMSX3("ZA9_XFUUSR")[1],,{||CNOMUSR})

RETURN OREPORT

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION REPORTPRINT(OREPORT,CALIASQRY,OVENPROD)

DBSELECTAREA("SC6")
DBSETORDER(2)

OREPORT:SECTION(1):BEGINQUERY()

_cQry := " SELECT ZA9_FILIAL, "
_cQry += "        ZA9_XFUST, "
_cQry += "        ZA9_XFUMOT, "
_cQry += "        ZA9_XNUMOR, "
_cQry += "        ZA9_XFUCON, "
_cQry += "        ZA9_XFUFEC, "
_cQry += "        ZA9_XFUPRX, "
_cQry += "        ZA9_XFUULT, "
_cQry += "        ZA9_XFUUSR "
_cQry += " FROM "+RETSQLNAME("ZA9")+" ZA9 "
_cQry += " WHERE ZA9.ZA9_FILIAL = '"+XFILIAL("ZA9")+"' "
_cQry += "   AND ZA9.ZA9_XNUMOR >= "+___SQLGETVALUE(MV_PAR01)+" "
_cQry += "   AND ZA9.ZA9_XNUMOR <= "+___SQLGETVALUE(MV_PAR02)+" "
_cQry += "   AND ZA9.ZA9_XFUPRX >= "+___SQLGETVALUE(MV_PAR03)+" "
_cQry += "   AND ZA9.ZA9_XFUPRX <= "+___SQLGETVALUE(MV_PAR04)+" "
_cQry += "   OR ZA9.ZA9_XFUULT >= "+___SQLGETVALUE(MV_PAR05)+" "
_cQry += "   AND ZA9.ZA9_XFUULT <= "+___SQLGETVALUE(MV_PAR06)+" "
_cQry += "   AND ZA9.D_E_L_E_T_= ' '"
__EXECSQL(CALIASQRY,_cQry,{}, .F. )

OREPORT:SECTION(1):ENDQUERY()

DBSELECTAREA("SA1")
DBSETORDER(1)
DBSELECTAREA("SCJ")
DBSETORDER(1)
DBSELECTAREA(CALIASQRY)
DBGOTOP()
OREPORT:SETMETER((CALIASQRY)->(LASTREC()))
OREPORT:SECTION(1):INIT()

WHILE !(OREPORT:CANCEL) .AND. !((CALIASQRY)->(EOF))
 
    LPOSCJ := SCJ->(MSSEEK(XFILIAL("SCJ")+CALIASQRY->ZA9_XNUMOR))
    LPOSA1 := SA1->(MSSEEK(XFILIAL("SA1")+SCJ->CJ_CLIENTE+SCJ->CJ_LOJA))
    
    CNUMOR := CALIASQRY->ZA9_XNUMOR
    
    IF LPOSA1
        CCODCLI := SA1->A1_COD
        CCODLOJ := SA1->A1_LOJA
        CNOME := SA1->A1_NOME
        CREGIAO := SA1->A1_DSCREG
        CUF := SA1->A1_EST
    ELSE 
        CCODCLI := ""
        CCODLOJ := ""
        CNOME := ""
        CREGIAO := ""
        CUF := ""
    ENDIF
    
    IF LPOSCJ
        CVEND := POSICIONE("SA3",1,XFILIAL("SA3")+SCJ->CJ_XVEND1,"A3_NOME")
        CXFILIAL := SCJ->CJ_FILIAL
        
        DO CASE 
        CASE SCJ->CJ_XTPVEN=="1"
        CXTPVEN := "1-PROJETO"
        
        CASE SCJ->CJ_XTPVEN=="2"
        CXTPVEN := "2-VENDA UNITARIA"
        
        CASE SCJ->CJ_XTPVEN=="3"
        CXTPVEN := "3-DEALER"
        OTHERWISE
        CXTPVEN := " "
        ENDCASE
    ELSE 
        CVEND := " "
        CXFILIAL := " "
        CXTPVEN := " "
    ENDIF
    
    DDTFEC := CALIASQRY->ZA9_XFUFEC
    
    DO CASE 
    CASE CALIASQRY->ZA9_XFUMOT=="1"
    CMOTIVO := "1=PRECO"
    
    CASE CALIASQRY->ZA9_XFUMOT=="2"
    CMOTIVO := "2=PRAZO"
    
    CASE CALIASQRY->ZA9_XFUMOT=="3"
    CMOTIVO := "3=QUALIDADE"
    
    CASE CALIASQRY->ZA9_XFUMOT=="4"
    CMOTIVO := "4=CONDICAO DE PAGAMENTO"
    
    CASE CALIASQRY->ZA9_XFUMOT=="5"
    CMOTIVO := "5=MAU ATENDIMENTO"
    
    CASE CALIASQRY->ZA9_XFUMOT=="6"
    CMOTIVO := "6=PRORROGADO"
    OTHERWISE
    CMOTIVO := " "
    ENDCASE
    
    DDTPRX := CALIASQRY->ZA9_XFUPRX
    
    DO CASE 
    CASE CALIASQRY->ZA9_XFUCON=="1"
    CCONCOR := "1=COZIL"
    
    CASE CALIASQRY->ZA9_XFUCON=="2"
    CCONCOR := "2=ALFATEC"
    
    CASE CALIASQRY->ZA9_XFUCON=="3"
    CCONCOR := "3=BERTA"
    
    CASE CALIASQRY->ZA9_XFUCON=="4"
    CCONCOR := "4=ELVI"
    
    CASE CALIASQRY->ZA9_XFUCON=="5"
    CCONCOR := "5=PPIENK"
    
    CASE CALIASQRY->ZA9_XFUCON=="6"
    CCONCOR := "6=TOPEMA"
    
    CASE CALIASQRY->ZA9_XFUCON=="7"
    CCONCOR := "7=TRAMONTINA/ELETROLUX"
    
    CASE CALIASQRY->ZA9_XFUCON=="8"
    CCONCOR := "8=LOCAL"
    
    CASE CALIASQRY->ZA9_XFUCON=="9"
    CCONCOR := "9=EVEREST"
    OTHERWISE
    CCONCOR := " "
    ENDCASE
    
    DDTULT := CALIASQRY->ZA9_XFUULT
    
    DO CASE 
    CASE CALIASQRY->ZA9_XFUST=="1"
    CSTATUS := "1-PROJETO CANCELADO"
    
    CASE CALIASQRY->ZA9_XFUST=="2"
    CSTATUS := "2-PERDIDO"
    
    CASE CALIASQRY->ZA9_XFUST=="3"
    CSTATUS := "3-EM ANDAMENTO"
    
    CASE CALIASQRY->ZA9_XFUST=="4"
    CSTATUS := "4-SUBSTITUIDO"
    OTHERWISE
    CSTATUS := " "
    ENDCASE
    
    NVALTOT := U_M5R11TOT(CNUMOR)
    
    CNOMUSR := fGetName(CALIASQRY->ZA9_XFUUSR)
    
    OREPORT:INCMETER()
    OREPORT:SECTION(1):PRINTLINE()
    
    (CALIASQRY)->(DBSKIP())
    ENDDO

DBSELECTAREA(CALIASQRY)

OREPORT:SETLANDSCAPE()
OREPORT:SECTION(1):FINISH()

(CALIASQRY)->(DBCLOSEAREA())

RETURN 

Static Function fGetName(cUser)
Return USRFULLNAME(cUser)
/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M5R11TOT(CNUM)

LOCAL NVALFRE := 0
LOCAL NVALSEG := 0
LOCAL NVALDES := 0
LOCAL NVALFRET := 0
LOCAL NVALTOT := 0
LOCAL CALIASTOT := GETNEXTALIAS()

_cQry := " SELECT CK_NUM, "
_cQry += "        SUM(CK_VALOR) AS TOTAL "
_cQry += " FROM "+RETSQLNAME("SCK")+" SCK "
_cQry += " WHERE SCK.CK_FILIAL = '"+XFILIAL("SCK")+"' "
_cQry += "   AND SCK.CK_NUM = "+___SQLGETVALUE(CNUM)+" "
_cQry += "   AND SCK.D_E_L_E_T_= ' ' "
_cQry += " GROUP BY SCK.CK_NUM "
__EXECSQL(CALIASTOT,_cQry,{}, .F. )

NVALFRE := POSICIONE("SCJ",1,XFILIAL("SCJ")+CNUM,"CJ_FRETE")
NVALSEG := POSICIONE("SCJ",1,XFILIAL("SCJ")+CNUM,"CJ_SEGURO")
NVALDES := POSICIONE("SCJ",1,XFILIAL("SCJ")+CNUM,"CJ_DESPESA")
NVALFRET := POSICIONE("SCJ",1,XFILIAL("SCJ")+CNUM,"CJ_FRETAUT")

NVALTOT := CALIASTOT->TOTAL+NVALFRE+NVALSEG+NVALDES+NVALFRET

(CALIASTOT)->(DBCLOSEAREA())

RETURN NVALTOT
