#INCLUDE "protheus.ch"

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M09R002()

LOCAL AREGS := {}
LOCAL ABUTTONS := {}
LOCAL CPERG := "M09R002"
LOCAL ASAYS := {}
LOCAL NOPCA := 0

PRIVATE OPROCESS := NIL
PRIVATE TITULO := OEMTOANSI("RELATORIO DE CONFERENCIA - APURAï¿½ï¿½O DE PIS E COFINS")

AADD(AREGS,{CPERG,"01","DATA DE","","","MV_CH1","D",8,0,0,"G","","MV_PAR01","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""})
AADD(AREGS,{CPERG,"02","DATA ATï¿½","","","MV_CH2","D",8,0,0,"G","","MV_PAR02","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""})
AADD(AREGS,{CPERG,"03","FILIAIS","","","MV_CH3","C",80,0,0,"G","","MV_PAR03","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""})

//VALIDPERG(CPERG,AREGS)

PERGUNTE(CPERG, .F. )

AADD(ASAYS,OEMTOANSI("ESTE PROGRAMA MONTA UM RELATORIO DE COMPARAï¿½ï¿½O DOS VALORES DA   "))
AADD(ASAYS,OEMTOANSI("APURAï¿½ï¿½O DE PIS E COFINS                                        "))
AADD(ASAYS,OEMTOANSI("                                                                "))
AADD(ASAYS,OEMTOANSI("                                                                "))
AADD(ASAYS,OEMTOANSI("                                                                "))

AADD(ABUTTONS,{5, .T. ,{|O|NOPCA := 0,PERGUNTE(CPERG, .T. )}})
AADD(ABUTTONS,{1, .T. ,{|O|NOPCA := 1,O:OWND:END()}})
AADD(ABUTTONS,{2, .T. ,{|O|O:OWND:END()}})

FORMBATCH(TITULO,ASAYS,ABUTTONS)

IF NOPCA==1
    OPROCESS := MSNEWPROCESS():NEW({|LEND|M09R002A(OPROCESS)},TITULO)
    OPROCESS:ACTIVATE()
ENDIF

RETURN NIL

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION M09R002A(OPROCESS)

LOCAL AAREA := GETAREA()
LOCAL LRETORNO :=  .T. 
LOCAL CQRY := ""
LOCAL NA := 0
LOCAL _CARQUIVO := ""
LOCAL CPATH :=  ALLTRIM(GETTEMPPATH())
LOCAL CDIRDOCS := "\SYSTEM\"
LOCAL CBARRA := IIF(ISSRVUNIX(),"/","\")
LOCAL CREGANT := ""

LOCAL ACABEC := {}
LOCAL AESTILOS := {}

LOCAL CCFOP := ""
LOCAL NTOTREG := 0

PRIVATE ACMPTMP := {}
PRIVATE ACMPTST := {}
PRIVATE CARQTRB1 := ""
PRIVATE CARQTRB2 := ""
PRIVATE AIND := {}

PRIVATE CARQUIVO := CRIATRAB(, .F. )
PRIVATE NHANDLE := 0
PRIVATE CCPOORGPUB := GETNEWPAR("MV_A1M996","A1_B2B")

AADD(AESTILOS,{"BOLD"})
AADD(AESTILOS,{"BOLD","ITALIC"})

AADD(ACMPTMP,{"FT_FILIAL",TAMSX3("FT_FILIAL")[3],TAMSX3("FT_FILIAL")[1],TAMSX3("FT_FILIAL")[2]})
AADD(ACMPTMP,{"FT_NFISCAL",TAMSX3("FT_NFISCAL")[3],TAMSX3("FT_NFISCAL")[1],TAMSX3("FT_NFISCAL")[2]})
AADD(ACMPTMP,{"FT_NFELETR",TAMSX3("FT_NFELETR")[3],TAMSX3("FT_NFELETR")[1],TAMSX3("FT_NFELETR")[2]})
AADD(ACMPTMP,{"FT_SERIE",TAMSX3("FT_SERIE")[3],TAMSX3("FT_SERIE")[1],TAMSX3("FT_SERIE")[2]})
AADD(ACMPTMP,{"FT_CLIEFOR",TAMSX3("FT_CLIEFOR")[3],TAMSX3("FT_CLIEFOR")[1],TAMSX3("FT_CLIEFOR")[2]})
AADD(ACMPTMP,{"FT_LOJA",TAMSX3("FT_LOJA")[3],TAMSX3("FT_LOJA")[1],TAMSX3("FT_LOJA")[2]})
AADD(ACMPTMP,{"A2_NOME",TAMSX3("A2_NOME")[3],TAMSX3("A2_NOME")[1],TAMSX3("A2_NOME")[2]})
AADD(ACMPTMP,{"A1_CGC",TAMSX3("A1_CGC")[3],TAMSX3("A1_CGC")[1],TAMSX3("A1_CGC")[2]})
AADD(ACMPTMP,{"FT_ITEM",TAMSX3("FT_ITEM")[3],TAMSX3("FT_ITEM")[1],TAMSX3("FT_ITEM")[2]})
AADD(ACMPTMP,{"FT_CFOP",TAMSX3("FT_CFOP")[3],TAMSX3("FT_CFOP")[1],TAMSX3("FT_CFOP")[2]})
AADD(ACMPTMP,{"D2_TES",TAMSX3("D2_TES")[3],TAMSX3("D2_TES")[1],TAMSX3("D2_TES")[2]})
AADD(ACMPTMP,{"X5DESCRI",TAMSX3("X5_DESCRI")[3],TAMSX3("X5_DESCRI")[1],TAMSX3("X5_DESCRI")[2]})
AADD(ACMPTMP,{"FT_CODBCC",TAMSX3("FT_CODBCC")[3],TAMSX3("FT_CODBCC")[1],TAMSX3("FT_CODBCC")[2]})
AADD(ACMPTMP,{"FT_CSTPIS",TAMSX3("FT_CSTPIS")[3],TAMSX3("FT_CSTPIS")[1],TAMSX3("FT_CSTPIS")[2]})
AADD(ACMPTMP,{"FT_CSTCOF",TAMSX3("FT_CSTCOF")[3],TAMSX3("FT_CSTCOF")[1],TAMSX3("FT_CSTCOF")[2]})
AADD(ACMPTMP,{"FT_ALIQPIS",TAMSX3("FT_ALIQPIS")[3],TAMSX3("FT_ALIQPIS")[1],TAMSX3("FT_ALIQPIS")[2]})
AADD(ACMPTMP,{"FT_ALIQCOF",TAMSX3("FT_ALIQCOF")[3],TAMSX3("FT_ALIQCOF")[1],TAMSX3("FT_ALIQCOF")[2]})
AADD(ACMPTMP,{"A1_XORGPUB",TAMSX3(CCPOORGPUB)[3],TAMSX3(CCPOORGPUB)[1],TAMSX3(CCPOORGPUB)[2]})
AADD(ACMPTMP,{"LINHA","C",40,0})
AADD(ACMPTMP,{"FT_VALCONT",TAMSX3("FT_VALCONT")[3],TAMSX3("FT_VALCONT")[1],TAMSX3("FT_VALCONT")[2]})
AADD(ACMPTMP,{"E1_SALDO",TAMSX3("E1_SALDO")[3],TAMSX3("E1_SALDO")[1],TAMSX3("E1_SALDO")[2]})
AADD(ACMPTMP,{"FT_TOTAL",TAMSX3("FT_TOTAL")[3],TAMSX3("FT_TOTAL")[1],TAMSX3("FT_TOTAL")[2]})
AADD(ACMPTMP,{"FT_BASEPIS",TAMSX3("FT_BASEPIS")[3],TAMSX3("FT_BASEPIS")[1],TAMSX3("FT_BASEPIS")[2]})
AADD(ACMPTMP,{"FT_BASECOF",TAMSX3("FT_BASECOF")[3],TAMSX3("FT_BASECOF")[1],TAMSX3("FT_BASECOF")[2]})
AADD(ACMPTMP,{"FT_VALPIS",TAMSX3("FT_VALPIS")[3],TAMSX3("FT_VALPIS")[1],TAMSX3("FT_VALPIS")[2]})
AADD(ACMPTMP,{"FT_VALCOF",TAMSX3("FT_VALCOF")[3],TAMSX3("FT_VALCOF")[1],TAMSX3("FT_VALCOF")[2]})
AADD(ACMPTMP,{"FT_VALIPI",TAMSX3("FT_VALIPI")[3],TAMSX3("FT_VALIPI")[1],TAMSX3("FT_VALIPI")[2]})
AADD(ACMPTMP,{"FT_PRODUTO",TAMSX3("FT_PRODUTO")[3],TAMSX3("FT_PRODUTO")[1],TAMSX3("FT_PRODUTO")[2]})
AADD(ACMPTMP,{"FT_NFORI",TAMSX3("FT_NFORI")[3],TAMSX3("FT_NFORI")[1],TAMSX3("FT_NFORI")[2]})
AADD(ACMPTMP,{"DTNFORI",TAMSX3("FT_ENTRADA")[3],TAMSX3("FT_ENTRADA")[1],TAMSX3("FT_ENTRADA")[2]})
AADD(ACMPTMP,{"B1_POSIPI",TAMSX3("B1_POSIPI")[3],TAMSX3("B1_POSIPI")[1],TAMSX3("B1_POSIPI")[2]})
AADD(ACMPTMP,{"CG1_CODIGO",TAMSX3("CG1_CODIGO")[3],TAMSX3("CG1_CODIGO")[1],TAMSX3("CG1_CODIGO")[2]})
AADD(ACMPTMP,{"CG1_ALIQ",TAMSX3("CG1_ALIQ")[3],TAMSX3("CG1_ALIQ")[1],TAMSX3("CG1_ALIQ")[2]})
AADD(ACMPTMP,{"D2_TIPO",TAMSX3("D2_TIPO")[3],TAMSX3("D2_TIPO")[1],TAMSX3("D2_TIPO")[2]})
AADD(ACMPTMP,{"D2_LOTECTL",TAMSX3("D2_LOTECTL")[3],TAMSX3("D2_LOTECTL")[1],TAMSX3("D2_LOTECTL")[2]})
AADD(ACMPTMP,{"FT_ICMSRET",TAMSX3("FT_ICMSRET")[3],TAMSX3("FT_ICMSRET")[1],TAMSX3("FT_ICMSRET")[2]})
AADD(ACMPTMP,{"FT_FRETE",TAMSX3("FT_FRETE")[3],TAMSX3("FT_FRETE")[1],TAMSX3("FT_FRETE")[2]})
AADD(ACMPTMP,{"FT_SEGURO",TAMSX3("FT_SEGURO")[3],TAMSX3("FT_SEGURO")[1],TAMSX3("FT_SEGURO")[2]})
AADD(ACMPTMP,{"FT_DESPESA",TAMSX3("FT_DESPESA")[3],TAMSX3("FT_DESPESA")[1],TAMSX3("FT_DESPESA")[2]})
AADD(ACMPTMP,{"FT_DESCONT",TAMSX3("FT_DESCONT")[3],TAMSX3("FT_DESCONT")[1],TAMSX3("FT_DESCONT")[2]})

AADD(ACMPTMP,{"A1_NOME",TAMSX3("A1_NOME")[3],TAMSX3("A1_NOME")[1],TAMSX3("A1_NOME")[2]})
AADD(ACMPTMP,{"A1_NREDUZ",TAMSX3("A1_NREDUZ")[3],TAMSX3("A1_NREDUZ")[1],TAMSX3("A1_NREDUZ")[2]})
AADD(ACMPTMP,{"A1_VEND",TAMSX3("A1_VEND")[3],TAMSX3("A1_VEND")[1],TAMSX3("A1_VEND")[2]})
AADD(ACMPTMP,{"A1_REGIAO",TAMSX3("A1_REGIAO")[3],TAMSX3("A1_REGIAO")[1],TAMSX3("A1_REGIAO")[2]})
AADD(ACMPTMP,{"A1_EST",TAMSX3("A1_EST")[3],TAMSX3("A1_EST")[1],TAMSX3("A1_EST")[2]})

AADD(ACMPTMP,{"B1_DESC",TAMSX3("B1_DESC")[3],TAMSX3("B1_DESC")[1],TAMSX3("B1_DESC")[2]})
AADD(ACMPTMP,{"FT_BASEICM",TAMSX3("FT_BASEICM")[3],TAMSX3("FT_BASEICM")[1],TAMSX3("FT_BASEICM")[2]})
AADD(ACMPTMP,{"FT_VALICM",TAMSX3("FT_VALICM")[3],TAMSX3("FT_VALICM")[1],TAMSX3("FT_VALICM")[2]})
AADD(ACMPTMP,{"FT_DIFAL",TAMSX3("FT_DIFAL")[3],TAMSX3("FT_DIFAL")[1],TAMSX3("FT_DIFAL")[2]})
AADD(ACMPTMP,{"FT_VFCPDIF",TAMSX3("FT_VFCPDIF")[3],TAMSX3("FT_VFCPDIF")[1],TAMSX3("FT_VFCPDIF")[2]})
AADD(ACMPTMP,{"FT_ICMSCOM",TAMSX3("FT_ICMSCOM")[3],TAMSX3("FT_ICMSCOM")[1],TAMSX3("FT_ICMSCOM")[2]})

AADD(ACMPTMP,{"FT_ISENICM",TAMSX3("FT_ISENICM")[3],TAMSX3("FT_ISENICM")[1],TAMSX3("FT_ISENICM")[2]})
AADD(ACMPTMP,{"FT_OUTRICM",TAMSX3("FT_OUTRICM")[3],TAMSX3("FT_OUTRICM")[1],TAMSX3("FT_OUTRICM")[2]})
AADD(ACMPTMP,{"FT_ALIQICM",TAMSX3("FT_ALIQICM")[3],TAMSX3("FT_ALIQICM")[1],TAMSX3("FT_ALIQICM")[2]})
AADD(ACMPTMP,{"FT_CLASFIS",TAMSX3("FT_CLASFIS")[3],TAMSX3("FT_CLASFIS")[1],TAMSX3("FT_CLASFIS")[2]})

AADD(ACMPTMP,{"A1_INSCR",TAMSX3("A1_INSCR")[3],TAMSX3("A1_INSCR")[1],TAMSX3("A1_INSCR")[2]})
AADD(ACMPTMP,{"FT_ENTRADA",TAMSX3("FT_ENTRADA")[3],TAMSX3("FT_ENTRADA")[1],TAMSX3("FT_ENTRADA")[2]})

//CARQTRB1 := CRIATRAB(ACMPTMP, .T. )
//DBUSEAREA( .T. ,"DBFCDX",CARQTRB1,"TMPTRB", .T. , .F. )
//DBSELECTAREA("TMPTRB")


//Cria a temporï¿½ria
oTempTable := FWTemporaryTable():New("TMPTRB")
 
 
//Define as colunas usadas
oTempTable:SetFields( ACMPTMP )
 
//Efetua a criaï¿½ï¿½o da tabela
oTempTable:Create()





AADD(AIND,{CRIATRAB(NIL, .F. ),"FT_FILIAL+FT_NFISCAL+FT_SERIE+FT_CLIEFOR+FT_LOJA+FT_PRODUTO+FT_ITEM","FILIAL + DOC + SERIE + CLIEFOR + LOJA + PRODUTO + ITEM"})
FOR NA := 1 TO  LEN(AIND)
    INDREGUA("TMPTRB",AIND[NA][1],AIND[NA][2],,,OEMTOANSI("CRIANDO ï¿½NDICE TEMPORï¿½RIO..."))
NEXT

DBCLEARINDEX()

FOR NA := 1 TO  LEN(AIND)
    DBSETINDEX(AIND[NA][1]+ORDBAGEXT())
NEXT

CQRY := " SELECT	FT_FILIAL,"
CQRY += " 			FT_NFISCAL,FT_NFELETR,"
CQRY += " 			FT_SERIE,"
CQRY += " 			FT_CLIEFOR,"
CQRY += " 			RTRIM(LTRIM(ISNULL(A1_CGC,' ')))+RTRIM(LTRIM(ISNULL(A2_CGC,' '))) A1_CGC,"
CQRY += " 			FT_LOJA,"
CQRY += " 			(SELECT A2_NOME FROM SA2010 SA2 WHERE A2_FILIAL = '"+XFILIAL("SA2")+"' AND A2_COD = FT_CLIEFOR AND A2_LOJA = FT_LOJA AND SA2.D_E_L_E_T_ = ' ') A2_NOME, "
CQRY += " 			FT_ITEM,"
CQRY += " 			FT_CFOP,"
CQRY += " 			D2_TES,"
CQRY += " 			X5_DESCRI X5DESCRI,"
CQRY += " 			ISNULL(FT_CODBCC,'  ') FT_CODBCC,"
CQRY += " 			FT_CSTPIS,"
CQRY += " 			FT_CSTCOF,"
CQRY += " 			FT_ALIQPIS,"
CQRY += " 			FT_ALIQCOF,"
CQRY += " 			CASE WHEN FT_TIPO NOT IN ('D','B') AND "+CCPOORGPUB+" IN ('1','S') THEN 'S' ELSE 'N' END A1_XORGPUB,"
CQRY += " 			CASE	WHEN SUBSTRING(FT_CFOP,1,1)='7' THEN 'FAT.EXP'"
CQRY += " 					WHEN SUBSTRING(FT_CFOP,2,3) IN ('110','109') THEN 'FAT.ZFM'"
CQRY += " 					WHEN SUBSTRING(FT_CFOP,2,3) IN ('201','202','203','204') THEN 'DEVOLUCAO'"
CQRY += " 					WHEN FT_ALIQCOF=3.00 AND FT_BASECOF>0 THEN 'FAT.CUM'"
CQRY += " 					WHEN FT_ALIQCOF=7.60 AND FT_BASECOF>0 THEN 'FAT.NCUM'"
CQRY += " 			ELSE 'NAO TRATADO' END LINHA,"
CQRY += " 			0 E1_SALDO,"
CQRY += " 			FT_VALCONT,"
CQRY += " 			CASE WHEN FT_ESPECIE='RPS' THEN FT_VALCONT ELSE FT_TOTAL END FT_TOTAL,"
CQRY += " 	   		CASE WHEN F4_PISCRED IN ('1','2') THEN FT_BASEPIS ELSE 0 END FT_BASEPIS,"
CQRY += " 			CASE WHEN F4_PISCRED IN ('1','2') THEN FT_BASECOF ELSE 0 END FT_BASECOF,"
CQRY += " 			CASE WHEN F4_PISCRED IN ('1','2') THEN FT_VALPIS ELSE 0 END FT_VALPIS,"
CQRY += " 			CASE WHEN F4_PISCRED IN ('1','2') THEN FT_VALCOF - FT_MVALCOF ELSE 0 END FT_VALCOF,"
CQRY += " 			FT_VALIPI,"
CQRY += " 			SD2.R_E_C_N_O_ RECSD,"
CQRY += " 			FT_TIPO,"
CQRY += " 			FT_PRODUTO,"
CQRY += " 			FT_NFORI,"
CQRY += " 		   	' ' DTNFORI,"
CQRY += " 		   	SFT.R_E_C_N_O_ RECSFT,"
CQRY += " 		   	SFT.FT_POSIPI B1_POSIPI,"
CQRY += " 		   	ISNULL(CG1_CODIGO,'')CG1_CODIGO,"
CQRY += " 		   	ISNULL(CG1_ALIQ,0)CG1_ALIQ,"
CQRY += " 		   	D2_TIPO,D2_LOTECTL,FT_ICMSRET,FT_FRETE,FT_SEGURO,FT_DESPESA,FT_DESCONT"

CQRY += "           ,A1_NOME,A1_NREDUZ,A1_VEND,A1_REGIAO,A1_EST,B1_DESC,FT_VALICM, FT_BASEICM, FT_DIFAL, FT_VFCPDIF, FT_ICMSCOM, FT_ISENICM, FT_OUTRICM,FT_ALIQICM, FT_CLASFIS"

CQRY += "           ,A1_INSCR,FT_ENTRADA"

CQRY += " FROM "+RETSQLNAME("SFT")+" SFT"
CQRY += " LEFT JOIN "+RETSQLNAME("SB1")+" SB1 ON B1_FILIAL ='"+XFILIAL("SB1")+"' AND B1_COD=FT_PRODUTO AND SB1.D_E_L_E_T_=' '"
CQRY += " LEFT JOIN "+RETSQLNAME("SD2")+" SD2 ON D2_FILIAL =FT_FILIAL AND D2_DOC=FT_NFISCAL AND D2_SERIE=FT_SERIE AND D2_CLIENTE=FT_CLIEFOR AND D2_LOJA=FT_LOJA AND D2_ITEM=FT_ITEM AND SD2.D_E_L_E_T_=' '"
CQRY += " LEFT JOIN "+RETSQLNAME("SF4")+" SF4 ON F4_FILIAL ='"+XFILIAL("SF4")+"' AND F4_CODIGO=D2_TES AND SF4.D_E_L_E_T_=' '"
CQRY += " LEFT JOIN "+RETSQLNAME("SX5")+" SX5 ON X5_FILIAL ='"+XFILIAL("SX5")+"' AND X5_TABELA='13' AND X5_CHAVE=FT_CFOP AND SX5.D_E_L_E_T_=' '"
CQRY += " LEFT JOIN "+RETSQLNAME("SA1")+" SA1 ON A1_FILIAL ='"+XFILIAL("SA1")+"' AND A1_COD=FT_CLIEFOR AND A1_LOJA=FT_LOJA AND SA1.D_E_L_E_T_=' ' AND FT_TIPO NOT IN ('D','B')"
CQRY += " LEFT JOIN "+RETSQLNAME("SA2")+" SA2 ON A2_FILIAL ='"+XFILIAL("SA2")+"' AND A2_COD=FT_CLIEFOR AND A2_LOJA=FT_LOJA AND SA2.D_E_L_E_T_=' ' AND FT_TIPO     IN ('D','B')"
CQRY += " LEFT JOIN "+RETSQLNAME("SB5")+" SB5 ON B5_FILIAL=B1_FILIAL AND B5_COD=B1_COD AND SB5.D_E_L_E_T_=' '"
CQRY += " LEFT JOIN "+RETSQLNAME("CG1")+" CG1 ON CG1_FILIAL='"+XFILIAL("CG1")+"' AND CG1_CODIGO=B5_CODATIV AND CG1.D_E_L_E_T_=' '"
CQRY += " WHERE"
CQRY += "     FT_FILIAL IN ('"+STRTRAN( ALLTRIM(MV_PAR03),",","','")+"')"
CQRY += " AND FT_ENTRADA BETWEEN '"+DTOS(MV_PAR01)+"' AND '"+DTOS(MV_PAR02)+"'"
CQRY += " AND FT_TIPOMOV='S'"
CQRY += " AND FT_DTCANC=' '"
CQRY += " AND SFT.D_E_L_E_T_=' '"
CQRY += " UNION ALL"
CQRY += " SELECT	FT_FILIAL,"
CQRY += " 			FT_NFISCAL,FT_NFELETR,"
CQRY += " 			FT_SERIE,"
CQRY += " 			FT_CLIEFOR,"
CQRY += " 			RTRIM(LTRIM(ISNULL(A1_CGC,' ')))+RTRIM(LTRIM(ISNULL(A2_CGC,' '))) A1_CGC,"
CQRY += " 			FT_LOJA,"
CQRY += " 			(SELECT A2_NOME FROM SA2010 SA2 WHERE A2_FILIAL = '"+XFILIAL("SA2")+"' AND A2_COD = FT_CLIEFOR AND A2_LOJA = FT_LOJA AND SA2.D_E_L_E_T_ = ' ') A2_NOME, "
CQRY += " 			FT_ITEM,"
CQRY += " 			FT_CFOP,"
CQRY += " 			D1_TES,"
CQRY += " 			X5_DESCRI X5DESCRI,"
CQRY += " 			ISNULL(FT_CODBCC,'  ') FT_CODBCC,"
CQRY += " 			FT_CSTPIS,"
CQRY += " 			FT_CSTCOF,"
CQRY += " 			FT_ALIQPIS,"
CQRY += " 			FT_ALIQCOF,"
CQRY += " 			'N' A1_XORGPUB,"
CQRY += " 			'ENTRADA' LINHA,"
CQRY += " 			0 E1_SALDO,"
CQRY += " 			FT_VALCONT,"
CQRY += " 			FT_VALCONT FT_TOTAL,"
CQRY += " 	   		CASE WHEN F4_PISCRED IN ('1','2') THEN FT_BASEPIS ELSE 0 END FT_BASEPIS,"
CQRY += " 			CASE WHEN F4_PISCRED IN ('1','2') THEN FT_BASECOF ELSE 0 END FT_BASECOF,"
CQRY += " 			CASE WHEN F4_PISCRED IN ('1','2') THEN FT_VALPIS ELSE 0 END FT_VALPIS,"
CQRY += " 			CASE WHEN F4_PISCRED IN ('1','2') THEN FT_VALCOF - FT_MVALCOF ELSE 0 END FT_VALCOF,"
CQRY += " 			FT_VALIPI,"
CQRY += " 			SD1.R_E_C_N_O_ RECSD,"
CQRY += " 			FT_TIPO,"
CQRY += " 			FT_PRODUTO,"
CQRY += " 			FT_NFORI,"
CQRY += " 			' ' DTNFORI,"
CQRY += "	   		SFT.R_E_C_N_O_ RECSFT,"
CQRY += " 		   	SFT.FT_POSIPI B1_POSIPI,"
CQRY += "	   		ISNULL(CG1_CODIGO,'')CG1_CODIGO,"
CQRY += "	   		ISNULL(CG1_ALIQ,0)CG1_ALIQ,"
CQRY += " 		   	D1_TIPO, D1_LOTECTL,FT_ICMSRET,FT_FRETE,FT_SEGURO,FT_DESPESA,FT_DESCONT"

CQRY += "           ,A1_NOME, A1_NREDUZ, A1_VEND, A1_REGIAO, A1_EST, B1_DESC,FT_VALICM,FT_BASEICM,FT_DIFAL, FT_VFCPDIF, FT_ICMSCOM, FT_ISENICM, FT_OUTRICM,FT_ALIQICM, FT_CLASFIS"

CQRY += "           ,A1_INSCR,FT_ENTRADA"

CQRY += " FROM "+RETSQLNAME("SFT")+" SFT"
CQRY += " LEFT JOIN "+RETSQLNAME("SB1")+" SB1 ON B1_FILIAL='"+XFILIAL("SB1")+"' AND B1_COD=FT_PRODUTO AND SB1.D_E_L_E_T_=' '"
CQRY += " LEFT JOIN "+RETSQLNAME("SD1")+" SD1 ON D1_FILIAL=FT_FILIAL AND D1_DOC=FT_NFISCAL AND D1_SERIE=FT_SERIE AND D1_FORNECE=FT_CLIEFOR AND D1_LOJA=FT_LOJA AND D1_ITEM=FT_ITEM AND SD1.D_E_L_E_T_=' '"
CQRY += " LEFT JOIN "+RETSQLNAME("SF4")+" SF4 ON F4_FILIAL='"+XFILIAL("SF4")+"' AND F4_CODIGO=D1_TES AND SF4.D_E_L_E_T_=' '"
CQRY += " LEFT JOIN "+RETSQLNAME("SX5")+" SX5 ON X5_FILIAL='"+XFILIAL("SX5")+"' AND X5_TABELA='13' AND X5_CHAVE=FT_CFOP AND SX5.D_E_L_E_T_=' '"
CQRY += " LEFT JOIN "+RETSQLNAME("SA1")+" SA1 ON A1_FILIAL='"+XFILIAL("SA1")+"' AND A1_COD=FT_CLIEFOR AND A1_LOJA=FT_LOJA AND SA1.D_E_L_E_T_=' ' AND FT_TIPO     IN ('D','B')"
CQRY += " LEFT JOIN "+RETSQLNAME("SA2")+" SA2 ON A2_FILIAL='"+XFILIAL("SA2")+"' AND A2_COD=FT_CLIEFOR AND A2_LOJA=FT_LOJA AND SA2.D_E_L_E_T_=' ' AND FT_TIPO NOT IN ('D','B')"
CQRY += " LEFT JOIN "+RETSQLNAME("SB5")+" SB5 ON B5_FILIAL=B1_FILIAL AND B5_COD=B1_COD AND SB5.D_E_L_E_T_=' '"
CQRY += " LEFT JOIN "+RETSQLNAME("CG1")+" CG1 ON CG1_FILIAL='"+XFILIAL("CG1")+"' AND CG1_CODIGO=B5_CODATIV AND CG1.D_E_L_E_T_=' '"
CQRY += " WHERE"
CQRY += "     FT_FILIAL IN ('"+STRTRAN( ALLTRIM(MV_PAR03),",","','")+"')"
CQRY += " AND FT_ENTRADA BETWEEN '"+DTOS(MV_PAR01)+"' AND '"+DTOS(MV_PAR02)+"'"
CQRY += " AND FT_TIPOMOV='E'"
CQRY += " AND FT_DTCANC=' '"
CQRY += " AND SFT.D_E_L_E_T_=' '"
CQRY += " ORDER BY FT_FILIAL, FT_NFISCAL, FT_SERIE, FT_CLIEFOR, FT_LOJA, FT_ITEM"

MEMOWRITE("\SYSTEM\RFISR50.TXT",CQRY)

IF SELECT("QUERY")>0
    DBSELECTAREA("QUERY")
    DBCLOSEAREA()
ENDIF

DBSELECTAREA("SE1")
DBSETORDER(1)

DBSELECTAREA("SF4")
DBSETORDER(1)

DBSELECTAREA("SF2")
DBSETORDER(1)

DBSELECTAREA("SD2")
DBSETORDER(3)

DBSELECTAREA("SD1")
DBSETORDER(1)

DBUSEAREA( .T. ,"TOPCONN",TCGENQRY(,,CQRY),"QUERY", .F. , .T. )

TCSETFIELD("QUERY","DTNFORI","D",8,0)

DBSELECTAREA("QUERY")

DBSELECTAREA("QUERY")
(QUERY)->(DBGOTOP())
(QUERY)->(DBEVAL({||NTOTREG++},{||!(EOF())}))
(QUERY)->(DBGOTOP())
OPROCESS:SETREGUA2(NTOTREG)

IF !((QUERY)->(EOF()))

    WHILE !(EOF())
    
      OPROCESS:INCREGUA2("GRAVANDO DADOS ... ")

        RECLOCK("TMPTRB", .T. )

        FOR NA := 1 TO  LEN(ACMPTMP)
            (TMPTRB)->(&(ACMPTMP[NA][1])) := GETVLDVALUE((QUERY)->(&(ACMPTMP[NA][1])),NA)
        NEXT

        NSALDOTIT := 0
        NSALDOTOT := 0
        NSALDORET := 0

        IF TMPTRB->A1_XORGPUB="S" .AND. !(CREGANT==(QUERY)->(FT_FILIAL+FT_NFISCAL+FT_SERIE+FT_CLIEFOR+FT_LOJA))
            DBSELECTAREA("SF2")
            
            IF DBSEEK((TMPTRB)->(FT_FILIAL+FT_NFISCAL+FT_SERIE))
                DBSELECTAREA("SE1")
                
                IF DBSEEK(XFILIAL("SE1")+SF2->F2_PREFIXO+SF2->F2_DOC)

                    WHILE !(EOF()) .AND. SE1->E1_FILIAL==XFILIAL("SE1") .AND. SE1->E1_PREFIXO==SF2->F2_PREFIXO .AND. SE1->E1_NUM=SF2->F2_DOC
                    
                        IF !((SE1->E1_TIPO) $ ("NF ") .AND. SE1->E1_CLIENTE==SF2->F2_CLIENTE .AND. SE1->E1_LOJA=SF2->F2_LOJA)
                            DBSELECTAREA("SE1")
                            DBSKIP()
                            LOOP 
                        ENDIF

                        NSALDOTIT := SALDOTIT(SE1->E1_PREFIXO,SE1->E1_NUM,SE1->E1_PARCELA,SE1->E1_TIPO,SE1->E1_NATUREZ,"R",SE1->E1_CLIENTE,SE1->E1_MOEDA,MV_PAR02,MV_PAR02,SE1->E1_LOJA)

                        NSALDOTIT := NSALDOTIT-SE1->E1_SDACRES+SE1->E1_SDDECRE

                        IF NSALDOTIT<SE1->E1_VLCRUZ
                            NSALDORET := SUBRETBX()
                        ENDIF

                        NSALDOTOT += NSALDOTIT-NSALDORET

                        DBSELECTAREA("SE1")
                        DBSKIP()
                        ENDDO
                ENDIF
            ENDIF
        ENDIF

        TMPTRB->E1_SALDO := NSALDOTOT

        LDEVOL :=  .F. 
        CCFOP :=  UPPER( ALLTRIM(QUERY->FT_CFOP))

        IF QUERY->FT_TIPO=="D"
            
            IF CCFOP<"5000"
                DBSELECTAREA("SD1")
                
                IF DBSEEK((QUERY)->(FT_FILIAL+FT_NFISCAL+FT_SERIE+FT_CLIEFOR+FT_LOJA+FT_PRODUTO+FT_ITEM))
                    DBSELECTAREA("SD2")
                    
                    IF DBSEEK(SD1->(D1_FILIAL+D1_NFORI+D1_SERIORI+D1_FORNECE+D1_LOJA+D1_COD+D1_ITEMORI))
                        DBSELECTAREA("SF4")
                        DBSEEK(XFILIAL("SF4")+SD2->D2_TES)
                        
                        IF SD2->D2_EMISSAO>=MV_PAR01 .AND. SD2->D2_EMISSAO<=MV_PAR02
                            TMPTRB->LINHA :=  ALLTRIM(TMPTRB->LINHA)+" DEVOL NO MES - "+SD2->D2_CF
                            LDEVOL :=  .T. 
                        ELSE 

                            TMPTRB->DTNFORI := SD2->D2_EMISSAO
                        ENDIF

                        TMPTRB->LINHA :=  ALLTRIM(TMPTRB->LINHA)+IIF((SF4->F4_PISCOF) $ ("1,2,3") .AND. (SF4->F4_PISCRED) $ ("1,2") .AND. SD2->D2_VALIMP5+SD2->D2_VALIMP6>0," S.TRIB"," ")
                    ENDIF
                ENDIF
            ELSE 
                DBSELECTAREA("SD2")
                
                IF DBSEEK((QUERY)->(FT_FILIAL+FT_NFISCAL+FT_SERIE+FT_CLIEFOR+FT_LOJA+FT_PRODUTO+FT_ITEM))
                    DBSELECTAREA("SD1")
                    
                    IF DBSEEK(SD2->(D2_FILIAL+D2_NFORI+D2_SERIORI+D2_CLIENTE+D2_LOJA+D2_COD+D2_ITEMORI))
                        DBSELECTAREA("SF4")
                        DBSEEK(XFILIAL("SF4")+SD1->D1_TES)
                        
                        IF SD1->D1_DTDIGIT>=MV_PAR01 .AND. SD1->D1_DTDIGIT<=MV_PAR02
                            TMPTRB->LINHA :=  ALLTRIM(TMPTRB->LINHA)+" DEVOL NO MES - "+SD1->D1_CF
                            LDEVOL :=  .T. 
                        ELSE 

                            TMPTRB->DTNFORI := SD1->D1_DTDIGIT
                        ENDIF
                        TMPTRB->LINHA :=  ALLTRIM(TMPTRB->LINHA)+IIF((SF4->F4_PISCOF) $ ("1,2,3") .AND. (SF4->F4_PISCRED) $ ("1,2") .AND. SD1->D1_VALIMP5+SD1->D1_VALIMP6>0," E.TRIB"," ")
                    ENDIF
                ENDIF
            ENDIF
        ENDIF

        (TMPTRB)->(MSUNLOCK())
        CREGANT := (QUERY)->(FT_FILIAL+FT_NFISCAL+FT_SERIE+FT_CLIEFOR+FT_LOJA)

       IF LDEVOL
            DBSELECTAREA("TMPTRB")
            
            IF CCFOP<"5000"
                
                IF DBSEEK(SD2->(D2_FILIAL+D2_DOC+D2_SERIE+D2_CLIENTE+D2_LOJA+D2_COD+D2_ITEM))
                    RECLOCK("TMPTRB", .F. )
                    TMPTRB->LINHA :=  ALLTRIM(TMPTRB->LINHA)+" DEVOL NO MES - "+CCFOP
                    (TMPTRB)->(MSUNLOCK())
                ENDIF
            ELSE 
                
                IF DBSEEK(SD1->(D1_FILIAL+D1_DOC+D1_SERIE+D1_FORNECE+D1_LOJA+D1_COD+D1_ITEM))
                    RECLOCK("TMPTRB", .F. )
                    TMPTRB->LINHA :=  ALLTRIM(TMPTRB->LINHA)+" DEVOL NO MES - "+CCFOP
                    (TMPTRB)->(MSUNLOCK())
                ENDIF
            ENDIF
        ENDIF

        DBSELECTAREA("QUERY")
        (QUERY)->(DBSKIP())
        ENDDO

    XMLINITFILE(AESTILOS)

    ACABEC := {}

    AADD(ACABEC,{X3XTIT("FT_FILIAL"),"FT_FILIAL",TAMSX3("FT_FILIAL")[3],TAMSX3("FT_FILIAL")[1],TAMSX3("FT_FILIAL")[2]})
    AADD(ACABEC,{X3XTIT("FT_NFISCAL"),"FT_NFISCAL",TAMSX3("FT_NFISCAL")[3],TAMSX3("FT_NFISCAL")[1],TAMSX3("FT_NFISCAL")[2]})
    AADD(ACABEC,{X3XTIT("FT_NFELETR"),"FT_NFELETR",TAMSX3("FT_NFELETR")[3],TAMSX3("FT_NFELETR")[1],TAMSX3("FT_NFELETR")[2]})
    AADD(ACABEC,{X3XTIT("FT_SERIE"),"FT_SERIE",TAMSX3("FT_SERIE")[3],TAMSX3("FT_SERIE")[1],TAMSX3("FT_SERIE")[2]})
    AADD(ACABEC,{X3XTIT("FT_CLIEFOR"),"FT_CLIEFOR",TAMSX3("FT_CLIEFOR")[3],TAMSX3("FT_CLIEFOR")[1],TAMSX3("FT_CLIEFOR")[2]})
    AADD(ACABEC,{X3XTIT("FT_LOJA"),"FT_LOJA",TAMSX3("FT_LOJA")[3],TAMSX3("FT_LOJA")[1],TAMSX3("FT_LOJA")[2]})
    AADD(ACABEC,{X3XTIT("A2_NOME"),"A2_NOME",TAMSX3("A2_NOME")[3],TAMSX3("A2_NOME")[1],TAMSX3("A2_NOME")[2]})
    AADD(ACABEC,{X3XTIT("A1_CGC"),"A1_CGC",TAMSX3("A1_CGC")[3],TAMSX3("A1_CGC")[1],TAMSX3("A1_CGC")[2]})
    AADD(ACABEC,{X3XTIT("FT_ITEM"),"FT_ITEM",TAMSX3("FT_ITEM")[3],TAMSX3("FT_ITEM")[1],TAMSX3("FT_ITEM")[2]})
    AADD(ACABEC,{X3XTIT("FT_CFOP"),"FT_CFOP",TAMSX3("FT_CFOP")[3],TAMSX3("FT_CFOP")[1],TAMSX3("FT_CFOP")[2]})
   AADD(ACABEC,{X3XTIT("D2_TES"),"D2_TES",TAMSX3("D2_TES")[3],TAMSX3("D2_TES")[1],TAMSX3("D2_TES")[2]})
    AADD(ACABEC,{X3XTIT("X5_DESCRI"),"X5_DESCRI",TAMSX3("X5_DESCRI")[3],TAMSX3("X5_DESCRI")[1],TAMSX3("X5_DESCRI")[2]})
    AADD(ACABEC,{X3XTIT("FT_CODBCC"),"FT_CODBCC",TAMSX3("FT_CODBCC")[3],TAMSX3("FT_CODBCC")[1],TAMSX3("FT_CODBCC")[2]})
    AADD(ACABEC,{X3XTIT("FT_CSTPIS"),"FT_CSTPIS",TAMSX3("FT_CSTPIS")[3],TAMSX3("FT_CSTPIS")[1],TAMSX3("FT_CSTPIS")[2]})
    AADD(ACABEC,{X3XTIT("FT_CSTCOF"),"FT_CSTCOF",TAMSX3("FT_CSTCOF")[3],TAMSX3("FT_CSTCOF")[1],TAMSX3("FT_CSTCOF")[2]})
    AADD(ACABEC,{X3XTIT("FT_ALIQPIS"),"FT_ALIQPIS",TAMSX3("FT_ALIQPIS")[3],TAMSX3("FT_ALIQPIS")[1],TAMSX3("FT_ALIQPIS")[2]})
    AADD(ACABEC,{X3XTIT("FT_ALIQCOF"),"FT_ALIQCOF",TAMSX3("FT_ALIQCOF")[3],TAMSX3("FT_ALIQCOF")[1],TAMSX3("FT_ALIQCOF")[2]})
    AADD(ACABEC,{"A1_XORGPUB","A1_XORGPUB",TAMSX3(CCPOORGPUB)[3],TAMSX3(CCPOORGPUB)[1],TAMSX3(CCPOORGPUB)[2]})
    AADD(ACABEC,{"LINHA","LINHA","C",20,0})
    AADD(ACABEC,{X3XTIT("FT_VALCONT"),"FT_VALCONT",TAMSX3("FT_VALCONT")[3],TAMSX3("FT_VALCONT")[1],TAMSX3("FT_VALCONT")[2]})
    AADD(ACABEC,{X3XTIT("E1_SALDO"),"E1_SALDO",TAMSX3("E1_SALDO")[3],TAMSX3("E1_SALDO")[1],TAMSX3("E1_SALDO")[2]})
    AADD(ACABEC,{X3XTIT("FT_TOTAL"),"FT_TOTAL",TAMSX3("FT_TOTAL")[3],TAMSX3("FT_TOTAL")[1],TAMSX3("FT_TOTAL")[2]})
    AADD(ACABEC,{X3XTIT("FT_BASEPIS"),"FT_BASEPIS",TAMSX3("FT_BASEPIS")[3],TAMSX3("FT_BASEPIS")[1],TAMSX3("FT_BASEPIS")[2]})
    AADD(ACABEC,{X3XTIT("FT_BASECOF"),"FT_BASECOF",TAMSX3("FT_BASECOF")[3],TAMSX3("FT_BASECOF")[1],TAMSX3("FT_BASECOF")[2]})
    AADD(ACABEC,{X3XTIT("FT_VALPIS"),"FT_VALPIS",TAMSX3("FT_VALPIS")[3],TAMSX3("FT_VALPIS")[1],TAMSX3("FT_VALPIS")[2]})
    AADD(ACABEC,{X3XTIT("FT_VALCOF"),"FT_VALCOF",TAMSX3("FT_VALCOF")[3],TAMSX3("FT_VALCOF")[1],TAMSX3("FT_VALCOF")[2]})
    AADD(ACABEC,{X3XTIT("FT_VALIPI"),"FT_VALIPI",TAMSX3("FT_VALIPI")[3],TAMSX3("FT_VALIPI")[1],TAMSX3("FT_VALIPI")[2]})
    AADD(ACABEC,{X3XTIT("FT_PRODUTO"),"FT_PRODUTO",TAMSX3("FT_PRODUTO")[3],TAMSX3("FT_PRODUTO")[1],TAMSX3("FT_PRODUTO")[2]})
    AADD(ACABEC,{X3XTIT("FT_NFORI"),"FT_NFORI",TAMSX3("FT_NFORI")[3],TAMSX3("FT_NFORI")[1],TAMSX3("FT_NFORI")[2]})
    AADD(ACABEC,{"DTNFORI","DTNFORI",TAMSX3("FT_ENTRADA")[3],TAMSX3("FT_ENTRADA")[1],TAMSX3("FT_ENTRADA")[2]})
    AADD(ACABEC,{X3XTIT("B1_POSIPI"),"B1_POSIPI",TAMSX3("B1_POSIPI")[3],TAMSX3("B1_POSIPI")[1],TAMSX3("B1_POSIPI")[2]})
    AADD(ACABEC,{X3XTIT("CG1_CODIGO"),"CG1_CODIGO",TAMSX3("CG1_CODIGO")[3],TAMSX3("CG1_CODIGO")[1],TAMSX3("CG1_CODIGO")[2]})
    AADD(ACABEC,{X3XTIT("CG1_ALIQ"),"CG1_ALIQ",TAMSX3("CG1_ALIQ")[3],TAMSX3("CG1_ALIQ")[1],TAMSX3("CG1_ALIQ")[2]})
    AADD(ACABEC,{X3XTIT("D2_TIPO"),"D2_TIPO",TAMSX3("D2_TIPO")[3],TAMSX3("D2_TIPO")[1],TAMSX3("D2_TIPO")[2]})
    AADD(ACABEC,{X3XTIT("D2_LOTECTL"),"D2_LOTECTL",TAMSX3("D2_LOTECTL")[3],TAMSX3("D2_LOTECTL")[1],TAMSX3("D2_LOTECTL")[2]})
    AADD(ACABEC,{X3XTIT("FT_ICMSRET"),"FT_ICMSRET",TAMSX3("FT_ICMSRET")[3],TAMSX3("FT_ICMSRET")[1],TAMSX3("FT_ICMSRET")[2]})
    AADD(ACABEC,{X3XTIT("FT_FRETE"),"FT_FRETE",TAMSX3("FT_FRETE")[3],TAMSX3("FT_FRETE")[1],TAMSX3("FT_FRETE")[2]})
    AADD(ACABEC,{X3XTIT("FT_SEGURO"),"FT_SEGURO",TAMSX3("FT_SEGURO")[3],TAMSX3("FT_SEGURO")[1],TAMSX3("FT_SEGURO")[2]})
    AADD(ACABEC,{X3XTIT("FT_DESPESA"),"FT_DESPESA",TAMSX3("FT_DESPESA")[3],TAMSX3("FT_DESPESA")[1],TAMSX3("FT_DESPESA")[2]})
    AADD(ACABEC,{X3XTIT("FT_DESCONT"),"FT_DESCONT",TAMSX3("FT_DESCONT")[3],TAMSX3("FT_DESCONT")[1],TAMSX3("FT_DESCONT")[2]})

    AADD(ACABEC,{X3XTIT("A1_NOME"),"A1_NOME",TAMSX3("A1_NOME")[3],TAMSX3("A1_NOME")[1],TAMSX3("A1_NOME")[2]})
    AADD(ACABEC,{X3XTIT("A1_NREDUZ"),"A1_NREDUZ",TAMSX3("A1_NREDUZ")[3],TAMSX3("A1_NREDUZ")[1],TAMSX3("A1_NREDUZ")[2]})
    AADD(ACABEC,{X3XTIT("A1_VEND"),"A1_VEND",TAMSX3("A1_VEND")[3],TAMSX3("A1_VEND")[1],TAMSX3("A1_VEND")[2]})
    AADD(ACABEC,{X3XTIT("A1_REGIAO"),"A1_REGIAO",TAMSX3("A1_REGIAO")[3],TAMSX3("A1_REGIAO")[1],TAMSX3("A1_REGIAO")[2]})
    AADD(ACABEC,{X3XTIT("A1_EST"),"A1_EST",TAMSX3("A1_EST")[3],TAMSX3("A1_EST")[1],TAMSX3("A1_EST")[2]})

    AADD(ACABEC,{X3XTIT("B1_DESC"),"B1_DESC",TAMSX3("B1_DESC")[3],TAMSX3("B1_DESC")[1],TAMSX3("B1_DESC")[2]})
    AADD(ACABEC,{X3XTIT("FT_BASEICM"),"FT_BASEICM",TAMSX3("FT_BASEICM")[3],TAMSX3("FT_BASEICM")[1],TAMSX3("FT_BASEICM")[2]})
    AADD(ACABEC,{X3XTIT("FT_VALICM"),"FT_VALICM",TAMSX3("FT_VALICM")[3],TAMSX3("FT_VALICM")[1],TAMSX3("FT_VALICM")[2]})
    AADD(ACABEC,{X3XTIT("FT_DIFAL"),"FT_DIFAL",TAMSX3("FT_DIFAL")[3],TAMSX3("FT_DIFAL")[1],TAMSX3("FT_DIFAL")[2]})
    AADD(ACABEC,{X3XTIT("FT_VFCPDIF"),"FT_VFCPDIF",TAMSX3("FT_VFCPDIF")[3],TAMSX3("FT_VFCPDIF")[1],TAMSX3("FT_VFCPDIF")[2]})
    AADD(ACABEC,{X3XTIT("FT_ICMSCOM"),"FT_ICMSCOM",TAMSX3("FT_ICMSCOM")[3],TAMSX3("FT_ICMSCOM")[1],TAMSX3("FT_ICMSCOM")[2]})

    AADD(ACABEC,{X3XTIT("FT_ISENICM"),"FT_ISENICM",TAMSX3("FT_ISENICM")[3],TAMSX3("FT_ISENICM")[1],TAMSX3("FT_ISENICM")[2]})
    AADD(ACABEC,{X3XTIT("FT_OUTRICM"),"FT_OUTRICM",TAMSX3("FT_OUTRICM")[3],TAMSX3("FT_OUTRICM")[1],TAMSX3("FT_OUTRICM")[2]})
    AADD(ACABEC,{X3XTIT("FT_ALIQICM"),"FT_ALIQICM",TAMSX3("FT_ALIQICM")[3],TAMSX3("FT_ALIQICM")[1],TAMSX3("FT_ALIQICM")[2]})
    AADD(ACABEC,{X3XTIT("FT_CLASFIS"),"FT_CLASFIS",TAMSX3("FT_CLASFIS")[3],TAMSX3("FT_CLASFIS")[1],TAMSX3("FT_CLASFIS")[2]})

    AADD(ACABEC,{X3XTIT("A1_INSCR"),"A1_INSCR",TAMSX3("A1_INSCR")[3],TAMSX3("A1_INSCR")[1],TAMSX3("A1_INSCR")[2]})
    AADD(ACABEC,{X3XTIT("FT_ENTRADA"),"FT_ENTRADA",TAMSX3("FT_ENTRADA")[3],TAMSX3("FT_ENTRADA")[1],TAMSX3("FT_ENTRADA")[2]})

    RESUME1()
    DBSELECTAREA("RESUME")
    DBGOTOP()
    XMLADDPLAN("RESUMIDO1",TITULO,,ACABEC,1,,OPROCESS,2)

    RESUME2()
    DBSELECTAREA("RESUME")
    DBGOTOP()
    XMLADDPLAN("RESUMIDO2",TITULO,,ACABEC,1,,OPROCESS,2)

    DBSELECTAREA("TMPTRB")
    DBGOTOP()
    XMLADDPLAN("ANALITICO",TITULO,,ACABEC,1,,OPROCESS,2)

    RESUMEDIF()
    DBGOTOP()
    DBSELECTAREA("RESUMEDIF")
    XMLADDPLAN("A DIFERIR",TITULO,,ACABEC,1,,OPROCESS,2)

    RESUMEBLP()
    DBGOTOP()
    DBSELECTAREA("RESUMEBLP")
    XMLADDPLAN("BLOCOP",TITULO,,ACABEC,1,,OPROCESS,2)

    XMLCLOSEFILE("ARQUIVO GERADO COM SUCESSO!")

    CPYS2T(CDIRDOCS+CBARRA+CARQUIVO,CPATH, .T. )

    /*OEXCELAPP := MSEXCEL():NEW()
    OEXCELAPP:WORKBOOKS:OPEN(CPATH+CARQUIVO)
    OEXCELAPP:SETVISIBLE( .T. )
    OEXCELAPP:DESTROY()*/
    ShellExecute("OPEN", CPATH+CARQUIVO,"","",1)
ELSE 

    AVISO("AVISO","Nï¿½O FORAM ENCONTRADOS REGISTROS QUE ATENDESSEM AOS CRITï¿½RIOS DE FILTRO.",{"OK"},,"ATENï¿½ï¿½O",,"BMPPERG")
    LRETORNO :=  .F. 
ENDIF

IF SELECT("QUERY")>0
    (QUERY)->(DBCLOSEAREA())
ENDIF

IF SELECT("TMPTRB")>0
    (TMPTRB)->(DBCLOSEAREA())
ENDIF

RETURN LRETORNO

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
//STATIC FUNCTION VALIDPERG(CPERG,AREGS)
//
//LOCAL I := 0
//LOCAL J := 0
//LOCAL AAREA := GETAREA()
//
//DBSELECTAREA("SX1")
//DBSETORDER(1)
//
//FOR I := 1 TO  LEN(AREGS)
//    
//    IF !(DBSEEK(PADR(CPERG, LEN(X1_GRUPO))+AREGS[I][2]))
//        RECLOCK("SX1", .T. )
//        FOR J := 1 TO  LEN(AREGS[1])
//            FIELDPUT(J,AREGS[I][J])
//        NEXT
//        MSUNLOCK()
//    ENDIF
//NEXT
//
//RESTAREA(AAREA)
//
//RETURN NIL

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION GETVLDVALUE(XVALOR,NPOS)

LOCAL AAREA := GETAREA()
LOCAL XRETORNO := NIL

IF VALTYPE(XVALOR)=="U"
    XRETORNO := CRIAVAR(ACMPTMP[NPOS][1], .F. )
ELSEIF VALTYPE(XVALOR)=="C"
    
    IF EMPTY( ALLTRIM(XVALOR))
        XRETORNO := CRIAVAR(ACMPTMP[NPOS][1], .F. )
    ELSE 
        
        IF ACMPTMP[NPOS][2]=="C"
            
            XRETORNO := XVALOR
        ELSEIF ACMPTMP[NPOS][2]=="N"
            XRETORNO := XVALOR
        ELSEIF ACMPTMP[NPOS][2]=="D"
            XRETORNO := STOD(XVALOR)
        ELSEIF ACMPTMP[NPOS][2]=="L"
            XRETORNO := &(XVALOR)
        ENDIF
    ENDIF

ELSEIF VALTYPE(XVALOR)=="N"
    XRETORNO := XVALOR
ELSEIF ACMPTMP[NPOS][2]=="D"
    XRETORNO := XVALOR
ELSEIF VALTYPE(XVALOR)=="L"
    XRETORNO := XVALOR
ENDIF

RESTAREA(AAREA)

RETURN XRETORNO

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION XMLINITFILE(ASTYLE)

LOCAL LRETORNO :=  .T. 
LOCAL NLOOP := 0
LOCAL NLOOPSTYLE := 0
LOCAL CSTRING := ""

CSTRING := '<?XML VERSION="1.0"?>' + CRLF
CSTRING += '<SS:WORKBOOK XMLNS:SS="URN:SCHEMAS-MICROSOFT-COM:OFFICE:SPREADSHEET">' + CRLF
IF !(EMPTY(ASTYLE))
    CSTRING += "    <SS:STYLES>" + CRLF
    FOR NLOOP := 1 TO  LEN(ASTYLE)
        CSTRING += '        <SS:STYLE SS:ID="'+ ALLTRIM(STR(NLOOP))+'">' + CRLF
        CSTRING += "            <SS:FONT "
        FOR NLOOPSTYLE := 1 TO  LEN(ASTYLE[NLOOP])
            CSTRING += "SS:"+ASTYLE[NLOOP][NLOOPSTYLE]+'="1" '
        NEXT
        CSTRING += "/>" + CRLF
        CSTRING += "        </SS:STYLE>" + CRLF
    NEXT
    CSTRING += "    </SS:STYLES>" + CRLF
ENDIF

GRVARQ(CSTRING,@NHANDLE)

RETURN LRETORNO

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION XMLADDPLAN(CWKSHEET,CTITULO,APRESECTION,ACABEC,NSTYLEID,AFOOTER,OPROCESS,NSTYLECAB,BFUNCTION)

LOCAL LRETORNO :=  .T. 
LOCAL NLOOP := 0
LOCAL NTOTREG := 0

LOCAL CALIAS := ALIAS()

LOCAL NTAMTOT := 0

LOCAL NPOSTEXT := 1
LOCAL NPOSFIELD := 2
LOCAL NPOSTYPE := 3
LOCAL NPOSSIZE := 4
LOCAL CSTRING := ""

ACABEC := IIF(ACABEC==NIL,{},ACABEC)

IF  LEN(ACABEC)==0
    CONOUT("**XMLADDPLAN: Nï¿½O FOI INFORMADO CORRETAMENTE O CABAï¿½ALHO PARA O XML!**")
    RETURN  .F. 
ENDIF

FOR NLOOP := 1 TO  LEN(ACABEC)
    NTAMTOT += ACABEC[NLOOP][NPOSSIZE]
NEXT

CSTRING := '    <SS:WORKSHEET SS:NAME="'+CWKSHEET+'">' + CRLF
CSTRING += "        <SS:TABLE>" + CRLF

FOR NLOOP := 1 TO  LEN(ACABEC)
    CSTRING += '            <SS:COLUMN SS:WIDTH="'+ ALLTRIM(STR(ACABEC[NLOOP][NPOSSIZE]))+'"/>' + CRLF
NEXT

IF !(EMPTY(CTITULO))
    CSTRING += "<SS:ROW>" + CRLF
    
    IF NSTYLECAB<>NIL .AND. VALTYPE(NSTYLECAB)=="N"
        CSTRING += '    	<SS:CELL SS:MERGEACROSS="'+ ALLTRIM(STR( LEN(ACABEC)-1))+'" SS:STYLEID="'+ ALLTRIM(STR(NSTYLECAB))+'"><SS:DATA SS:TYPE="STRING">'+CTITULO+"</SS:DATA></SS:CELL>" + CRLF
    ELSEIF NSTYLEID<>NIL .AND. VALTYPE(NSTYLEID)=="N"
        CSTRING += '    	<SS:CELL SS:MERGEACROSS="'+ ALLTRIM(STR( LEN(ACABEC)-1))+'" SS:STYLEID="'+ ALLTRIM(STR(NSTYLEID))+'"><SS:DATA SS:TYPE="STRING">'+CTITULO+"</SS:DATA></SS:CELL>" + CRLF
    ELSE 
        CSTRING += '    	<SS:CELL SS:MERGEACROSS="'+ ALLTRIM(STR( LEN(ACABEC)-1))+'"><SS:DATA SS:TYPE="STRING">'+CTITULO+"</SS:DATA></SS:CELL>" + CRLF
    ENDIF
    CSTRING += "</SS:ROW>" + CRLF
ENDIF

GRVARQ(CSTRING,@NHANDLE)

IF NSTYLEID<>NIL .AND. VALTYPE(NSTYLEID)=="N"
    CSTRING := '           <SS:ROW SS:STYLEID="'+ ALLTRIM(STR(NSTYLEID))+'">' + CRLF
ELSE 
    CSTRING := "            <SS:ROW>" + CRLF
ENDIF

FOR NLOOP := 1 TO  LEN(ACABEC)
    CSTRING += "                <SS:CELL>" + CRLF
    CSTRING += '                    <SS:DATA SS:TYPE="STRING">'+ACABEC[NLOOP][NPOSTEXT]+"</SS:DATA>" + CRLF
    CSTRING += "                </SS:CELL>" + CRLF
NEXT

CSTRING += "            </SS:ROW>" + CRLF

GRVARQ(CSTRING,@NHANDLE)

DBSELECTAREA(CALIAS)
(CALIAS)->(DBGOTOP())
(CALIAS)->(DBEVAL({||NTOTREG++},{||!(EOF())}))
(CALIAS)->(DBGOTOP())

IF NTOTREG==0

    CSTRING := "        </SS:TABLE>" + CRLF
    CSTRING += "    </SS:WORKSHEET>" + CRLF

    GRVARQ(CSTRING,@NHANDLE)

    RETURN NIL
ENDIF

OPROCESS:SETREGUA2(NTOTREG)

WHILE !((CALIAS)->(EOF()))
 
    OPROCESS:INCREGUA2("GERANDO PLANILHA... ("+CWKSHEET+")")

    IF BFUNCTION<>NIL
        EVAL(BFUNCTION)
    ENDIF

    CSTRING := "            <SS:ROW>" + CRLF
    FOR NLOOP := 1 TO  LEN(ACABEC)
        CSTRING += "                <SS:CELL>" + CRLF
        
        IF ACABEC[NLOOP][NPOSTYPE]=="C"
 CSTRING += '	                    <SS:DATA SS:TYPE="STRING">'+(CALIAS)->(&(ACABEC[NLOOP][NPOSFIELD]))+"</SS:DATA>" + CRLF
        ELSEIF ACABEC[NLOOP][NPOSTYPE]=="N"
            CSTRING += '	                    <SS:DATA SS:TYPE="NUMBER">'+ ALLTRIM(STR((CALIAS)->(&(ACABEC[NLOOP][NPOSFIELD]))))+"</SS:DATA>" + CRLF
        ELSEIF ACABEC[NLOOP][NPOSTYPE]=="D"
            CSTRING += '	                    <SS:DATA SS:TYPE="STRING">'+DTOC((CALIAS)->(&(ACABEC[NLOOP][NPOSFIELD])))+"</SS:DATA>" + CRLF
        ENDIF
        CSTRING += "                </SS:CELL>" + CRLF
    NEXT
    CSTRING += "            </SS:ROW>" + CRLF

    GRVARQ(CSTRING,@NHANDLE)

    (CALIAS)->(DBSKIP())
    ENDDO

CSTRING := "        </SS:TABLE>" + CRLF
CSTRING += "    </SS:WORKSHEET>" + CRLF

GRVARQ(CSTRING,@NHANDLE)

RETURN LRETORNO

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION XMLCLOSEFILE(CMSG)

LOCAL LRETORNO :=  .T. 

GRVARQ("</SS:WORKBOOK>",@NHANDLE, .T. )

MSGINFO(CMSG,)

RETURN LRETORNO

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION GRVARQ(CTEXT,NHDL,LCLOSE)

LOCAL CDIRDOCS := "\SYSTEM\"
LOCAL CBARRA := IIF(ISSRVUNIX(),"/","\")

LCLOSE := IIF(LCLOSE==NIL, .F. ,LCLOSE)

IF NHDL==0
    
    CARQUIVO := CARQUIVO+".XML"
    
    NHDL := FCREATE(CDIRDOCS+CBARRA+CARQUIVO)
    
    IF NHDL==- (1)
        MSGSTOP("NÃO FOI POSSÍVEL CRIAR O ARQUIVO .XML PARA SER UTILIZADO COM O EXCEL. VERIFIQUE AS PERMISSÕES.",)
        RETURN NIL
    ENDIF
ENDIF

FWRITE(NHDL,CTEXT)
CTEXT := ""

IF LCLOSE
    
    FCLOSE(NHDL)
ENDIF

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION X3XTIT(CCAMPO)

LOCAL AAREA := GETAREA()
LOCAL CRETORNO := ""

DBSELECTAREA("SX3")
DBSETORDER(2)
IF DBSEEK(CCAMPO, .F. )

    CRETORNO := GetSX3Cache(CCAMPO, "X3_TITULO")
ENDIF

RESTAREA(AAREA)
RETURN CRETORNO

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION RESUME1()

LOCAL AIND := {}
LOCAL NHANDLE := 0

PRIVATE CARQTRB4 := ""
PRIVATE CARQTRB5 := ""
PRIVATE CARQUIVO2 := CRIATRAB(, .F. )

IF SELECT("RESUME")>0
    DBSELECTAREA("RESUME")
    (RESUME)->(DBCLOSEAREA())
ENDIF

//CARQTRB4 := CRIATRAB(ACMPTMP, .T. )
//DBUSEAREA( .T. ,"DBFCDX",CARQTRB4,"RESUME", .T. , .F. )

//Cria a temporï¿½ria
oTempTable := FWTemporaryTable():New("RESUME")
 
 
//Define as colunas usadas
oTempTable:SetFields( ACMPTMP )



//Cria ï¿½ndice com colunas setadas anteriormente
oTempTable:AddIndex("1", {"FT_CFOP", "X5DESCRI","FT_CODBCC","FT_CSTPIS","FT_CSTCOF","FT_ALIQPIS","FT_ALIQCOF","A1_XORGPUB","LINHA","CFOP","DESCR.CFO","CST","ALIQ"} )


 
//Efetua a criaï¿½ï¿½o da tabela
oTempTable:Create()




//DBSELECTAREA("RESUME")
//
//AADD(AIND,{CRIATRAB(NIL, .F. ),"FT_CFOP+X5_DESCRI+FT_CODBCC+FT_CSTPIS+FT_CSTCOF+STR(FT_ALIQPIS,6,2)+STR(,FT_ALIQCOF,6,2)+A1_XORGPUB+LINHA","CFOP + DESCR.CFO + CST + ALIQ"})
//FOR NA := 1 TO  LEN(AIND)
//    INDREGUA("RESUME",AIND[NA][1],AIND[NA][2],,,OEMTOANSI("CRIANDO ï¿½NDICE TEMPORï¿½RIO..."))
//NEXT
//
//DBCLEARINDEX()

FOR NA := 1 TO  LEN(AIND)
    DBSETINDEX(AIND[NA][1]+ORDBAGEXT())
NEXT

DBSELECTAREA("TMPTRB")
DBGOTOP()
WHILE !(EOF())
 
 DBSELECTAREA("RESUME")
    
    IF DBSEEK((TMPTRB)->(FT_CFOP+X5DESCRI+FT_CODBCC+FT_CSTPIS+FT_CSTCOF)+STR(TMPTRB->FT_ALIQPIS,6,2)+STR(TMPTRB->FT_ALIQCOF,6,2)+TMPTRB->A1_XORGPUB+TMPTRB->LINHA)
        RECLOCK("RESUME", .F. )
    ELSE 
        RECLOCK("RESUME", .T. )
        RESUME->FT_CFOP := TMPTRB->FT_CFOP
        RESUME->X5DESCRI := TMPTRB->X5DESCRI
        RESUME->FT_CODBCC := TMPTRB->FT_CODBCC
        RESUME->FT_CSTPIS := TMPTRB->FT_CSTPIS
        RESUME->FT_CSTCOF := TMPTRB->FT_CSTCOF
        RESUME->FT_ALIQPIS := TMPTRB->FT_ALIQPIS
        RESUME->FT_ALIQCOF := TMPTRB->FT_ALIQCOF
        RESUME->A1_XORGPUB := TMPTRB->A1_XORGPUB
        RESUME->LINHA := TMPTRB->LINHA
    ENDIF
    RESUME->A2_NOME := POSICIONE("SA2",1,XFILIAL("SA2")+TMPTRB->FT_CLIEFOR+TMPTRB->FT_LOJA,"A2_NOME")
    
    RESUME->FT_VALCONT += TMPTRB->FT_VALCONT
    RESUME->E1_SALDO += TMPTRB->E1_SALDO
    RESUME->FT_TOTAL += TMPTRB->FT_TOTAL
    RESUME->FT_BASEPIS += TMPTRB->FT_BASEPIS
    RESUME->FT_BASECOF += TMPTRB->FT_BASECOF
    RESUME->FT_VALPIS += TMPTRB->FT_VALPIS
    RESUME->FT_VALCOF += TMPTRB->FT_VALCOF
    RESUME->FT_VALIPI += TMPTRB->FT_VALIPI
    
    RESUME->FT_ICMSRET += TMPTRB->FT_ICMSRET
    RESUME->FT_FRETE += TMPTRB->FT_FRETE
    RESUME->FT_SEGURO += TMPTRB->FT_SEGURO
    RESUME->FT_DESPESA += TMPTRB->FT_DESPESA
    RESUME->FT_DESCONT += TMPTRB->FT_DESCONT
    
    RESUME->FT_BASEICM += TMPTRB->FT_BASEICM
    RESUME->FT_VALICM += TMPTRB->FT_VALICM
    RESUME->FT_DIFAL += TMPTRB->FT_DIFAL
    RESUME->FT_VFCPDIF += TMPTRB->FT_VFCPDIF
    RESUME->FT_ICMSCOM += TMPTRB->FT_ICMSCOM
    
    RESUME->FT_ISENICM += TMPTRB->FT_ISENICM
    RESUME->FT_OUTRICM += TMPTRB->FT_OUTRICM
    
    (RESUME)->(MSUNLOCK())
    
    DBSELECTAREA("TMPTRB")
    DBSKIP()
    ENDDO

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION RESUME2()

LOCAL AIND := {}
LOCAL NHANDLE := 0

PRIVATE CARQTRB4 := ""
PRIVATE CARQTRB5 := ""
PRIVATE CARQUIVO2 := CRIATRAB(, .F. )

IF SELECT("RESUME")>0
    DBSELECTAREA("RESUME")
    (RESUME)->(DBCLOSEAREA())
ENDIF

/*CARQTRB4 := CRIATRAB(ACMPTMP, .T. )
DBUSEAREA( .T. ,"DBFCDX",CARQTRB4,"RESUME", .T. , .F. )*/
//Cria a temporï¿½ria
oTempTable := FWTemporaryTable():New("RESUME")
 
 
//Define as colunas usadas
oTempTable:SetFields( ACMPTMP )



//Cria ï¿½ndice com colunas setadas anteriormente
oTempTable:AddIndex("1", {"FT_CFOP", "X5DESCRI","FT_CODBCC","FT_CSTPIS","FT_CSTCOF","FT_ALIQPIS","FT_ALIQCOF","A1_XORGPUB","LINHA","FT_PRODUTO","D2_LOTECTL","CFOP","DESCR.CFO","CST","ALIQ"} )


 
//Efetua a criaï¿½ï¿½o da tabela
oTempTable:Create()

DBSELECTAREA("RESUME")

//AADD(AIND,{CRIATRAB(NIL, .F. ),"FT_CFOP+X5_DESCRI+FT_CODBCC+FT_CSTPIS+FT_CSTCOF+STR(FT_ALIQPIS,6,2)+STR(FT_ALIQCOF,6,2)+A1_XORGPUB+LINHA+FT_PRODUTO+D2_LOTECTL","CFOP + DESCR.CFO + CST + ALIQ"})
FOR NA := 1 TO  LEN(AIND)
    INDREGUA("RESUME",AIND[NA][1],AIND[NA][2],,,OEMTOANSI("CRIANDO ï¿½NDICE TEMPORï¿½RIO..."))
NEXT

DBCLEARINDEX()

FOR NA := 1 TO  LEN(AIND)
    DBSETINDEX(AIND[NA][1]+ORDBAGEXT())
NEXT

DBSELECTAREA("TMPTRB")
DBGOTOP()
WHILE !(EOF())
 
    DBSELECTAREA("RESUME")
    
    IF DBSEEK((TMPTRB)->(FT_CFOP+X5DESCRI+FT_CODBCC+FT_CSTPIS+FT_CSTCOF)+STR(TMPTRB->FT_ALIQPIS,6,2)+STR(TMPTRB->FT_ALIQCOF,6,2)+TMPTRB->A1_XORGPUB+TMPTRB->LINHA+TMPTRB->FT_PRODUTO+TMPTRB->D2_LOTECTL)
        RECLOCK("RESUME", .F. )
    ELSE 
        RECLOCK("RESUME", .T. )
        RESUME->FT_CFOP := TMPTRB->FT_CFOP
        RESUME->X5DESCRI := TMPTRB->X5DESCRI
        RESUME->FT_CODBCC := TMPTRB->FT_CODBCC
        RESUME->FT_CSTPIS := TMPTRB->FT_CSTPIS
        RESUME->FT_CSTCOF := TMPTRB->FT_CSTCOF
        RESUME->FT_ALIQPIS := TMPTRB->FT_ALIQPIS
        RESUME->FT_ALIQCOF := TMPTRB->FT_ALIQCOF
        RESUME->A1_XORGPUB := TMPTRB->A1_XORGPUB
        RESUME->LINHA := TMPTRB->LINHA
        RESUME->FT_PRODUTO := TMPTRB->FT_PRODUTO
        RESUME->D2_LOTECTL := TMPTRB->D2_LOTECTL
    ENDIF
    
    RESUME->A2_NOME := POSICIONE("SA2",1,XFILIAL("SA2")+TMPTRB->FT_CLIEFOR+TMPTRB->FT_LOJA,"A2_NOME")
    RESUME->FT_VALCONT += TMPTRB->FT_VALCONT
    RESUME->E1_SALDO += TMPTRB->E1_SALDO
    RESUME->FT_TOTAL += TMPTRB->FT_TOTAL
    RESUME->FT_BASEPIS += TMPTRB->FT_BASEPIS
    RESUME->FT_BASECOF += TMPTRB->FT_BASECOF
    RESUME->FT_VALPIS += TMPTRB->FT_VALPIS
    RESUME->FT_VALCOF += TMPTRB->FT_VALCOF
    RESUME->FT_VALIPI += TMPTRB->FT_VALIPI
    RESUME->FT_ICMSRET += TMPTRB->FT_ICMSRET
    RESUME->FT_FRETE += TMPTRB->FT_FRETE
    RESUME->FT_SEGURO += TMPTRB->FT_SEGURO
    RESUME->FT_DESPESA += TMPTRB->FT_DESPESA
    RESUME->FT_DESCONT += TMPTRB->FT_DESCONT
    
    RESUME->FT_BASEICM += TMPTRB->FT_BASEICM
    RESUME->FT_VALICM += TMPTRB->FT_VALICM
    RESUME->FT_DIFAL += TMPTRB->FT_DIFAL
    RESUME->FT_VFCPDIF += TMPTRB->FT_VFCPDIF
    RESUME->FT_ICMSCOM += TMPTRB->FT_ICMSCOM
    
    RESUME->FT_ISENICM += TMPTRB->FT_ISENICM
    RESUME->FT_OUTRICM += TMPTRB->FT_OUTRICM
    
    (RESUME)->(MSUNLOCK())
    
    DBSELECTAREA("TMPTRB")
    DBSKIP()
    ENDDO

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION RESUMEDIF()

LOCAL AIND := {}
LOCAL NHANDLE := 0

PRIVATE CARQTRB6 := ""
PRIVATE CARQTRB7 := ""
//PRIVATE CARQUIVO3 := CRIATRAB(, .F. )

IF SELECT("RESUMEDIF")>0
    DBSELECTAREA("RESUMEDIF")
    (RESUMEDIF)->(DBCLOSEAREA())
ENDIF

//CARQTRB6 := CRIATRAB(ACMPTMP, .T. )
//DBUSEAREA( .T. ,"DBFCDX",CARQTRB6,"RESUMEDIF", .T. , .F. )



//Cria a temporï¿½ria
oTempTable := FWTemporaryTable():New("RESUMEDIF")
 
 
//Define as colunas usadas
oTempTable:SetFields( ACMPTMP )



//Cria ï¿½ndice com colunas setadas anteriormente
oTempTable:AddIndex("1", {"A1_CGC", "FT_CSTPIS","FT_CSTCOF","FT_ALIQPIS","FT_ALIQCOF","A1_XORGPUB","LINHA","CGC","ALIQ"} )


 
//Efetua a criaï¿½ï¿½o da tabela
oTempTable:Create()





//DBSELECTAREA("RESUMEDIF")
//
//AADD(AIND,{CRIATRAB(NIL, .F. ),"A1_CGC+FT_CSTPIS+FT_CSTCOF+STR(FT_ALIQPIS,6,2)+STR(FT_ALIQCOF,6,2)+A1_XORGPUB+LINHA","CGC + ALIQ"})
//FOR NA := 1 TO  LEN(AIND)
//    INDREGUA("RESUMEDIF",AIND[NA][1],AIND[NA][2],,,OEMTOANSI("CRIANDO ï¿½NDICE TEMPORï¿½RIO..."))
//NEXT
//
//DBCLEARINDEX()

FOR NA := 1 TO  LEN(AIND)
    DBSETINDEX(AIND[NA][1]+ORDBAGEXT())
NEXT

DBSELECTAREA("TMPTRB")
DBGOTOP()
WHILE !(EOF())
 
    IF (!((TMPTRB->A1_XORGPUB) $ ("1/S"))) .OR. (!(( ALLTRIM(TMPTRB->LINHA)) $ ("FAT.CUM/FAT.NCUM")))
        DBSKIP()
        LOOP 
    ENDIF

    DBSELECTAREA("RESUMEDIF")
    
    IF DBSEEK((TMPTRB)->(A1_CGC+FT_CSTPIS+FT_CSTCOF)+STR(TMPTRB->FT_ALIQPIS,6,2)+STR(TMPTRB->FT_ALIQCOF,6,2)+TMPTRB->A1_XORGPUB+TMPTRB->LINHA)
        RECLOCK("RESUMEDIF", .F. )
    ELSE 
        RECLOCK("RESUMEDIF", .T. )
        RESUMEDIF->A1_CGC := TMPTRB->A1_CGC
        RESUMEDIF->FT_CSTPIS := TMPTRB->FT_CSTPIS
        RESUMEDIF->FT_CSTCOF := TMPTRB->FT_CSTCOF
        RESUMEDIF->FT_ALIQPIS := TMPTRB->FT_ALIQPIS
        RESUMEDIF->FT_ALIQCOF := TMPTRB->FT_ALIQCOF
        RESUMEDIF->A1_XORGPUB := TMPTRB->A1_XORGPUB
        RESUMEDIF->LINHA := TMPTRB->LINHA
    ENDIF

    RESUMEDIF->A2_NOME := POSICIONE("SA2",1,XFILIAL("SA2")+TMPTRB->FT_CLIEFOR+TMPTRB->FT_LOJA,"A2_NOME")
    RESUMEDIF->FT_VALCONT += TMPTRB->FT_VALCONT
    RESUMEDIF->E1_SALDO += TMPTRB->E1_SALDO
    RESUMEDIF->FT_VALPIS += (TMPTRB)->(((E1_SALDO) * (FT_ALIQPIS)) / (100))
    RESUMEDIF->FT_VALCOF += (TMPTRB)->(((E1_SALDO) * (FT_ALIQCOF)) / (100))
    RESUMEDIF->FT_VALIPI += TMPTRB->FT_VALIPI
    RESUMEDIF->FT_ICMSRET += TMPTRB->FT_ICMSRET
    RESUMEDIF->FT_FRETE += TMPTRB->FT_FRETE
    RESUMEDIF->FT_SEGURO += TMPTRB->FT_SEGURO
    RESUMEDIF->FT_DESPESA += TMPTRB->FT_DESPESA
    RESUMEDIF->FT_DESCONT += TMPTRB->FT_DESCONT

    RESUMEDIF->FT_BASEICM += TMPTRB->FT_BASEICM
    RESUMEDIF->FT_VALICM += TMPTRB->FT_VALICM
    RESUMEDIF->FT_DIFAL += TMPTRB->FT_DIFAL
    RESUMEDIF->FT_VFCPDIF += TMPTRB->FT_VFCPDIF
    RESUMEDIF->FT_ICMSCOM += TMPTRB->FT_ICMSCOM

    RESUMEDIF->FT_ISENICM += TMPTRB->FT_ISENICM
    RESUMEDIF->FT_OUTRICM += TMPTRB->FT_OUTRICM

    (RESUMEDIF)->(MSUNLOCK())

    DBSELECTAREA("TMPTRB")
    DBSKIP()
    ENDDO

DBSELECTAREA("RESUMEDIF")
DBGOTOP()
WHILE !(EOF())
 
    IF RESUMEDIF->E1_SALDO==0
        RECLOCK("RESUMEDIF")
        (RESUMEDIF)->(DBDELETE())
        MSUNLOCK()
    ENDIF

    DBSELECTAREA("RESUMEDIF")
    DBSKIP()
    ENDDO

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION SUBRETBX()

LOCAL AAREASE1 := SE1->(GETAREA())
LOCAL AAREA := GETAREA()
LOCAL NRET := 0

LOCAL CPREFIXO := SE1->E1_PREFIXO
LOCAL CNUMERO := SE1->E1_NUM
LOCAL CCLIENTE := SE1->E1_CLIENTE
LOCAL CLOJA := SE1->E1_LOJA
LOCAL NMOEDA := SE1->E1_MOEDA
LOCAL DDATA := MV_PAR02

DBSELECTAREA("SE1")
DBSETORDER(1)
IF DBSEEK(XFILIAL("SE1")+CPREFIXO+CNUMERO)

    WHILE !(EOF()) .AND. SE1->E1_FILIAL==XFILIAL("SE1") .AND. SE1->E1_PREFIXO==CPREFIXO .AND. SE1->E1_NUM==CNUMERO .AND. SE1->E1_CLIENTE==CCLIENTE .AND. SE1->E1_LOJA==CLOJA
    
        IF ((SE1->E1_TIPO) $ (MVPIABT)) .OR. (((SE1->E1_TIPO) $ (MVCFABT)) .OR. (((SE1->E1_TIPO) $ (MVCSABT)) .OR. (((SE1->E1_TIPO) $ (MVIRABT)) .OR. (((SE1->E1_TIPO) $ (MVINABT)) .OR. ((SE1->E1_TIPO) $ (MVISABT))))))
            
            IF SE1->E1_BAIXA<=DDATA
                NRET += XMOEDA(SE1->E1_VALOR,SE1->E1_MOEDA,NMOEDA,DDATA)
            ENDIF
        ENDIF

        DBSELECTAREA("SE1")
        DBSKIP()
        ENDDO
ENDIF

RESTAREA(AAREASE1)
RESTAREA(AAREA)

RETURN NRET

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION RESUMEBLP()

LOCAL AIND := {}
LOCAL NHANDLE := 0

PRIVATE CARQTRB6A := ""

IF SELECT("RESUMEBLP")>0
    DBSELECTAREA("RESUMEBLP")
    (RESUMEBLP)->(DBCLOSEAREA())
ENDIF

//CARQTRB6A := CRIATRAB(ACMPTMP, .T. )
//DBUSEAREA( .T. ,"DBFCDX",CARQTRB6A,"RESUMEBLP", .T. , .F. )


//Cria a temporï¿½ria
oTempTable := FWTemporaryTable():New("RESUME")
 
 
//Define as colunas usadas
oTempTable:SetFields( ACMPTMP )



//Cria ï¿½ndice com colunas setadas anteriormente
oTempTable:AddIndex("1", {"FT_FILIAL", "CG1_CODIGO","B1_POSIPI","FT_CFOP","CG1_ALIQ","D2_TES","COIGO","POSIPI","CFOP","TES"} )


 
//Efetua a criaï¿½ï¿½o da tabela
oTempTable:Create()




//
//DBSELECTAREA("RESUMEBLP")
//
//AADD(AIND,{CRIATRAB(NIL, .F. ),"FT_FILIAL+CG1_CODIGO+B1_POSIPI+FT_CFOP+STR(CG1_ALIQ,6,2)+D2_TES","COIGO+POSIPI+CFOP+TES"})
//FOR NA := 1 TO  LEN(AIND)
//    INDREGUA("RESUMEBLP",AIND[NA][1],AIND[NA][2],,,OEMTOANSI("CRIANDO ï¿½NDICE TEMPORï¿½RIO..."))
//NEXT
//
//DBCLEARINDEX()

FOR NA := 1 TO  LEN(AIND)
    DBSETINDEX(AIND[NA][1]+ORDBAGEXT())
NEXT

DBSELECTAREA("TMPTRB")
DBGOTOP()
WHILE !(EOF())
 
    DBSELECTAREA("RESUMEBLP")
    
    IF DBSEEK((TMPTRB)->(FT_FILIAL+CG1_CODIGO+B1_POSIPI+FT_CFOP)+STR(TMPTRB->CG1_ALIQ,6,2)+D2_TES)
        RECLOCK("RESUMEBLP", .F. )
    ELSE 
        RECLOCK("RESUMEBLP", .T. )
        RESUMEBLP->FT_FILIAL := TMPTRB->FT_FILIAL
        RESUMEBLP->CG1_CODIGO := TMPTRB->CG1_CODIGO
        RESUMEBLP->B1_POSIPI := TMPTRB->B1_POSIPI
        RESUMEBLP->FT_CFOP := TMPTRB->FT_CFOP
        RESUMEBLP->X5DESCRI := TMPTRB->X5DESCRI
        RESUMEBLP->D2_TES := TMPTRB->D2_TES
        RESUMEBLP->CG1_ALIQ := TMPTRB->CG1_ALIQ
    ENDIF
    
    RESUMEBLP->FT_VALCONT += TMPTRB->FT_VALCONT
    RESUMEBLP->FT_VALIPI += TMPTRB->FT_VALIPI
    RESUMEBLP->E1_SALDO += TMPTRB->FT_VALCONT-TMPTRB->FT_VALIPI
    
    MSUNLOCK()
    
    DBSELECTAREA("TMPTRB")
    DBSKIP()
    ENDDO

RETURN 
