#INCLUDE "protheus.ch"

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M04A04()

LOCAL ACORES := {}

LOCAL LINVERTE :=  .F. 

PRIVATE AINDEXSC2 := {}
PRIVATE CQUERYSC2 := ""
PRIVATE CFILMARKBSC2 := ""
PRIVATE BFILTRASC2
PRIVATE CCADASTRO := "REEMPENHO DAS ORDENS DE PRODUCAO"
PRIVATE CMARCA := GETMARK()

AROTINA := {{ANSITOOEM("PESQUISAR"),"AXPESQUI",0,1},{ANSITOOEM("VISUALIZAR"),"U_M04A04VIS()",0,2},{ANSITOOEM("ESTRUTURA"),"U_M04A04EST()",0,3},{ANSITOOEM("REEMPENHAR"),"U_M04A04EMP()",0,3},{ANSITOOEM("LEGENDA"),'BRWLEGENDA(CCADASTRO,"LEGENDA",{{"BR_VERDE","O.P. EM ABERTO"},{"BR_VERMELHO","O.P. PRODUZIDA OU ENCERRADA"}})',0,3}}

CQUERYSC2 := "C2_FILIAL = '"+XFILIAL("SC2")+"' "

CQUERYSC2 += "AND C2_QUANT > C2_QUJE AND EMPTY(C2_DATRF)"

CFILMARKBSC2 := "C2_FILIAL == '"+XFILIAL("SC2")+"'"

CFILMARKBSC2 += " .AND. C2_QUANT > C2_QUJE .AND. EMPTY(C2_DATRF)"

BFILTRASC2 := {|X|IIF(X==NIL,FILBROWSE("SC2",@AINDEXSC2,@CFILMARKBSC2),IIF(X==1,CFILMARKBSC2,CQUERYSC2))}
EVAL(BFILTRASC2)

AADD(ACORES,{"SC2->C2_QUJE == 0 .AND. EMPTY(SC2->C2_DATRF)","BR_VERDE"})
AADD(ACORES,{"SC2->C2_QUJE > 0 .AND. C2_QUANT > C2_QUJE .AND. EMPTY(SC2->C2_DATRF)","BR_AMARELO"})
AADD(ACORES,{"C2_QUANT <= C2_QUJE .OR. !EMPTY(SC2->C2_DATRF)","BR_VERMELHO"})

DBSELECTAREA("SC2")
DBSETORDER(1)

MARKBROW("SC2","C2_OK","C2_QUANT - C2_QUJE = 0",,@LINVERTE,@CMARCA)

DBSELECTAREA("SC2")
RETINDEX("SC2")
DBCLEARFILTER()
AEVAL(AINDEXSC2,{|X|FERASE(X[1]+ORDBAGEXT())})

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M04A04VIS()

LOCAL NOPCE := 2
LOCAL NOPCG := 2
LOCAL _LRET :=  .F. 
LOCAL _NI
Local nCont

PRIVATE COPCAO
PRIVATE AHEADER := {}
PRIVATE ACOLS := {}
PRIVATE ACPOENCHOICE := {}

DBSELECTAREA("SX3")
DBSETORDER(1)
DBSEEK("SC2")
WHILE !(EOF()) .AND. SX3->X3_ARQUIVO=="SC2"
 
    IF X3USO(X3_USADO) .AND. CNIVEL>=X3_NIVEL
        AADD(ACPOENCHOICE,SX3->X3_CAMPO)
    ENDIF
    DBSELECTAREA("SX3")
    DBSKIP()
    ENDDO

REGTOMEMORY("SC2",COPCAO=="VISUALIZAR")

//DBSELECTAREA("SX3")
//DBSEEK("SD4")
//WHILE !(EOF()) .AND. X3_ARQUIVO=="SD4"

_aCmp := FWSX3Util():GetAllFields( "SD4" , .T. )
		//While !Eof() .And. SX3->X3_ARQUIVO=="CNF"

For nCont := 1 to Len(_aCmp)

 
    IF X3USO(getsx3cache(_aCmp[nCont],"X3_USADO")) .AND. CNIVEL>=getsx3cache(_aCmp[nCont],"X3_NIVEL")

        AADD(AHEADER,{ RTRIM(getsx3cache(_aCmp[nCont],"X3_TITULO")),getsx3cache(_aCmp[nCont],"X3_CAMPO"),getsx3cache(_aCmp[nCont],"X3_PICTURE"),getsx3cache(_aCmp[nCont],"X3_TAMANHO"),getsx3cache(_aCmp[nCont],"X3_DECIMAL"),"ALLWAYSTRUE()",getsx3cache(_aCmp[nCont],"X3_USADO"),getsx3cache(_aCmp[nCont],"X3_TIPO"),getsx3cache(_aCmp[nCont],"X3_ARQUIVO"),getsx3cache(_aCmp[nCont],"X3_CONTEXT")})
        
        IF  ALLTRIM(getsx3cache(_aCmp[nCont],"X3_CAMPO"))=="D4_COD"

            AADD(AHEADER,{"DESCRICAO","B1_DESC","@!",50,0,"ALLWAYSTRUE()",getsx3cache(_aCmp[nCont],"X3_USADO"),"C","SB1",,getsx3cache(_aCmp[nCont],"X3_CONTEXT")})
        ENDIF
    ENDIF
//    DBSKIP()
//    ENDDO
next

ACOLS := {}
DBSELECTAREA("SD4")
DBSETORDER(2)
IF DBSEEK(XFILIAL("SD4")+SC2->C2_NUM+SC2->C2_ITEM+SC2->C2_SEQUEN+SC2->C2_ITEMGRD, .F. )
    WHILE !(EOF()) .AND. SD4->D4_FILIAL+SD4->D4_OP==XFILIAL("SD4")+SC2->C2_NUM+SC2->C2_ITEM+SC2->C2_SEQUEN+SC2->C2_ITEMGRD
    
        AADD(ACOLS,ARRAY( LEN(AHEADER)+1))
        FOR _NI := 1 TO  LEN(AHEADER)
            
            IF AHEADER[_NI][2]=="B1_DESC"
                ACOLS[ LEN(ACOLS)][_NI] := POSICIONE("SB1",1,XFILIAL("SB1")+SD4->D4_COD,"B1_DESC")
            ELSE 
                ACOLS[ LEN(ACOLS)][_NI] := FIELDGET(FIELDPOS(AHEADER[_NI][2]))
            ENDIF
        NEXT
        ACOLS[ LEN(ACOLS)][ LEN(AHEADER)+1] :=  .F. 
        DBSELECTAREA("SD4")
        DBSKIP()
        ENDDO
ELSE 

    IF  LEN(ACOLS)<=0
        ACOLS := {ARRAY( LEN(AHEADER)+1)}
        FOR _NI := 1 TO  LEN(AHEADER)
            ACOLS[1][_NI] := CRIAVAR(AHEADER[_NI][2])
        NEXT
        ACOLS[1][ LEN(AHEADER)+1] :=  .F. 
    ENDIF
ENDIF

CTITULO := "EMPENHOS DA O.P. "+SC2->C2_NUM+"-"+SC2->C2_ITEM+"-"+SC2->C2_SEQUEN
CALIASENCHOICE := "SC2"
CALIASGETD := "SD4"
CLINOK := "ALLWAYSTRUE()"
CTUDOK := "ALLWAYSTRUE()"
CFIELDOK := "ALLWAYSTRUE()"

_LRET := MODELO3(CTITULO,CALIASENCHOICE,CALIASGETD,ACPOENCHOICE,CLINOK,CTUDOK,NOPCE,NOPCG,CFIELDOK, .F. ,999,,1)

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M04A04EST()

PRIVATE LDBTREE :=  .F. 
PRIVATE CIND5 := ""
PRIVATE NOPCX := 2
PRIVATE L200AUTO :=  .F. 

DBSELECTAREA("SG1")
DBSETORDER(1)
DBSEEK(XFILIAL("SG1")+SC2->C2_PRODUTO)

PERGUNTE("MTA200", .F. )
A200PROC("SG1",SG1->(RECNO()),2)

DBSELECTAREA("SC2")

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M04A04EMP()

LOCAL LEND :=  .F. 
LOCAL NOPS := 0
LOCAL NI
LOCAL AFILIAL := {}
LOCAL ODLGLOG

PRIVATE ASAV650 := ARRAY(20)
PRIVATE LCONSTERC
PRIVATE LCONSNPT
PRIVATE LPROJ711 :=  .F. 
PRIVATE LMATA712 :=  .F. 
PRIVATE LPCPA107 :=  .F. 
PRIVATE LPCPA113 :=  .F. 
PRIVATE LGEROUOP :=  .T. 
PRIVATE L650AUTO :=  .F. 
PRIVATE LZRHEADER := IIF(L650AUTO, .T. , .F. )
PRIVATE AHEADER := {}
PRIVATE ACOLS := {}
PRIVATE AROTINA := {}

IF AVISO("ATENCAO !","DESEJA PROCESSAR O REEMPENHO DAS OP'S MARCADAS ?",{"SIM","NAO"})<>1
    RETURN 
ENDIF

DBSELECTAREA("SC2")
_CSELEC := "SELECT SC2.R_E_C_N_O_ AS REGISTRO"
_CQUERY := " FROM "
_CQUERY += RETSQLNAME("SC2")+" SC2 "
_CQUERY += " WHERE SC2.C2_FILIAL = '"+XFILIAL("SC2")+"'"
_CQUERY += "   AND SC2.C2_OK = '"+CMARCA+"'"
_CQUERY += "   AND SC2.D_E_L_E_T_ = ' '"
_CORDER := " ORDER BY SC2.C2_NUM, SC2.C2_ITEM, SC2.C2_SEQUEN"

IF SELECT("TRBSC2")>0
    DBSELECTAREA("TRBSC2")
    DBCLOSEAREA()
ENDIF

DBUSEAREA( .T. ,"TOPCONN",TCGENQRY(,,_CSELEC+_CQUERY+_CORDER),"TRBSC2", .F. , .T. )

DBSELECTAREA("TRBSC2")
DBGOTOP()
WHILE !(EOF())
 
    DBSELECTAREA("SC2")
    DBGOTO(TRBSC2->REGISTRO)

    IF AERRO := VALEXCLOP()[1]

        PROCESSA({||REEMPOP()},"PROCESSANDO O REEMPENHO DA O.P. "+SC2->C2_NUM+"-"+SC2->C2_ITEM+"-"+SC2->C2_SEQUEN+" ...")

        NOPS += 1

        DBSELECTAREA("SC2")
        RECLOCK("SC2", .F. )
        SC2->C2_OK := "  "
        SC2->C2_BATCH := ""
        SC2->C2_BATROT := FUNNAME()
        SC2->C2_BATUSR := ""
        MSUNLOCK()
    ENDIF

    AADD(ACOLS,{IIF(AERRO[1],"BR_VERDE","BR_VERMELHO"),SC2->C2_NUM+SC2->C2_ITEM+SC2->C2_SEQUEN+SC2->C2_ITEMGRD,AERRO[2], .F. })

    DBSELECTAREA("TRBSC2")
    DBSKIP()
    ENDDO

IF SELECT("TRBSC2")>0
    DBSELECTAREA("TRBSC2")
    DBCLOSEAREA()
ENDIF

IF NOPS>0

    AADD(AFILIAL,{CFILANT,0,XFILIAL("SC2")})
    PERGUNTE("MTA650", .F. )
    FOR NI := 1 TO 20
        ASAV650[NI] := &("MV_PAR"+ STRZERO(NI,2))
    NEXT
    LCONSNPT := ASAV650[14]==1
    LCONSTERC := !(ASAV650[15]==1)

    PROCESSA({|LEND|MA650PROCESS(@LEND,NOPS)},"GERAÇÃO DE OPS INTERMEDIARIAS E SCS",OEMTOANSI("GERANDO OPS INTERMEDIARIAS E SCS..."), .F. )
    LGEROUOP :=  .F. 
ENDIF

IF  LEN(ACOLS)>0

    DBSELECTAREA("SC2")
    DBSETORDER(1)

    AHEADER := {}
    AADD(AHEADER,{"","LEGENDA","@BMP",1,0,".F.","???????????????","C","TRB"})
    AADD(AHEADER,{"OP","OP","@!",TAMSX3("D4_OP")[1],0,".F.","???????????????","N","TRB"})
    AADD(AHEADER,{"OCORRENCIA","OCORR","@!",100,0,".F.","???????????????","C","TRB"})

    ODLGLOG := MSDIALOG():NEW(150,1,720,1220,OEMTOANSI("RESUMO PROCESSAMENTO"),,,,,,,,, .T. ,,,)

    OLINHAS := IW_MULTILINE(10,10,255,600, .F. , .F. ,,)

    SBUTTON():NEW(265,570,1,{||ODLGLOG:END()},,)

    ODLGLOG:ACTIVATE( .T. ,)
ENDIF

DBSELECTAREA("SC2")
RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION VALEXCLOP()

LOCAL LOK :=  .T. 
LOCAL CERROR := ""
LOCAL AAREA := GETAREA()
LOCAL AAREASD4 := SD4->(GETAREA())

DBSELECTAREA("SD4")
DBSETORDER(2)
DBSEEK(XFILIAL("SD4")+SC2->C2_NUM+SC2->C2_ITEM+SC2->C2_SEQUEN+SC2->C2_ITEMGRD)
WHILE !(EOF()) .AND. SD4->D4_FILIAL+SD4->D4_OP==XFILIAL("SD4")+SC2->C2_NUM+SC2->C2_ITEM+SC2->C2_SEQUEN+SC2->C2_ITEMGRD
 
    IF SD4->D4_QTDEORI<>SD4->D4_QUANT

        LOK :=  .F. 
        CERROR := "EXISTE REQUISIÇÃO APONTADAS PARA A OP !("+SC2->C2_NUM+SC2->C2_ITEM+SC2->C2_SEQUEN+SC2->C2_ITEMGRD+")"

    ELSEIF !(EMPTY(SD4->D4_OPORIG))

        DBSELECTAREA("SC2")
        DBSETORDER(1)
        
        IF DBSEEK(XFILIAL("SC2")+SD4->D4_OPORIG)

            IF (!(EMPTY(SC2->C2_DATRF))) .OR. (SC2->C2_QUJE<>0)

                LOK :=  .F. 
                CERROR := "EXISTEM OP INTERMEDIARIA APONTADAS PARCIALMENTE !("+SD4->D4_OPORIG+")"
            ELSE 

    ARET := VALEXCLOP()
                LOK := ARET[1]
                CERROR := ARET[2]
            ENDIF
        ENDIF
    ENDIF

    IF !(LOK)
        EXIT 
    ENDIF

    DBSELECTAREA("SD4")
    DBSKIP()
    ENDDO

DBSELECTAREA("SC2")

RESTAREA(AAREASD4)
RESTAREA(AAREA)

RETURN {LOK,CERROR}

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION REEMPOP()

LOCAL ASAVAREA := GETAREA()
LOCAL ASAVDC := SDC->(GETAREA())
LOCAL ASAVD4 := SD4->(GETAREA())
LOCAL ASAVB1 := SB1->(GETAREA())
LOCAL ASAVC2 := SC2->(GETAREA())
LOCAL NTOTREGS := 0

DBSELECTAREA("SD4")
_CSELEC := "SELECT SD4.R_E_C_N_O_ AS REGISTRO, SD4.D4_COD "
_CCOUNT := "SELECT COUNT(*) AS TOTREGS "
_CQUERY := " FROM "
_CQUERY += RETSQLNAME("SD4")+" SD4 "
_CQUERY += " WHERE SD4.D4_FILIAL = '"+XFILIAL("SD4")+"' "
_CQUERY += "   AND SD4.D4_OP = '"+SC2->C2_NUM+SC2->C2_ITEM+SC2->C2_SEQUEN+"' "
_CQUERY += "   AND SD4.D4_LOTECTL = '' "
_CQUERY += "   AND ( SD4.D4_QUANT > 0 OR SD4.D4_QUANT = 0 ) "
_CQUERY += "   AND SD4.D_E_L_E_T_ = ' ' "
_CORDER := " ORDER BY SD4.D4_COD"

IF SELECT("TRB")>0
    DBSELECTAREA("TRB")
    DBCLOSEAREA()
ENDIF

DBUSEAREA( .T. ,"TOPCONN",TCGENQRY(,,_CCOUNT+_CQUERY),"TRB", .F. , .T. )

NTOTREGS := TRB->TOTREGS

IF SELECT("TRB")>0
    DBSELECTAREA("TRB")
    DBCLOSEAREA()
ENDIF

DBUSEAREA( .T. ,"TOPCONN",TCGENQRY(,,_CSELEC+_CQUERY+_CORDER),"TRB", .F. , .T. )

DBSELECTAREA("TRB")
DBGOTOP()
PROCREGUA(NTOTREGS)
WHILE !(EOF())
 
    INCPROC("REEMPENHANDO PRODUTO "+ ALLTRIM(SD4->D4_COD)+" ...")

    DBSELECTAREA("SD4")
    DBGOTO(TRB->REGISTRO)

    IF SB2->(DBSEEK(XFILIAL("SB2")+SD4->D4_COD+SD4->D4_LOCAL)) .AND. SD4->D4_QUANT>0

        GRAVAB2EMP("-",SD4->D4_QUANT,"F")
    ENDIF

    RECLOCK("SD4", .F. )
    DBDELETE()
    MSUNLOCK()

    IF !(EMPTY(SD4->D4_OPORIG))

        DBSELECTAREA("SC2")
        DBSETORDER(1)
        
        IF DBSEEK(XFILIAL("SC2")+SD4->D4_OPORIG)

  EXCLUIOP()
        ENDIF
    ENDIF

    DBSELECTAREA("TRB")
    DBSKIP()
    ENDDO

IF SELECT("TRB")>0
    DBSELECTAREA("TRB")
    DBCLOSEAREA()
ENDIF

RESTAREA(ASAVAREA)
RESTAREA(ASAVDC)
RESTAREA(ASAVD4)
RESTAREA(ASAVB1)
RESTAREA(ASAVC2)

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION GERAEMPENHO()

LOCAL CPRODUTO := ""
LOCAL NPROC

AESTRUTURA := {}
BUSCAESTRU(SC2->C2_PRODUTO,1)

AESTRUTURA := ASORT(AESTRUTURA,,,{ |X,Y|Y[1]>X[1]})

CPRODANT := ""
CTRT := ""
FOR NPROC := 1 TO  LEN(AESTRUTURA)

    CPRODUTO := AESTRUTURA[NPROC][1]
    NQTD := AESTRUTURA[NPROC][2]

    IF CPRODANT==CPRODUTO
        CTRT := IIF(EMPTY(CTRT),"001", STRZERO( VAL(CTRT)+1,3))
    ENDIF

    DBSELECTAREA("SB1")
    DBSETORDER(1)
    DBSEEK(XFILIAL("SB1")+CPRODUTO)

    DBSELECTAREA("SD4")
    RECLOCK("SD4", .T. )
    SD4->D4_FILIAL := XFILIAL("SD4")
    SD4->D4_COD := CPRODUTO
    SD4->D4_LOCAL := "99"
    SD4->D4_OP := SC2->C2_NUM+SC2->C2_ITEM+SC2->C2_SEQUEN
   SD4->D4_DATA := SC2->C2_EMISSAO

    NQTD := (NQTD) * (SC2->C2_QUANT)
    SD4->D4_QUANT := NQTD
    SD4->D4_QTDEORI := NQTD
    SD4->D4_TRT := CTRT
    SD4->D4_PRODUTO := SC2->C2_PRODUTO
    MSUNLOCK()

    CRIASB2(SB1->B1_COD,SB1->B1_LOCPAD)

    CPRODANT := CPRODUTO
NEXT

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION BUSCAESTRU(CPRODUTO,NQTDBASE)

LOCAL AAREA := GETAREA()
LOCAL NRECSG1 := 0

DBSELECTAREA("SG1")
DBSETORDER(1)
DBSEEK(XFILIAL("SG1")+CPRODUTO)
WHILE !(EOF()) .AND. SG1->G1_FILIAL+SG1->G1_COD==XFILIAL("SG1")+CPRODUTO
 
    NQUANT := ((SG1->G1_QUANT) / (100-SG1->G1_PERDA)) * (100)
    NQUANT := (NQUANT) * (NQTDBASE)

    AADD(AESTRUTURA,{SG1->G1_COMP,NQUANT,CNIVEL})

    NRECSG1 := SG1->(RECNO())
    CCOMP := SG1->G1_COMP
    
    IF DBSEEK(XFILIAL("SG1")+CCOMP)
        BUSCAESTRU(CCOMP,NQUANT)
    ENDIF
    DBGOTO(NRECSG1)

    DBSELECTAREA("SG1")
    DBSKIP()
    ENDDO

RESTAREA(AAREA)

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M04A04DEL()

LOCAL CQUERY := ""

IF ( .F. ) 
 CALLPROC("RPCSETENV","01","01",,,"PCP",,{"SC2"})
 ELSE
 RPCSETENV("01","01",,,"PCP",,{"SC2"})
 ENDIF

DBSELECTAREA("SD4")

CQUERY := "SELECT SC2.R_E_C_N_O_ RECSC2 "
CQUERY += "FROM "+RETSQLNAME("SC2")+" SC2 "
CQUERY += "INNER JOIN "+RETSQLNAME("SD4")+" SD4 ON D4_FILIAL = C2_FILIAL AND D4_OPORIG = C2_NUM+C2_ITEM+C2_SEQUEN+C2_GRADE AND SD4.D_E_L_E_T_ = '*' AND D4_OPORIG <> ' ' "
CQUERY += "WHERE SC2.D_E_L_E_T_ = ' ' "
CQUERY += "AND C2_QUJE = 0 "
CQUERY += "AND C2_DATRF = ' ' "
CQUERY += "AND C2_SEQPAI <> ' ' "

IF SELECT("TRB")>0
    DBSELECTAREA("TRB")
    DBCLOSEAREA()
ENDIF

DBUSEAREA( .T. ,"TOPCONN",TCGENQRY(,,CQUERY),"TRB", .F. , .T. )

DBSELECTAREA("TRB")
DBGOTOP()

WHILE !(EOF())
 
    DBSELECTAREA("SC2")
    DBGOTO(TRB->RECSC2)

    IF !(EOF())

        IF VALEXCLOP()[1]

            EXCLUIOP()
        ENDIF
    ENDIF

    DBSELECTAREA("TRB")
    DBSKIP()
    ENDDO

IF SELECT("TRB")>0
    DBSELECTAREA("TRB")
    DBCLOSEAREA()
ENDIF

IF ( .F. ) 
 CALLPROC("RPCCLEARENV")
 ELSE
 RPCCLEARENV()
 ENDIF

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION EXCLUIOP()

LOCAL ASAVAREA := GETAREA()
LOCAL LRET :=  .T. 
LOCAL AESTA650 := {}
LOCAL I

AADD(AESTA650,{{"C2_NUM",SC2->C2_NUM,NIL},{"C2_ITEM",SC2->C2_ITEM,NIL},{"C2_SEQUEN",SC2->C2_SEQUEN,NIL},{"C2_PRODUTO",SC2->C2_PRODUTO,NIL},{"C2_LOCAL",SC2->C2_LOCAL,NIL},{"C2_QUANT",SC2->C2_QUANT,NIL},{"C2_UM",SC2->C2_UM,NIL},{"C2_DATPRI",SC2->C2_DATPRI,NIL},{"C2_DATPRF",SC2->C2_DATPRF,NIL},{"C2_EMISSAO",SC2->C2_EMISSAO,NIL},{"C2_PRIOR",SC2->C2_PRIOR,NIL},{"C2_TPOP",SC2->C2_TPOP,NIL},{"C2_CC",SC2->C2_CC,NIL},{"C2_REVISAO",SC2->C2_REVISAO,NIL},{"C2_ITEMCTA",SC2->C2_ITEMCTA,NIL},{"C2_CLVL",SC2->C2_CLVL,NIL},{"C2_SEQMRP",SC2->C2_SEQMRP,NIL},{"C2_LINHA",SC2->C2_LINHA,NIL},{"C2_MOPC",SC2->C2_MOPC,NIL},{"C2_PMACNUT",SC2->C2_PMACNUT,NIL},{"C2_PMICNUT",SC2->C2_PMICNUT,NIL},{"C2_OBS",SC2->C2_OBS,NIL},{"C2_STATUS",SC2->C2_STATUS,NIL},{"C2_SEGUM",SC2->C2_SEGUM,NIL},{"C2_OPC",SC2->C2_OPC,NIL},{"C2_QTSEGUM",SC2->C2_QTSEGUM,NIL},{"C2_BATORCA","N",NIL},{"C2_PERDA",SC2->C2_PERDA,NIL}})

FOR I := 1 TO  LEN(AESTA650)
    LMSERROAUTO :=  .F. 
    LMSHELPAUTO :=  .T. 
    AAREASC2 := SC2->(GETAREA())
    MSEXECAUTO({|X,Y|MATA650(X,Y)},AESTA650[I],5)
    RESTAREA(AAREASC2)
    LMSHELPAUTO :=  .F. 
    
    IF LMSERROAUTO
        
        LRET :=  .F. 
    ENDIF
NEXT

RESTAREA(ASAVAREA)

RETURN LRET
