#INCLUDE "protheus.ch"

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M04M08()

LOCAL ACORES := {{"B1_MSBLQL == '1'","BR_VERMELHO"},{"B1_MSBLQL = '2'","BR_VERDE"}}

PRIVATE AROTINA := {}
PRIVATE CSTRING := "SB1"
PRIVATE CDELFUNC := ".T."

PRIVATE ALEGENDA := {{"BR_VERDE","ATIVO"},{"BR_VERMELHO","BLOQUEADO"}}

PRIVATE CCADASTRO := OEMTOANSI("ALTERAÇÃO DE UNIDADE DE MEDIDA")

AADD(AROTINA,{"PESQUISAR","AXPESQUI",0,1})
AADD(AROTINA,{"VISUALIZAR","AXVISUAL",0,2})
AADD(AROTINA,{"ALTERA UM","U_M04A08ALT()",0,4})
AADD(AROTINA,{"LEGENDA","U_M04A08LEG()",0,4})

DBSELECTAREA(CSTRING)
DBSETORDER(1)
MBROWSE(,,,,CSTRING,,,,,,ACORES)

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M04A08ALT()

LOCAL AAREA := GETAREA()

LOCAL APOSOBJ := {}
LOCAL AOBJECTS := {}
LOCAL ASIZE := MSADVSIZE()
LOCAL ODLGMAIN := NIL
LOCAL NOPCA := 0
LOCAL ABUTTONS := {}
LOCAL OFLDPED := NIL
LOCAL OFLDESTR := NIL
LOCAL CLISTBOX := ""
LOCAL CLBOXSLD := ""

LOCAL ATITULO := {"","PRODUTO","TIPO","DESCRICAO","UNID.ATU","UNID.NOVA","2UNID.NOVA","FATOR","TP.CONV","FATOR CONV.ESTR.","TP.CONV.EST","QTD.ESTR."}
LOCAL ATITESTR := {"","COMPONENTE","PROD.PAI","FATOR","QTD.","QTD.NOVA","TP.CONV.EST"}

PRIVATE OOK := LOADBITMAP(GETRESOURCES(),"LBOK")
PRIVATE ONO := LOADBITMAP(GETRESOURCES(),"LBNO")
PRIVATE OVERMELHO := LOADBITMAP(GETRESOURCES(),"BR_VERMELHO")
PRIVATE OVERDE := LOADBITMAP(GETRESOURCES(),"BR_VERDE")
PRIVATE OLISTBOX := NIL
PRIVATE OLBOXESTR := NIL

PRIVATE ADADOS := {}
PRIVATE AESTRUC := {}
PRIVATE AORDEM := {3,7,4,5}

CTYPE := "ARQUIVOS NAO PROCESSADOS | *.CSV | ARQUIVOS JA PROCESSADOS | *.PRC "

CARQ := CGETFILE(CTYPE,OEMTOANSI("SELECIONE O ARQUIVO DE INTERFACE"),1,"", .F. ,48+0)

IF !(FILE(CARQ))
    AVISO("ATENÇÃO !","ARQUIVO SELECIONADO NAO LOCALIZADO !",{"OK"})
    RETURN 
ENDIF

PROCESSA({||U_M04M08I(CARQ)},"PROCESSANDO LEITURA...")

AADD(ABUTTONS,{"PESQUISA",{||PESQPED()},"PESQUISAR",OEMTOANSI("PESQUISAR")})
AADD(ABUTTONS,{"PENDENTE",{||MARCAPED( .T. , .T. )},"MARC.TODOS [F4]",OEMTOANSI("MAR.TOD.")})
AADD(ABUTTONS,{"LBNO",{||MARCAPED( .F. , .F. )},"DESM.TODOS [F5]",OEMTOANSI("DES.TOD.")})

SETKEY(115,{|A,B|MARCAPED( .T. , .T. )})
SETKEY(116,{|A,B|MARCAPED( .F. , .F. )})

AOBJECTS := {}

AADD(AOBJECTS,{80,80, .T. , .T. })
AADD(AOBJECTS,{100,80, .T. , .T. })

AADD(AOBJECTS,{20,20, .T. , .F. })

AINFO := {ASIZE[1],ASIZE[2],ASIZE[3],ASIZE[4],3,3}
APOSOBJ := MSOBJSIZE(AINFO,AOBJECTS)

ODLGMAIN := TDIALOG():NEW(ASIZE[7],0,ASIZE[6],ASIZE[5],OEMTOANSI("ALTERA UNIDADE DE MEDIDA"),,,,,,,,OMAINWND, .T. )

OFLDPED := TFOLDER():NEW(APOSOBJ[1][1],APOSOBJ[1][2],{OEMTOANSI("PRODUTOS")},{},ODLGMAIN,,,, .T. , .T. ,APOSOBJ[1][4]-APOSOBJ[1][2],APOSOBJ[1][3]-APOSOBJ[1][1])

OFLDESTR := TFOLDER():NEW(APOSOBJ[2][1],APOSOBJ[2][2],{OEMTOANSI("ESTRUTURAS")},{},ODLGMAIN,,,, .T. , .T. ,APOSOBJ[2][4]-APOSOBJ[2][2],APOSOBJ[2][3]-APOSOBJ[2][1]+10)

OLISTBOX:=VAR:=CLISTBOX:=TWBROWSE():NEW(0,0,(OFLDPED:ADIALOGS[1]:NCLIENTWIDTH) / (2),(OFLDPED:ADIALOGS[1]:NCLIENTHEIGHT) / (2),,{ATITULO[1],ATITULO[2],ATITULO[3],ATITULO[4],ATITULO[5],ATITULO[6],ATITULO[7],ATITULO[8],ATITULO[9],ATITULO[10],ATITULO[11],ATITULO[12]},,OFLDPED:ADIALOGS[1],,,,,{|NROW,NCOL,NFLAGS|MARCAITEM()},,,,,,, .F. ,, .T. ,, .F. ,,,)

OLISTBOX:SETARRAY(ADADOS)

OLISTBOX:BLINE := {||{IIF(ADADOS[OLISTBOX:NAT][1],OOK,ONO),ADADOS[OLISTBOX:NAT][2],ADADOS[OLISTBOX:NAT][3],ADADOS[OLISTBOX:NAT][4],ADADOS[OLISTBOX:NAT][5],ADADOS[OLISTBOX:NAT][6],ADADOS[OLISTBOX:NAT][7],TRANSFORM(ADADOS[OLISTBOX:NAT][8],"@E 99,999.9999"),ADADOS[OLISTBOX:NAT][9],TRANSFORM(ADADOS[OLISTBOX:NAT][10],"@E 99,999.9999"),ADADOS[OLISTBOX:NAT][11],TRANSFORM(ADADOS[OLISTBOX:NAT][12],"@E 9,999,999")}}

OLISTBOX:BCHANGE := {||POSICESTRU()}

OLBOXESTR:=VAR:=CLBOXSLD:=TWBROWSE():NEW(0,0,(OFLDESTR:ADIALOGS[1]:NCLIENTWIDTH) / (2),(OFLDESTR:ADIALOGS[1]:NCLIENTHEIGHT) / (2),,{ATITESTR[1],ATITESTR[2],ATITESTR[3],ATITESTR[4],ATITESTR[5],ATITESTR[6],ATITESTR[7]},,OFLDESTR:ADIALOGS[1],,,,,,,,,,,, .F. ,, .T. ,, .F. ,,,)
OLBOXESTR:SETARRAY(AESTRUC)

OLBOXESTR:BLINE := {||{AESTRUC[OLBOXESTR:NAT][1],AESTRUC[OLBOXESTR:NAT][2],AESTRUC[OLBOXESTR:NAT][3],TRANSFORM(AESTRUC[OLBOXESTR:NAT][4],"@E 99,999.9999"),TRANSFORM(AESTRUC[OLBOXESTR:NAT][5],"@E 9,999,999.9999"),TRANSFORM(AESTRUC[OLBOXESTR:NAT][6],"@E 9,999,999.9999"),AESTRUC[OLBOXESTR:NAT][7]}}

ODLGMAIN:ACTIVATE({||ENCHOICEBAR(ODLGMAIN,{||IIF( .T. ,(NOPCA := 1, ODLGMAIN:END()),)},{||NOPCA := 0, ODLGMAIN:END()},,ABUTTONS)})

SETKEY(113,NIL)
SETKEY(114,NIL)
SETKEY(115,NIL)
SETKEY(116,NIL)
SETKEY(117,NIL)
SETKEY(118,NIL)
SETKEY(119,NIL)

IF NOPCA==1
    GRAVAALT()
ENDIF

RESTAREA(AAREA)

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MARCAITEM()

ADADOS[OLISTBOX:NAT][1] := !(ADADOS[OLISTBOX:NAT][1])

OLISTBOX:REFRESH()
OLBOXESTR:REFRESH()

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MARCAPED(LMARCAPV,LTODOS)

LOCAL NLOOP := 0

FOR NLOOP := 1 TO  LEN(ADADOS)

    IF LTODOS
        ADADOS[NLOOP][1] :=  .T. 
    ELSE 
        ADADOS[NLOOP][1] :=  .F. 
    ENDIF
NEXT

OLISTBOX:REFRESH()
OLBOXESTR:REFRESH()

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION POSICESTRU()

NPOSSLD := ASCAN(AESTRUC,{|X| ALLTRIM(X[2])== ALLTRIM(ADADOS[OLISTBOX:NAT][2])})
IF NPOSSLD>0
    OLBOXESTR:NAT := NPOSSLD
ENDIF
OLBOXESTR:REFRESH()

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION PESQPED()

LOCAL CCAMPO := "                                        "
LOCAL AITENS := {}
LOCAL ACHAVE := {}
LOCAL CCOMBO := ""
LOCAL LSEEK :=  .F. 

LOCAL NPOSARR := 0
LOCAL NORD := 1

AADD(AITENS,"PRODUTO")
AADD(ACHAVE,{1})

ODLG := MSDIALOG():NEW(0,0,100,490,"PESQUISA",,, .F. ,,,,,, .T. ,,, .F. )

OCBX := TCOMBOBOX():NEW(5,5,{ | U |IIF(PCOUNT()==0,CCOMBO,CCOMBO := U)},AITENS,206,36,ODLG,,,,,, .T. ,ODLG:OFONT,, .F. ,, .F. ,,,,"CCOMBO")
OCBX:BCHANGE := {||NORD := OCBX:NAT, CCAMPO := "                                        "}

OPESQGET := TGET():NEW(22,5,{ | U |IIF(PCOUNT()==0,CCAMPO,CCAMPO := U)},,206,10,,,,,, .F. ,, .T. ,, .F. ,, .F. , .F. ,, .F. , .F. ,,"CCAMPO",,,,)

SBUTTON():NEW(5,215,1,{||LSEEK :=  .T. , ODLG:END()},ODLG, .T. ,,)
SBUTTON():NEW(20,215,2,{||ODLG:END()},ODLG, .T. ,,)

ODLG:ACTIVATE(ODLG:BLCLICKED,ODLG:BMOVED,ODLG:BPAINTED, .T. ,,,,ODLG:BRCLICKED,)

IF LSEEK

    AORDEM := {ACHAVE[NORD][1],ACHAVE[NORD][2],ACHAVE[NORD][3],ACHAVE[NORD][4]}

    ADADOS := ASORT(ADADOS,,,{ |X,Y|X[ACHAVE[NORD][1]]+X[ACHAVE[NORD][2]]+X[ACHAVE[NORD][3]]+X[ACHAVE[NORD][4]]<Y[ACHAVE[NORD][1]]+Y[ACHAVE[NORD][2]]+Y[ACHAVE[NORD][3]]+Y[ACHAVE[NORD][4]]})
    
    IF !(EMPTY(CCAMPO))
        NPOSARR := ASCAN(ADADOS,{|X| ALLTRIM( UPPER( SUBSTR(X[ACHAVE[NORD][1]]+X[ACHAVE[NORD][2]]+X[ACHAVE[NORD][3]]+X[ACHAVE[NORD][4]],1, LEN( ALLTRIM(CCAMPO)))))== ALLTRIM( UPPER(CCAMPO))})
        
        IF NPOSARR==0
            AVISO("AVISO","ITEM NÃO LOCALIZADO. INFORME OUTRA CHAVE DE BUSCA",{"OK"},,"ATENÇÃO:")
        ELSE 
            OLISTBOX:NAT := NPOSARR
        ENDIF
    ENDIF
    OLISTBOX:REFRESH()
ENDIF

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
//STATIC FUNCTION CRIASX1(AREGS)
//
//LOCAL AAREAATU := GETAREA()
//LOCAL AAREASX1 := SX1->(GETAREA())
//LOCAL NJ := 0
//LOCAL NY := 0
//
//DBSELECTAREA("SX1")
//DBSETORDER(1)
//
//FOR NY := 1 TO  LEN(AREGS)
//    
//    IF !(MSSEEK(AREGS[NY][1]+AREGS[NY][2]))
//        RECLOCK("SX1", .T. )
//        FOR NJ := 1 TO FCOUNT()
//            
//            IF NJ<= LEN(AREGS[NY])
//                FIELDPUT(NJ,AREGS[NY][NJ])
//            ENDIF
//        NEXT
//        MSUNLOCK()
//    ENDIF
//NEXT
//
//RESTAREA(AAREASX1)
//RESTAREA(AAREAATU)
//
//RETURN NIL

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION GRAVAALT()

LOCAL NLOOP := 0
LOCAL NQTDGRAV := 0
LOCAL NPROC1
LOCAL NPOSSG1

FOR NLOOP := 1 TO  LEN(ADADOS)
    
    IF !(ADADOS[NLOOP][1])
        LOOP 
    ENDIF
    
    NPOSSG1 := ASCAN(AESTRUC,{|X| ALLTRIM(X[2])== ALLTRIM(ADADOS[NLOOP][2])})
    
    IF NPOSSG1<>0
        
        FOR NPROC1 := NPOSSG1 TO  LEN(AESTRUC)
            
            IF  ALLTRIM(AESTRUC[NPROC1][2])<> ALLTRIM(ADADOS[NLOOP][2])
                EXIT 
            ENDIF
            
            SG1->(DBGOTO(AESTRUC[NPROC1][8]))
            RECLOCK("SG1", .F. )
            SG1->G1_QUANT := AESTRUC[NPROC1][6]
            MSUNLOCK()
            
            NQTDGRAV++
        NEXT
        
        SB1->(DBGOTO(ADADOS[NLOOP][13]))
        RECLOCK("SB1", .F. )
        SB1->B1_UM := ADADOS[NLOOP][6]
        SB1->B1_SEGUM := ADADOS[NLOOP][7]
        SB1->B1_CONV := ADADOS[NLOOP][8]
        SB1->B1_TIPCONV := ADADOS[NLOOP][9]
        MSUNLOCK()
    ENDIF
NEXT

IF NQTDGRAV==0
    AVISO("INCONSISTÊNCIA","PRODUTOS E ESTRUTURAS NÃO FORAM ALTERADOS ",{"OK"},3,"ATENÇÃO:")
ELSE 
    AVISO("OK","PRODUTOS E ESTRUTURAS ALTERADAS : "+ STRZERO(NQTDGRAV,4),{"OK"},3,"ATENÇÃO:")
ENDIF

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M04A08LEG()

BRWLEGENDA(CCADASTRO,"LEGENDA",ALEGENDA)

RETURN  .T. 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION MARCAITEST()

ADADOS[OLISTBOX:NAT][1] := !(ADADOS[OLISTBOX:NAT][1])

OLISTBOX:REFRESH()

RETURN 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION M04M08I(CARQ)

LOCAL LCONTINUA :=  .T. 
LOCAL NPROC
LOCAL CCODPROD := ""
PRIVATE NHDL := 0
PRIVATE ASTRUCT := {}
PRIVATE ALOG := {}

NHDL := FT_FUSE(CARQ)

IF NHDL<>NIL .AND. NHDL<=0
    
    AVISO("ATENÇÃO !","NÃO FOI POSSÍVEL A ABERTURA DO ARQUIVO "+ ALLTRIM(CARQ)+" !",{"OK"})
    
    FT_FUSE()
    
    RETURN 
ENDIF

PROCREGUA(FT_FLASTREC())

FT_FGOTOP()
LPRIMLINHA :=  .T. 

WHILE !(FT_FEOF())
 
    INCPROC("ANALISANDO ARQUIVO...")
    
    CBUFFER :=  ALLTRIM(FT_FREADLN())
    CBUFFER :=  UPPER(CBUFFER)
    
    CBUFFER := STRTRAN(CBUFFER,'"',"")
    
    ACAMPOS := {}
    FOR NPROC := 1 TO 9
        
        NPOS := AT(";",CBUFFER)
        
        IF LPRIMLINHA .AND. NPROC==1 .AND. !((LEFT( ALLTRIM(LEFT(CBUFFER,NPOS-1)),1)) $ ("ABCDEFGHI"))
            MSGSTOP(OEMTOANSI("DIVERGÊNCIA DE LAYOUT NA PRIMEIRA COLUNA ! FAVOR VERIFICAR ! "),)
            LCONTINUA :=  .F. 
            EXIT 
        ENDIF
        
        IF NPOS==0 .AND. NPROC<>9
            MSGSTOP(NPROC,)
            MSGSTOP(OEMTOANSI("ERRO NA IMPORTAÇÂO DO ARQUIVO ! DIVERGÊNCIA DE QUANTIDADE DE COLUNAS !"),)
            LCONTINUA :=  .F. 
            EXIT 
        ELSEIF NPOS==0
            NPOS := 100
        ENDIF
        
        AADD(ACAMPOS,LEFT(CBUFFER,NPOS-1))
        CBUFFER :=  SUBSTR(CBUFFER,NPOS+1)
    NEXT
    
    IF !(LCONTINUA)
        EXIT 
    ENDIF
    
    CCODPROD :=  ALLTRIM(ACAMPOS[1])
    CUMATU :=  ALLTRIM(ACAMPOS[2])
    CUMNOVA :=  ALLTRIM(ACAMPOS[3])
    
    C2UMNOVA :=  ALLTRIM(ACAMPOS[5])
    NFATOR :=  VAL(STRTRAN(ACAMPOS[6],",","."))
    CTPCONV :=  ALLTRIM(ACAMPOS[7])
    NFTRESTR :=  VAL(STRTRAN(ACAMPOS[8],",","."))
    CTPCONVE :=  ALLTRIM(ACAMPOS[9])
    
    DBSELECTAREA("SB1")
    DBSETORDER(1)
    
    IF EMPTY(CCODPROD) .AND. !(LPRIMLINHA)
        MSGSTOP(OEMTOANSI("CÓDIGO DE PRODUTO EM BRANCO ! CÓDIGO : ")+CCODPROD,)
        AADD(ALOG,"CÓDIGO DE PRODUTO EM BRANCO. CÓDIGO : "+CCODPROD)
        FT_FSKIP()
        LOOP 
    ELSEIF !(LPRIMLINHA) .AND. !(DBSEEK(XFILIAL("SB1")+CCODPROD))
        MSGSTOP(OEMTOANSI("CÓDIGO DE PRODUTO NÃO ENCONTRADO... CÓDIGO : ")+CCODPROD,)
        AADD(ALOG,"CODIGO DA PRODUTO NÃO ENCONTRADO .. CÓDIGO : "+CCODPROD)
        FT_FSKIP()
        LOOP 
    ENDIF
    
    IF !(LPRIMLINHA)
        
        AADD(ADADOS,{ .F. ,SB1->B1_COD,SB1->B1_TIPO,LEFT(SB1->B1_DESC,40),SB1->B1_UM, UPPER(CUMNOVA), UPPER(C2UMNOVA),NFATOR, UPPER(CTPCONV),NFTRESTR, UPPER(CTPCONVE),0,(SB1)->(RECNO())})
        NQTDSG1 := 0
        
        DBSELECTAREA("SG1")
        DBSETORDER(2)
        DBSEEK(XFILIAL("SG1")+SB1->B1_COD)
        WHILE !(EOF()) .AND. SG1->G1_FILIAL+SG1->G1_COMP==XFILIAL("SG1")+SB1->B1_COD
        
            MQTDNOVA := IIF(CTPCONVE=="M",(SG1->G1_QUANT) * (NFTRESTR),(SG1->G1_QUANT) / (NFTRESTR))
            
            AADD(AESTRUC,{" ",SG1->G1_COMP,SG1->G1_COD,NFTRESTR,SG1->G1_QUANT,MQTDNOVA, UPPER(CTPCONVE),(SG1)->(RECNO())})
            NQTDSG1++
            
            DBSKIP()
            ENDDO
        
        ADADOS[ LEN(ADADOS)][12] := NQTDSG1
    ENDIF
    
    LPRIMLINHA :=  .F. 
    
    FT_FSKIP()
    ENDDO

FT_FUSE()

IF !(LCONTINUA)
    RETURN 
ENDIF

ADADOS := ASORT(ADADOS,,,{ |X,Y|X[2]<Y[2]})

AESTRUC := ASORT(AESTRUC,,,{ |X,Y|X[2]+X[3]<Y[2]+Y[3]})

RETURN 
