#INCLUDE "protheus.ch"

CLASS REST_GETBAIXAEXP FROM LONGNAMECLASS
    DATA CCGCEMP
    DATA DESCRIPTION__
    DATA DESCRIPTION_FORMAT
    DATA DESCRIPTION_GET
    DATA DESCRIPTION_INFO_GET
    DATA DESCRIPTION_SECURITY
    DATA DESCRIPTION_SSL
    DATA DESCRIPTION_SYNTAX_GET
    DATA NOPCAO

    METHOD GET(_QUERYPARAM,CCGCEMP,NOPCAO,WSNOSEND)
    METHOD POST(_QUERYPARAM,CIDROTINA,WSNOSEND)

END CLASS

CLASS REST_POSTADIANTAMENTO FROM LONGNAMECLASS
    DATA CIDROTINA
    DATA DESCRIPTION__
    DATA DESCRIPTION_FORMAT
    DATA DESCRIPTION_INFO_POST
    DATA DESCRIPTION_POST

    METHOD GET(_QUERYPARAM,CCGCEMP,NOPCAO,WSNOSEND)
    METHOD POST(_QUERYPARAM,CIDROTINA,WSNOSEND)

ENDCLASS
METHOD POST(_QUERYPARAM,CIDROTINA,WSNOSEND) CLASS REST_POSTADIANTAMENTO

LOCAL NVALTOT := 0
LOCAL _NERRO := 0
LOCAL CBODY := ::GETCONTENT()
LOCAL ACONTAS := {}
LOCAL APERCS := {}
LOCAL ARECS := {}
LOCAL CJSON := ""
LOCAL AARRAY := {}

LOCAL ASE2 := {}
LOCAL NZ := 0
LOCAL CCUSTO := ""

LOCAL CQUERY := ""
LOCAL CALSQRY := ""
LOCAL CJSON := ""
LOCAL CTAMFIL := CVALTOCHAR(TAMSX3("EZ_FILIAL")[1])
LOCAL NOPCAO := IIF(::NOPCAO<>NIL,::NOPCAO,1)

PRIVATE LMSHELPAUTO :=  .T. 
PRIVATE LMSERROAUTO :=  .F. 
PRIVATE LAUTOERRNOFILE :=  .T. 
PRIVATE OJSOAUX

RPCSETENV("01","01")

IF EMPTY(CBODY)
    CJSON := '{"ERROR": "CONTEUDO JSON INVALIDO.","LRET":FALSE}'
    ::SETRESPONSE(CJSON)
    RETURN  .T. 
ENDIF

FWJSONDESERIALIZE(CBODY,@OJSOAUX)

PERGUNTE("FIN050", .F. )
MV_PAR01 := 2
MV_PAR04 := 2

DBSELECTAREA("SA2")
SA2->(DBSETORDER(3))

IF SA2->(DBSEEK(XFILIAL("SA2")+OJSOAUX:CPF))

    DBSELECTAREA("SE2")
    SE2->(DBSETORDER(1))

    IF SE2->(DBSEEK(XFILIAL("SE2")+"CDP"+CVALTOCHAR(OJSOAUX:IDRELATORIODESPESA)))
        CJSON := '{"MESSAGE": "TITULO JÁ INCLUSO.","LRET":TRUE}'
        ::SETRESPONSE(CJSON)
        RETURN  .T. 
    ENDIF

    AADD(AARRAY,{"E2_PREFIXO","CDP",NIL})
    AADD(AARRAY,{"E2_NUM",CVALTOCHAR(OJSOAUX:IDRELATORIODESPESA),NIL})
    AADD(AARRAY,{"E2_TIPO","PA",NIL})
    AADD(AARRAY,{"E2_NATUREZ",SA2->A2_NATUREZ,NIL})
    AADD(AARRAY,{"E2_FORNECE",SA2->A2_COD,NIL})
    AADD(AARRAY,{"E2_EMISSAO",CTOD(OJSOAUX:DATADESPESAAPROVACAOFORMATADA),NIL})
    AADD(AARRAY,{"E2_VENCTO",CTOD(OJSOAUX:VENCIMENTO),NIL})
    AADD(AARRAY,{"E2_VENCREA",DATAVALIDA(CTOD(OJSOAUX:VENCIMENTO), .T. ),NIL})
    AADD(AARRAY,{"E2_VLCRUZ",OJSOAUX:VALORDESPESA,NIL})
    AADD(AARRAY,{"E2_FORBCO",SA2->A2_BANCO,NIL})
    AADD(AARRAY,{"E2_FORAGE",SA2->A2_AGENCIA,NIL})
    AADD(AARRAY,{"E2_FAGEDV",SA2->A2_DVAGE,NIL})
    AADD(AARRAY,{"E2_FORCTA",SA2->A2_NUMCON,NIL})
    AADD(AARRAY,{"E2_FCTADV",SA2->A2_DVCTA,NIL})
    AADD(AARRAY,{"E2_HIST",OJSOAUX:HISTORICO,NIL})
    AADD(AARRAY,{"E2_CCUSTO",OJSOAUX:CENTRODECUSTO,NIL})
    AADD(AARRAY,{"E2_VALOR",OJSOAUX:VALORDESPESA,NIL})
    AADD(AARRAY,{"E2_XIDADT",CVALTOCHAR(OJSOAUX:IDDESPESA),NIL})
    AADD(AARRAY,{"AUTBANCO",SA2->A2_BANCO2,NIL})
    AADD(AARRAY,{"AUTAGENCIA",AVKEY(SA2->A2_AGENCI2,"A6_AGENCIA"),NIL})
    AADD(AARRAY,{"AUTCONTA",AVKEY(SA2->A2_NUMCO2,"A6_NUMCON"),NIL})

    AAREA := FWGETAREA()

    LMSERROAUTO :=  .F. 
    MSEXECAUTO({ |X,Y,Z|FINA050(X,Y,Z)},AARRAY,,3)

    IF LMSERROAUTO

        _CSTRERRO := ""
        _AERROS := GETAUTOGRLOG()
        _NERRO := ASCAN(_AERROS,{|X|("INVALIDO") $ ( ALLTRIM( UPPER(X)))})

        IF _NERRO>0
            _CSTRERRO += _AERROS[_NERRO]
        ELSE 

            FOR _NERRO := 1 TO  LEN(_AERROS)
                _CSTRERRO += _AERROS[_NERRO]+CHR(10)+CHR(13)
            NEXT
        ENDIF

        _CSTRERRO :=  ALLTRIM(_CSTRERRO)

        CJSON := "{"
        CJSON += '"MESSAGE":"'+"ERRO DE EXECAUTO ID = "+_CSTRERRO+'",'
        CJSON += '"LRET":FALSE'
        CJSON += "}"
    ELSE 

        CJSON := "{"
        CJSON += '"MESSAGE":"TÍTULO INCLUSO COM SUCESSO: '+SE2->E2_NUM+'",'
        CJSON += '"LRET":TRUE'
        CJSON += "}"
    ENDIF
ELSE 

    CJSON := "{"
    CJSON += '"MESSAGE":"FORNECEDOR NÃO LOCALIZADO.",'
    CJSON += '"LRET":FALSE'
    CJSON += "}"
ENDIF

ACONTAS := {}
ARECS := {}
APERCS := {}
NVALTOT := 0
LMSERROAUTO :=  .F. 

IF DECODEUTF8(CJSON)<>NIL
    CJSON := DECODEUTF8(CJSON)
ENDIF

::SETRESPONSE(CJSON)

RETURN  .T. 



PRIVATE LMSHELPAUTO :=  .T. 
PRIVATE LMSERROAUTO :=  .F. 
PRIVATE LAUTOERRNOFILE :=  .T. 
PRIVATE NVALOR := 0
PRIVATE ARATALL := {}
PRIVATE OJSOAUX

IF EMPTY(CBODY)
    CJSON := '{"ERROR": "CONTEUDO JSON INVALIDO.","LRET":FALSE}'
    ::SETRESPONSE(CJSON)
    RETURN  .T. 
ENDIF

FWJSONDESERIALIZE(CBODY,@OJSOAUX)

PERGUNTE("FIN050", .F. )
MV_PAR01 := 2
MV_PAR04 := 2

DBSELECTAREA("SE2")
SE2->(DBSETORDER(1))

IF SE2->(DBSEEK(XFILIAL("SE2")+OJSOAUX:PREFIXO+CVALTOCHAR(OJSOAUX:IDRELATORIO)))
    CJSON := '{"MESSAGE": "TITULO JÁ INCLUSO.","LRET":TRUE}'
    ::SETRESPONSE(CJSON)
    RETURN  .T. 
ENDIF

DBSELECTAREA("SA2")
SA2->(DBSETORDER(3))

SA2->(DBGOTOP())
IF SA2->(DBSEEK(XFILIAL("SA2")+OJSOAUX:CPF))

    NPOSNAT := 0
    NVALTOT := 0
    CAUXNAT := ""
    NENTAUX := 0
    NPRCAUX := 0
    ARATEVEZ := {}
    AAUXEZ := {}
    ARATEZ := {}
    LDESPESAS :=  .T. 

    IF ATTISMEMBEROF(OJSOAUX,"DESPESAS")

        FOR NZ := 1 TO  LEN(OJSOAUX:DESPESAS)

            NVALTOT += OJSOAUX:DESPESAS[NZ]:VALORDESPESA
        NEXT

        FOR NZ := 1 TO  LEN(OJSOAUX:DESPESAS)

            NPERCENT := ((OJSOAUX:DESPESAS[NZ]:VALORDESPESA) * (100)) / (NVALTOT)

            AAUXEV := {}

            NENTAUX := OJSOAUX:DESPESAS[NZ]:VALORDESPESA
            NPRCAUX := NPERCENT

            AADD(AAUXEV,{"EV_NATUREZ",OJSOAUX:DESPESAS[NZ]:NATUREZA,NIL})
            AADD(AAUXEV,{"EV_VALOR",OJSOAUX:DESPESAS[NZ]:VALORDESPESA,NIL})
            AADD(AAUXEV,{"EV_PERC",NPERCENT,NIL})
            AADD(AAUXEV,{"EV_RATEICC","1",NIL})

            CAUX := STRTRAN(OJSOAUX:DESPESAS[NZ]:CENTROCUSTO,";","")
            CCUSTO :=  SUBSTR(CAUX,1,AT("-",CAUX)-1)

            AAUXEZ := {}

            AADD(AAUXEZ,{"EZ_CONTA",OJSOAUX:DESPESAS[NZ]:CONTACONTABIL,NIL})
            AADD(AAUXEZ,{"EZ_CCUSTO", SUBSTR(CAUX,1,AT("-",CAUX)-1),NIL})
            AADD(AAUXEZ,{"EZ_VALOR",OJSOAUX:DESPESAS[NZ]:VALORDESPESA,NIL})
            AADD(AAUXEZ,{"CHAVE",OJSOAUX:DESPESAS[NZ]:CONTACONTABIL+ SUBSTR(CAUX,1,AT("-",CAUX)-1),NIL})

            IF ATTISMEMBEROF(OJSOAUX:DESPESAS[NZ],"ITEM")

                IF !(EMPTY(OJSOAUX:DESPESAS[NZ]:ITEM))
                    AADD(AAUXEZ,{"EZ_ITEMCTA",OJSOAUX:DESPESAS[NZ]:ITEM,NIL})
                ENDIF
            ENDIF

            AADD(ARATEZ,AAUXEZ)

            IF  LEN(ARATEVEZ)>0

                NPOSNAT := ASCAN(ARATEVEZ,{|X| ALLTRIM(X[1][2])==OJSOAUX:DESPESAS[NZ]:NATUREZA})

                IF NPOSNAT>0

                    ARATEVEZ[NPOSNAT][2][2] += OJSOAUX:DESPESAS[NZ]:VALORDESPESA
                    ARATEVEZ[NPOSNAT][3][2] += NPERCENT

                    NPOSCHV := ASCAN(ARATEVEZ[NPOSNAT][5][2],{|X| ALLTRIM(X[4][2])==OJSOAUX:DESPESAS[NZ]:CONTACONTABIL+ SUBSTR(CAUX,1,AT("-",CAUX)-1)})

                    IF NPOSCHV>0
                        ARATEVEZ[NPOSNAT][5][2][NPOSCHV][3][2] += OJSOAUX:DESPESAS[NZ]:VALORDESPESA
                    ELSE 
                        AADD(ARATEVEZ[NPOSNAT][5][2],AAUXEZ)
                    ENDIF

                    ARATEZ := {}
                ELSE 

                    AADD(AAUXEV,{"AUTRATEICC",ARATEZ,NIL})
                    AADD(ARATEVEZ,AAUXEV)
                    ARATEZ := {}
                ENDIF
            ELSE 

                AADD(AAUXEV,{"AUTRATEICC",ARATEZ,NIL})
                AADD(ARATEVEZ,AAUXEV)
                ARATEZ := {}
            ENDIF

            CAUXNAT := OJSOAUX:DESPESAS[NZ]:NATUREZA
        NEXT
    ELSE 

        NVALTOT := OJSOAUX:VALORDESPESA
        LDESPESAS :=  .F. 
    ENDIF

    AADD(ASE2,{"E2_FILIAL",FWXFILIAL("SE2"),NIL})
    AADD(ASE2,{"E2_NUM",OJSOAUX:IDRELATORIO,NIL})
    AADD(ASE2,{"E2_PREFIXO",OJSOAUX:PREFIXO,NIL})
    AADD(ASE2,{"E2_PARCELA",OJSOAUX:PARCELA,NIL})
    AADD(ASE2,{"E2_TIPO",OJSOAUX:TIPO,NIL})
    AADD(ASE2,{"E2_NATUREZ",OJSOAUX:NATUREZA,NIL})
    AADD(ASE2,{"E2_FORNECE",SA2->A2_COD,NIL})
    AADD(ASE2,{"E2_LOJA",SA2->A2_LOJA,NIL})
    AADD(ASE2,{"E2_NOMFOR",SA2->A2_NOME,NIL})
    AADD(ASE2,{"E2_EMISSAO",DDATABASE,NIL})
    AADD(ASE2,{"E2_VENCTO",CTOD(OJSOAUX:VENCIMENTO),NIL})
    AADD(ASE2,{"E2_VENCREA",DATAVALIDA(CTOD(OJSOAUX:VENCIMENTO), .T. ),NIL})
    AADD(ASE2,{"E2_VALOR",NVALTOT,NIL})
    AADD(ASE2,{"E2_HIST",OJSOAUX:HISTORICO,NIL})
    AADD(ASE2,{"E2_CCUSTO",CCUSTO,NIL})
    AADD(ASE2,{"E2_MOEDA",1,NIL})
    AADD(ASE2,{"E2_MULTNAT","1",NIL})
    AADD(ASE2,{"E2_XIDREL",OJSOAUX:IDRELATORIO,NIL})

    IF LDESPESAS
        AADD(ASE2,{"AUTRATEEV",ARATEVEZ,NIL})
    ENDIF

    ASE2 := FWVETBYDIC(ASE2,"SE2", .F. )

    MSEXECAUTO({ |X,Y,Z|FINA050(X,Y,Z)},ASE2,,3)

    IF LMSERROAUTO

        _CSTRERRO := ""
        _AERROS := GETAUTOGRLOG()
        _NERRO := ASCAN(_AERROS,{|X|("INVALIDO") $ ( ALLTRIM( UPPER(X)))})

        IF _NERRO>0
            _CSTRERRO += _AERROS[_NERRO]
        ELSE 

            FOR _NERRO := 1 TO  LEN(_AERROS)
                _CSTRERRO += _AERROS[_NERRO]+CHR(10)+CHR(13)
            NEXT
        ENDIF

        _CSTRERRO :=  ALLTRIM(_CSTRERRO)

        CJSON := "{"
        CJSON += '"MESSAGE":"'+"ERRO DE EXECAUTO ID = "+_CSTRERRO+'",'
        CJSON += '"LRET":FALSE'
        CJSON += "}"
    ELSE 

        CJSON := "{"
        CJSON += '"MESSAGE":"TÍTULO INCLUSO COM SUCESSO: '+SE2->E2_NUM+'",'
        CJSON += '"LRET":TRUE'
        CJSON += "}"
    ENDIF
ELSE 

    CJSON := "{"
    CJSON += '"MESSAGE":"FORNECEDOR NÃO LOCALIZADO.",'
    CJSON += '"LRET":FALSE'
    CJSON += "}"
ENDIF

ACONTAS := {}
ARECS := {}
APERCS := {}
NVALTOT := 0
LMSERROAUTO :=  .F. 

IF DECODEUTF8(CJSON)<>NIL
    CJSON := DECODEUTF8(CJSON)
ENDIF

::SETRESPONSE(CJSON)

RETURN  .T. 



CALSQRY := CRIATRAB(NIL, .F. )

CQUERY := " SELECT E2_XIDADT AS IDEXPENSE, E2_XIDREL AS IDREL, PR2.R_E_C_N_O_ RECNO FROM "+RETSQLNAME("PR2")+" PR2 "
CQUERY += " INNER JOIN "+RETSQLNAME("SE2")+" SE2 "
CQUERY += " ON E2_FILIAL = SUBSTRING(PR2_CHAVE,1,"+CTAMFIL+") AND E2_FILIAL+E2_PREFIXO+E2_NUM+E2_PARCELA+E2_TIPO = PR2_CHAVE "
CQUERY += " WHERE "
CQUERY += " PR2_STINT = 'P' AND PR2_ALIAS = 'SE2' "

IF NOPCAO==1
    CQUERY += " AND E2_XIDREL <> ' ' "
ELSE 
    CQUERY += " AND E2_XIDADT <> ' ' "
ENDIF

CQUERY += " AND PR2.D_E_L_E_T_ = ' ' "

IF (SELECT(CALSQRY)>0) 
 (CALSQRY)->(DBCLOSEAREA())
ENDIF
DBUSEAREA( .T. ,"TOPCONN",TCGENQRY(,,CQUERY),CALSQRY, .T. , .T. )

IF !((CALSQRY)->(EOF()))
    CJSON += '{"BAIXAS":['
    WHILE !((CALSQRY)->(EOF()))
    
        CJSON += "{"
        CJSON += '"IDADT":"'+ ALLTRIM(CALSQRY->IDEXPENSE)+'",'
        CJSON += '"IDREL":"'+ ALLTRIM(CALSQRY->IDREL)+'",'
        CJSON += '"RECNO":"'+CVALTOCHAR(CALSQRY->RECNO)+'",'
        CJSON += '"DATA":"'+FWTIMESTAMP(1,DDATABASE)+'"'
        CJSON += "},"
        
        (CALSQRY)->(DBSKIP())
        ENDDO
    
    CJSON := LEFT(CJSON,RAT(",",CJSON)-1)
    
    CJSON += "]}"
ELSE 
    
    CJSON := "[]"
ENDIF

::SETCONTENTTYPE("APPLICATION/JSON")
::SETRESPONSE(CJSON)

RETURN  .T. 

CBODY := ::GETCONTENT()
OJSOAUX := NIL
CJSON := ""

FWJSONDESERIALIZE(CBODY,@OJSOAUX)

DBSELECTAREA("PR2")

(PR2)->(DBGOTO(OJSOAUX:RECNO))

(PR2)->(RECLOCK("PR2", .F. ))

PR2->PR2_STINT := "I"

(PR2)->(MSUNLOCK())

CJSON := "{"
CJSON += '"LRET":TRUE,'
CJSON += '"MENSAGEM":"DADOS CONFIRMADOS COM SUCESSO"'
CJSON += "}"

::SETRESPONSE(CJSON)

RETURN  .T. 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION TESTADESPESA()
LOCAL CBODY := GETBODY()
LOCAL NVALTOT := 0
LOCAL _NERRO := 0
LOCAL ACONTAS := {}
LOCAL APERCS := {}
LOCAL ARECS := {}
LOCAL CJSON := ""
LOCAL ASE2 := {}
LOCAL NZ := 0
LOCAL CCUSTO := ""

PRIVATE LMSHELPAUTO :=  .T. 
PRIVATE LMSERROAUTO :=  .F. 
PRIVATE LAUTOERRNOFILE :=  .T. 
PRIVATE NVALOR := 0
PRIVATE ARATALL := {}
PRIVATE OJSOAUX
CSTRING := "REEMBOLSO ANDRÃ‰ LOPES GUERRA           "

DECODEUTF8(CSTRING)

RPCSETENV("01","01")

IF EMPTY(CBODY)
    CJSON := '{"ERROR": "CONTEUDO JSON INVALIDO.","LRET":FALSE}'

    RETURN  .T. 
ENDIF

FWJSONDESERIALIZE(CBODY,@OJSOAUX)

PERGUNTE("FIN050", .F. )
MV_PAR01 := 2
MV_PAR04 := 2

DBSELECTAREA("SE2")
SE2->(DBSETORDER(1))

IF SE2->(DBSEEK(XFILIAL("SE2")+OJSOAUX:PREFIXO+CVALTOCHAR(OJSOAUX:IDRELATORIO)))
    CJSON := '{"MESSAGE": "TITULO JÁ INCLUSO.","LRET":TRUE}'

    RETURN  .T. 
ENDIF

DBSELECTAREA("SA2")
SA2->(DBSETORDER(3))

SA2->(DBGOTOP())
IF SA2->(DBSEEK(XFILIAL("SA2")+OJSOAUX:CPF))

    NPOSNAT := 0
    NVALTOT := 0
    CAUXNAT := ""
    NENTAUX := 0
    NPRCAUX := 0
    ARATEVEZ := {}
    AAUXEZ := {}
    ARATEZ := {}
    LDESPESAS :=  .T. 

    IF ATTISMEMBEROF(OJSOAUX,"DESPESAS")

        FOR NZ := 1 TO  LEN(OJSOAUX:DESPESAS)

            NVALTOT += OJSOAUX:DESPESAS[NZ]:VALORDESPESA
        NEXT

        FOR NZ := 1 TO  LEN(OJSOAUX:DESPESAS)

            NPERCENT := ((OJSOAUX:DESPESAS[NZ]:VALORDESPESA) * (100)) / (NVALTOT)

            AAUXEV := {}

            NENTAUX := OJSOAUX:DESPESAS[NZ]:VALORDESPESA
            NPRCAUX := NPERCENT

            AADD(AAUXEV,{"EV_NATUREZ",OJSOAUX:DESPESAS[NZ]:NATUREZA,NIL})
            AADD(AAUXEV,{"EV_VALOR",OJSOAUX:DESPESAS[NZ]:VALORDESPESA,NIL})
            AADD(AAUXEV,{"EV_PERC",NPERCENT,NIL})
            AADD(AAUXEV,{"EV_RATEICC","1",NIL})

            CAUX := STRTRAN(OJSOAUX:DESPESAS[NZ]:CENTROCUSTO,";","")
            CCUSTO :=  SUBSTR(CAUX,1,AT("-",CAUX)-1)

            AAUXEZ := {}

            AADD(AAUXEZ,{"EZ_CONTA",OJSOAUX:DESPESAS[NZ]:CONTACONTABIL,NIL})
            AADD(AAUXEZ,{"EZ_CCUSTO", SUBSTR(CAUX,1,AT("-",CAUX)-1),NIL})
            AADD(AAUXEZ,{"EZ_VALOR",OJSOAUX:DESPESAS[NZ]:VALORDESPESA,NIL})
            AADD(AAUXEZ,{"CHAVE",OJSOAUX:DESPESAS[NZ]:CONTACONTABIL+ SUBSTR(CAUX,1,AT("-",CAUX)-1),NIL})

            AADD(ARATEZ,AAUXEZ)

            IF  LEN(ARATEVEZ)>0

                NPOSNAT := ASCAN(ARATEVEZ,{|X| ALLTRIM(X[1][2])==OJSOAUX:DESPESAS[NZ]:NATUREZA})

                IF NPOSNAT>0

                    ARATEVEZ[NPOSNAT][2][2] += OJSOAUX:DESPESAS[NZ]:VALORDESPESA
                    ARATEVEZ[NPOSNAT][3][2] += NPERCENT

                    NPOSCHV := ASCAN(ARATEVEZ[NPOSNAT][5][2],{|X| ALLTRIM(X[4][2])==OJSOAUX:DESPESAS[NZ]:CONTACONTABIL+ SUBSTR(CAUX,1,AT("-",CAUX)-1)})

                    IF NPOSCHV>0
                        ARATEVEZ[NPOSNAT][5][2][NPOSCHV][3][2] += OJSOAUX:DESPESAS[NZ]:VALORDESPESA
                    ELSE 
                        AADD(ARATEVEZ[NPOSNAT][5][2],AAUXEZ)
                    ENDIF

                    ARATEZ := {}
                ELSE 

                    AADD(AAUXEV,{"AUTRATEICC",ARATEZ,NIL})
                    AADD(ARATEVEZ,AAUXEV)
                    ARATEZ := {}
                ENDIF
            ELSE 

                AADD(AAUXEV,{"AUTRATEICC",ARATEZ,NIL})
                AADD(ARATEVEZ,AAUXEV)
                ARATEZ := {}
            ENDIF

            CAUXNAT := OJSOAUX:DESPESAS[NZ]:NATUREZA
        NEXT
    ELSE 

        NVALTOT := OJSOAUX:VALORDESPESA
        LDESPESAS :=  .F. 
    ENDIF

    AADD(ASE2,{"E2_FILIAL",FWXFILIAL("SE2"),NIL})
    AADD(ASE2,{"E2_NUM",OJSOAUX:IDRELATORIO,NIL})
    AADD(ASE2,{"E2_PREFIXO",OJSOAUX:PREFIXO,NIL})
    AADD(ASE2,{"E2_PARCELA",OJSOAUX:PARCELA,NIL})
    AADD(ASE2,{"E2_TIPO",OJSOAUX:TIPO,NIL})
    AADD(ASE2,{"E2_NATUREZ",OJSOAUX:NATUREZA,NIL})
    AADD(ASE2,{"E2_FORNECE",SA2->A2_COD,NIL})
    AADD(ASE2,{"E2_LOJA",SA2->A2_LOJA,NIL})
    AADD(ASE2,{"E2_NOMFOR",SA2->A2_NOME,NIL})
    AADD(ASE2,{"E2_EMISSAO",DDATABASE,NIL})
    AADD(ASE2,{"E2_VENCTO",CTOD(OJSOAUX:VENCIMENTO),NIL})
    AADD(ASE2,{"E2_VENCREA",DATAVALIDA(CTOD(OJSOAUX:VENCIMENTO), .T. ),NIL})
    AADD(ASE2,{"E2_VALOR",NVALTOT,NIL})
    AADD(ASE2,{"E2_HIST",OJSOAUX:HISTORICO,NIL})
    AADD(ASE2,{"E2_CCUSTO",CCUSTO,NIL})
    AADD(ASE2,{"E2_MOEDA",1,NIL})
    AADD(ASE2,{"E2_MULTNAT","1",NIL})
    AADD(ASE2,{"E2_XIDREL",OJSOAUX:IDRELATORIO,NIL})

    IF LDESPESAS
        AADD(ASE2,{"AUTRATEEV",ARATEVEZ,NIL})
    ENDIF

    ASE2 := FWVETBYDIC(ASE2,"SE2", .F. )

    LMSERROAUTO :=  .F. 
    MSEXECAUTO({ |X,Y,Z|FINA050(X,Y,Z)},ASE2,,3)

    IF LMSERROAUTO

        _CSTRERRO := ""
        _AERROS := GETAUTOGRLOG()
        _NERRO := ASCAN(_AERROS,{|X|("INVALIDO") $ ( ALLTRIM( UPPER(X)))})

        IF _NERRO>0
            _CSTRERRO += _AERROS[_NERRO]
        ELSE 

            FOR _NERRO := 1 TO  LEN(_AERROS)
                _CSTRERRO += _AERROS[_NERRO]+CHR(10)+CHR(13)
            NEXT
        ENDIF

        _CSTRERRO :=  ALLTRIM(_CSTRERRO)

        CJSON := "{"
        CJSON += '"MESSAGE":"'+"ERRO DE EXECAUTO ID = "+_CSTRERRO+'",'
        CJSON += '"LRET":FALSE'
        CJSON += "}"
    ELSE 

        CJSON := "{"
        CJSON += '"MESSAGE":"TÍTULO INCLUSO COM SUCESSO: '+SE2->E2_NUM+'",'
        CJSON += '"LRET":TRUE'
        CJSON += "}"
    ENDIF
ELSE 

    CJSON := "{"
    CJSON += '"MESSAGE":"FORNECEDOR NÃO LOCALIZADO.",'
    CJSON += '"LRET":FALSE'
    CJSON += "}"
ENDIF

ACONTAS := {}
ARECS := {}
APERCS := {}
NVALTOT := 0
LMSERROAUTO :=  .F. 

IF DECODEUTF8(CJSON)<>NIL
    CJSON := DECODEUTF8(CJSON)
ENDIF

RETURN  .T. 

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION GETBODY()

CBODY := '{"NATUREZA":"51030182","HISTORICO":"REEMBOLSO ANDRÉ LOPES GUERRA","PREFIXO":"DES","IDRELATORIO":"3767612","CPF":"33945693888","EMPRESA":"0101","PARCELA":"1","TIPO":"DP",'
CBODY += '"VENCIMENTO":"22/08/2023","SOLICITANTE":"000014","DESPESAS":[{"URL":" ","CODIGODESPESA":33270873,"CONTACONTABIL":"51030906","CENTROCUSTO":"201001-100",'
CBODY += '"NATUREZA":"51030182","VALORDESPESA":15},{"URL":" ","CODIGODESPESA":33270887,"CONTACONTABIL":"51030910","CENTROCUSTO":"201001-100","NATUREZA":"51030119","VALORDESPESA":20}]}'

CTESTE := "REEMBOLSO ANDRÃ‰ LOPES GUERRA           "
CTESTE2 := "REEMBOLSO ANDRÉ LOPES GUERRA"

A := DECODEUTF8(CTESTE)
B := DECODEUTF8(CTESTE2)
C := B

RETURN CBODY

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
USER FUNCTION GETBODY()

CBODY := '{"NATUREZA":"51030182","HISTORICO":"REEMBOLSO ANDRÉ LOPES GUERRA","PREFIXO":"DES","IDRELATORIO":"3767612","CPF":"33945693888","EMPRESA":"0101","PARCELA":"1",
CBODY += '"TIPO":"DP","VENCIMENTO":"22/08/2023","SOLICITANTE":"000014","DESPESAS":[{"URL":" ","CODIGODESPESA":33270873,"CONTACONTABIL":"51030906","CENTROCUSTO":"201001-100",'
CBODY +=    '"NATUREZA":"51030182","VALORDESPESA":15},{"URL":" ","CODIGODESPESA":33270887,"CONTACONTABIL":"51030910","CENTROCUSTO":"201001-100",
CBODY +=    '"NATUREZA":"51030119","VALORDESPESA":20}]}'

CTESTE := "REEMBOLSO ANDRÃ‰ LOPES GUERRA           "
CTESTE2 := "REEMBOLSO ANDRÉ LOPES GUERRA"

A := DECODEUTF8(CTESTE)
B := DECODEUTF8(CTESTE2)
C := B

RETURN CBODY

/////////////////////////////////////////////////////////////
// FONTE RECONSTRUIDO PELO TIME BSO ********************** //
/////////////////////////////////////////////////////////////
STATIC FUNCTION VLDCHAR(CSTRING)
LOCAL CCHAR := ""
LOCAL NX := 0
LOCAL NY := 0
LOCAL CVOGAL := "AEIOUAEIOU"
LOCAL CAGUDO := "ÁÉÍÓÚ"+"ÁÉÍÓÚ"
LOCAL CCIRCU := "ÂÊÎÔÛ"+"ÂÊÎÔÛ"
LOCAL CTREMA := "ÄËÏÖÜ"+"ÄËÏÖÜ"
LOCAL CCRASE := "ÀÈÌÒÙ"+"ÀÈÌÒÙ"
LOCAL CTIO := "ÃÕ"
LOCAL CTIOU := "ÃÕ"
LOCAL CCECID := "ÇÇ"
LOCAL CPONTUA := ":"

LIMAGEM := IIF(LIMAGEM==NIL, .F. ,LIMAGEM)
LNOTAGS := IIF(LNOTAGS==NIL, .T. ,LNOTAGS)

FOR NX := 1 TO  LEN(CSTRING)
    CCHAR :=  SUBSTR(CSTRING,NX,1)
    
    IF (CCHAR) $ (CAGUDO+CCIRCU+CTREMA+CCECID+CTIO+CCRASE+CTIOU+CPONTUA)
        NY := AT(CCHAR,CAGUDO)
        
        IF NY>0
            CSTRING := STRTRAN(CSTRING,CCHAR, SUBSTR(CVOGAL,NY,1))
        ENDIF
        
        NY := AT(CCHAR,CCIRCU)
        
        IF NY>0
            CSTRING := STRTRAN(CSTRING,CCHAR, SUBSTR(CVOGAL,NY,1))
        ENDIF
        
        NY := AT(CCHAR,CTREMA)
        
        IF NY>0
            CSTRING := STRTRAN(CSTRING,CCHAR, SUBSTR(CVOGAL,NY,1))
        ENDIF
        
        NY := AT(CCHAR,CCRASE)
        
        IF NY>0
            CSTRING := STRTRAN(CSTRING,CCHAR, SUBSTR(CVOGAL,NY,1))
        ENDIF
        
        NY := AT(CCHAR,CTIO)
        
        IF NY>0
            CSTRING := STRTRAN(CSTRING,CCHAR, SUBSTR("AO",NY,1))
        ENDIF
        
        NY := AT(CCHAR,CTIOU)
        
        IF NY>0
            CSTRING := STRTRAN(CSTRING,CCHAR, SUBSTR("AO",NY,1))
        ENDIF
        
        NY := AT(CCHAR,CCECID)
        
        IF NY>0
            CSTRING := STRTRAN(CSTRING,CCHAR, SUBSTR("CC",NY,1))
        ENDIF
    ENDIF
NEXT
FOR NX := 1 TO  LEN(CSTRING)
    CCHAR :=  SUBSTR(CSTRING,NX,1)
    
    IF (ASC(CCHAR)<32) .OR. (ASC(CCHAR)>122)
        CSTRING := STRTRAN(CSTRING,CCHAR,".")
    ENDIF
NEXT

RETURN CSTRING
