#Include 'Protheus.ch'

User Function MT094CPC()

Local cCampos := "C7_XTPPROD|C7_XOBS|C7_XSOLICIT|C7_NUMSC|C7_NUM|C7_SOLICIT|C7_CC|C7_OBS|C7_OBSM|C7_CONTA|B1_TIPO|C7_XREVISA|C7_XQATU|C7_XULTPRC|C7_XPORCEN|C7_COND|C7_XDESCPG|C7_DATPRF|C7_XLIBPRE|C7_CODTAB|C7_NUMCOT"
//Local cCampos := "C7_NUM|C7_SOLICIT|C7_CC|C7_OBS|C7_OBSM|C7_CONTA|B1_TIPO|C7_XREVISA|C7_XQATU|C7_XULTPRC|C7_XPORCEN|C7_COND|C7_XDESCPG|C7_DATPRF|C7_XLIBPRE"

Return (cCampos)
